Text_SwordsDanceTeach::
    .string "לא הרבה אנשים מגיעים לכאן.\p"
    .string "אם אתאמן כאן, אני משוכנע\n"
    .string "שאהיה חזק יותר ויותר.\p"
    .string "כן, חזק יותר ויותר…\p"
    .string "רוצה ללמוד מהלך כזה?\n"
    .string "קוראים לו מחול חרבות.$"

Text_SwordsDanceDeclined::
    .string "טוב, גם זה בסדר גמור.$"

Text_SwordsDanceWhichMon::
    .string "בסדר, בחר לאיזה פוקימון\n"
    .string "אני צריך ללמד את זה.$"

Text_SwordsDanceTaught::
    .string "הלוואי שנוכל להמשיך להתחזק\n"
    .string "עוד ועוד, נכון?$"

SevenIsland_Text_IslandSign::
    .string "אי 7\n"
    .string "אי המסע האינסופי$"

SevenIsland_Text_IslandsMadeInSevenDays::
    .string "האיים האלה נקראים איי סווי\n"
    .string "כי יש כאן שבעה איים.\p"
    .string "…לפחות ככה הצעירים\n"
    .string "מאמינים.\p"
    .string "האמת היא שהם נקראים כך\n"
    .string "כי מספרים שהם נבראו\l"
    .string "בשבעה ימים.$"

SevenIsland_Text_IslandVirtuallyUntouched::
    .string "האי הזה נשאר כמעט לגמרי\n"
    .string "במצבו הטבעי.\p"
    .string "בגלל זה קצת קשה\n"
    .string "לטייל בו ברגל.$"

