OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
    .string "ביל: היי!\n"
    .string "סליו!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
    .string "סליו: ביל!\n"
    .string "אני לא מאמין שבאת עד לכאן.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
    .string "ביל: ברור שכן!\n"
    .string "איך המחקר שלך מתקדם?\p"
    .string "…אה, רגע אחד.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
    .string "{PLAYER}, זה החבר שלי סליו.\n"
    .string "הוא משוגע אמיתי על מחשבים!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
    .string "סליו, זה {PLAYER}, מועמד\n"
    .string "עולה לתואר אלוף הפוקימון!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
    .string "סליו, זה {PLAYER},\n"
    .string "אלוף הפוקימון המכהן!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
    .string "סליו: זה ממש מרשים.\p"
    .string "קשה לי להודות בזה, אבל אין\n"
    .string "לי שום כישרון לקרבות.\p"
    .string "בכל אופן, נעים להכיר.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
    .string "ביל: אז ספר לי מה חדש.\n"
    .string "איך המכונה שלך עובדת?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
    .string "סליו: היא עובדת מצוין, אבל\n"
    .string "אנחנו מרוחקים מדי כאן.\p"
    .string "המחשבים באי הזה פשוט לא\n"
    .string "מתחברים למחשב שלך, ביל.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
    .string "ביל: אה, כן?\n"
    .string "טוב, תן לי להעיף מבט.\p"
    .string "…רגע אחד…\n"
    .string "נראה לי שאפשר לסדר את זה.\l"
    .string "תן לי לעזור לך, בסדר?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
    .string "{PLAYER}, אפשר לבקש ממך\n"
    .string "לחכות לי עוד קצת?\p"
    .string "…למען האמת, אפשר לבקש\n"
    .string "ממך טובה?\p"
    .string "האי שליד האי הזה\n"
    .string "נקרא אי 2.\p"
    .string "יש שם בחור שמנהל\n"
    .string "משחקיה.\p"
    .string "יש לו חיבה לסלעים\n"
    .string "ולאבני חן נדירות.\p"
    .string "אנחנו בקשר, כי שנינו\n"
    .string "משוגעים לדבר.\p"
    .string "אז אפשר לבקש ממך למסור\n"
    .string "לו את המטאוריט הזה?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
    .string "{PLAYER} קיבל את המטאוריט\n"
    .string "מביל.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
    .string "סליו: {PLAYER}, אם אתה נוסע\n"
    .string "לאי 2, קח בבקשה את זה.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
    .string "זהו כרטיס לשירות המעבורות\n"
    .string "בין האיים המקומיים.\p"
    .string "הוא יאפשר לך לנוע בין\n"
    .string "האיים אחד, שתיים ושלוש.\p"
    .string "אה, וכדאי שתיקח גם את זה.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
    .string "{PLAYER} קיבל דף נוסף\n"
    .string "למפת העיר!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
    .string "{PLAYER} קיבל\n"
    .string "את מפת העיר!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
    .string "ביל: נתראה בקרוב!\n"
    .string "תמסור לו ד”ש ממני!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
    .string "הממ…\p"
    .string "אולי ננסה את זה ככה…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
    .string "אה, היי, {PLAYER}!\p"
    .string "ראית?\n"
    .string "הצלחנו להפעיל את המחשב!\p"
    .string "יש לי עוד כמה דברים\n"
    .string "להראות לסליו.\p"
    .string "אולי תצא לסיבוב או משהו\n"
    .string "לעוד קצת זמן?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
    .string "אני מצטער שאני גוזל\n"
    .string "כל כך הרבה מזמנו של ביל.\p"
    .string "ואני מצטער גם שאני מארח\n"
    .string "כל כך גרוע בביקור שלך כאן.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
    .string "שירותי המחשב הרגילים\n"
    .string "אינם זמינים…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
    .string "ביל: אה, היי!\n"
    .string "{PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
    .string "ביל: מה לקח לך כל כך הרבה?\n"
    .string "נהנית בחוץ?\p"
    .string "סיימנו את העבודה.\n"
    .string "המחשבים פועלים!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
    .string "סליו: העבודה הלכה\n"
    .string "מהר בטירוף.\p"
    .string "ביל הוא בחור מדהים…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
    .string "ביל: לא, לא! כמעט לא\n"
    .string "נשאר לי מה לעשות.\p"
    .string "סליו, כל הכבוד לך.\n"
    .string "למדת המון.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
    .string "סליו: באמת?\n"
    .string "אהה…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
    .string "ביל: אז זהו זה.\n"
    .string "סיימתי את העבודה.\l"
    .string "כדאי שנחזור לקאנטו.\p"
    .string "סליו, נתראה בקרוב.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
    .string "סליו: {PLAYER}, אני מצטער\n"
    .string "ששלחנו אותך לבד היום.\p"
    .string "אני מבטיח שאסייר איתך\n"
    .string "באיים האלה מתישהו.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
    .string "סליו: שלום!\n"
    .string "אתה נראה עסוק כתמיד.\p"
    .string "ומה איתי?\p"
    .string "ובכן, אני משפר את\n"
    .string "מכונת הרשת שלי.\p"
    .string "כשאסיים עם המכונה,\n"
    .string "אני מקווה שתהיה הראשון\l"
    .string "להשתמש בה, {PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
    .string "סליו: {PLAYER}, איך הולך\n"
    .string "לך לאחרונה?\p"
    .string "אה, באמת?\n"
    .string "תפסת עוד פוקימונים.\p"
    .string "אתה יודע מה?\n"
    .string "אולי אני יכול להועיל לך.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
    .string "אני משפר עכשיו את\n"
    .string "מכונת הרשת.\p"
    .string "אני משנה אותה כך שתוכל\n"
    .string "לטפל בהחלפות למרחקים.\p"
    .string "כשאסיים, תוכל להחליף\n"
    .string "ולקבל פוקימונים אקזוטיים\l"
    .string "ממאמנים רחוקים.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
    .string "אבל יש בעיה קטנה.\p"
    .string "כדי שהחיבור יעבוד, המכונה\n"
    .string "צריכה אבן חן מיוחדת.\p"
    .string "היא אמורה להיות באי 1,\n"
    .string "אבל עוד לא מצאתי אותה.\p"
    .string "מי יודע איפה היא מסתתרת.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
    .string "ניסיתי למצוא את האבן\n"
    .string "אפילו בזמן הלימודים.\p"
    .string "התוצאה היא שלא התקדמתי\n"
    .string "לא בחיפוש ולא בלימודים…\p"
    .string "אם הייתי נשען על ביל,\n"
    .string "בטוח שהמחקר שלי היה מתקדם.\p"
    .string "אבל הפעם אני רוצה לנסות\n"
    .string "לעשות דברים בעצמי.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
    .string "הו!\n"
    .string "ז-זה…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
    .string "{PLAYER} מסר את האודם\n"
    .string "לסליו.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
    .string "תודה רבה!\n"
    .string "{PLAYER}, אתה פשוט מדהים.\p"
    .string "… … …  … … …\p"
    .string "אממ… אפשר לבקש ממך עוד\n"
    .string "טובה ענקית אחת?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
    .string "זה… זה לא משהו מוזר.\n"
    .string "בבקשה, אני צריך את עזרתך.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
    .string "בזמן שחקרתי אבני חן\n"
    .string "גיליתי משהו חשוב.\p"
    .string "יש עוד אבן חן שמהווה\n"
    .string "זוג עם האודם הזה.\p"
    .string "אבן החן השנייה אמורה\n"
    .string "להיות באיי סווי.\p"
    .string "{PLAYER}, בבקשה, אני צריך\n"
    .string "שתמצא את האבן השנייה.\p"
    .string "{PLAYER}, אפשר לקבל את\n"
    .string "כרטיס המעבורת ומפת העיר?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
    .string "{PLAYER} החזיר את הכרטיס\n"
    .string "המשולש וקיבל את כרטיס הקשת.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
    .string "התקבל דף נוסף\n"
    .string "למפת העיר!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
    .string "זהו כרטיס המעבורת שלי.\p"
    .string "הוא יאפשר לך להגיע\n"
    .string "לכל איי סווי.\p"
    .string "{PLAYER}, בבקשה, אני לא\n"
    .string "מסוגל בלי העזרה שלך.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
    .string "{PLAYER} מסר את הספיר\n"
    .string "לסליו.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
    .string "סליו: אז זו אבן החן\n"
    .string "שמהווה זוג עם האודם…\p"
    .string "{PLAYER}, עברת לא מעט\n"
    .string "כדי להשיג אותה, נכון?\p"
    .string "אתה לא צריך לספר לי.\n"
    .string "אני יודע שזה לא היה קל.\p"
    .string "תודה רבה לך!\p"
    .string "עכשיו תורי לעבוד בשבילך!\n"
    .string "תן לי בבקשה קצת זמן.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
    .string "טוב, זה נראה בסדר…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
    .string "הצלחתי!\n"
    .string "התחברתי ללאנט!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
    .string "{PLAYER}…\n"
    .string "{PLAYER}, הצלחתי!\p"
    .string "הצלחתי להתחבר למאמנים\n"
    .string "במחוז הואן!\p"
    .string "סוף סוף מכונת הרשת\n"
    .string "פועלת במלואה!\p"
    .string "{PLAYER}, הכול בזכותך!\p"
    .string "בזכותך החלום שלי\n"
    .string "התגשם…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
    .string "אני…\n"
    .string "אני לא בוכה.\p"
    .string "מספיק לדבר עליי!\p"
    .string "{PLAYER}, אתה תמשיך לחפש\n"
    .string "פוקימונים אקזוטיים, נכון?\p"
    .string "אני מאחל לך בהצלחה!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
    .string "סליו: שלום!\p"
    .string "{PLAYER}, שמעתי עליך\n"
    .string "שמועות.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
    .string "{PLAYER}, מהו סוג הפוקימון\n"
    .string "האהוב עליך?\p"
    .string "ביל הוא פוקימניאק,\n"
    .string "אז הוא אוהב כל סוג.\p"
    .string "מסתבר שהראשון שהוא תפס\n"
    .string "היה אברה.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
    .string "אגב, {PLAYER}, אתה מהעיירה\n"
    .string "פאלט, נכון?\p"
    .string "שמעתי שזה מקום שקט\n"
    .string "ונעים מאוד.\p"
    .string "עיר הולדתו של ביל היא עיר\n"
    .string "גולדנרוד, שם גרים הוריו.\p"
    .string "שמעתי שזו עיר חגיגית\n"
    .string "ותוססת למדי.\p"
    .string "הייתי רוצה לבקר שם יום אחד.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
    .string "{PLAYER}, יש משהו שאתה\n"
    .string "לא סובל?\p"
    .string "מסתבר שביל פשוט לא מסוגל\n"
    .string "לשתות חלב בכלל.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
    .string "הו, אתה זר כאן!\n"
    .string "היי! מאיפה באת?\p"
    .string "…העיירה פאלט?\n"
    .string "לא מכיר את המקום!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
    .string "באי הזה יש הר געש\n"
    .string "עצום.\p"
    .string "הוא לא התפרץ מזמן,\n"
    .string "אז למה לא לצאת לטיול?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
    .string "הלוואי שיכולתי להחליף\n"
    .string "פוקימונים עם החבר שלי הרחוק…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
    .string "החלפתי פוקימון עם החבר\n"
    .string "שלי שגר רחוק!\p"
    .string "כולם אומרים שאפשר להודות\n"
    .string "לך ולסליו.\p"
    .string "אז תודה!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
    .string "מכונת הרשת\n"
    .string "רמת חיבור 0\p"
    .string "…מערכת אחסון הפוקימונים\n"
    .string "בכיוונון…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
    .string "מכונת הרשת\n"
    .string "רמת חיבור 1\p"
    .string "נוצר חיבור עם מחוז\n"
    .string "קאנטו.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
    .string "מכונת הרשת\n"
    .string "רמת חיבור 2\p"
    .string "נוצר חיבור עם מחוזות\n"
    .string "קאנטו והואן.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
    .string "התקבל הכרטיס המשולש!$"

