SixIsland_GreenPath_Text_JaclynIntro::
    .string "…האה?\p"
    .string "דמיינתי את הבית שלי, אז איך\n"
    .string "השתגרתי דווקא לכאן?$"

SixIsland_GreenPath_Text_JaclynDefeat::
    .string "טעות ענקית!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
    .string "אני כל כך מפוזרת!\p"
    .string "אני צריכה להתרכז כדי\n"
    .string "להשתגר נכון לבית שלי!$"

SixIsland_GreenPath_Text_LeftRouteSign::
    .string "דרך הירוק\n"
    .string "סבך התבניות בהמשך$"

SixIsland_GreenPath_Text_RightRouteSign::
    .string "דרך הירוק\n"
    .string "תחשוב ירוק, שמור על הטבע!$"

