FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
    .string "פקח: פה הופא!\p"
    .string "איפהי אה הפיאיי פלי פהאפאהי. עפור\l"
    .string "לי פפקפה!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
    .string "אהי פופך עאיך!\n"
    .string "פה פהאפאהי!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
    .string "הא? פפהר, אפל אהי\n"
    .string "מחפף אפעפור לי!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
    .string "{PLAYER} נתן את\n"
    .string "שיני הזהב לפקח!$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
    .string "הפקח הכניס את\n"
    .string "את השיניים לפה!\p$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
    .string "פקח: תודה, ילד!\n"
    .string "אף אחד לא הבין אף מילה שאמרתי.\p"
    .string "לא יכולתי לעבוד ככה. הרשה לי\l"
    .string "להעניק לך משהו עבור הטרחה.\p$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
    .string "{PLAYER} קיבל את מ”נ40!$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
    .string "פקח: מ”נ40 מכיל\n"
    .string "את המהלך עוצמה!\p"
    .string "זה מאפשר לפוקימון להזיז סלעים\l"
    .string "כאשר אתה מחוץ לקרב.\p"
    .string "אה כן, מצאת את הביתן הסודי באזור\l"
    .string "הספארי?\p"
    .string "אם אתה מוצא, אתה זוכה במ”נ!\p"
    .string "השמועה אומרת שזה מ”נ גלישה הנדיר.$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
    .string "תמונות של פוקימון\n"
    .string "ומאובנים.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
    .string "סחורת פוקימון ישנה.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
    .string "פקח: תודה לך, ילדה!\n"
    .string "את מצילה חיים אמיתית!\p"
    .string "אף אחד לא הבין מילה\n"
    .string "ממה שאמרתי, לא אחד!\p"
    .string "הייתי כל כך מבויש להראות את הפנים\n"
    .string "שלי במשרד, אפילו.\p"
    .string "תן לי לתת לך משהו על העזרה שלך.$"


@ Unused
FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
    .string "なんや　にもつ\n"
    .string "いっぱいやんけ！$"
