SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
    .string "…חכה! אל תאמר מילה!\p"
    .string "רצית את זה!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
    .string "{PLAYER} קיבל מ”מ92\n"
    .string "אשליה.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
    .string "אתה כבר יודע, נכון?\n"
    .string "מ”מ92 הוא על-חושי.\p"
    .string "זה מתקפה שעשויה גם להוריד\n"
    .string "את הסטטיסטיקות המיוחדות של היריב.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
    .string "איפה אתה מתכנן לשים את זה?\n"
    .string "אין לך מקום.$"
