RockTunnel_B1F_Text_SofiaIntro::
    .string "אתה יודע איך אפשר להימנע\n"
    .string "מהתברברות בהרים?\p"
    .string "אפשר לקפל ענפים כסימני שביל.$"

RockTunnel_B1F_Text_SofiaDefeat::
    .string "אוה!\n"
    .string "עשיתי כמיטב יכולתי!$"

RockTunnel_B1F_Text_SofiaPostBattle::
    .string "אני רוצה לחזור הביתה!$"

RockTunnel_B1F_Text_DudleyIntro::
    .string "חחחח!\n"
    .string "אתה יכול לנצח את הכוח שלי?$"

RockTunnel_B1F_Text_DudleyDefeat::
    .string "אופס!\n"
    .string "הובסתי בכוח!$"

RockTunnel_B1F_Text_DudleyPostBattle::
    .string "אני הולך לכוח כי אני שונא\n"
    .string "לחשוב.$"

RockTunnel_B1F_Text_CooperIntro::
    .string "יש לך הפוקדקס?\n"
    .string "אני גם רוצה אחד!$"

RockTunnel_B1F_Text_CooperDefeat::
    .string "יו!.\n"
    .string "אני כל כך מקנא!$"

RockTunnel_B1F_Text_CooperPostBattle::
    .string "כשאתה מסיים את הפוקדקס שלך,\n"
    .string "אפשר לקבל אותו?$"

RockTunnel_B1F_Text_SteveIntro::
    .string "אה… אתה יודע על קוספליי של\n"
    .string "פוקימונים?$"

RockTunnel_B1F_Text_SteveDefeat::
    .string "טוב, זהו.$"

RockTunnel_B1F_Text_StevePostBattle::
    .string "קוספליי של פוקימונים זה להתחפש\n"
    .string "לפוקימונים לכיף.\p"
    .string "קלאפרי היא פוקימון פופולרי.$"

RockTunnel_B1F_Text_AllenIntro::
    .string "הטכניקות של הפוקימונים שלי ישאירו\n"
    .string "אותך בוכה!$"

RockTunnel_B1F_Text_AllenDefeat::
    .string "אני מוותר!\n"
    .string "אתה טכנאי טוב יותר!$"

RockTunnel_B1F_Text_AllenPostBattle::
    .string "בהרים, תמצא הרבה\n"
    .string "פוקימוני אבן.$"

RockTunnel_B1F_Text_MarthaIntro::
    .string "אני לא באה לפה הרבה, אבל אני\n"
    .string "אלחם בך.$"

RockTunnel_B1F_Text_MarthaDefeat::
    .string "או!\n"
    .string "הפסדתי!$"

RockTunnel_B1F_Text_MarthaPostBattle::
    .string "אני אוהבת פוקימונים קטנים.\n"
    .string "פוקימונים גדולים יותר מדי מפחידים!$"

RockTunnel_B1F_Text_EricIntro::
    .string "תן לי את המכה הכי טובה שלך!$"

RockTunnel_B1F_Text_EricDefeat::
    .string "שיגרתי אותה!$"

RockTunnel_B1F_Text_EricPostBattle::
    .string "אני אגדל את הפוקימונים שלי כדי\n"
    .string "להביס את שלך, ילד.$"

RockTunnel_B1F_Text_WinstonIntro::
    .string "אני מצייר תמונות של פוקימונים\n"
    .string "כשהמבית.$"

RockTunnel_B1F_Text_WinstonDefeat::
    .string "פוו…\n"
    .string "אני מותש…$"

RockTunnel_B1F_Text_WinstonPostBattle::
    .string "אני אמן, לא לוחם.\n"
    .string "אני אלך הביתה לצייר.$"
