CeladonCity_Condominiums_1F_Text_Meowth::
    .string "מיאו: מיאו!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "אתה לא צריך לבזבז את כל הכסף שלך\n"
    .string "על משקעות.\p"
    .string "הנה, נסה את זה.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "שום דבר לא מרווה כמו\n"
    .string "תה חם.\p"
    .string "זה הכי טוב שיש.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "הפוקימונים\n"
    .string "האהובים שלי מארחים לי חברה.\p"
    .string "מיאו אפילו מביא הביתה כסף!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "הו שלום חמוד.\n"
    .string "נהנת מהתה שלי?\p"
    .string "דרך אגב, אתה במקרה מהעיר\n"
    .string "פאלט?\p"
    .string "ילדה משם בשם דייזי,\n"
    .string "שותה תה כל יום.\p"
    .string "היא מגיעה לחנות של סלדון\n"
    .string "כדי לקנות תה.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "קלפרי: פיפ\n"
    .string "פיפיפ פיפ!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "מחטן: קיה\n"
    .string "קיה-הו!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "אחוזת סלדון\n"
    .string "סוויטת המנהל$"

