CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
    .string "חליל הסברינה מעורר\n"
    .string "פוקימונים בעזרת מנגינה שרק הם\l"
    .string "מסוגלים לשמוע!$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
    .string "רכבתי לכאן בעליה\n"
    .string "בשביל האופניים מהעיר פיושיה!$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
    .string "אם רק היו לי אופניים, הייתי יכול\n"
    .string "הייתי יכול לנסוע דרך שביל\l"
    .string "האופניים!$"

