Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
    .string "אני בטיול רגוע על האופניים החדשים\n"
    .string "שלי עם החברה שלי.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
    .string "אנחנו רוכבים יחד על האופניים\n"
    .string "החדשים שלנו.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
    .string "בואו נראה מה המשקפת מראה לנו…\p"
    .string "זהו הכלבו של סלאדון!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
    .string "בואו נראה מה המשקפת מראה לנו…\p"
    .string "יש שם שביל ארוך מעל המים רחוק\n"
    .string "מאוד.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
    .string "שלום! זוכר אותי?\n"
    .string "אני אחד מהעוזרים של פרופ' אוק.\p"
    .string "אם הפוקידע שלך מכיל נתונים\n"
    .string "מלאים על 04 מינים, אני אמור להעניק\l"
    .string "לך פרס.\p"
    .string "פרופ' אוק הפקיד אותי עם\n"
    .string "מטבע הקמע עבורך.\p"
    .string "אז, {PLAYER}, הרשה לי לשאול אותך.\p"
    .string "האם אספת נתונים לפחות על\n"
    .string "04 סוגי פוקימונים?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
    .string "מעולה! לכדת או החזקת\n"
    .string "{STR_VAR_3} סוגי פוקימונים!\p"
    .string "מזל טוב!\n"
    .string "הנה, זה בשבילך!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
    .string "{PLAYER} קיבל את מטבע הקמע\n"
    .string "מהעוזר.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
    .string "מטבע הקמע הוא פריט שצריך\n"
    .string "להחזיק על ידי פוקימון.\p"
    .string "אם הפוקימון מופיע בקרב מנצח,\n"
    .string "תרוויח יותר כסף.$"
