FuchsiaCity_Text_DidYouTrySafariGame::
    .string "ניסית את\n"
    .string "משחק הספארי? יש פוקימונים\l"
    .string "שאפשר לתפוס רק שם.$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "יש גן חיות\n"
    .string "מול הכניסה באיזור הספארי.\p"
    .string "מאחורה נמצא משחק הספארי\l"
    .string "שם ניתן לתפוס פוקימונים.$"

FuchsiaCity_Text_WheresSara::
    .string "אריק: איפה שרה?\n"
    .string "היא אמרה שכאן ניפגש.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "הפוקיבול שם הוא\n"
    .string "בכלל לא פריט, אלא פוקימון.$"

FuchsiaCity_Text_CitySign::
    .string "העיר פיושה\n"
    .string "שטפו את עיניכם בורוד המרהיב!$"

FuchsiaCity_Text_SafariGameSign::
    .string "משחק ספארי\n"
    .string "תפסו פוקימונים!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "איזור ספארי\n"
    .string "בית הפקח$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "גן העדן לפוקימונים\n"
    .string "איזור הספארי$"

FuchsiaCity_Text_GymSign::
    .string "העיר פיושה\n"
    .string "מכון פוקימון מנהיג: קוגה\p"
    .string "מאסטר הנינג'ה הרעיל.$"

FuchsiaCity_Text_ChanseySign::
    .string "שם: בת מזל\p"
    .string "לתפוס אחת כזו זה עניין של מזל.\p$"

FuchsiaCity_Text_VoltorbSign::
    .string "שם: וולטורב\p"
    .string "נראה ממש כמו פוקיבול.\p$"

FuchsiaCity_Text_KangaskhanSign::
    .string "שם: קנגסקאן\p"
    .string "ימון אמהיפוק שמגדלת את\l"
    .string "צאצאיה בתוך כיס בבטן שלה.\p$"

FuchsiaCity_Text_SlowpokeSign::
    .string "שם: סלופוק\p"
    .string "חביב ומאוד איטי.\p$"

FuchsiaCity_Text_LaprasSign::
    .string "שם: לפרס\p"
    .string "ידוע גם כמלך הימים.\p$"

FuchsiaCity_Text_OmanyteSign::
    .string "שם: אומנייט\p"
    .string "ימון ששוחזרפוק ממאובן\p$"

FuchsiaCity_Text_KabutoSign::
    .string "שם: קאבוטו\p"
    .string "ימון ששוחזרפוק ממאובן\p$"

FuchsiaCity_Text_Ellipsis::
    .string "...$"

Text_SubstituteTeach::
    .string "הלוואי ואני הייתי תינוק של קנגסקאן\p"
    .string "הייתי שמח להחליף את התינוק..\n"
    .string "ולהתכרבל בכיס של אמא קנגסקאן\p"
    .string "אבל רק פוקימונים יודעים להשתמש\n"
    .string "במהלך 'ממלא מקום'…\p"
    .string "אתה רוצה שאלמד את אחד\n"
    .string "מהפוקימונים שלך את המהלך 'ממלא\l"
    .string "מקום'?$"

Text_SubstituteDeclined::
    .string "אה, באמת?\n"
    .string "חבל זה נראה מהלך כיף…$"

Text_SubstituteWhichMon::
    .string "איזה פוקימון ללמד\n"
    .string "'ממלא מקום'?$"

Text_SubstituteTaught::
    .string "מה הייתי נותן כדי להתכרבל\n"
    .string "בכיס של הקנגסקאן…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "אבא שלי הוא המנהיג של המכון\n"
    .string "בעיר הזו.\p"
    .string "אני מתאמן עם פוקימוני רעל\n"
    .string "בדיוק כמו אבא שלי.$"

FuchsiaCity_Text_SafariZoneSign::
    .string "גן עדן לפוקימון!\n"
    .string "איזור הספארי$"
