ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
    .string "היי, שלום!\n"
    .string "מה נשמע?\p"
    .string "מה אני עושה פה, אתה שואל?\n"
    .string "אני מחפש זהב, כמובן!\p"
    .string "כשאתעשר, אני קונה לי\n"
    .string "בית בקאנטו.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
    .string "היי, שלום! מה נשמע?\n"
    .string "שמעת? מצאתי זהב!\p"
    .string "זכרת שחיפשתי זהב,\n"
    .string "נכון?\p"
    .string "אתה לא יכול להתחיל לדמיין\n"
    .string "כמה אני שמח.\p"
    .string "אז אני אראה לך!\n"
    .string "זה בשבילך!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
    .string "זה נאגט!\p"
    .string "אין לי שום עצות חכמות\n"
    .string "לתת לך, אז זה יצטרך להספיק!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
    .string "אופס, התיק שלך גדוש לגמרי!\n"
    .string "אתן לך את זה מאוחר יותר.$"
