ThreeIsland_Text_IslandSign::
    .string "אי 3\n"
    .string "אי הקשר המשפחתי$"

ThreeIsland_Text_IslandBelongsToUs::
    .string "יאהו!\p"
    .string "מהיום והלאה, האי הזה\n"
    .string "שייך לנו!$"

ThreeIsland_Text_GoBackToKanto::
    .string "אנחנו לא צריכים שתביאו לפה\n"
    .string "רעש וצרות!\p"
    .string "אנחנו מבקשים שתחזרו\n"
    .string "לקאנטו!$"

ThreeIsland_Text_BossIsOnHisWay::
    .string "היי, לך לבכות במקום אחר.\n"
    .string "הבוס שלנו כבר בדרך.\p"
    .string "כשהוא יגיע, נעשה לך מופע\n"
    .string "אופנועים אדיר שלא תשכח\l"
    .string "בחיים!$"

ThreeIsland_Text_GetOffIslandNow::
    .string "מ-מה!? בחיים לא!\n"
    .string "תסתלקו מהאי עכשיו!$"

ThreeIsland_Text_WhosGonnaMakeMe::
    .string "ומי בדיוק יכריח אותי?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
    .string "אתה הבוס?\n"
    .string "תחזור לקאנטו מיד!$"

ThreeIsland_Text_JustGotHerePal::
    .string "הא?\p"
    .string "רק עכשיו הגעתי לכאן, חבר.\p"
    .string "מה זה היחס העוין הזה?\n"
    .string "ממש לא יפה מצדך!$"

ThreeIsland_Text_FollowersRaisingHavoc::
    .string "האנשים שלך משתוללים כאן\n"
    .string "עם האופנועים.\p"
    .string "יש לך בכלל מושג כמה\n"
    .string "צרות הם גרמו לנו\l"
    .string "כאן באי?$"

ThreeIsland_Text_OughtToBeThankingUs::
    .string "לא, אחי, אני ממש לא מבין.\p"
    .string "תסתכל על המקום הזה.\n"
    .string "מה אתם עושים פה בשביל כיף?\p"
    .string "אתם צריכים להודות לנו על זה\n"
    .string "שהכנסנו חיים לכפר הישנוני.\p"
    .string "אבל היי, אם אתה מתעקש, תנסה\n"
    .string "לגרום לנו לעזוב.$"

ThreeIsland_Text_YouCowardsToughInPack::
    .string "גררר… פחדנים שכמותכם…\n"
    .string "גיבורים רק בחבורה…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
    .string "אתה, על מה אתה בוהה?\n"
    .string "לא לימדו אותך שזה לא יפה?\p"
    .string "אתה רוצה לעשות מזה עניין\n"
    .string "או מה?$"

ThreeIsland_Text_ThatsSmart::
    .string "זה חכם מצדך.\n"
    .string "אל תתערב בזה.$"

ThreeIsland_Text_Biker1Intro::
    .string "חה, אני אוהב את האומץ שלך.\n"
    .string "אתה תפסיד לי כסף, אבל…$"

ThreeIsland_Text_Biker1Defeat::
    .string "מ…\n"
    .string "מה זה הילד הזה?!$"

ThreeIsland_Text_Biker1PostBattle::
    .string "אוף, נו באמת…\n"
    .string "שלא תעז לצחוק!$"

ThreeIsland_Text_Biker2Intro::
    .string "אתה לא מקאנטו?\n"
    .string "אתה אמור להיות בצד שלנו!$"

ThreeIsland_Text_Biker2Defeat::
    .string "תפסיק עם השטויות!$"

ThreeIsland_Text_Biker2PostBattle::
    .string "מה הבעיה שלך,\n"
    .string "למה אתה מתלהט ככה?\p"
    .string "ממש לא מגניב, אחי!$"

ThreeIsland_Text_Biker3Intro::
    .string "הזמנו את הבוס לכאן,\n"
    .string "והיית חייב להרוס הכול!\p"
    .string "ביישת אותנו, אחי!$"

ThreeIsland_Text_Biker3Defeat::
    .string "… … …   … … …$"

ThreeIsland_Text_Biker3PostBattle::
    .string "בוס, אני אומר לך, אתה חייב\n"
    .string "לעשות משהו עם הילד הזה!$"

ThreeIsland_Text_PaxtonIntro::
    .string "עקבתי אחריך, ואני אומר\n"
    .string "שכבר עשית מספיק.\p"
    .string "מה אתה, חבר שלהם\n"
    .string "או משהו?\p"
    .string "אז אני מניח שתילחם בי\n"
    .string "במקומם.$"

ThreeIsland_Text_PaxtonDefeat::
    .string "בסדר, מספיק!\n"
    .string "נעזוב כמו שרצית!\p"
    .string "נשמח לא לראות יותר את\n"
    .string "האי המשעמם הזה!$"

ThreeIsland_Text_PaxtonPostBattle::
    .string "פחח! כן, תמשיך להסתובב\n"
    .string "עם האיכרים האלה!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
    .string "תודה לך! הבריונים האלה\n"
    .string "היו רק צרות צרורות.\p"
    .string "אוי, תראה, הפוקימון שלך\n"
    .string "נפצע בגללי.$"

ThreeIsland_Text_GivenFullRestore::
    .string "{PLAYER} קיבל\n"
    .string "שיחזור מלא.$"

ThreeIsland_Text_OhYourBagIsFull::
    .string "אה?\n"
    .string "התיק שלך מלא.$"

ThreeIsland_Text_YouveGotImpressiveMons::
    .string "יש לך פוקימונים ממש\n"
    .string "מרשימים.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
    .string "יהיה נהדר אם מישהו חזק\n"
    .string "כמוך יגור כאן.\p"
    .string "אני מקווה שלפחות תישאר\n"
    .string "כאן קצת.\p"
    .string "…סליחה?\n"
    .string "אתה מחפש את לוסטל?\p"
    .string "לוסטל הלכה לכיוון גשר\n"
    .string "בונד לפני זמן מה.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
    .string "אי 3 הוא בעצם המאוכלס\n"
    .string "ביותר מבין האיים כאן.\p"
    .string "ועדיין, הוא קצת מנומנם מדי.\p"
    .string "אבל לא הייתי רוצה לראות כאן\n"
    .string "שוב בריונים כמו האופנוענים.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
    .string "אני הולך לאמן את הדודו שלי\n"
    .string "ביער הפירות.\p"
    .string "כשהוא יתפתח, אני הולך\n"
    .string "לשחק משחק באי 2.$"

ThreeIsland_Text_Doduo::
    .string "דודו: גיגיה!$"
