MtMoon_1F_Text_MarcosIntro::
    .string "וואו!\n"
    .string "הבהלת אותי!\l"
    .string "…אה, אתה סתם ילד!$"

MtMoon_1F_Text_MarcosDefeat::
    .string "וואו!\n"
    .string "הבהלה השנייה היום!$"

MtMoon_1F_Text_MarcosPostBattle::
    .string "ילדים כמוך לא צריכים להסתובב\n"
    .string "כאן בחושך.$"

MtMoon_1F_Text_JoshIntro::
    .string "הגעת גם אתה לחקור את המערה?$"

MtMoon_1F_Text_JoshDefeat::
    .string "להפסיד זה מבאס!\n"
    .string "זה כל כך לא מגניב.$"

MtMoon_1F_Text_JoshPostBattle::
    .string "ירדתי עד לכאן רק כדי להרשים\n"
    .string "בנות.$"

MtMoon_1F_Text_MiriamIntro::
    .string "וואו! זה הרבה יותר גדול\n"
    .string "ממה שחשבתי!$"

MtMoon_1F_Text_MiriamDefeat::
    .string "אוי!\n"
    .string "הפסדתי!$"

MtMoon_1F_Text_MiriamPostBattle::
    .string "איך יוצאים מכאן?\n"
    .string "זה כל כך גדול, אני עלולה ללכת\l"
    .string "לאיבוד.$"

MtMoon_1F_Text_JovanIntro::
    .string "מה!\n"
    .string "אל תתפוס אותי בהפתעה!$"

MtMoon_1F_Text_JovanDefeat::
    .string "הפוקימונים שלי לא מספיק טובים!$"

MtMoon_1F_Text_JovanPostBattle::
    .string "אני חייב למצוא פוקימונים חזקים.\n"
    .string "איפה הם יכולים להיות?$"

MtMoon_1F_Text_IrisIntro::
    .string "מה?\n"
    .string "אני מחכה לחברים שלי שימצאו\l"
    .string "אותי כאן.$"

MtMoon_1F_Text_IrisDefeat::
    .string "הפסדתי?$"

MtMoon_1F_Text_IrisPostBattle::
    .string "באתי כי שמעתי שיש כאן\n"
    .string "מאובנים נדירים מאוד.$"

MtMoon_1F_Text_KentIntro::
    .string "אנשים חשודים במערה הזאת.\n"
    .string "מה איתך?$"

MtMoon_1F_Text_KentDefeat::
    .string "תפסת אותי!$"

MtMoon_1F_Text_KentPostBattle::
    .string "ראיתי אותם!\n"
    .string "אני בטוח שהם מצוות רוקט!$"

MtMoon_1F_Text_RobbyIntro::
    .string "אתה צריך לעבור דרך המערה הזאת\n"
    .string "כדי להגיע לעיר סרוליאן.$"

MtMoon_1F_Text_RobbyDefeat::
    .string "הפסדתי.$"

MtMoon_1F_Text_RobbyPostBattle::
    .string "זובאט זה פוקימון קשוח!\n"
    .string "אבל אם תתפוס אחד, תוכל לסמוך\l"
    .string "עליו.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
    .string "תיזהר!\n"
    .string "זובאט הוא מוצץ דם!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
    .string "שלום, אני חופר פה מאובנים\n"
    .string "מתחת להר הירח.\p"
    .string "לפעמים ברוק ממכון פיוטר עוזר לי.$"
