SevenIsland_TrainerTower_Text_DarioIntro::
    .string "חשתי בהתקרבותך.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
    .string "אני מוותר…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
    .string "בעתידך אני חש שתפגוש\n"
    .string "רבים אחרים.\p"
    .string "אני חושב שכוח מוזר\n"
    .string "יקשור ביניכם.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
    .string "אי שם באי הזה ישנים\n"
    .string "פוקימונים מוזרים.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
    .string "איזה מאמן מדהים!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
    .string "אי שם באי הזה ישנים\n"
    .string "פוקימונים מוזרים.\p"
    .string "יכול להיות שהם\n"
    .string "מחכים דווקא לך?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
    .string "הכניסה למגדל המאמנים\n"
    .string "מאמנים, עמדו באתגר!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
    .string "מגדל המאמנים לפניך$"

@ Unused text perhaps indicating Trainer Tower was planned to be unlocked by something
SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
    .string "トレーナータワーには\n"
    .string "いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
    .string "トレーナータワーが　あいてる！\n"
    .string "さっそく　はいってみよう！$"

