VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
    .string "לא תעריך את הזנב\n"
    .string "החמוד של פיקאצ'ו שלי?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
    .string "האמפ!\p"
    .string "הפיקאצ'ו שלי חמוד פי שניים\n"
    .string "מהפיקאצ'ו ההוא!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
    .string "אני פשוט מתה על הסיל שלי!\n"
    .string "הוא כל כך חמוד!\p"
    .string "הוא צווח, “קיואו” כשאני\n"
    .string "מחבקת אותו!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
    .string "אה, לא!\p"
    .string "הסיל שלי הרבה יותר אטרקטיבי.\n"
    .string "פי שניים הייתי אומר.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
    .string "פיקאצ'ו: צ'ו! פיקאצ'ו!$"

VermilionCity_PokemonFanClub_Text_Seel::
    .string "סיל: קיו!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
    .string "אני יושב ראש מועדון הפוקימונים!\p"
    .string "אני מגדל יותר ממאה\n"
    .string "פוקימונים!\p"
    .string "אני מאוד בררן כשזה נוגע\n"
    .string "לפוקימונים!\p"
    .string "אז…\p"
    .string "האם הגעת לבקר כדי לשמוע על\n"
    .string "הפוקימונים שלי?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
    .string "טוב!\n"
    .string "אז תקשיב!\p"
    .string "הרפידאש האהוב עליי…\p"
    .string "הוא…חמוד…נפלא…חכם…\n"
    .string "וגם…מדהים…אתה חושב כך?…\l"
    .string "אה כן…זה…מדהים…\l"
    .string "אדיב…לאהוב אותו!\p"
    .string "חיבוק אותו…כש…הוא ישן…חם\n"
    .string "ומלטף…מרהיב…\l"
    .string "…אופס! תסתכל על השעה!\l"
    .string "עיקבתי אותך יותר מדי זמן!\p"
    .string "תודה ששמעת אותי!\n"
    .string "אני רוצה שתיקח את זה!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
    .string "{PLAYER} קיבלת שובר לאופניים\n"
    .string "מהיושב ראש.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
    .string "קח את שובר האופניים הזה ל\n"
    .string "חנות האופניים בעיר סרוליאן.\p"
    .string "החלף את זה באופניים\n"
    .string "בחינם!\p"
    .string "אל תדאג, הפירו האהוב עליי\n"
    .string "יעוף אותי לכל מקום שאני צריך ללכת.\p"
    .string "אז, אין לי צורך באופניים.\p"
    .string "אני מקווה שתאהב לרכב!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
    .string "אה. חזור כשאתה רוצה\n"
    .string "לשמוע את הסיפור שלי!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
    .string "שלום, {PLAYER}!\p"
    .string "האם הגעת לראות אותי שוב על\n"
    .string "הפוקימונים שלי?\p"
    .string "לא?\n"
    .string "חבל!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
    .string "פנה מקום לזה!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
    .string "היושב ראש שלנו מאוד מדברני\n"
    .string "על פוקימונים.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
    .string "בואו נקשיב בנימוס למאמנים\n"
    .string "אחרים!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
    .string "אם מישהו מתפאר, תתפאר גם אתה!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
    .string "היושב ראש שלנו באמת אוהב את\n"
    .string "הפוקימונים שלו.\p"
    .string "אבל האדם הכי אהוב על ידי\n"
    .string "פוקימונים הוא דייזי, אני חושב.$"
