PokemonTower_7F_Text_Grunt1Intro::
    .string "מה אתה רוצה?\n"
    .string "למה אתה כאן?$"

PokemonTower_7F_Text_Grunt1Defeat::
    .string "אני מוותר!$"

PokemonTower_7F_Text_Grunt1PostBattle::
    .string "אני לא אשכח את זה!$"

PokemonTower_7F_Text_Grunt2Intro::
    .string "הזקן הזה צעד ישר לתוך\n"
    .string "המחבוא שלנו.\p"
    .string "ואז, הוא התחיל להתלונן על איך\n"
    .string "צוות רוקט מתעלל בפוקימונים.\p"
    .string "אז, אנחנו פשוט מדברים על זה\n"
    .string "כמבוגרים.$"

PokemonTower_7F_Text_Grunt2Defeat::
    .string "בבקשה!\n"
    .string "לא עוד!$"

PokemonTower_7F_Text_Grunt2PostBattle::
    .string "פוקימונים טובים רק בשביל\n"
    .string "להרוויח כסף. למה לא להשתמש בהם?\p"
    .string "תישאר מחוץ לעסקים שלנו!$"

PokemonTower_7F_Text_Grunt3Intro::
    .string "אתה לא מציל אף אחד, ילד!$"

PokemonTower_7F_Text_Grunt3Defeat::
    .string "אל תילחם נגד צוות רוקט!$"

PokemonTower_7F_Text_Grunt3PostBattle::
    .string "אתה לא תצא מזה!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
    .string "מר פוג'י: הא?\n"
    .string "באת להציל אותי?\p"
    .string "תודה. אבל, באתי לכאן מרצוני\n"
    .string "החופשי.\p"
    .string "באתי להרגיע את רוחה של\n"
    .string "אמא של קיובון.\p"
    .string "אני חושב שרוחו של מארוואק\n"
    .string "סוף סוף עזבה אותנו.\p"
    .string "אני חייב להודות לך על הדאגה\n"
    .string "האכפתית שלך.\p"
    .string "בוא אחריי לביתי, בית הפוקימונים,\n"
    .string "בתחתית המגדל הזה.$"
