PewterCity_Museum_1F_Text_Its50YForChildsTicket::
    .string "כן, כן.\n"
    .string "המחיר הוא ¥05 לכרטיס ילד.\p"
    .string "היית רוצה להיכנס?$"

PewterCity_Museum_1F_Text_ComeAgain::
    .string "חזור שוב!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
    .string "נכון, ¥05!\n"
    .string "תודה רבה!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
    .string "אין לך מספיק כסף.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
    .string "בבקשה תהנה מהביקור.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
    .string "אי אפשר להיכנס מאחורה!\n"
    .string "ניסיון נחמד, ילד, אבל לא.\p"
    .string "אה, מה שתגיד!\n"
    .string "אתה יודע מה זה אמבר?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
    .string "האמבר מכיל את החומר הגנטי\n"
    .string "של פוקימונים קדומים.\p"
    .string "יש מעבדה איפשהו שמנסה להחיות\n"
    .string "פוקימונים מתוך האמבר.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
    .string "האמבר הוא למעשה שרף, החומר\n"
    .string "הדביק שנוזל מעצים.\p"
    .string "השרף הקדום התאבק לאורך זמן\n"
    .string "והפך לאמבר קשיח כמו סלע.$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
    .string "אני צריך להיות אסיר תודה על\n"
    .string "חיי הארוכים.\p"
    .string "מעולם לא חשבתי שאזכה לראות את\n"
    .string "עצמות הדרקון!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
    .string "ששש! תקשיב, אני חייב לשתף\n"
    .string "מישהו בסוד.\p"
    .string "אני חושב שהחתיכת אמבר הזו\n"
    .string "מכילה DNA של פוקימון!\p"
    .string "זו תהיה פריצת דרך מדעית מדהימה\n"
    .string "אם ניתן יהיה להחיות פוקימונים\l"
    .string "מהאמבר הזה.\p"
    .string "אבל, הקולגות שלי פשוט מתעלמים\n"
    .string "ממה שיש לי להגיד.\p"
    .string "אז, יש לי בקשה!\p"
    .string "אני רוצה שתיקח את זה לבדיקה\n"
    .string "במעבדת פוקימון כלשהי.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
    .string "{PLAYER} קיבל את האמבר הישן\n"
    .string "מהאיש.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
    .string "ששש!\n"
    .string "תבדוק את האמבר הישן!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
    .string "אין לך מקום בשביל זה.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
    .string "יש לנו שני מאובנים נדירים של\n"
    .string "פוקימונים פרה-היסטוריים בתצוגה.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
    .string "ישנו חתיכת אמבר יפה בצבע\n"
    .string "זהב שקוף.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "מאובן של אירודקטייל\n"
    .string "פוקימון פרימיטיבי ונדיר.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "מאובן של קאבוטופס\n"
    .string "פוקימון פרימיטיבי ונדיר.$"
