SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
    .string "רקוד, רקוד!\n"
    .string "ריקוד הצ'נסי!\p"
    .string "תצטרף גם אתה!\n"
    .string "רקוד, רקוד!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
    .string "רוצה לרקוד?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
    .string "קדימה, תרקוד!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
    .string "{PLAYER} רקד את ריקוד הצ'נסי!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
    .string "אהאהאהאהא!\p"
    .string "הנה, עכשיו אתה מלא מרץ!\n"
    .string "איזה מזל!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
    .string "צ'נסי: צ'נסי! צ'נסי!$"
