Route18_Text_WiltonIntro::
    .string "אני תמיד בודק כל אזור דשא\n"
    .string "כדי למצוא פוקימונים חדשים.$"

Route18_Text_WiltonDefeat::
    .string "אוף!$"

Route18_Text_WiltonPostBattle::
    .string "הלוואי והיו לי אופניים!$"

Route18_Text_RamiroIntro::
    .string "קורוקוקו!\n"
    .string "איך הציפור שלי נשמעת?$"

Route18_Text_RamiroDefeat::
    .string "הייתי חייב להציק לך!$"

Route18_Text_RamiroPostBattle::
    .string "אני אוסף פוקימונים ימיים בסופי\n"
    .string "שבוע כי הים כל כך קרוב.$"

Route18_Text_JacobIntro::
    .string "זה השטח שלי!\n"
    .string "תעוף מפה!$"

Route18_Text_JacobDefeat::
    .string "לעזאזל!$"

Route18_Text_JacobPostBattle::
    .string "זה האזור האהוב עליי לתפיסת\n"
    .string "פוקימונים.$"

Route18_Text_RouteSign::
    .string "שביל 81\n"
    .string "עיר סלדון - עיר פוקסיה$"

Route18_Text_CyclingRoadSign::
    .string "שביל האופניים\n"
    .string "אין כניסה להולכי רגל!$"
