Text_SeismicTossTeach::
    .string "הסודות של החלל…\n"
    .string "המסתורין של האדמה…\p"
    .string "יש כל כך הרבה דברים שאנחנו\n"
    .string "יודעים עליהם מעט.\p"
    .string "אבל זה צריך להמריץ אותנו ללמוד\n"
    .string "יותר, לא לוותר.\p"
    .string "הדבר היחיד שצריך לזרוק…\p"
    .string "ובכן, מה דעתך על המהלך מכה ססמית?\n"
    .string "האם ללמד אותה לפוקימון?$"

Text_SeismicTossDeclined::
    .string "האם כך?\n"
    .string "אני בטוח שתחזור כדי ללמוד זאת.$"

Text_SeismicTossWhichMon::
    .string "איזה פוקימון רוצה ללמוד את\n"
    .string "המהלך מכה ססמית?$"

Text_SeismicTossTaught::
    .string "אני מקווה שלא תוותר.\n"
    .string "תמשיך כך.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
    .string "אבן ירח, הא?\p"
    .string "מה כל כך מיוחד בה?\n"
    .string "נראית לי כמו סתם אבן רגילה.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
    .string "02 ביולי, 9691!\p"
    .string "בני האדם דרכו לראשונה על\n"
    .string "הירח ביום הזה.\p"
    .string "קניתי טלוויזיה צבעונית רק כדי\n"
    .string "לצפות בחדשות האלה.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
    .string "החודש, אנחנו מריצים תערוכה\n"
    .string "בנושא חלל.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
    .string "אני רוצה פיקאצ'ו!\n"
    .string "הוא כל כך חמוד!\p"
    .string "ביקשתי מאבא שלי לתפוס לי אחד!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
    .string "כן, פיקאצ'ו בקרוב, אני מבטיח!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
    .string "מעבורת חלל$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
    .string "מטאוריט שנפל על הר הירח.\n"
    .string "נחשב להיות אבן ירח.$"
