SafariZone_SecretHouse_Text_CongratsYouveWon::
    .string "אה! סוף סוף!\p"
    .string "אתה הראשון שהגיע ל\n"
    .string "הבית הסודי!\p"
    .string "למרות שעשיתי קמפיין\n"
    .string "לפתיחה הגדולה שלנו,\p"
    .string "התחלתי לדאוג שאף אחד\n"
    .string "לא ינצח את פרס הקמפיין שלנו.\p"
    .string "מזל טוב!\n"
    .string "זכית!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
    .string "{PLAYER} קיבל את מ”נ30\n"
    .string "מהמאבטח!$"

SafariZone_SecretHouse_Text_ExplainSurf::
    .string "מ”נ30 זה גלישה.\p"
    .string "הפוקימון יוכל לשוט איתך\n"
    .string "על פני המים עם זה.\p"
    .string "וה-מ”נ הזה לא בזבזני, אז\n"
    .string "תוכל להשתמש בו שוב ושוב.\p"
    .string "אתה ממש בר מזל שזכית בפרס\n"
    .string "המדהים הזה!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
    .string "אין לך מקום עבור\n"
    .string "הפרס המדהים הזה!$"
