Route19_Text_RichardIntro::
    .string "אני צריך להתחמם ולתרגל\n"
    .string "לפני שאני יוצא לשחות.$"

Route19_Text_RichardDefeat::
    .string "מחומם ומוכן!$"

Route19_Text_RichardPostBattle::
    .string "תודה, ילד!\n"
    .string "אני מוכן לשחות.$"

Route19_Text_ReeceIntro::
    .string "חכה! תאט קצת!\n"
    .string "זה לא בריא ללב שלך!$"

Route19_Text_ReeceDefeat::
    .string "אוי!\n"
    .string "זה קריר!$"

Route19_Text_ReecePostBattle::
    .string "תיזהר מ-טנטאקורל.\n"
    .string "העקיצה שלהם מאוד כואבת.$"

Route19_Text_MatthewIntro::
    .string "אני אוהב לשחות!\n"
    .string "מה איתך?$"

Route19_Text_MatthewDefeat::
    .string "נפילה כואבת!$"

Route19_Text_MatthewPostBattle::
    .string "אני יכול אפילו לנצח פוקימונים\n"
    .string "ימיים בשחייה.$"

Route19_Text_DouglasIntro::
    .string "מה נמצא מעבר לאופק?$"

Route19_Text_DouglasDefeat::
    .string "בלעתי מים!$"

Route19_Text_DouglasPostBattle::
    .string "אני רואה כמה איים שם\n"
    .string "באופק!$"

Route19_Text_DavidIntro::
    .string "ניסיתי לצלול ולמצוא פוקימונים,\n"
    .string "אבל זה לא עבד.$"

Route19_Text_DavidDefeat::
    .string "עזרה!$"

Route19_Text_DavidPostBattle::
    .string "כנראה שצריך לדוג כדי למצוא\n"
    .string "פוקימונים ימיים.$"

Route19_Text_TonyIntro::
    .string "אני מביט על הים כדי לשכוח\n"
    .string "את כל הדברים הרעים שקרו.$"

Route19_Text_TonyDefeat::
    .string "אוי!\n"
    .string "טראומטי!$"

Route19_Text_TonyPostBattle::
    .string "אני מביט על הים כדי לשכוח\n"
    .string "את מה שקרה.$"

Route19_Text_AnyaIntro::
    .string "וואו, אני אוהבת את הכלי רכב שלך!\n"
    .string "תוכל לתת לי אותו אם אנצח?$"

Route19_Text_AnyaDefeat::
    .string "אוי, הפסדתי!$"

Route19_Text_AnyaPostBattle::
    .string "עדיין יש דרך ארוכה עד\n"
    .string "לאיי הקצף…\p"
    .string "אני רוצה לחזור לפוקסיה…$"

Route19_Text_AliceIntro::
    .string "שחייה זה כיף!\n"
    .string "כוויות שמש לא!$"

Route19_Text_AliceDefeat::
    .string "הלם!$"

Route19_Text_AlicePostBattle::
    .string "החבר שלי רצה לשחות\n"
    .string "עד איי הקצף.$"

Route19_Text_AxleIntro::
    .string "היי, שם!\n"
    .string "המים האלו מסוכנים!$"

Route19_Text_AxleDefeat::
    .string "אוי!\n"
    .string "איזו סכנה!$"

Route19_Text_AxlePostBattle::
    .string "הרגליים שלי! נתפסו לי השרירים!\n"
    .string "גלוב, גלוב…$"

Route19_Text_ConnieIntro::
    .string "שחיתי לכאן עם החברים שלי…\n"
    .string "אני עייפה…$"

Route19_Text_ConnieDefeat::
    .string "אני מותשת…$"

Route19_Text_ConniePostBattle::
    .string "אם הייתי רוכבת על פוקימון בים,\n"
    .string "הייתי רוצה שיהיה זה לאפרס.\p"
    .string "לאפרס כל כך גדול, אני חושבת\n"
    .string "שהוא ישמור עליי יבשה.$"

Route19_Text_RouteSign::
    .string "נתיב מים 91\n"
    .string "פוקסיה - איי הקצף$"

Route19_Text_LiaIntro::
    .string "ליאה: אני שומרת על אחי הקטן.\n"
    .string "הוא הפך למאמן פוקימונים.$"

Route19_Text_LiaDefeat::
    .string "ליאה: ככה מתייחסים לאח\n"
    .string "הקטן שלי?!$"

Route19_Text_LiaPostBattle::
    .string "ליאה: יש לך אח קטן?\n"
    .string "אני מקווה שאתה מלמד אותו\n"
    .string "דברים טובים.$"

Route19_Text_LiaNotEnoughMons::
    .string "ליאה: אני רוצה להילחם יחד עם\n"
    .string "אחי הקטן.\p"
    .string "אין לך שני פוקימונים?$"

Route19_Text_LucIntro::
    .string "לוק: אחותי הגדולה לימדה אותי\n"
    .string "לשחות ולאמן פוקימונים.$"

Route19_Text_LucDefeat::
    .string "לוק: וואו!\n"
    .string "מישהו חזק יותר מאחותי הגדולה!$"

Route19_Text_LucPostBattle::
    .string "לוק: אחותי הגדולה חזקה ונחמדה.\n"
    .string "אני חושב שהיא מדהימה!$"

Route19_Text_LucNotEnoughMons::
    .string "לוק: אני לא רוצה להילחם אם\n"
    .string "לא אוכל להילחם יחד עם אחותי.\p"
    .string "אין לך שני פוקימונים?$"
