SevenIsland_TanobyRuins_Text_BrandonIntro::
    .string "אתה יודע משהו על\n"
    .string "חדר האבן הזה?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
    .string "זה היה מיותר.\n"
    .string "לא היית צריך להיות כזה גס.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
    .string "חורבות טאנובי הן בנות\n"
    .string "0051 שנה לפחות.\p"
    .string "אבל זו תעלומה גדולה\n"
    .string "למה בכלל בנו אותן.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
    .string "מספרים שפוקימון מיסטי\n"
    .string "ישן כאן בפנים.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
    .string "אני לא כזה טוב בקרבות.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
    .string "שמעתי שיש עוד חורבות\n"
    .string "כמו אלה שכאן.\p"
    .string "אולי הן מקומות המנוחה\n"
    .string "של פוקימונים מיסטיים אחרים?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
    .string "קליפורד מלמד אותי\n"
    .string "לצייר.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
    .string "אולי נסתבך בצרות\n"
    .string "אם נרעיש כאן.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
    .string "אמרתי שאני רוצה לצייר\n"
    .string "מבנה עתיק.\p"
    .string "אז קליפורד הביא אותי לכאן.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
    .string "היום, מלבד השיעור שלנו,\n"
    .string "באנו לראות את החדר.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
    .string "הו, כמה יוצא דופן.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
    .string "אה, אז אתה חוקר פוקימונים\n"
    .string "בכוחות עצמך…\p"
    .string "כן, אתה בהחלט אדם\n"
    .string "יוצא דופן, אין ספק.$"
