CeruleanCity_House1_Text_AnyInterestInBerries::
    .string "אני רוקח מגוון תרופות\n"
    .string "מאבקת פירות יער.\p"
    .string "בעזרת אבקת פירות יער איכותית\n"
    .string "אני יודע להכין כל סוג של תרופה.\p"
    .string "עכשיו תגיד לי, אתה מתעניין בפירות\n"
    .string "יער?$"

CeruleanCity_House1_Text_HaveJustTheThing::
    .string "או, יופי! אז יש לי את הדבר\n"
    .string "בדיוק בשבילך.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
    .string "יש משהו חדש בקומה השנייה של\n"
    .string "מרכזי פוקימון, זה נמצא בפינה\l"
    .string "הישירה.\p"
    .string "הם התקינו מכונה על חוטית\n"
    .string "שטוחנת פירות יער.\p"
    .string "פה אתה נכנס לתמונה.\p"
    .string "יש לי טובה לבקש ממך\p"
    .string "תוכל להכין עבורי אבקת פירות יער\n"
    .string "בעזרת המכונה הזו?\p"
    .string "אל תשכח, המכונה נמצאת בפינה\n"
    .string "הישירה במרכזי פוקימון.\p"
    .string "אני ארקח עבורך תרופות אם\n"
    .string "תביא לי אבקת פירות יער.\p"
    .string "אל תשכח, טתחן פירות יער כדי\n"
    .string "שיהפכו לאבקת פירות יער, והבא אותה\l"
    .string "אלי.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
    .string "למה אתה משקר לי?\p"
    .string "כמה פירות יער יש לך?\n"
    .string "אפילו לא אחד!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
    .string "אתה לא מתעניין בפירות יער?\p"
    .string "אדון צעיר, זה חשוב להתעניין\n"
    .string "בכל מיני נושאים.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
    .string "אה אהם! נו הבאת לי\n"
    .string "אבקת פירות יער?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
    .string "עם מה תרצה להחליף\n"
    .string "את זה?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
    .string "אתה תחליף את אבקת פירות היער שלך\n"
    .string "עבור{STR_VAR_1} אחד?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
    .string "הממ? אין לך מספיק\n"
    .string "אבקת פירות יער.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
    .string "זו אבקת פירות יער מצויינת.\n"
    .string "אני יכול להכין ממנה תרופה מעולה.\p"
    .string "תרצה להחליף עוד אבקה עבור\n"
    .string "משהו אחר?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
    .string "אוקיי.\n"
    .string "אני מקווה לראות אותך שוב בקרוב.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
    .string "בוא לראות אותי אם תרצה להחליף\n"
    .string "את אבקת פירות היער שלך.$"
