Route20_Text_BarryIntro::
    .string "המים רדודים כאן.\n"
    .string "יש הרבה אנשים שוחים.$"

Route20_Text_BarryDefeat::
    .string "השפריץ!$"

Route20_Text_BarryPostBattle::
    .string "הלוואי שיכולתי לרכוב על הפוקימון\n"
    .string "שלי. אני בטוח שאתה לא עייף.$"

Route20_Text_ShirleyIntro::
    .string "האיים הימיים הם מפלט שקט.\n"
    .string "אני כאן בנופש.$"

Route20_Text_ShirleyDefeat::
    .string "תפסיק עם זה!$"

Route20_Text_ShirleyPostBattle::
    .string "יש מערה ענקית מתחת לאי הזה.$"

Route20_Text_TiffanyIntro::
    .string "אני אוהבת לצוף עם הדגים\n"
    .string "כאן בין הגלים.$"

Route20_Text_TiffanyDefeat::
    .string "איי!$"

Route20_Text_TiffanyPostBattle::
    .string "רוצה לצוף יחד איתי?$"

Route20_Text_IreneIntro::
    .string "גם אתה כאן בחופשה?$"

Route20_Text_IreneDefeat::
    .string "בלי רחמים בכלל!$"

Route20_Text_IrenePostBattle::
    .string "בעבר הרחוק, האיים הימיים היו אי\n"
    .string "בודד.$"

Route20_Text_DeanIntro::
    .string "תראה איזה גוף חטוב יש לי!$"

Route20_Text_DeanDefeat::
    .string "חלש!$"

Route20_Text_DeanPostBattle::
    .string "הייתי צריך לחזק את הפוקימון שלי\n"
    .string "ולא אותי!$"

Route20_Text_DarrinIntro::
    .string "למה אתה רוכב על פוקימון?\n"
    .string "אתה לא יודע לשחות?$"

Route20_Text_DarrinDefeat::
    .string "אוי!\n"
    .string "טורפדתי!$"

Route20_Text_DarrinPostBattle::
    .string "לרכוב על פוקימון נראה ממש כיף!$"

Route20_Text_RogerIntro::
    .string "רכבתי לכאן על פוקימון מעופף.$"

Route20_Text_RogerDefeat::
    .string "אוי, לא!\n"
    .string "מה אעשה עכשיו?$"

Route20_Text_RogerPostBattle::
    .string "הציפורים שלי מותשות.\n"
    .string "הן לא יכולות לעוף ולהחזיר אותי!$"

Route20_Text_NoraIntro::
    .string "החבר שלי נתן לי פנינים גדולות.$"

Route20_Text_NoraDefeat::
    .string "אוי, לא!\n"
    .string "הפנינים שלי היו בפנים!$"

Route20_Text_NoraPostBattle::
    .string "האם הפנינים שלי יגדלו בתוך\n"
    .string "קלויסטר?$"

Route20_Text_MissyIntro::
    .string "שחיתי לכאן מאי סינאבר.\n"
    .string "זה לא היה קל, אני אומרת לך.$"

Route20_Text_MissyDefeat::
    .string "אני כל כך מאוכזבת!$"

Route20_Text_MissyPostBattle::
    .string "הפוקימונים השתלטו על אחוזה\n"
    .string "נטושה באי סינאבר.\p"
    .string "עכשיו קוראים לה אחוזת הפוקימון.$"

Route20_Text_MelissaIntro::
    .string "בסינאבר שבמערב יש מעבדה לפוקימון.\p"
    .string "אבא שלי עובד שם.$"

Route20_Text_MelissaDefeat::
    .string "רגע!\n"
    .string "אתה אמור לחכות!$"

Route20_Text_MelissaPostBattle::
    .string "סינאבר הוא אי געשי.\p"
    .string "שמעתי שהוא התרומם מתוך הים\n"
    .string "כשהר געש התפרץ.$"

Route20_Text_SeafoamIslands::
    .string "האיים הימיים$"

Route20_Text_MistyTrainsHere::
    .string "מאמנים חזקים ופוקימון מים נפוצים\n"
    .string "באזור הזה.\p"
    .string "אומרים שמיסטי ממכון סרוליאן\n"
    .string "מתאמנת כאן.$"
