SilphCo_2F_Text_ConnorIntro::
    .string "הצילו!\n"
    .string "אני עובד בארגון סילף.$"

SilphCo_2F_Text_ConnorDefeat::
    .string "איך ידעת\n"
    .string "שאני שייך לצוות רוקט?$"

SilphCo_2F_Text_ConnorPostBattle::
    .string "אני עובד גם בארגון סילף וגם ב\n"
    .string "צוות רוקט.$"

SilphCo_2F_Text_JerryIntro::
    .string "אסור להיכנס כאן!\n"
    .string "לך הביתה!$"

SilphCo_2F_Text_JerryDefeat::
    .string "אתה טוב.$"

SilphCo_2F_Text_JerryPostBattle::
    .string "אתה יכול לפתור את המבוך כאן?\n"
    .string "זה לא קל, אני אומר לך!$"

SilphCo_2F_Text_Grunt1Intro::
    .string "אסור לילדים להיות כאן!$"

SilphCo_2F_Text_Grunt1Defeat::
    .string "קשה!$"

SilphCo_2F_Text_Grunt1PostBattle::
    .string "האריחים בצורת יהלום הם בלוקי\n"
    .string "השתגרות.\p"
    .string "הם מעבירי אנשים בבניין הזה\n"
    .string "ההייטק.$"

SilphCo_2F_Text_Grunt2Intro::
    .string "היי, ילד!\n"
    .string "מה אתה עושה פה?$"

SilphCo_2F_Text_Grunt2Defeat::
    .string "פישלתי!$"

SilphCo_2F_Text_Grunt2PostBattle::
    .string "ארגון סילף יהיה שייך לצוות רוקט!$"

Text_ThunderWaveTeach::
    .string "איייי!\n"
    .string "לא! תפסיק! עזרה!\p"
    .string "אה, אתה לא עם צוות רוקט.\n"
    .string "סליחה, חשבתי…\p"
    .string "האם תסלח לי אם אלמד\n"
    .string "אותך את טכניקת גל רעם?$"

Text_ThunderWaveDeclined::
    .string "אה…\n"
    .string "אבל גל רעם היא מאוד שימושית…$"

Text_ThunderWaveWhichMon::
    .string "לאיזה פוקימון אני אמור ללמד\n"
    .string "את גל רעם?$"

Text_ThunderWaveTaught::
    .string "גל רעם גורמת לשיתוק אצל\n"
    .string "הפוקימון היריב.\p"
    .string "פוקימון משותק עשוי לא להיות\n"
    .string "יכול להניע במהלך הקרב.\p"
    .string "זו התקפה מסוג חשמלי, אז היא\n"
    .string "לא תעבוד על כמה פוקימונים.$"

SilphCo_2F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 2$"
