Route21_South_Text_JackIntro::
	.string "תפסתי את הפוקימונים שלי בים.$"

Route21_South_Text_JackDefeat::
	.string "צוללן!!\n"
	.string "שוקע!!$"

Route21_South_Text_JackPostBattle::
	.string "איפה אתה תופס את הפוקימונים שלך?$"

Route21_South_Text_JeromeIntro::
	.string "עכשיו אני בתחרות איש ברזל.$"

Route21_South_Text_JeromeDefeat::
	.string "מתנשף…\n"
	.string "מתנשף… מתנשף…$"

Route21_South_Text_JeromePostBattle::
	.string "אני מותש! אבל נשאר לי עוד\n"
	.string "מירוץ אופניים ומרתון!$"

Route21_South_Text_RolandIntro::
	.string "אהה!\n"
	.string "תן לי להרגיש את השמש והרוח!$"

Route21_South_Text_RolandDefeat::
	.string "איי!\n"
	.string "הפסדתי!$"

Route21_South_Text_RolandPostBattle::
	.string "אני שרוף מהשמש לגמרי!$"

Route21_South_Text_ClaudeIntro::
	.string "היי, אל תפחיד את הדגים!$"

Route21_South_Text_ClaudeDefeat::
	.string "סליחה! פשוט אני מתוסכל כי\n"
	.string "לא תפסתי כלום.$"

Route21_South_Text_ClaudePostBattle::
	.string "איזה באסה, לא תפסתי כלום.\n"
	.string "אולי המקום הזה בכלל בריכה\l"
	.string "ענקית או משהו?$"

Route21_South_Text_NolanIntro::
	.string "תשמור לי על חברה עד שיהיה לי\n"
	.string "תפיסה.$"

Route21_South_Text_NolanDefeat::
	.string "זה לפחות שרף קצת זמן.$"

Route21_South_Text_NolanPostBattle::
	.string "רגע, רגע!\n"
	.string "יש לי תפיסה! כן!$"

Route21_North_Text_LilIntro::
	.string "ליל: הא? קרב?\n"
	.string "יאן, אתה לא יכול לבד?$"

Route21_North_Text_LilDefeat::
	.string "ליל: אה, רואה?\n"
	.string "הפסדנו. מרוצה עכשיו?$"

Route21_North_Text_LilPostBattle::
	.string "ליל: אני עייפה.\n"
	.string "לא נלך הביתה כבר?$"

Route21_North_Text_LilNotEnoughMons::
	.string "ליל: הא? קרב?\n"
	.string "אין לי כוח לעשות את זה לבד.\l"
	.string "תביא שני פוקימונים, טוב?$"

Route21_North_Text_IanIntro::
	.string "יאן: אחותי לא עושה מספיק כושר,\n"
	.string "אז גררתי אותה לכאן.$"

Route21_North_Text_IanDefeat::
	.string "יאן: אההה, ליל!\n"
	.string "תתאפסי על עצמך!$"

Route21_North_Text_IanPostBattle::
	.string "יאן: נו, ליל!\p"
	.string "את לא תרדי במשקל ככה!$"

Route21_North_Text_IanNotEnoughMons::
	.string "יאן: אנחנו רוצים קרב זוגות.\n"
	.string "אז תוכל להביא שני פוקימונים?$"
