FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
    .string "אתה מסתובב בכל מקום,\n"
    .string "נכון?\p"
    .string "אתה לא מאמן את הפוקימונים\n"
    .string "שלך קשה מדי, נכון?\p"
    .string "תן לי להעיף מבט.\n"
    .string "… … …   … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
    .string "אה, הממ…\n"
    .string "אני מבין, אני מבין…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
    .string "הו, מרשים.\n"
    .string "אתה מתייחס יפה לפוקימונים.\p"
    .string "אני חושב שאפשר להפקיד\n"
    .string "את זה בידיך.\p"
    .string "בבקשה, אשמח שתיקח את זה.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
    .string "{PLAYER} קיבל ביצה\n"
    .string "מהאיש!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
    .string "…לרוע המזל, אין לך מקום\n"
    .string "בשבילה בקבוצה שלך.\p"
    .string "כדאי שתחזור לקחת אותה\n"
    .string "בפעם אחרת.$"

@ Unused
FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
    .string "やあ\n"
    .string "タマゴを　もらいに\l"
    .string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
    .string "קיבלתי את הביצה הזאת\n"
    .string "כשהייתי במסע.\p"
    .string "אני שמח שפגשתי מישהו כמוך.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
    .string "הו, שלום.\n"
    .string "איזה {STR_VAR_2} חמוד.\p"
    .string "כשאני מסתכל עליו אני נזכר\n"
    .string "בילדה מתוקה שפגשתי במסע.\p"
    .string "היא סירקה פוקימונים בעדינות…\n"
    .string "היא הייתה מלאך קטן.\p"
    .string "השם של הילדה הזאת…\n"
    .string "נדמה לי שזה היה דייזי.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
    .string "זו סביבה מצוינת\n"
    .string "לגידול פוקימונים.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
    .string "הפוקימונים שלך גדלים\n"
    .string "בצורה מרשימה!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
    .string "אתה יודע, אני חושבת שיש לך\n"
    .string "כישרון להיות מגדל פוקימון.$"
