SafariZone_West_Text_RestHouse::
    .string "בית מנוחה$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
    .string "הודעת בקשה\p"
    .string "בבקשה תמצא את\n"
    .string "השיניים הזהובות\l"
    .string "האבודות של שומר הספארי.\l"
    .string "הן כאן איפשהו.\p"
    .string "פרס מוצע!\n"
    .string "ליצור קשר: שומר$"

SafariZone_West_Text_SearchForSecretHouse::
    .string "עצות מאמן\p"
    .string "קמפיין חקר האזור!\n"
    .string "החיפוש אחרי הבית הסודי!$"

SafariZone_West_Text_AreaSign::
    .string "אזור 3\n"
    .string "מזרח: אזור המרכז$"
