CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
    .string "איווי יכול להתפתח\n"
    .string "ל-1 מתוך 3 סוגים של פוקימונים.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
    .string "יש הודעת אימייל!\p"
    .string "...\p"
    .string "3 הציפורים האגדיות הן הפוקימונים\l"
    .string "ארטיקונו, זאפדוס, ומולטרס.\p"
    .string "מיקומם אינו ידוע.\p"
    .string "אנחנו מתכננים לחקור את המערה\l"
    .string "שליד העיר סרוליאן.\p"
    .string "מאת: צוות מחקר הפוקימון\p"
    .string "...$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
    .string "מקטרת ענבר!$"
