Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
    .string "בסדר, סדר שש פוקבולים\n"
    .string "בחגורה שלי…\p"
    .string "כן, זה יעשה את זה.\n"
    .string "מקסימום, אתה\n"
    .string "יכול להיות עם שישה פוקימונים.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
    .string "צוות רוקט תוקף את תושבי\n"
    .string "סרוליאן…\p"
    .string "אין יום שעובר בלי\n"
    .string "שצוות רוקט יהיה בחדשות.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
    .string "איש: שלום שם, ילד!\n"
    .string "יש לי עסקה מיוחדת בשבילך!\p"
    .string "אתן לך את הפוקימון הסודי\n"
    .string "מג'יקארפ רק ב¥005!\p"
    .string "אז, תקנה את זה, נכון?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
    .string "איש: שלום שם, מתוקה!\n"
    .string "יש לי עסקה מיוחדת בשבילך!\p"
    .string "אתן לך את הפוקימון הסודי\n"
    .string "מג'יקארפ רק ב¥005!\p"
    .string "אז, תקני את זה, נכון?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
    .string "{PLAYER} שילם סכום\n"
    .string "שערורייתי של ¥005 וקנה\n"
    .string "את המג'יקארפ…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
    .string "לא? אתה אומר לא?\n"
    .string "אני עושה את זה רק כטובה עבורך!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
    .string "אין יותר מקום לעוד\n"
    .string "פוקימונים, נראה.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
    .string "תזדקק ליותר כסף מזה!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
    .string "איש: טוב, אני לא נותן החזרות.\n"
    .string "ידעת מה אתה קונה!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
    .string "לפעמים, יהיו לך יותר מדי\n"
    .string "פוקימונים כדי להוסיף עוד.\p"
    .string "במקרה כזה, פשוט כדאי\n"
    .string "שתאחסן כמה בעזרת כל מחשב.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
    .string "זה עיתון.$"
