SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
    .string "קפטן: אווררר…\n"
    .string "אני מרגיש נורא…\l"
    .string "אורפ! מחלת ים…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
    .string "{PLAYER} שפשף את גבו של\n"
    .string "הקפטן!\p"
    .string "שפשוף-שפשוף…\n"
    .string "שפשוף-שפשוף…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
    .string "קפטן: פיו! תודה לך!\n"
    .string "אני מרגיש הרבה יותר טוב עכשיו.\p"
    .string "אתה רוצה לראות את טכניקת\n"
    .string "החיתוך הנסתרת שלי?\p"
    .string "יכולתי להראות לך את טכניקת\n"
    .string "החיתוך היקרה שלי אם לא הייתי חולה…\p"
    .string "אני יודע! אתה יכול לקבל את זה!\n"
    .string "זה מהלך נסתר!\p"
    .string "למד את החיתוך לפוקימון שלך,\n"
    .string "ותוכל לראות אותו חותך בכל זמן!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
    .string "{PLAYER} קיבל את מ”נ10\n"
    .string "מהקפטן!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
    .string "באמצעות חיתוך, אתה יכול לכרות\n"
    .string "עצים קטנים.\p"
    .string "למה שלא תנסה את זה עם העצים\n"
    .string "סביב עיר ורמיליון?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
    .string "קפטן: …פיו!\p"
    .string "עכשיו שאני כבר לא חולה,\n"
    .string "אני מניח שהגיע הזמן.\p"
    .string "ה-S.S. אן יצא להפלגה בקרוב!\p"
    .string "להתראות, עד שנחזור\n"
    .string "לעיר ורמיליון!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
    .string "אוי, לא!\n"
    .string "אין לך מקום בשביל זה!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
    .string "איכס!\n"
    .string "לא הייתי צריך להסתכל!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
    .string "איך להתגבר על מחלת ים…\n"
    .string "הקפטן קורא את זה!$"
