PalletTown_RivalsHouse_Text_HiBrothersAtLab::
    .string "דייזי: הי,  {PLAYER}!\p"
    .string "אח שלי, {RIVAL}, נמצא במעבדה\p"
    .string "של סבא שלנו.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
    .string "דייזי: {PLAYER}, שמעתי שהיה לך\n"
    .string "קרב נגד {RIVAL}.\p"
    .string "הלוואי שהייתי שם לראות את זה!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
    .string "סבא ביקש ממך לעשות משהו בשבילו?\p"
    .string "הוא נהיה ממש עצלן.\n"
    .string "הנה, זה יעזור לך.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
    .string "{PLAYER} קיבל את המפה מדייזי.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
    .string "אין לך מקום בשביל זה בתיק שלך.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
    .string "אתה יכול להשתמש במפה כדי להבין\n"
    .string "איפה אתה, או כדי לבדוק מה השמות\l"
    .string "של מקומות.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
    .string "דייזי: כמו בני אדם גם פוקימונים\n"
    .string "הם יצורים חיים.\p"
    .string "כשהם מתעייפים תדאג לתת להם לנוח.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
    .string "זו מפה של כל מחוז קאנטו.\n"
    .string "זה יהיה שימושי!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
    .string "המדפים מלאים בספרים על פוקימונים.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
    .string "דייזי: הי,  {PLAYER}!\n"
    .string "תזמון מצויין.\p"
    .string "בדיוק הכנתי תה, אתה רוצה\n"
    .string "להצטרף אלי?\p"
    .string "אוייש, הפוקימונים שלך נראים\n"
    .string "קצת מלוכלכים.\p"
    .string "תרצה שאטפח אחד מהם?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
    .string "אתה לא רוצה שאטפח את הפוקימונים\n"
    .string "שלך? בסדר, בוא רק נשתה תה.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
    .string "איזה פוקימון תרצה שאטפח עבורך?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
    .string "דייזי: אין בעיה, הוא יראה מצויין\n"
    .string "ממש עוד רגע.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
#ifdef BUGFIX @ The localizers missed what should be a textcolor change in the localizations.
    .string "{COLOR DARK_GRAY}{STR_VAR_1} נראה חולמני ומרוצה…\p"
    .string "{COLOR RED}דייזי: הנה! סיימתי.\n"
#else @ In the JP games, gender-based text used a different font instead of different colors.
    .string "{FONT_NORMAL}{STR_VAR_1} נראה חולמני ומרוצה…\p"
    .string "{FONT_FEMALE}דייזי: הנה! סיימתי.\n"
#endif
    .string "רואה? הוא לא נראה נהדר?\p"
    .string "חיחי…\n"
    .string "זה פוקימון כל כך חמוד.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
    .string "אוי, אני מצטערת, אני לא יכולה\n"
    .string "לטפח ביצה, רק פוקימונים.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
    .string "דייזי: הפוקימונים שלך ילמדו לאהוב\n"
    .string "אותך אם תגדל אותם באהבה.\p"
    .string "לדוגמא, {PLAYER}, אני יכולה לראות\n"
    .string "את הפוקימון הראשון שלך?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
    .string "הפוקימון שלך אוהב אותך מעבר\n"
    .string "למה שמילים יכולות לתאר.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
    .string "הוא נראה מאוד שמח ומרוצה.\p"
    .string "הלוואי ש{RIVAL} היה פה לראות את\n"
    .string "זה אולי הוא היה לומד ממך משהו.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
    .string "נראה שהוא מרוצה למדי.\n"
    .string "תמשיך להתייחס אליו טוב!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
    .string "הוא מתחיל לחבב אותך.\n"
    .string "האמון בניכים מתחיל לצמוח.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
    .string "הוא עדיין לא מכיר אותך כל כך\p"
    .string "פןקימונים קצת נרתאים כשהם פוגשים\n"
    .string "אותך לראשונה.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
    .string "{PLAYER}, אני לא אוהבת את הצורה\n"
    .string "שבה הוא מסתכל עליך.\p"
    .string "תוכל לנסות להיות יותר נחמד אליו?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
    .string "זה לא קל לי להגיד את זה, אבל...\p"
    .string "אתה יודע מה הסיבה שהפוקימון\n"
    .string "שלך שונא אותך כל כך?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
    .string "“קלפרי” המתוקה והחמודה$"

