SafariZone_East_Text_KeepAnyItemFoundOnSafari::
    .string "אתה יכול לשמור כל פריט שתמצא ב\n"
    .string "אזור הספארי.\p"
    .string "אבל, תסיים את הזמן אם תנסה\n"
    .string "לקחת את כולם בבת אחת.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
    .string "לך לחלק העמוק ביותר של\n"
    .string "אזור הספארי. תזכה בפרס!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
    .string "ה-איבי שלי התפתח ל-\n"
    .string "פלייריאון.\p"
    .string "אבל, ה-איבי של חבר הפך ל-\n"
    .string "ואפוריון. תוהה למה?$"
