ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
    .string "היי, שמעת את החדשות?\p"
    .string "רשת המחשבים כאן יכולה\n"
    .string "עכשיו להתחבר לאלה שבקאנטו.\p"
    .string "אני לא יודע איך זה קרה,\n"
    .string "אבל זה פנטסטי!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
    .string "אי אפשר לגלוש בין האיים\n"
    .string "באזורים האלה.\p"
    .string "הזרמים מהירים ומסוכנים\n"
    .string "מדי.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
    .string "בואו נמעך פירות יער!\n"
    .string "…זה בזבוז של פירות?\p"
    .string "תמיד אפשר למצוא פירות\n"
    .string "על הקרקע ביער הפירות.$"
