OneIsland_KindleRoad_Text_MariaIntro::
    .string "מזג האוויר מהמם!\n"
    .string "מושלם לקרב!$"

OneIsland_KindleRoad_Text_MariaDefeat::
    .string "אאאאיייי!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
    .string "אל תתיז לי מים על הפנים!\n"
    .string "תהרוס לי את האיפור.$"

OneIsland_KindleRoad_Text_AbigailIntro::
    .string "אני מתחילה להישרף מהשמש…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
    .string "אוף, אתה ממש נורא.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
    .string "אני אוהבת את הכובע שלך.\n"
    .string "אולי כדאי שגם אני אחבוש כזה…$"

OneIsland_KindleRoad_Text_FinnIntro::
    .string "מכאן נראה שהר אמבר מתנשא\n"
    .string "אל תוך השמיים.$"

OneIsland_KindleRoad_Text_FinnDefeat::
    .string "וואו, אתה ממש קשוח, אה?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
    .string "השמיים באזורים האלה\n"
    .string "פשוט עצומים.$"

OneIsland_KindleRoad_Text_GarrettIntro::
    .string "לקחתי הפסקה מהשחייה,\n"
    .string "ואתה בא לאתגר אותי?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
    .string "היי, מה זה…\n"
    .string "אתה ממש טוב!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
    .string "במקום להשתמש בגלישה כל הזמן,\n"
    .string "כדאי שתשחה קצת בעצמך.$"

OneIsland_KindleRoad_Text_TommyIntro::
    .string "רגע! רגע אחד!\n"
    .string "נדמה לי שתפסתי דג ענק!$"

OneIsland_KindleRoad_Text_TommyDefeat::
    .string "שוב הפסדתי הכול…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
    .string "לא רק שהפסדתי, גם הדג הענק\n"
    .string "ברח לי!$"

OneIsland_KindleRoad_Text_SharonIntro::
    .string "תוכל לעזור לי קצת\n"
    .string "עם האימונים שלי?$"

OneIsland_KindleRoad_Text_SharonDefeat::
    .string "היית ברמה גבוהה משלי.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
    .string "ברור שאתה מיומן.\n"
    .string "אתה מוצא חן בעיניי!$"

OneIsland_KindleRoad_Text_TanyaIntro::
    .string "אין יום שבו אנחנו\n"
    .string "לא מתאמנים!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
    .string "איזו טיפשה אני!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
    .string "מעכשיו אתאמן עוד יותר קשה!$"

OneIsland_KindleRoad_Text_SheaIntro::
    .string "כל בוקר, לפני ארוחת הבוקר,\n"
    .string "אני שוחה סביב האי הזה.$"

OneIsland_KindleRoad_Text_SheaDefeat::
    .string "הוף…\n"
    .string "הוף…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
    .string "הפסדתי כי אני מותש מכל\n"
    .string "הריצה שעשיתי…$"

OneIsland_KindleRoad_Text_HughIntro::
    .string "תתלבש כמו שצריך לקרב!\n"
    .string "תוריד את התלבושת המצחיקה!$"

OneIsland_KindleRoad_Text_HughDefeat::
    .string "למה דווקא אני?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
    .string "אפילו לוחמי קרב מגע נעשים\n"
    .string "מודעים לאופנה בימינו…$"

OneIsland_KindleRoad_Text_BryceIntro::
    .string "אתה יודע, בטבע כל דבר\n"
    .string "פשוט טעים יותר.$"

OneIsland_KindleRoad_Text_BryceDefeat::
    .string "אוףף, פספסתי!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
    .string "המים באזורים געשיים\n"
    .string "טעימים במיוחד.$"

OneIsland_KindleRoad_Text_ClaireIntro::
    .string "אכלנו צהריים ושבענו,\n"
    .string "אז אולי קרב קטן להתעמלות?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
    .string "זה גרם לי להזיע.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
    .string "מה אני אעשה?\n"
    .string "אני שוב מתה מרעב.$"

OneIsland_KindleRoad_Text_KiaIntro::
    .string "קיה: אני והאח הגדול שלי\n"
    .string "צמד מנצח!$"

OneIsland_KindleRoad_Text_KiaDefeat::
    .string "קיה: הא?!\n"
    .string "אני לא מאמינה!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
    .string "קיה: איך יכול להיות מישהו\n"
    .string "טוב יותר מהאח הגדול שלי?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
    .string "קיה: אם אתה רוצה להילחם\n"
    .string "בנו, אתה חייב להביא איתך\l"
    .string "לפחות שני פוקימונים.$"

OneIsland_KindleRoad_Text_MikIntro::
    .string "מיק: יחד עם קיה אני\n"
    .string "לא מפחד מכלום!$"

OneIsland_KindleRoad_Text_MikDefeat::
    .string "מיק: וואו!\n"
    .string "זה יותר מדי!$"

OneIsland_KindleRoad_Text_MikPostBattle::
    .string "מיק: איך הצמד שלי עם קיה\n"
    .string "יכול היה להיכשל?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
    .string "מיק: היי, בא לך להילחם\n"
    .string "בשנינו?\p"
    .string "אז תביא איתך שני פוקימונים\n"
    .string "או יותר.$"

OneIsland_KindleRoad_Text_RouteSign::
    .string "זוהי דרך קינדל.\p"
    .string "המשך ישר להר אמבר.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "הצת את האש שבלבך!\n"
    .string "ספא אמבר$"

