SilphCo_5F_Text_RocketsInUproarAboutIntruder::
    .string "צוות רוקט בהמולה על\n"
    .string "איזה פולש.\p"
    .string "זה אתה, נכון?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
    .string "צוות רוקט ברחו!\n"
    .string "אתה הגיבור שלנו! תודה!$"

SilphCo_5F_Text_Grunt1Intro::
    .string "שמעתי על ילד שמסתובב\n"
    .string "סביבות כאן.$"

SilphCo_5F_Text_Grunt1Defeat::
    .string "בום!$"

SilphCo_5F_Text_Grunt1PostBattle::
    .string "לא חכם להתעמת עם\n"
    .string "צוות רוקט!$"

SilphCo_5F_Text_BeauIntro::
    .string "אנחנו לומדים טכנולוגיית פוקי בול\n"
    .string "בקומה הזו.$"

SilphCo_5F_Text_BeauDefeat::
    .string "לעזאזל!\n"
    .string "קללה!$"

SilphCo_5F_Text_BeauPostBattle::
    .string "עבדנו על פוקי בול\n"
    .string "הכי מתקדם, שיתפוס כל דבר.$"

SilphCo_5F_Text_DaltonIntro::
    .string "מההה?\p"
    .string "אסור שיהיו ילדים\n"
    .string "כאן!$"

SilphCo_5F_Text_DaltonDefeat::
    .string "אוי, אלוהים!$"

SilphCo_5F_Text_DaltonPostBattle::
    .string "אתה עדיין בקומה 5.\n"
    .string "הדרך ארוכה עד לבוס שלי!$"

SilphCo_5F_Text_Grunt2Intro::
    .string "תראה קצת כבוד לצוות רוקט!$"

SilphCo_5F_Text_Grunt2Defeat::
    .string "קח…\n"
    .string "קח…$"

SilphCo_5F_Text_Grunt2PostBattle::
    .string "זה מזכיר לי.\p"
    .string "קופינג מתפתח לויזינג!$"

SilphCo_5F_Text_PorygonFirstVRMon::
    .string "זה דיווח פוקימון!\p"
    .string "מעבדת פוקימון יצרה את פוריגון,\n"
    .string "הפוקימון הראשון במציאות וירטואלית.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
    .string "זה דיווח פוקימון!\p"
    .string "אושר מעל 053 טכניקות פוקימון\n"
    .string "המאושרות.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
    .string "זה דיווח פוקימון!\p"
    .string "כמה פוקימונים אושרו\n"
    .string "כמתפתחים כאשר הם מומרות.$"

SilphCo_5F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 5$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
    .string "החלאות שלקחו את הבניין שלנו…\p"
    .string "הבוס שלהם אמר שהוא מחפש\n"
    .string "פוקימונים חזקים.\p"
    .string "אני מקווה שהנשיא שלנו הצליח\n"
    .string "להימנע מבעיות…$"
