Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "בוא נראה...\n"
	.string "אוי! תפסת רק\l"
	.string "{STR_VAR_3} סוגים של פוקימונים!\p"
	.string "אתה צריך {STR_VAR_1} סוגים\n"
	.string "אם אתה רוצה את ה{STR_VAR_2}.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "...אה. אני מבין.\p"
	.string "כשתתפוס {STR_VAR_1} סוגים של\n"
	.string "פוקימונים, תחזור בשביל\l"
	.string "ה{STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "אה! אני רואה שאין לך\n"
	.string "מקום בשביל ה{STR_VAR_2}.$"
