@ Same as Hoenn's day-care text, used by the Four Island Day-Care. Unused text translated in Emerald

DayCare_Text_ImDaycareManSpeakToMyWife::
	.string "אני מנהל מעון יום.\p"
	.string "אני עוזר לטפל בפוקימונים של\n"
	.string "מאמנים.\p"
	.string "אם תרצה שאעזור לגדל את אחד\n"
	.string "הפוקימונים שלך, תדבר עם אישתי.$"

DayCare_Text_DoYouWantEgg::
	.string "הא, הנה אתה!\p"
	.string "גידלנו את הפוקימון שלך, ופתאום\n"
	.string "וואו איזו הפתעה זו הייתה!\p"
	.string "הפוקימון שלך הטיל ביצה!\p"
	.string "אנחנו לא יודעים איך זה קרה,\n"
	.string "אבל הפוקימון שלך עשה את זה.\p"
	.string "אז אתה רוצה אותה?$"

DayCare_Text_YourMonIsDoingFine::
	.string "הנה אתה, טוב לראות אותך.\n"
	.string "{STR_VAR_1} מסתדר פה מצויין.$"

DayCare_Text_IllKeepIt::
	.string "בסדר גמור, אני אמשיך לטפל בו\n"
	.string "תודה!$"

DayCare_Text_YouHaveNoRoomForIt::
	.string "אין לך מקום בשביל זה...\n"
	.string "תחזור אחרי שפינת לזה מקום.$"

DayCare_Text_ReceivedEgg::
	.string "{PLAYER} קיבל ביצה ממנהל\n"
	.string "מכון היום.$"

DayCare_Text_TakeGoodCareOfIt::
	.string "תטפל בהם היטב.$"

DayCare_Text_SeeWifeIfYouWantToPickUpMon::
	.string "ポケモンを　ひきとりたい　ときは\n"
	.string "ばさんに　いって　おくれ$"

DayCare_Text_YourMonsAreDoingFine::
	.string "הא, הנה אתה! {STR_VAR_1}\n"
	.string "ו{STR_VAR_2} מסתדרים פה מצויין.$"

DayCare_Text_IWillKeepDoYouWantIt::
	.string "אני אמשיך לשמור עליו.\n"
	.string "אתה בטוח שזה מה שאתה רוצה?$"

DayCare_Text_WouldYouLikeUsToRaiseMon::
	.string "אני מנהלת במכון היום.\p"
	.string "אנחנו יכולים לגדל פוקימונים עבורך.\p"
	.string "תרצה שנגדל עבורך אחד?$"

DayCare_Text_WhichMonShouldWeRaise::
	.string "איזה פוקימון תרצה שנגדל עבורך?$"

DayCare_Text_WellRaiseYourMon::
	.string "בסדר, נגדל עבורך את {STR_VAR_1}\n"
	.string "לבנתיים.\p"
	.string "תחזור בשבילו בהמשך.$"

DayCare_Text_WeCanRaiseOneMore::
	.string "אנחנו יכולים לגדל עבורך\n"
	.string "שני פוקימונים.\p"
	.string "תרצה שנגדל עבורך עוד פוקימון?$"

DayCare_Text_HusbandWasLookingForYou::
	.string "בעלי מחפש אותך.$"

DayCare_Text_FineThenComeAgain::
	.string "הו, אוקי.\n"
	.string "נתראה פעם הבאה.$"

DayCare_Text_NotEnoughMoney::
	.string "אין לך מספיק כסף...$"

DayCare_Text_TakeOtherOneBackToo::
	.string "אתה לוקח בחזרה גם את השני?$"

DayCare_Text_ComeAgain::
	.string "בסדר.\n"
	.string "נתראה פעם הבאה.$"

DayCare_Text_GoodToSeeYou::
	.string "הא, הנה אתה!\n"
	.string "טוב לראות אותך.\p"
	.string "הפוקימון שלך מסתדר פה מצויין.$"

DayCare_Text_YourMonHasGrownXLevels::
	.string "{STR_VAR_1} עלה {STR_VAR_2} רמות.$"

DayCare_Text_YourPartyIsFull::
	.string "הקבוצה שלך מלאה.\n"
	.string "תפנה מקום ותחזור אלי.$"

DayCare_Text_TakeBackWhichMon::
	.string "どっちの　ポケモンを　ひきとるかい？$"

DayCare_Text_ItWillCostX::
	.string "אם אתה רוצה את {STR_VAR_1}\n"
	.string "בחזרה, זה יעלה ¥{STR_VAR_2}.$"

DayCare_Text_HeresYourMon::
	.string "מצויין!\n"
	.string "הנה הפוקימון שלך.$"

DayCare_Text_TookBackMon::
	.string "{PLAYER} לקח בחזרה את\n"
	.string "{STR_VAR_1} ממנהלת מכון היום.$"

DayCare_Text_YouHaveJustOneMon::
	.string "אוי, יש לך רק פוקימון\n"
	.string "אחד.\p"
	.string "תחזור בפעם אחרת.$"

DayCare_Text_TakeYourMonBack::
	.string "תרצה את הפוקימון שלך בחזרה?$"

DayCare_Text_WhatWillYouBattleWith::
	.string "אם תשאיר את הפוקימון אצלי,\n"
	.string "לא יהיה לך עם מי להילחם.\p"
	.string "תחזור בפעם אחרת.$"

DayCare_Text_Huh::
	.string "הא?$"
