gFameCheckerFlavorText_ProfOak0:: @ 0x81AD106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מעבדת המחקר של פרופסור אוק$"

gFameCheckerFlavorText_ProfOak1:: @ 0x81AD145
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ליצור מדריך מלא על כל\n"
	.string "הפוקימונים בעולם...\p"
	.string "זה היה החלום שלי!$"

gFameCheckerFlavorText_ProfOak2:: @ 0x81AD1BB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}פרופסור אוק אולי לא נראה כמו הרבה,\n"
	.string "אבל הוא הסמכות בנושא פוקימונים.\p"
	.string "מאמנים רבים מחזיקים אותו\n"
	.string "בהערכה רבה.$"

gFameCheckerFlavorText_ProfOak3:: @ 0x81AD258
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}פרופסור אוק מתגורר עם\n"
	.string "נכדיו, דייזי ו{RIVAL}.$"

gFameCheckerFlavorText_ProfOak4:: @ 0x81AD2B9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}שמעתי שאוק מגלה הרבה\n"
	.string "עניין בך, ילד.\p"
	.string "הזקן הזה היה פעם חזק\n"
	.string "ויפה תואר.\p"
	.string "אבל זה היה לפני עשרות שנים.\n"
	.string "הוא צל של מה שהיה פעם.$"

gFameCheckerFlavorText_ProfOak5:: @ 0x81AD377
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}פרופסור אוק עומד להיות לו\n"
	.string "תוכנית רדיו בקרוב.\p"
	.string "התוכנית תיקרא סמינר\n"
	.string "הפוקימונים של פרופסור אוק.$"

gFameCheckerFlavorText_Daisy0:: @ 0x81AD40C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אם תראה לדייזי את הפוקימון שלך,\n"
	.string "היא יכולה להגיד כמה הוא אוהב אותך.\p"
	.string "מדי פעם, היא אפילו מטפחת\n"
	.string "פוקימון בשבילך.$"

gFameCheckerFlavorText_Daisy1:: @ 0x81AD4AE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אבל האדם שהכי אהוב על\n"
	.string "הפוקימונים היא דייזי, אני חושב.$"

gFameCheckerFlavorText_Daisy2:: @ 0x81AD516
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}היא טיפחה פוקימונים בעדינות...\n"
	.string "היא הייתה מלאך קטן.\p"
	.string "שמה של הילדה הקטנה הזו...\n"
	.string "אני חושב שזה היה דייזי.$"

gFameCheckerFlavorText_Daisy3:: @ 0x81AD5A7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}פרופסור אוק מתגורר עם\n"
	.string "נכדיו, דייזי ו{RIVAL}.$"

gFameCheckerFlavorText_Daisy4:: @ 0x81AD608
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ילדה מעיירת פאלט, דייזי,\n"
	.string "נהנית מתה כל יום.\p"
	.string "היא מבקרת בחנות הכלבו של סלדון\n"
	.string "כדי לקנות קצת תה.$"

gFameCheckerFlavorText_Daisy5:: @ 0x81AD69F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אלופת האביב בתחרות הפוקימונים\n"
	.string "היא דייזי אוק מעיירת\l"
	.string "פאלט!$"

gFameCheckerFlavorText_Brock0:: @ 0x81AD705
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים בעיר פיוטר\n"
	.string "מנהיג: ברוק\l"
	.string "מאמן הפוקימונים המוצק כסלע!$"

gFameCheckerFlavorText_Brock1:: @ 0x81AD771
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}כוח הרצון הקשוח שלי ניכר\n"
	.string "אפילו בפוקימונים שלי.\p"
	.string "הפוקימונים שלי כולם קשוחים כסלע\n"
	.string "ובעלי נחישות אמיתית.\p"
	.string "נכון - כל הפוקימונים שלי הם מסוג\n"
	.string "סלע!$"

gFameCheckerFlavorText_Brock2:: @ 0x81AD840
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אין הרבה מאמני פוקימונים\n"
	.string "רציניים כאן.\p"
	.string "כולם כמו לוכדי חרקים,\n"
	.string "אתה יודע, סתם חובבנים.\p"
	.string "אבל ברוק ממכון פיוטר לא כזה,\n"
	.string "בכלל לא.$"

gFameCheckerFlavorText_Brock3:: @ 0x81AD908
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ברוק מגניב. הוא לא רק קשוח.\n"
	.string "אנשים אוהבים ומכבדים אותו.\p"
	.string "אני רוצה להיות מנהיג מכון\n"
	.string "כמוהו.$"

gFameCheckerFlavorText_Brock4:: @ 0x81AD99A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}היי, אני חופר מאובנים כאן\n"
	.string "מתחת להר ירח.\p"
	.string "לפעמים, ברוק ממכון פיוטר\n"
	.string "נותן לי יד.$"

gFameCheckerFlavorText_Brock5:: @ 0x81ADA27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ברוק נדיר צוחק, אבל אומרים שהוא\n"
	.string "לא יכול להפסיק אם הוא מתחיל.$"

gFameCheckerFlavorText_Misty0:: @ 0x81ADA91
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים בעיר צלסטיק\n"
	.string "מנהיגה: מיסטי\l"
	.string "בת הים הפרועה!$"

gFameCheckerFlavorText_Misty1:: @ 0x81ADAF6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}המדיניות שלי היא התקפה מלאה\n"
	.string "עם פוקימונים מסוג מים!$"

gFameCheckerFlavorText_Misty2:: @ 0x81ADB5A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מיסטי היא מאמנת שתמשיך\n"
	.string "להשתפר.\p"
	.string "היא לא תפסיד למישהו כמוך!$"

gFameCheckerFlavorText_Misty3:: @ 0x81ADBD9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מאמנים חזקים ופוקימוני מים\n"
	.string "הם מראה נפוץ באזורים האלה.\p"
	.string "אומרים שמיסטי ממכון\n"
	.string "צלסטיק מתאמנת כאן.$"

gFameCheckerFlavorText_Misty4:: @ 0x81ADC72
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}המצוק הזה הוא מקום דייטים מפורסם.\p"
	.string "למיסטי, מנהיגת המכון, יש תקוות\n"
	.string "גדולות לגבי המקום הזה.$"

gFameCheckerFlavorText_Misty5:: @ 0x81ADCEB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אומרים שמיסטי מעריצה את לורליי\n"
	.string "מהרביעייה העילית.$"

gFameCheckerFlavorText_LtSurge0:: @ 0x81ADD3C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים בעיר ורמיליון\n"
	.string "מנהיג: סגן סרג'\l"
	.string "האמריקאי המחשמל!$"

gFameCheckerFlavorText_LtSurge1:: @ 0x81ADDA7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני אומר לך, ילד, פוקימוני חשמל\n"
	.string "הצילו אותי במלחמה!$"

gFameCheckerFlavorText_LtSurge2:: @ 0x81ADE0B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}כשהייתי בצבא, סגן סרג'\n"
	.string "היה המפקד הקשוח שלי.\p"
	.string "הוא היה מדריך קשה.$"

gFameCheckerFlavorText_LtSurge3:: @ 0x81ADE82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}סגן סרג' תמיד היה ידוע\n"
	.string "באופיו הזהיר בצבא.$"

gFameCheckerFlavorText_LtSurge4:: @ 0x81ADEEC
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}סגן סרג' התקין את המלכודות במכון\n"
	.string "בעצמו.\p"
	.string "הוא הציב מנעולים כפולים בכל מקום.$"

gFameCheckerFlavorText_LtSurge5:: @ 0x81ADF6A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אומרים שסגן סרג' היה טייס\n"
	.string "כשהיה באמריקה.\p"
	.string "הוא השתמש בחשמל שנוצר על ידי\n"
	.string "פוקימונים כדי להפעיל את המטוס שלו.$"

gFameCheckerFlavorText_Erika0:: @ 0x81AE009
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים בעיר סלדון\n"
	.string "מנהיגת: אריקה\l"
	.string "הנסיכה אוהבת הטבע!$"

gFameCheckerFlavorText_Erika1:: @ 0x81AE072
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני תלמידה של אמנות\n"
	.string "סידור הפרחים.\p"
	.string "הפוקימונים שלי הם אך ורק\n"
	.string "מסוג דשא.$"

gFameCheckerFlavorText_Erika2:: @ 0x81AE0F3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}המנהיגה שלנו אריקה אולי שקטה,\n"
	.string "אבל היא מפורסמת באזור.$"

gFameCheckerFlavorText_Erika3:: @ 0x81AE15B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אנחנו משתמשים רק בפוקימוני דשא\n"
	.string "במכון שלנו.\p"
	.string "למה? אנחנו גם משתמשים בהם להכנת\n"
	.string "סידורי פרחים!$"

gFameCheckerFlavorText_Erika4:: @ 0x81AE1E5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}לעולם לא אאסוף פוקימונים\n"
	.string "אם הם לא יפים.$"

gFameCheckerFlavorText_Erika5:: @ 0x81AE247
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}יש שמועה שאם תציץ לתוך\n"
	.string "מכון סלדון, לעתים קרובות\l"
	.string "תראה את אריקה מנמנמת.$"

gFameCheckerFlavorText_Koga0:: @ 0x81AE2B6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים בעיר פוקסיה\n"
	.string "מנהיג: קוגה\l"
	.string "אדון הנינג'ה הרעיל$"

gFameCheckerFlavorText_Koga1:: @ 0x81AE31D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}התייאש מפני האימה הזוחלת של\n"
	.string "פוקימוני רעל!$"

gFameCheckerFlavorText_Koga2:: @ 0x81AE37D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}למרות שהפסדתי, אמשיך\n"
	.string "להתאמן לפי תורתו\l"
	.string "של קוגה, מאסטר הנינג'ה שלי.$"

gFameCheckerFlavorText_Koga3:: @ 0x81AE407
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אבי הוא מנהיג המכון של\n"
	.string "העיר הזו.\p"
	.string "אני מתאמנת להשתמש בפוקימוני רעל\n"
	.string "כמו אבי.$"

gFameCheckerFlavorText_Koga4:: @ 0x81AE48D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אומרים שלקוגה יש ידע מעמיק\n"
	.string "ברפואה.\p"
	.string "הוא אפילו מכין תרופות כדי לטפל\n"
	.string "בפוקימונים שלו לבריאות.$"

gFameCheckerFlavorText_Koga5:: @ 0x81AE51B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אזור הספארי ענק, לא\n"
	.string "היית אומר?\p"
	.string "מנהיג מכון פוקסיה, קוגה, \n"
	.string "מסייר בשטח מדי פעם.\p"
	.string "הודות לו, אנחנו יכולים לשחק כאן\n"
	.string "בידיעה שאנחנו בטוחים.$"

gFameCheckerFlavorText_Sabrina0:: @ 0x81AE5E8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים בעיר זעפרן\n"
	.string "מנהיגת: סברינה\l"
	.string "המאסטרית של פוקימוני פסיכי!$"

gFameCheckerFlavorText_Sabrina1:: @ 0x81AE656
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}שמעת על מנהיגת המכון\n"
	.string "בעיר זעפרן?\p"
	.string "היא משתמשת בפוקימונים מסוג פסיכי,\n"
	.string "נכון?$"

gFameCheckerFlavorText_Sabrina2:: @ 0x81AE6D7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}יש לי כוחות פסיכיים מאז\n"
	.string "שהייתי ילדה.\p"
	.string "זה התחיל כשכף שזרקתי\n"
	.string "ברשלנות, התעקמה.$"

gFameCheckerFlavorText_Sabrina3:: @ 0x81AE762
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני לא אוהבת להילחם, אבל אם תרצה,\n"
	.string "אראה לך את הכוחות שלי!$"

gFameCheckerFlavorText_Sabrina4:: @ 0x81AE7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אנשים אומרים שסברינה יכולה\n"
	.string "לתקשר עם הפוקימונים שלה\l"
	.string "במהלך קרב בלי לדבר.$"

gFameCheckerFlavorText_Sabrina5:: @ 0x81AE841
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}סברינה פשוט חיסלה את מאסטר\n"
	.string "הקראטה בדלת הסמוכה.$"

gFameCheckerFlavorText_Blaine0:: @ 0x81AE89E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מכון פוקימונים באי סינבר\n"
	.string "מנהיג: בליין\l"
	.string "מאסטר החידות החם!$"

gFameCheckerFlavorText_Blaine1:: @ 0x81AE90A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הפוקימונים האשיים שלי כולם קשוחים\n"
	.string "ומוכנים עם חום עז!\p"
	.string "הם שורפים את כל המאתגרים!$"

gFameCheckerFlavorText_Blaine2:: @ 0x81AE990
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}המנהיג שלנו, בליין, אבד\n"
	.string "בהרים לגמרי.\p"
	.string "הלילה ירד כשפוקימון ציפור אש\n"
	.string "הופיע.\p"
	.string "האור שלו אפשר לבליין למצוא\n"
	.string "את דרכו למטה בבטחה.$"

gFameCheckerFlavorText_Blaine3:: @ 0x81AEA59
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}בליין ממכון סינבר הוא בחור\n"
	.string "די מוזר.\p"
	.string "הוא חי באי מזמן לפני\n"
	.string "שהמעבדה נבנתה.$"

gFameCheckerFlavorText_Blaine4:: @ 0x81AEAEE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}זו תמונה של בליין ו\n"
	.string "מר פוג'י.\p"
	.string "הם עומדים כתף אל כתף\n"
	.string "עם חיוכים גדולים.$"

gFameCheckerFlavorText_Blaine5:: @ 0x81AEB69
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אומרים שבליין מסיר את משקפי\n"
	.string "השמש הכהים שלו רק כשהוא חושב על\l"
	.string "שאלות חידה חדשות.$"

gFameCheckerFlavorText_Lorelei0:: @ 0x81AEBDF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני לורליי מהרביעייה העילית.$"

gFameCheckerFlavorText_Lorelei1:: @ 0x81AEC28
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אף אחד לא יכול לנצח אותי כשמדובר\n"
	.string "בפוקימוני קרח.$"

gFameCheckerFlavorText_Lorelei2:: @ 0x81AEC82
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איפה האדם הזה נולד?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}היה לנו מאמן גדול וחזק\n"
	.string "שגדל באי הזה.\p"
	.string "אני מתערב שאפילו אתה מכיר אותה.\n"
	.string "זו לורליי מהרביעייה העילית!$"

gFameCheckerFlavorText_Lorelei3:: @ 0x81AED27
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ידועה בסגנון הקרב הלוגי, המחושב\n"
	.string "והקר שלה, ללורליי\l"
	.string "יש סוד מפתיע!$"

gFameCheckerFlavorText_Lorelei4:: @ 0x81AEDAA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ידעת שללורליי יש המון\n"
	.string "בובות ממולאות?\p"
	.string "בכל פעם שהיא חוזרת\n"
	.string "לאי ארבע, האוסף שלה גדל!$"

gFameCheckerFlavorText_Lorelei5:: @ 0x81AEE51
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הלפרס שיש לה, אני מדמיין שזה\n"
	.string "זה שהיא פגשה כילדה.\p"
	.string "אני מאמין שזה היה במערת מפל הקרח\n"
	.string "שהיא תפסה אותו.\p"
	.string "אולי הפוקימון הזה היה איתה\n"
	.string "מאז ומתמיד.$"

gFameCheckerFlavorText_Bruno0:: @ 0x81AEF25
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני ברונו מהרביעייה העילית!$"

gFameCheckerFlavorText_Bruno1:: @ 0x81AEF6C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}חייתי והתאמנתי עם\n"
	.string "פוקימוני הלחימה שלי!$"

gFameCheckerFlavorText_Bruno2:: @ 0x81AEFC6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ברונו כנראה הצטרף לרביעייה\n"
	.string "העילית מתוך שאיפתו הבוערת\l"
	.string "להילחם במאמנים הטובים ביותר.$"

gFameCheckerFlavorText_Bruno3:: @ 0x81AF04C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ברונו, שהוא בכיר ממני,\n"
	.string "מבקר בספא מדי פעם.\p"
	.string "הוא בא לשיקום פציעות, גם\n"
	.string "שלו וגם של הפוקימונים שלו.$"

gFameCheckerFlavorText_Bruno4:: @ 0x81AF0F0
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הוא אחד מהרביעייה העילית.\n"
	.string "שמו ברונו.\p"
	.string "הוא הלך מאוכזב כשגילה\n"
	.string "שכל חטיפי הזעם\l"
	.string "נמכרו.$"

gFameCheckerFlavorText_Bruno5:: @ 0x81AF19A
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אפילו ברונו...\n"
	.string "הוא התאמן עם בחור בשם\l"
	.string "ברולי לפני כן.$"

gFameCheckerFlavorText_Agatha0:: @ 0x81AF200
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני אגתה מהרביעייה העילית.$"

gFameCheckerFlavorText_Agatha1:: @ 0x81AF248
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}פוקימוני הרוח של אגתה\n"
	.string "מפחידים באופן מזעזע בקשיחותם.$"

gFameCheckerFlavorText_Agatha2:: @ 0x81AF2B7
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}לזקנה הזו יש גם פתיל\n"
	.string "קצר מאוד.\p"
	.string "לא צריך הרבה כדי לגרום\n"
	.string "לגברת המפחידה הזו לצעוק.$"

gFameCheckerFlavorText_Agatha3:: @ 0x81AF34E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}בנעוריה, אגתה ופרופסור\n"
	.string "אוק היו יריבים שהתחרו על\l"
	.string "העליונות כמאמנים.$"

gFameCheckerFlavorText_Agatha4:: @ 0x81AF3BE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני שומעת שאוק גילה הרבה\n"
	.string "עניין בך, ילד.\p"
	.string "הזקן הזה היה פעם קשוח\n"
	.string "ויפה תואר.\p"
	.string "אבל זה היה לפני עשרות שנים.\n"
	.string "הוא צל של עצמו לשעבר.$"

gFameCheckerFlavorText_Agatha5:: @ 0x81AF47C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}קחי את אגתה, לדוגמה.\p"
	.string "היא קבעה שיא כחברת הרביעייה\n"
	.string "העילית המבוגרת ביותר אי פעם.$"

gFameCheckerFlavorText_Lance0:: @ 0x81AF4FD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני מוביל את הרביעייה העילית.\p"
	.string "אתה יכול לקרוא לי לאנס מאמן\n"
	.string "הדרקונים.$"

gFameCheckerFlavorText_Lance1:: @ 0x81AF567
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אתה יודע שדרקונים הם\n"
	.string "פוקימונים מיתיים.\p"
	.string "קשה לתפוס ולגדל אותם,\n"
	.string "אבל הכוחות שלהם עליונים.\p"
	.string "הם כמעט בלתי ניתנים להשמדה.\n"
	.string "אין להיות חכם איתם.$"

gFameCheckerFlavorText_Lance2:: @ 0x81AF641
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הוא עומד למען צדק!\n"
	.string "הוא מגניב, ועדיין נלהב!\l"
	.string "הוא הכי גדול, לאנס!$"

gFameCheckerFlavorText_Lance3:: @ 0x81AF6BA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}יש לנו לקוח, לאנס, שמגיע\n"
	.string "מדי פעם.\p"
	.string "הוא תמיד קונה גלימות.\p"
	.string "אני תוהה... האם יש לו הרבה\n"
	.string "גלימות זהות בבית?$"

gFameCheckerFlavorText_Lance4:: @ 0x81AF758
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}סבו של לאנס נחשב להיות\n"
	.string "הזקן של שבט מפורסם של\l"
	.string "אדוני דרקונים.$"

gFameCheckerFlavorText_Lance5:: @ 0x81AF7CB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ממה ששמעתי, ללאנס יש\n"
	.string "בן דוד שהוא מנהיג מכון\l"
	.string "במקום רחוק.$"

gFameCheckerFlavorText_Bill0:: @ 0x81AF83E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אחרי הכל, ביל מפורסם בעולם\n"
	.string "כפוקימניאק.\p"
	.string "הוא המציא את מערכת האחסון\n"
	.string "לפוקימונים במחשב.$"

gFameCheckerFlavorText_Bill1:: @ 0x81AF8CA
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}לביל יש המון פוקימונים!\n"
	.string "הוא אוסף גם נדירים!$"

gFameCheckerFlavorText_Bill2:: @ 0x81AF929
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הוא הנכד שלי!\p"
	.string "הוא תמיד אהב לאסוף דברים,\n"
	.string "אפילו כילד!$"

gFameCheckerFlavorText_Bill3:: @ 0x81AF998
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ביל הוא פוקימניאק, אז הוא אוהב\n"
	.string "כל סוג.\p"
	.string "כנראה, הראשון שהוא תפס\n"
	.string "היה אברה.$"

gFameCheckerFlavorText_Bill4:: @ 0x81AFA20
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}עיר הולדתו של ביל היא עיר גולדנרוד,\n"
	.string "שם הוריו עדיין גרים.\p"
	.string "שמעתי שזו עיר די\n"
	.string "חגיגית והומה.$"

gFameCheckerFlavorText_Bill5:: @ 0x81AFAB9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}כנראה, ביל פשוט לא יכול\n"
	.string "לסבול חלב בכלל.$"

gFameCheckerFlavorText_MrFuji0:: @ 0x81AFB0C
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הוא ממש נחמד.\p"
	.string "הוא דואג לפוקימונים נטושים\n"
	.string "ויתומים.$"

gFameCheckerFlavorText_MrFuji1:: @ 0x81AFB76
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הזקן הזה צעד ישר אל\n"
	.string "המחבוא שלנו.\p"
	.string "ואז, הוא מתחיל לנאום על איך\n"
	.string "צוות רוקט מתעלל בפוקימונים.\p"
	.string "אז, אנחנו פשוט מדברים על זה\n"
	.string "כמו מבוגרים.$"

gFameCheckerFlavorText_MrFuji2:: @ 0x81AFC38
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}מגזין מעריצי פוקימון\n"
	.string "הגרלת פרס גדול חודשית!\p"
	.string "טופס ההרשמה הוא...\p"
	.string "נעלם! הוא נגזר.\n"
	.string "מישהו כבר הגיש בקשה.$"

gFameCheckerFlavorText_MrFuji3:: @ 0x81AFCE9
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}יש שמועה...\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}שמעתי שמר פוג'י לא במקור\n"
	.string "מהאזורים האלה גם כן.$"

gFameCheckerFlavorText_MrFuji4:: @ 0x81AFD49
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}זו תמונה של בליין ו\n"
	.string "מר פוג'י.\p"
	.string "הם עומדים כתף אל כתף\n"
	.string "עם חיוכים גדולים.$"

gFameCheckerFlavorText_MrFuji5:: @ 0x81AFDC4
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}עורך: מר פוג'י הביישן דחה\n"
	.string "את בקשות הראיון שלנו.\p"
	.string "הוא אדם טוב לב שאהוב\n"
	.string "ומוערך בעיר לבנדר.$"

gFameCheckerFlavorText_Giovanni0:: @ 0x81AFE68
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}צוות רוקט לוכד פוקימונים\n"
	.string "מכל רחבי העולם.\p"
	.string "הם כלים חשובים לשמירה על\n"
	.string "העסק הפלילי שלנו.\p"
	.string "אני המנהיג, ג'ובאני!$"

gFameCheckerFlavorText_Giovanni1:: @ 0x81AFF23
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איזה סוג פוקימון מועדף?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הבריונים האלה שהשתלטו על\n"
	.string "הבניין שלנו...\p"
	.string "הבוס שלהם אמר שהוא מחפש\n"
	.string "פוקימונים חזקים.$"

gFameCheckerFlavorText_Giovanni2:: @ 0x81AFFA8
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}איך האדם הזה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הבוס של צוות רוקט אכזרי\n"
	.string "בצורה נוראית!\p"
	.string "בשבילו, פוקימונים הם רק כלים\n"
	.string "לשימוש.$"

gFameCheckerFlavorText_Giovanni3:: @ 0x81B0022
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}ברוכים הבאים למחבוא שלי!\p"
	.string "כך יהיה עד שאוכל להחזיר את\n"
	.string "צוות רוקט לתפארתו הקודמת.$"

gFameCheckerFlavorText_Giovanni4:: @ 0x81B00A6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מה האדם הזה עושה?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}תהרוג אותי! ג'ובאני היה\n"
	.string "מנהיג המכון של וירידיאן?$"

gFameCheckerFlavorText_Giovanni5:: @ 0x81B0106
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}משפחה וחברים?\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אתה... אתה לא הילד של ג'ובאני,\n"
	.string "נכון?\p"
	.string "לא, זה לא יכול להיות נכון.\n"
	.string "לילד של ג'ובאני יש שיער אדום.$"


gFameCheckerPersonName_ProfOak:: @ 0x81B0188
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}פרופ' אוק$"

gFameCheckerPersonQuote_ProfOak:: @ 0x81B0198
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: פרופ' אוק\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}למה פוקימונים מתחרים ונלחמים\n"
	.string "כל כך קשה בשבילך?\p"
	.string "הם עושים זאת כי הם יכולים לראות\n"
	.string "את האהבה והאמון שיש לך\l"
	.string "כלפי פוקימונים.\p"
	.string "לעולם אל תשכח את זה.$"

gFameCheckerPersonName_Daisy:: @ 0x81B0251
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}דייזי$"

gFameCheckerPersonQuote_Daisy:: @ 0x81B025D
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: דייזי\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}בזמן שנהניתי בנוחות\n"
	.string "מהפסקות התה שלי, הפכת למאוד\l"
	.string "מיומן וחזק.\p"
	.string "אני מקווה שתישאר יריב טוב\n"
	.string "לאחי הקטן.$"

gFameCheckerPersonName_Brock:: @ 0x81B030F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ברוק$"

gFameCheckerPersonQuote_Brock:: @ 0x81B031B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: ברוק\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}בעולם הגדול שלנו, בטח יש\n"
	.string "הרבה מאמנים קשוחים.\p"
	.string "בוא נמשיך שנינו להתאמן\n"
	.string "ולהתחזק!$"

gFameCheckerPersonName_Misty:: @ 0x81B03B3
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מיסטי$"

gFameCheckerPersonQuote_Misty:: @ 0x81B03BF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: מיסטי\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני אמשיך להתאמן כאן\n"
	.string "במכון הזה.\p"
	.string "כשאשתפר, אשמח לצאת לדרך\n"
	.string "ולטייל.$"

gFameCheckerPersonName_LtSurge:: @ 0x81B0446
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}סגן סרג'$"

gFameCheckerPersonQuote_LtSurge:: @ 0x81B0456
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: סגן סרג'\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}היי, ילד!\n"
	.string "הדלקת אותי בקרב שלנו!\p"
	.string "לא ידעתי שיש מאמנים\n"
	.string "אמיצים כמוך.\p"
	.string "זה גרם לי לשנות את דעתי\n"
	.string "עליך!$"

gFameCheckerPersonName_Erika:: @ 0x81B0504
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}אריקה$"

gFameCheckerPersonQuote_Erika:: @ 0x81B0510
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: אריקה\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני כל כך שמחה שיש מאמנים\n"
	.string "חזקים כמוך.\p"
	.string "המודעות הזו לבדה מעוררת\n"
	.string "ומניעה אותי לנסות יותר חזק.\p"
	.string "בבקשה בקר אותי שוב.\n"
	.string "זזז...$"

gFameCheckerPersonName_Koga:: @ 0x81B05C2
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}קוגה$"

gFameCheckerPersonQuote_Koga:: @ 0x81B05CD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: קוגה\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אתה ואני, שנינו חייבים להציב\n"
	.string "מטרות גבוהות יותר ולעבוד לקראת\l"
	.string "עמידה באתגרים שלנו.\p"
	.string "עכשיו, אני חייב ללכת לאמן את בתי.$"

gFameCheckerPersonName_Sabrina:: @ 0x81B0667
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}סברינה$"

gFameCheckerPersonQuote_Sabrina:: @ 0x81B0675
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: סברינה\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}האהבה שיש לך כלפי\n"
	.string "הפוקימונים שלך...\p"
	.string "זה היה כוח שמעולם לא\n"
	.string "נוצח על ידי הכוח הפסיכי שלי.$"

gFameCheckerPersonName_Blaine:: @ 0x81B06FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}בליין$"

gFameCheckerPersonQuote_Blaine:: @ 0x81B0708
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: בליין\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}פוקימוני האש שלי!\n"
	.string "הם יהפכו לעוד יותר חזקים!\p"
	.string "ועכשיו, חידון. כמה סוגים של\n"
	.string "פוקימוני אש יש?$"

gFameCheckerPersonName_Lorelei:: @ 0x81B079F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}לורליי$"

gFameCheckerPersonQuote_Lorelei:: @ 0x81B07AD
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: לורליי\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}הייתי צריכה להודות לך על\n"
	.string "העזרה שלך.\p"
	.string "אבל לזה אין שום קשר לקרבות\n"
	.string "שלנו.\p"
	.string "כדאי שתיזהר בפעם הבאה!$"

gFameCheckerPersonName_Bruno:: @ 0x81B0845
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ברונו$"

gFameCheckerPersonQuote_Bruno:: @ 0x81B0851
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: ברונו\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}את הכוח העל של הפוקימונים\n"
	.string "שלך ושלך חוויתי בעצמי.\p"
	.string "בפעם הבאה, אולי אראה לך\n"
	.string "איך לאמן את עצמך.$"

gFameCheckerPersonName_Agatha:: @ 0x81B08EE
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}אגתה$"

gFameCheckerPersonQuote_Agatha:: @ 0x81B08FB
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: אגתה\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_FEMALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}כשתזדקן, אל תעז\n"
	.string "להתרכך כמו הזקן אוק!\p"
	.string "תהיה כמוני והמשך להילחם!$"

gFameCheckerPersonName_Lance:: @ 0x81B097F
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}לאנס$"

gFameCheckerPersonQuote_Lance:: @ 0x81B098B
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: לאנס\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אני שוקל לחזור לעיר\n"
	.string "הולדתי.\p"
	.string "אני רוצה לאמן מחדש את פוקימוני\n"
	.string "הדרקון שלי ולחזק אותם.\p"
	.string "אשמח להזמין אותך לעיר\n"
	.string "הולדתי יום אחד.$"

gFameCheckerPersonName_Bill:: @ 0x81B0A45
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ביל$"

gFameCheckerPersonQuote_Bill:: @ 0x81B0A50
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: ביל\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}היי, שם! לסליו היו רק\n"
	.string "מילים טובות עליך.\p"
	.string "לשמוע את זה משמח אותי.\p"
	.string "כשתתפוס פוקימונים נדירים,\n"
	.string "בוא להראות לי, בסדר? הבטח!$"

gFameCheckerPersonName_MrFuji:: @ 0x81B0AFF
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מר פוג'י$"

gFameCheckerPersonQuote_MrFuji:: @ 0x81B0B0E
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: מר פוג'י\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}במקום לקוות לאושר\n"
	.string "של רק הפוקימונים שלך...\p"
	.string "...האם אוכל לבקש ממך לאחל\n"
	.string "לאושר של כל הפוקימונים?$"

gFameCheckerPersonName_Giovanni:: @ 0x81B0BA6
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}ג'ובאני$"

gFameCheckerPersonQuote_Giovanni:: @ 0x81B0BB5
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE}מאת: ג'ובאני\n"
	.string "אל: {PLAYER}\p"
	.string "{FONT_MALE}{COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}אין שום דבר שאני רוצה לומר\n"
	.string "לך.\p"
	.string "אתרכז אך ורק בשיפור\n"
	.string "עצמי, ולא באחרים.$"

gFameCheckerFlavorTextOriginLocation_ProfOak0:: @ 0x81B0C45
	.string "עיר פאלט$"

gFameCheckerFlavorTextOriginLocation_ProfOak1::
	.string "מעבדת מחקר$"

gFameCheckerFlavorTextOriginLocation_ProfOak2::
	.string "מעבדת מחקר$"

gFameCheckerFlavorTextOriginLocation_ProfOak3::
	.string "עיר וירידיאן$"

gFameCheckerFlavorTextOriginLocation_ProfOak4::
	.string "ליגת פוקימון$"

gFameCheckerFlavorTextOriginLocation_ProfOak5::
	.string "מעבדת מחקר$"

gFameCheckerFlavorTextOriginLocation_Daisy0::
	.string "מעבדת מחקר$"

gFameCheckerFlavorTextOriginLocation_Daisy1::
	.string "עיר ורמיליון$"

gFameCheckerFlavorTextOriginLocation_Daisy2::
	.string "מבוך מים$"

gFameCheckerFlavorTextOriginLocation_Daisy3::
	.string "עיר וירידיאן$"

gFameCheckerFlavorTextOriginLocation_Daisy4::
	.string "אחוזת סלדון$"

gFameCheckerFlavorTextOriginLocation_Daisy5::
	.string "אי ארבע$"

gFameCheckerFlavorTextOriginLocation_Brock0::
	.string "עיר פיוטר$"

gFameCheckerFlavorTextOriginLocation_Brock1::
	.string "מכון פיוטר$"

gFameCheckerFlavorTextOriginLocation_Brock2::
	.string "עיר פיוטר$"

gFameCheckerFlavorTextOriginLocation_Brock3::
	.string "דרך 4$"

gFameCheckerFlavorTextOriginLocation_Brock4::
	.string "הר מון$"

gFameCheckerFlavorTextOriginLocation_Brock5::
	.string "מוזיאון פיוטר$"

gFameCheckerFlavorTextOriginLocation_Misty0::
	.string "עיר סרולין$"

gFameCheckerFlavorTextOriginLocation_Misty1::
	.string "מכון סרולין$"

gFameCheckerFlavorTextOriginLocation_Misty2::
	.string "מכון סרולין$"

gFameCheckerFlavorTextOriginLocation_Misty3::
	.string "איי סיפואם$"

gFameCheckerFlavorTextOriginLocation_Misty4::
	.string "כף סרולין$"

gFameCheckerFlavorTextOriginLocation_Misty5::
	.string "עיר סרולין$"

gFameCheckerFlavorTextOriginLocation_LtSurge0::
	.string "עיר ורמיליון$"

gFameCheckerFlavorTextOriginLocation_LtSurge1::
	.string "מכון ורמיליון$"

gFameCheckerFlavorTextOriginLocation_LtSurge2::
	.string "מכון ורמיליון$"

gFameCheckerFlavorTextOriginLocation_LtSurge3::
	.string "מכון ורמיליון$"

gFameCheckerFlavorTextOriginLocation_LtSurge4::
	.string "מכון ורמיליון$"

gFameCheckerFlavorTextOriginLocation_LtSurge5::
	.string "עיר ורמיליון$"

gFameCheckerFlavorTextOriginLocation_Erika0::
	.string "עיר סלדון$"

gFameCheckerFlavorTextOriginLocation_Erika1::
	.string "מכון סלדון$"

gFameCheckerFlavorTextOriginLocation_Erika2::
	.string "מכון סלדון$"

gFameCheckerFlavorTextOriginLocation_Erika3::
	.string "מכון סלדון$"

gFameCheckerFlavorTextOriginLocation_Erika4::
	.string "מכון סלדון$"

gFameCheckerFlavorTextOriginLocation_Erika5::
	.string "בניין סלדון$"

gFameCheckerFlavorTextOriginLocation_Koga0::
	.string "עיר פוקסיה$"

gFameCheckerFlavorTextOriginLocation_Koga1::
	.string "מכון פוקסיה$"

gFameCheckerFlavorTextOriginLocation_Koga2::
	.string "מכון פוקסיה$"

gFameCheckerFlavorTextOriginLocation_Koga3::
	.string "עיר פוקסיה$"

gFameCheckerFlavorTextOriginLocation_Koga4::
	.string "עיר פוקסיה$"

gFameCheckerFlavorTextOriginLocation_Koga5::
	.string "אזור הספארי$"

gFameCheckerFlavorTextOriginLocation_Sabrina0::
	.string "עיר זעפרן$"

gFameCheckerFlavorTextOriginLocation_Sabrina1::
	.string "אי שלוש$"

gFameCheckerFlavorTextOriginLocation_Sabrina2::
	.string "מכון זעפרן$"

gFameCheckerFlavorTextOriginLocation_Sabrina3::
	.string "מכון זעפרן$"

gFameCheckerFlavorTextOriginLocation_Sabrina4::
	.string "עיר זעפרן$"

gFameCheckerFlavorTextOriginLocation_Sabrina5::
	.string "מכון זעפרן$"

gFameCheckerFlavorTextOriginLocation_Blaine0::
	.string "אי סינבר$"

gFameCheckerFlavorTextOriginLocation_Blaine1::
	.string "מכון סינבר$"

gFameCheckerFlavorTextOriginLocation_Blaine2::
	.string "מכון סינבר$"

gFameCheckerFlavorTextOriginLocation_Blaine3::
	.string "אי סינבר$"

gFameCheckerFlavorTextOriginLocation_Blaine4::
	.string "מכון סינבר$"

gFameCheckerFlavorTextOriginLocation_Blaine5::
	.string "נופש מפואר$"

gFameCheckerFlavorTextOriginLocation_Lorelei0::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Lorelei1::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Lorelei2::
	.string "אי ארבע$"

gFameCheckerFlavorTextOriginLocation_Lorelei3::
	.string "אי חמש$"

gFameCheckerFlavorTextOriginLocation_Lorelei4::
	.string "אי ארבע$"

gFameCheckerFlavorTextOriginLocation_Lorelei5::
	.string "אי ארבע$"

gFameCheckerFlavorTextOriginLocation_Bruno0::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Bruno1::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Bruno2::
	.string "עיר זעפרן$"

gFameCheckerFlavorTextOriginLocation_Bruno3::
	.string "ספא אמבר$"

gFameCheckerFlavorTextOriginLocation_Bruno4::
	.string "אי שתיים$"

gFameCheckerFlavorTextOriginLocation_Bruno5::
	.string "קניון סבולט$"

gFameCheckerFlavorTextOriginLocation_Agatha0::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Agatha1::
	.string "רמת אינדיגו$"

gFameCheckerFlavorTextOriginLocation_Agatha2::
	.string "רמת אינדיגו$"

gFameCheckerFlavorTextOriginLocation_Agatha3::
	.string "אי שבע$"

gFameCheckerFlavorTextOriginLocation_Agatha4::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Agatha5::
	.string "אי שש$"

gFameCheckerFlavorTextOriginLocation_Lance0::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Lance1::
	.string "ליגת הפוקימון$"

gFameCheckerFlavorTextOriginLocation_Lance2::
	.string "עיר זעפרן$"

gFameCheckerFlavorTextOriginLocation_Lance3::
	.string "כל-בו סלדון$"

gFameCheckerFlavorTextOriginLocation_Lance4::
	.string "רמת אינדיגו$"

gFameCheckerFlavorTextOriginLocation_Lance5::
	.string "רמת אינדיגו$"

gFameCheckerFlavorTextOriginLocation_Bill0::
	.string "עיר סרולין$"

gFameCheckerFlavorTextOriginLocation_Bill1::
	.string "עיר סרולין$"

gFameCheckerFlavorTextOriginLocation_Bill2::
	.string "עיר פוקסיה$"

gFameCheckerFlavorTextOriginLocation_Bill3::
	.string "אי אחד$"

gFameCheckerFlavorTextOriginLocation_Bill4::
	.string "אי אחד$"

gFameCheckerFlavorTextOriginLocation_Bill5::
	.string "אי אחד$"

gFameCheckerFlavorTextOriginLocation_MrFuji0::
	.string "עיירת לבנדר$"

gFameCheckerFlavorTextOriginLocation_MrFuji1::
	.string "מגדל הפוקימון$"

gFameCheckerFlavorTextOriginLocation_MrFuji2::
	.string "עיירת לבנדר$"

gFameCheckerFlavorTextOriginLocation_MrFuji3::
	.string "עיירת לבנדר$"

gFameCheckerFlavorTextOriginLocation_MrFuji4::
	.string "מכון סינבר$"

gFameCheckerFlavorTextOriginLocation_MrFuji5::
	.string "אי סינבר$"

gFameCheckerFlavorTextOriginLocation_Giovanni0::
	.string "מחבוא רוקט$"

gFameCheckerFlavorTextOriginLocation_Giovanni1::
	.string "סילף בע”מ$"

gFameCheckerFlavorTextOriginLocation_Giovanni2::
	.string "סילף בע”מ$"

gFameCheckerFlavorTextOriginLocation_Giovanni3::
	.string "מכון וירידיאן$"

gFameCheckerFlavorTextOriginLocation_Giovanni4::
	.string "מכון וירידיאן$"

gFameCheckerFlavorTextOriginLocation_Giovanni5::
	.string "מחסן רוקט$"

gFameCheckerFlavorTextOriginObjectName_ProfOak0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_ProfOak1::
	.string "פרופ' אוק$"

gFameCheckerFlavorTextOriginObjectName_ProfOak2::
	.string "עוזר$"

gFameCheckerFlavorTextOriginObjectName_ProfOak3::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_ProfOak4::
	.string "אגתה$"

gFameCheckerFlavorTextOriginObjectName_ProfOak5::
	.string "עוזר$"

gFameCheckerFlavorTextOriginObjectName_Daisy0::
	.string "עוזר$"

gFameCheckerFlavorTextOriginObjectName_Daisy1::
	.string "אישה$"

gFameCheckerFlavorTextOriginObjectName_Daisy2::
	.string "איש$"

gFameCheckerFlavorTextOriginObjectName_Daisy3::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Daisy4::
	.string "זקנה$"

gFameCheckerFlavorTextOriginObjectName_Daisy5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Brock0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_Brock1::
	.string "ברוק$"

gFameCheckerFlavorTextOriginObjectName_Brock2::
	.string "בחור צעיר$"

gFameCheckerFlavorTextOriginObjectName_Brock3::
	.string "ילד$"

gFameCheckerFlavorTextOriginObjectName_Brock4::
	.string "איש$"

gFameCheckerFlavorTextOriginObjectName_Brock5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Misty0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_Misty1::
	.string "מיסטי$"

gFameCheckerFlavorTextOriginObjectName_Misty2::
	.string "לואיס$"

gFameCheckerFlavorTextOriginObjectName_Misty3::
	.string "בחור צעיר$"

gFameCheckerFlavorTextOriginObjectName_Misty4::
	.string "גברת$"

gFameCheckerFlavorTextOriginObjectName_Misty5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_LtSurge0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_LtSurge1::
	.string "סגן סרג'$"

gFameCheckerFlavorTextOriginObjectName_LtSurge2::
	.string "טאקר$"

gFameCheckerFlavorTextOriginObjectName_LtSurge3::
	.string "טאקר$"

gFameCheckerFlavorTextOriginObjectName_LtSurge4::
	.string "דוויין$"

gFameCheckerFlavorTextOriginObjectName_LtSurge5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Erika0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_Erika1::
	.string "אריקה$"

gFameCheckerFlavorTextOriginObjectName_Erika2::
	.string "לולה$"

gFameCheckerFlavorTextOriginObjectName_Erika3::
	.string "טמיה$"

gFameCheckerFlavorTextOriginObjectName_Erika4::
	.string "אריקה$"

gFameCheckerFlavorTextOriginObjectName_Erika5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Koga0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_Koga1::
	.string "קוגה$"

gFameCheckerFlavorTextOriginObjectName_Koga2::
	.string "קירק$"

gFameCheckerFlavorTextOriginObjectName_Koga3::
	.string "צ'ארין$"

gFameCheckerFlavorTextOriginObjectName_Koga4::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Koga5::
	.string "איש$"

gFameCheckerFlavorTextOriginObjectName_Sabrina0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_Sabrina1::
	.string "בחור צעיר$"

gFameCheckerFlavorTextOriginObjectName_Sabrina2::
	.string "סברינה$"

gFameCheckerFlavorTextOriginObjectName_Sabrina3::
	.string "סברינה$"

gFameCheckerFlavorTextOriginObjectName_Sabrina4::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Sabrina5::
	.string "טירון$"

gFameCheckerFlavorTextOriginObjectName_Blaine0::
	.string "שלט$"

gFameCheckerFlavorTextOriginObjectName_Blaine1::
	.string "בליין$"

gFameCheckerFlavorTextOriginObjectName_Blaine2::
	.string "דרק$"

gFameCheckerFlavorTextOriginObjectName_Blaine3::
	.string "אישה$"

gFameCheckerFlavorTextOriginObjectName_Blaine4::
	.string "תמונה$"

gFameCheckerFlavorTextOriginObjectName_Blaine5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Lorelei0::
	.string "לורליי$"

gFameCheckerFlavorTextOriginObjectName_Lorelei1::
	.string "לורליי$"

gFameCheckerFlavorTextOriginObjectName_Lorelei2::
	.string "זקן$"

gFameCheckerFlavorTextOriginObjectName_Lorelei3::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Lorelei4::
	.string "ילדה קטנה$"

gFameCheckerFlavorTextOriginObjectName_Lorelei5::
	.string "זקנה$"

gFameCheckerFlavorTextOriginObjectName_Bruno0::
	.string "ברונו$"

gFameCheckerFlavorTextOriginObjectName_Bruno1::
	.string "ברונו$"

gFameCheckerFlavorTextOriginObjectName_Bruno2::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Bruno3::
	.string "מועך$"

gFameCheckerFlavorTextOriginObjectName_Bruno4::
	.string "אישה$"

gFameCheckerFlavorTextOriginObjectName_Bruno5::
	.string "מועך$"

gFameCheckerFlavorTextOriginObjectName_Agatha0::
	.string "אגתה$"

gFameCheckerFlavorTextOriginObjectName_Agatha1::
	.string "מועך$"

gFameCheckerFlavorTextOriginObjectName_Agatha2::
	.string "מועך$"

gFameCheckerFlavorTextOriginObjectName_Agatha3::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Agatha4::
	.string "אגתה$"

gFameCheckerFlavorTextOriginObjectName_Agatha5::
	.string "זקנה$"

gFameCheckerFlavorTextOriginObjectName_Lance0::
	.string "לאנס$"

gFameCheckerFlavorTextOriginObjectName_Lance1::
	.string "לאנס$"

gFameCheckerFlavorTextOriginObjectName_Lance2::
	.string "אישה$"

gFameCheckerFlavorTextOriginObjectName_Lance3::
	.string "ילדה קטנה$"

gFameCheckerFlavorTextOriginObjectName_Lance4::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Lance5::
	.string "בחור צעיר$"

gFameCheckerFlavorTextOriginObjectName_Bill0::
	.string "{RIVAL}$"

gFameCheckerFlavorTextOriginObjectName_Bill1::
	.string "ילד קטן$"

gFameCheckerFlavorTextOriginObjectName_Bill2::
	.string "זקן$"

gFameCheckerFlavorTextOriginObjectName_Bill3::
	.string "סליו$"

gFameCheckerFlavorTextOriginObjectName_Bill4::
	.string "סליו$"

gFameCheckerFlavorTextOriginObjectName_Bill5::
	.string "סליו$"

gFameCheckerFlavorTextOriginObjectName_MrFuji0::
	.string "ילדה קטנה$"

gFameCheckerFlavorTextOriginObjectName_MrFuji1::
	.string "צוות רוקט$"

gFameCheckerFlavorTextOriginObjectName_MrFuji2::
	.string "מגזין$"

gFameCheckerFlavorTextOriginObjectName_MrFuji3::
	.string "איש$"

gFameCheckerFlavorTextOriginObjectName_MrFuji4::
	.string "תמונה$"

gFameCheckerFlavorTextOriginObjectName_MrFuji5::
	.string "עיתון פוקימון$"

gFameCheckerFlavorTextOriginObjectName_Giovanni0::
	.string "ג'ובאני$"

gFameCheckerFlavorTextOriginObjectName_Giovanni1::
	.string "מדען$"

gFameCheckerFlavorTextOriginObjectName_Giovanni2::
	.string "מדען$"

gFameCheckerFlavorTextOriginObjectName_Giovanni3::
	.string "ג'ובאני$"

gFameCheckerFlavorTextOriginObjectName_Giovanni4::
	.string "איש$"

gFameCheckerFlavorTextOriginObjectName_Giovanni5::
	.string "גדעון$"

PokemonJournal_Text_SpecialFeatureBrock::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון פיוטר\n"
	.string "מנהיג ברוק!\p"
	.string "ברוק לעתים רחוקות צוחק, אך אומרים\n"
	.string "שהוא לא מסוגל להפסיק אם הוא\l"
	.string "מתחיל.$"

PokemonJournal_Text_SpecialFeatureMisty::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון סרולין\n"
	.string "מנהיגה מיסטי!\p"
	.string "אומרים שמיסטי מעריצה את לורליי\n"
	.string "מהרביעייה העילית.$"

PokemonJournal_Text_SpecialFeatureLtSurge::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון ורמיליון\n"
	.string "מנהיג סגן סרג'!\p"
	.string "שמועות אומרות שסגן סרג' היה\n"
	.string "טייס בזמן שהיה בביתו באמריקה.\p"
	.string "הוא השתמש בחשמל שנוצר על ידי\n"
	.string "פוקימונים כדי להפעיל את מטוסו.$"

PokemonJournal_Text_SpecialFeatureErika::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון סלדון\n"
	.string "מנהיגה אריקה!\p"
	.string "שמועות אומרות שאם תציץ לתוך\n"
	.string "מכון סלדון, לעתים קרובות תוכל\l"
	.string "לראות את אריקה מנמנמת.$"

PokemonJournal_Text_SpecialFeatureKoga::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון פוקסיה\n"
	.string "מנהיג קוגה!\p"
	.string "אומרים שלקוגה יש ידע מעמיק\n"
	.string "ברפואה.\p"
	.string "הוא אפילו מכין תרופות כדי לטפל\n"
	.string "בפוקימונים שלו לבריאות.$"

PokemonJournal_Text_SpecialFeatureSabrina::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון זעפרן\n"
	.string "מנהיגה סברינה!\p"
	.string "אנשים אומרים שסברינה יכולה\n"
	.string "לתקשר עם הפוקימונים שלה\l"
	.string "במהלך קרב בלי לדבר.$"

PokemonJournal_Text_SpecialFeatureBlaine::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: מכון סינבר\n"
	.string "מנהיג בליין!\p"
	.string "אומרים שבליין מסיר את משקפי השמש\n"
	.string "הכהים שלו רק כשהוא חושב על\l"
	.string "שאלות חידון חדשות.$"

PokemonJournal_Text_SpecialFeatureLorelei::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת:\n"
	.string "לורליי מהרביעייה העילית!\p"
	.string "ידועה בסגנון הקרב הלוגי, המחושב\n"
	.string "והקר שלה, ללורליי\l"
	.string "יש סוד מפתיע!$"

PokemonJournal_Text_SpecialFeatureBruno::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת:\n"
	.string "ברונו מהרביעייה העילית!\p"
	.string "ברונו כנראה הצטרף לרביעייה\n"
	.string "העילית מתוך שאיפתו הבוערת\l"
	.string "להילחם במאמנים הטובים ביותר.$"

PokemonJournal_Text_SpecialFeatureAgatha::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת:\n"
	.string "אגתה מהרביעייה העילית!\p"
	.string "בצעירותה, אגתה ופרופ'\n"
	.string "אוק היו יריבים שהתחרו על\l"
	.string "העליונות כמאמנים.$"

PokemonJournal_Text_SpecialFeatureLance::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת:\n"
	.string "לאנס מהרביעייה העילית!\p"
	.string "סבו של לאנס נחשב\n"
	.string "לזקן של שבט מפורסם של\l"
	.string "אדוני דרקונים.$"

PokemonJournal_Text_SpecialFeatureProfOak::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת: פרופ' אוק,\n"
	.string "חוקר הפוקימון!\p"
	.string "מדווח שפרופ' אוק חי עם\n"
	.string "נכדיו דייזי ו{RIVAL}.$"

PokemonJournal_Text_SpecialFeatureDaisyOak::
	.string "זהו עיתון פוקימון\n"
	.string "מלפני שנים...\p"
	.string "עיתון פוקימון\n"
	.string "מיוחד תחרות!\p"
	.string "אלופת הגרנד של תחרות\n"
	.string "האביב היא דייזי אוק\l"
	.string "מעיירת פאלט!$"

PokemonJournal_Text_SpecialFeatureMrFuji::
	.string "עיתון פוקימון\p"
	.string "כתבה מיוחדת:\n"
	.string "מר פוג'י מבית הפוקימון!\p"
	.string "עורך: מר פוג'י הביישן דחה\n"
	.string "את בקשות הראיון שלנו.\p"
	.string "הוא אדם טוב לב שאהוב\n"
	.string "ומוערך בעיירת לבנדר.$"
