@ Flavor text for interacting with various background objects

Text_Bookshelf::
	.string "המדף מלא עד אפס מקום\n"
	.string "בספרי פוקימון.$"

Text_NothingButPokemonBooks::
	.string "ほんだなに　ならんでいるのは\n"
	.string "ポケモンの　ほん　ばかりだ$"

Text_ATownMap::
	.string "מפת העיר.$"

Text_PokeMartShelf::
    .string "וואו!\n"
    .string "המון דברים של פוקמון!$"

Text_DishesPlatesNeatlyLinedUp::
    .string "צלחות וכוסות מסודרות\n"
    .string "בצורה מסודרת.$"

Text_Kitchen::
    .string "זה מריח טעים!\n"
    .string "מישהו בישל כאן.$"

Text_Dresser::
    .string "זו שידה יפה.\n"
    .string "היא יכולה להכיל המון דברים.$"

Text_Snacks::
    .string "יש פה ערמה של חטיפים.$"

Text_PokemartSign::
    .string "כל הצרכים שלך מתמלאים כאן!\n"
    .string "חנות פוקימון$"

Text_PokecenterSign::
    .string "רפא את הפוקמון שלך!\n"
    .string "מרכז פוקימון$"

Text_Indigo_UltimateGoal::
    .string "אנדיגו פלטו\p"
    .string "המטרה הגבוהה ביותר של המאמנים!\n"
    .string "מרכז ליגת הפוקימון$"

Text_Indigo_HighestAuthority::
    .string "אנדיגו פלטו\p"
    .string "הרשות הגבוהה ביותר של פוקימונים!\n"
    .string "מרכז ליגת הפוקימון$"

Text_Food::
    .string "אמורים להיות בזה כל מיני דברים\n"
    .string "טעימים שאפשר לאכול.$"
	
Text_Blueprints::
    .string "זה סרטוט כלשהו.\n"
    .string "יש שם הרבה מילים וצורות.$"

Text_Painting::
    .string "זו תמונה יפה של פוקימון.\n"
    .string "נראה שהוא מרגיש טוב.$"

Text_PowerPlantMachine::
    .string "מה זה המכונה הזו יכולה להיות?\n"
    .string "טוב יותר שלא לעשות בה עוולות!$"

Text_Telephone::
    .string "זה טלפון.\n"
    .string "עדיף שלא להשתמש בו.$"

Text_Computer::
    .string "הכל מלא מילים מורכבות ומספרים\n"
    .string "שאין להם שום הגיון...$"

Text_AdvertisingPoster::
    .string "זה לוח הכרזות על מגוון\n"
    .string "מוצרים שונים.$"

Text_TastyFood::
    .string "אוי, זה מריח טעים!\n"
    .string "זה עושה אותי רעב!$"

Text_TrashBin::
    .string "בתוך זה...\n"
    .string "……\p"
    .string "אין כאן כלום!$"

Text_Cup::
    .string "זו כוס עם ציור של פוקימון\n"
    .string "עליה.$"

Text_PolishedWindow::
    .string "החלון מנוקה טוב מאוד.$"

Text_BeautifulSkyWindow::
    .string "מחוץ לחלון…\n"
    .string "השמיים נראים יפהפיים בצורה\l"
    .string "מדהימה.$"

Text_BlinkingLights::
    .string "אורות בצבעים שונים הולכים\n"
    .string "ונכבים.$"

Text_NeatlyLinedUpTools::
    .string "כל מיני כלים ממוינים\n"
    .string "בצורה מסודרת.$"

Text_ImpressiveMachine::
    .string "זה מכונה מסוג כלשהו.\n"
    .string "וואו, זה מרשים.$"

Text_VideoGame::
    .string "זה המשחק הווידאו החדש!\n"
    .string "זה נראה ממש כיף!$"

Text_Burglary::
    .string "יש כאן אותות ברורים של פריצה…$"

Text_PlayerFacingTVScreen::
    .string "יש פוקימון בטלוויזיה!\n"
    .string "נראה שהוא נהנה.$"

