Help_Text_WhatShouldIDo::
    .string "מה לעשות במצב הזה?$"

Help_Text_HowDoIDoThis::
    .string "איך אני עושה זאת?$"

Help_Text_WhatDoesThisTermMean::
    .string "מה משמעות מונח זה?$"

Help_Text_AboutThisGame::
    .string "על המשחק הזה$"

Help_Text_TypeMatchupList::
    .string "רשימת התאמת סוגים$"

Help_Text_Exit::
    .string "יציאה$"

Help_Text_Cancel::
    .string "ביטול$"

Help_Text_TryDoingItOnYourOwn::
.string "じぶんの ちからで やってみよう！$"

Help_Text_DescWhatShouldIDo::
    .string "בחר כדי לקבל רמזים להתמודדות\n"
    .string "עם מצבים מאתגרים.$"

Help_Text_DescHowDoIDoThis::
    .string "בחר בשביל הוראות מפורטות לפעולות\n"
    .string "שונות.$"

Help_Text_DescWhatDoesThisTermMean::
    .string "מילות הסבר מפורטות מוצגות\n"
    .string "למונחים שמופיעים במשחק.$"

Help_Text_DescAboutThisGame::
    .string "מילות הסבר מפורטות על המשחק\n"
    .string "הזה.$"

Help_Text_DescTypeMatchupList::
    .string "התאמות של סוגי פוקימון\n"
    .string "ומהלכים.$"

Help_Text_DescExit::
    .string "בחר לצאת ממערכת העזרה.$"

Help_Text_Greetings::
    .string "שלום! זו מערכת העזרה.\n"
    .string "תוכל לקרוא אותי בכל זמן ובכל מקום\l"
    .string "על ידי הקשה על כפתור ש או י.\l"
    .string "ההודעות תתעדכנה לפי המצב, אז תבדוק\l"
    .string "אותן בתדירות!$"

Help_Text_PlayingForFirstTime::
    .string "אני משחק לראשונה. עזרה!$"

Help_Text_WhatShouldIBeDoing::
    .string "מה אני אמור לעשות?$"

Help_Text_CantGetOutOfRoom::
    .string "אני לא יכול לצאת מחדר!$"

Help_Text_CantFindPersonIWant::
    .string "אני לא מוצא את האדם שאני רוצה.$"

Help_Text_TalkedToEveryoneNowWhat::
    .string "דיברתי עם כולם. מה עכשיו?$"

Help_Text_SomeoneBlockingMyWay::
    .string "יש מישהו שחוסם לי את הדרך!$"

Help_Text_ICantGoOn::
    .string "אני לא יכול להמשיך!$"

Help_Text_OutOfThingsToDo::
    .string "אין לי מה לעשות.$"

Help_Text_WhatHappenedToItemIGot::
    .string "מה קרה לפריט שקיבלתי?$"

Help_Text_WhatAreMyAdventureBasics::
    .string "מה הבסיס של ההרפתקה שלי?$"

Help_Text_HowAreRoadsForestsDifferent::
    .string "מה ההבדל בין דרכים ליערות?$"

Help_Text_HowAreCavesDifferent::
    .string "איך מערות שונות?$"

Help_Text_HowDoIProgress::
    .string "איך אני הולך הלאה?$"

Help_Text_WhenCanIUseItem::
    .string "מתי אני יכול להשתמש בפריטים?$"

Help_Text_WhatsABattle::
    .string "מה זה קרב?$"

Help_Text_HowDoIPrepareForBattle::
    .string "איך אני מתכונן לקרב?$"

Help_Text_WhatIsAMonsVitality::
    .string "מהו חיים של פוקימון?$"

Help_Text_MyMonsAreHurt::
    .string "הפוקימונים שלי פצועים!$"

Help_Text_WhatIsStatusProblem::
    .string "מהו סטאטוס של פוקימון?$"

Help_Text_WhatHappensIfAllMyMonsFaint::
    .string "מה קורה אם כל הפוקימונים שלי מתים?$"

Help_Text_CantCatchMons::
    .string "אני לא יכול לתפוס פוקימונים!$"

Help_Text_RanOutOfPotions::
    .string "נגמרו לי התרופות.$"

Help_Text_CanIBuyPokeBalls::
    .string "אפשר לקנות פוקיבול-ים?$"

Help_Text_WhatsATrainer::
    .string "מה זה מאמן?$"

Help_Text_HowDoIWinAgainstTrainer::
    .string "איך אני מנצח מאמן?$"

Help_Text_WhereDoMonsAppear::
    .string "איפה פוקימונים מופיעים?$"

Help_Text_WhatAreMoves::
    .string "מה הם תכניות הפוקימון?$"

Help_Text_WhatAreHiddenMoves::
    .string "מהזה מהלכים נסתרים?$"

Help_Text_WhatMovesShouldIUse::
    .string "באילו מהלכים אני צריך להשתמש?$"

Help_Text_WantToAddMoreMoves::
    .string "אני רוצה להוסיף מהלכים נוספים.$"

Help_Text_WantToMakeMonStronger::
    .string "אני רוצה לחזק את הפוקימון שלי.$"

Help_Text_FoeMonsTooStrong::
    .string "הפוקימונים של היריב חזקים מידי!$"

Help_Text_WhatDoIDoInCave::
    .string "מה לעשות במערה?$"

Help_Text_NothingIWantToKnow::
    .string "אין לי שום דבר שאני רוצה לדעת!$"

Help_Text_WhatsPokemonCenter::
    .string "מה זה מרכז פוקימון?$"

Help_Text_WhatsPokemonMart::
    .string "מה זה חנות פוקימון?$"

Help_Text_WantToEndGame::
    .string "אני רוצה לסיים את המשחק.$"

Help_Text_WhatsAMon::
    .string "מה זה פוקימון?$"


Help_Text_WhatIsThatPersonLike::
    .string "איך האדם ההוא?$"

Help_Text_WhatDoesHiddenMoveDo::
    .string "מה מהלך נסתר עושה?$"

Help_Text_WhatDoIDoInSafari::
    .string "מה לעשות במשחק ספארי?$"

Help_Text_WhatAreSafariRules::
    .string "מהם כללי המשחק בספארי?$"

Help_Text_WantToEndSafari::
    .string "אני רוצה לסיים את משחק הספארי!$"

Help_Text_WhatIsAGym::
    .string "מהו מכון?$"

Help_Text_AnswerPlayingForFirstTime::
    .string "אתה הדמות הראשית,\n"
    .string "וחוקר את עולם הפוקימונים.\n"
    .string "על ידי שיחה עם אנשים ופתרון\n"
    .string "חידות, דרכים חדשות נפתחות לך. שאף\n"
    .string "למטרה יחד עם הפוקימון הנהדר שלך.$"

Help_Text_AnswerWhatShouldIBeDoing::
    .string "כאשר אתה נתקל באדם אחר,\n"
    .string "תפנה אליו ולחץ על הכפתור A.\n"
    .string "זה יגרום לו לדבר ולפעול ביחד עם\n"
    .string "דמותך. באפשרותך גם לבדוק פריטים\n"
    .string "ועצות באותו האופן. שוחח עם אנשים\n"
    .string "ובדוק דברים בתדירות כדי לקבל מידע.$"

Help_Text_AnswerCantGetOutOfRoom::
    .string "בסולמות או ביציאות של בניין\n"
    .string "יש משטח אדום. הזז את דמותך\n"
    .string "כך שתעמוד מעל המשטח האדום. לחץ על\n"
    .string "הכפתור {PLUS} בפד השליטה אל מול\n"
    .string "הסולמות או היציאה כדי להתקדם.$"

Help_Text_AnswerCantFindPersonIWant::
    .string "זה לא משהו שאתה אמור לדאוג\n"
    .string "לו מדי. שוחח עם אנשים אחרים,\n"
    .string "בדוק תוויות ודברים. לפעמים תצטרך\n"
    .string "פשוט לעבור לעיר או למקום חדש.$"

Help_Text_AnswerTalkedToEveryoneNowWhat::
    .string "נסה לעבור לדרך, עיר או מקום חדש.$"

Help_Text_AnswerSomeoneBlockingMyWay::
    .string "יכול להיות שיש משהו בעיר\n"
    .string "או בתוך בניין שגורם לזה. נסה שוב\n"
    .string "לשוחח עם אנשים באזור. אם יש בעיה\n"
    .string "שצריך לפתור, ייתכן שתצטרך לעזור.\n"
    .string "ואז שוחח שוב עם מי שחוסם את דרכך.$"

Help_Text_AnswerICantGoOn::
    .string "נסה לשוחח שוב עם אנשים: גש אליהם\n"
    .string "ולחץ על הכפתור A. נסה גם לבדוק\n"
    .string "דברים כמו עצים וסלעים מוזרים עם\n"
    .string "הכפתור A. לחץ על {PLUS} בפד השליטה\n"
    .string "ונסה ללכת למקומות שנראים חסומים.$"

Help_Text_AnswerOutOfThingsToDo::
    .string "נסה ללכת למקומות שעדיין\n"
    .string "לא ביקרת בהם. בנוסף, בדוק הכל שנראה\n"
    .string "חשוד על ידי לחיצה על הכפתור A.$"

Help_Text_AnswerWhatHappenedToItemIGot::
    .string "כל פריט שאתה מקבל מדמות אחרת נכנס\n"
    .string "לתיק שלך. הפריט ממויין אוטומטית\n"
    .string "ומונח באחת משלוש הכיסיות.\n"
    .string "להוראות לשימוש בתיק, עיין בערך איך\n"
    .string "”אני עושה את זה?” במערכת העזרה.$"

Help_Text_AnswerWhatAreMyAdventureBasics::
    .string "אם פוקימונים נפגעים בקרב,\n"
    .string "קח אותם למרכז פוקימון ותן לצוות\n"
    .string "לרפא אותם. הרגל את עצמך לשמור את\n"
    .string "המשחק ואת התקדמותך. לפני מסע ארוך\n"
    .string "הצטייד בפריטי ריפוי בחנות פוקימון.$"

Help_Text_AnswerHowAreRoadsForestsDifferent::
    .string "יערות בגדול דומים לדרכים\n"
    .string "אך הם יכולים להיות כמו מבוך. בכל\n"
    .string "יער יש דרך לצאת, אז אל תוותר אם\n"
    .string "אתה נתקע.$"

Help_Text_AnswerHowAreCavesDifferent::
    .string "מערות אפלות ומסוכנות. פוקימונים\n"
    .string "פראיים יכולים להופיע בהן בכל מקום.\n"
    .string "מהר למרכז פוקימון או השתמש בפריטים.\n"
    .string "מעבר לכמה מערות מחכות ערים חדשות,\n"
    .string "אז אל תוותר.$"


Help_Text_AnswerHowDoIProgress::
    .string "מטרת המשחק היא לאמן את\n"
    .string "הפוקימונים שלך ולהתקדם.\l"
    .string "עליך לאסוף מידע ולפתור\l"
    .string "בעיות. למשל, מה צריך כדי\l"
    .string "לעקוף מכשול בדרך?\l"
    .string "ומה יגרום לאדם שחוסם\l"
    .string "אותך לזוז מהדרך?$"

Help_Text_AnswerWhenCanIUseItem::
    .string "יש כמה סוגים של פריטים.\n"
    .string "בחלק אפשר להשתמש רק בשטח,\l"
    .string "בחלק רק בזמן קרב, ובחלק\l"
    .string "בכל רגע.\l"
    .string "נסה להשתמש בפריט - אם זה\l"
    .string "לא אפשרי, תקבל הודעה.$"

Help_Text_AnswerWhatsABattle::
    .string "בקרב, הפוקימונים מנסים\n"
    .string "להוריד זה לזה את הנ”ח,\l"
    .string "מדד החיים. פוקימון שהנ”ח\l"
    .string "שלו מגיע לאפס מתעלף,\l"
    .string "והפוקימון השני מנצח.\l"
    .string "ניצחון מקנה נקודות נסיון\l"
    .string "שמעלות רמה ומחזקות.$"

Help_Text_AnswerHowDoIPrepareForBattle::
    .string "קודם כל, רפא לגמרי את\n"
    .string "הפוקימונים שאיתך בכל\l"
    .string "מרכז פוקימון.\l"
    .string "כדאי גם לקנות פריטי ריפוי\l"
    .string "למקרה חירום בחנות פוקימון.$"

Help_Text_AnswerWhatIsAMonsVitality::
    .string "כוח החיים של פוקימון נמדד\n"
    .string "בנ”ח. כשפוקימון נפגע בקרב\l"
    .string "יורדים לו נ”ח, וכשהם\l"
    .string "מגיעים לאפס הוא מתעלף.\l"
    .string "רפא פוקימון פצוע או מעולף\l"
    .string "במרכז פוקימון או בפריטים.$"

Help_Text_AnswerMyMonsAreHurt::
    .string "מרכז פוקימון הוא כמו מלון\n"
    .string "לפוקימונים. מכונה מיוחדת\l"
    .string "שם מרפאת כל בעיית מצב\l"
    .string "ומחזירה את כל הנ”ח.\l"
    .string "השירות חינם, אז התרגל\l"
    .string "לרפא אותם לעתים קרובות.$"

Help_Text_AnswerWhatIsStatusProblem::
    .string "בעיית מצב היא הפרעה שנגרמת\n"
    .string "לפוקימון מהתקפה של היריב.\l"
    .string "בין השאר כוויה, שיתוק,\l"
    .string "הרעלה, שינה וקיפאון.\l"
    .string "אפשר לרפא אותם במרכז\l"
    .string "פוקימון או בעזרת הפריט\l"
    .string "המתאים.$"

Help_Text_AnswerWhatHappensIfAllMyMonsFaint::
    .string "אם כל הפוקימונים שאיתך\n"
    .string "מתעלפים, אתה מאבד קצת\l"
    .string "כסף וחוזר הביתה או\l"
    .string "למרכז פוקימון.\l"
    .string "כדי להקטין את הסיכון, בקר\l"
    .string "לעתים קרובות במרכזי פוקימון\l"
    .string "והתרגל לשמור את המשחק.$"

Help_Text_AnswerCantCatchMons::
    .string "אם פוקימון פראי נחלץ\n"
    .string "מפוקיבול, נשאר בו עוד כוח.\l"
    .string "נסה להוריד לו עוד נ”ח,\l"
    .string "ולהחליש אותו בשיתוק או\l"
    .string "בשינה לפני התפיסה.\l"
    .string "אם הפוקיבול מתנדנד זמן מה,\l"
    .string "התפיסה ממש קרובה!$"

Help_Text_AnswerRanOutOfPotions::
    .string "יש חנויות פוקימון שמוכרות\n"
    .string "פריטים.\l"
    .string "לא תמצא חנות פוקימון בדרכים,\l"
    .string "ביערות או במערות.\l"
    .string "הצטייד בפריטים שאתה צריך\l"
    .string "כשאתה בעיר שיש בה חנות.$"

Help_Text_AnswerCanIBuyPokeBalls::
    .string "אפשר לקנות פוקיבולים בכל\n"
    .string "חנות פוקימון בכל עיר.\l"
    .string "לא תמצא חנות פוקימון בדרכים,\l"
    .string "ביערות או במערות.\l"
    .string "הצטייד בפוקיבולים כשאתה\l"
    .string "בעיר שיש בה חנות פוקימון.$"

Help_Text_AnswerWhatsATrainer::
    .string "מאמן הוא אדם שמגדל\n"
    .string "פוקימונים דרך קרבות.\l"
    .string "מאמנים יאתגרו אותך בכל\l"
    .string "מקום שבו הם נמצאים - בדרך,\l"
    .string "ביער, במערה, בכל מקום.\l"
    .string "אם מבטיכם נפגשים, אתה חייב\l"
    .string "לקבל את האתגר. אז היזהר!$"

Help_Text_AnswerHowDoIWinAgainstTrainer::
    .string "כדי לנצח מאמן בקרב, השתמש\n"
    .string "בפוקימונים שהסוג שלהם עדיף\l"
    .string "על זה של היריב. אפשר גם\l"
    .string "להביא פוקימונים מאומנים\l"
    .string "עם כוח מוחץ. גם יתרון\l"
    .string "מספרי על הפוקימונים של\l"
    .string "היריב הוא טקטיקה טובה.$"

Help_Text_AnswerWhereDoMonsAppear::
    .string "פוקימונים פראיים מופיעים\n"
    .string "בעשב גבוה, בדרכים וביערות,\l"
    .string "ובמערות האפלות בכל מקום.\l"
    .string "בערים אין פוקימונים פראיים\l"
    .string "ואין מאמנים, אז הן בטוחות.$"

Help_Text_AnswerWhatAreMoves::
    .string "פוקימון יכול ללמוד עד\n"
    .string "ארבעה מהלכים שונים. יש\l"
    .string "מגוון עצום של מהלכים -\l"
    .string "התקפות ומהלכים בעלי השפעה\l"
    .string "מיוחדת. לכל פוקימון יש\l"
    .string "מהלכים אחרים שהוא יכול\l"
    .string "ללמוד, וחלקם נלמדים ממכונות.$"

Help_Text_AnswerWhatAreHiddenMoves::
    .string "מהלכים נסתרים חשובים\n"
    .string "במיוחד להרפתקה שלך.\l"
    .string "כדי להשתמש בהם מחוץ לקרב,\l"
    .string "פתח את תפריט ”פוקימון”\l"
    .string "ותן לפוקימון שיודע את\l"
    .string "המהלך להשתמש בו. גם פוקימון\l"
    .string "מעולף יכול להשתמש בהם.$"

Help_Text_AnswerWhatMovesShouldIUse::
    .string "בחר ”הילחם” ויופיע תפריט\n"
    .string "המהלכים. חשוב על התאמת\l"
    .string "הסוגים והשתמש במהלכים\l"
    .string "היעילים ביותר. אפשר לבדוק\l"
    .string "את המהלכים דרך ”פוקימון”,\l"
    .string "בחירת פוקימון, ”סיכום”\l"
    .string "ואז ”כישורי פוקימון”.$"

Help_Text_AnswerWantToAddMoreMoves::
    .string "פוקימון יכול לדעת ארבעה\n"
    .string "מהלכים לכל היותר. הוא לומד\l"
    .string "אותם כשהוא עולה רמה, ואפשר\l"
    .string "גם ללמד אותו מהלך בעזרת\l"
    .string "מ”מ, מכונת מהלכים, או מ”נ.\l"
    .string "יש גם אנשים שמלמדים מהלכים.$"

Help_Text_AnswerWantToMakeMonStronger::
    .string "הדרך לחזק את הפוקימון שלך\n"
    .string "היא להילחם ולנצח הרבה.\l"
    .string "נקודות הנסיון שמרוויחים\l"
    .string "בניצחונות מצטברות ומעלות\l"
    .string "את הרמה של הפוקימונים\l"
    .string "שהשתתפו בקרב. הילחם הרבה\l"
    .string "בפוקימונים פראיים.$"

Help_Text_AnswerFoeMonsTooStrong::
    .string "אם היריבים חזקים מדי, נסה\n"
    .string "להעלות עוד את רמת\l"
    .string "הפוקימונים שלך. חזור בדרך\l"
    .string "שבאת והילחם בפוקימונים\l"
    .string "פראיים. אפשר גם להילחם\l"
    .string "במאמנים שעוד לא נלחמת בהם.$"

Help_Text_AnswerWhatDoIDoInCave::
    .string "בניגוד לדרכים וליערות,\n"
    .string "במערות פוקימונים פראיים\l"
    .string "מופיעים בכל מקום. אם\l"
    .string "הפוקימונים שלך נפגעים שם,\l"
    .string "מהר למרכז פוקימון או רפא\l"
    .string "אותם מיד. אל תנסה את מזלך!$"

Help_Text_AnswerNothingIWantToKnow::
    .string "סמוך על הידע והכוח שלך.\n"
    .string "האמן בעצמך ומצא את דרכך!$"

Help_Text_AnswerWhatsPokemonCenter::
    .string "מזהים מרכז פוקימון לפי\n"
    .string "הגג האדום והשלט שעליו.\l"
    .string "בכל מרכז פוקימון אפשר לרפא\l"
    .string "פוקימונים לגמרי ולהשתמש\l"
    .string "במחשב בחינם, אז הוא חיוני\l"
    .string "למסע. בקומה העליונה יש\l"
    .string "מתקנים לחיבור עם חברים.$"

Help_Text_AnswerWhatsPokemonMart::
    .string "מזהים חנות פוקימון לפי\n"
    .string "הגג הכחול והשלט שעליה.\l"
    .string "בכל חנות אפשר לקנות ולמכור\l"
    .string "פריטים. בחלק מהחנויות יש\l"
    .string "פריטים שנמכרים רק בעיר שלהן.$"

Help_Text_AnswerWantToEndGame::
    .string "אפשר לסיים את המשחק בבטחה\n"
    .string "בבחירת ”שמירה” בתפריט.\l"
    .string "אחרי השמירה אפשר לכבות\l"
    .string "את המשחק בלי חשש. כשתדליק\l"
    .string "אותו שוב תמשיך מהנקודה\l"
    .string "שבה שמרת לאחרונה.$"

Help_Text_AnswerWhatsAMon::
    .string "פוקימונים הם יצורים חיים\n"
    .string "שעוד יש בהם הרבה מסתורין.\l"
    .string "אפשר לראות אותם בעשב, בים\l"
    .string "ובמערות. הם נשמעים לרצון\l"
    .string "המאמנים שתפסו אותם.$"

Help_Text_AnswerWhatIsThatPersonLike::
    .string "השתמש בבודק תהילה שנמצא\n"
    .string "בכיס פריטי מפתח שבתיק.\l"
    .string "אולי תקבל רמז, אז נסה אותו.$"

Help_Text_AnswerWhatDoesHiddenMoveDo::
    .string "מהלך נסתר נלמד בעזרת מ”נ,\n"
    .string "מכונה נסתרת.\l"
    .string "מהלכים נסתרים עוזרים מאוד\l"
    .string "בהרפתקה. אחד מאיר מערות\l"
    .string "אפלות, אחר כורת עצים\l"
    .string "קטנים, ויש גם אחד לנסיעה\l"
    .string "על המים, וכן הלאה.$"

Help_Text_AnswerWhatDoIDoInSafari::
    .string "נסה לתפוס פוקימונים פראיים\n"
    .string "בזריקת כדורי ספארי מיוחדים.\l"
    .string "כל פריט שתמצא נשאר אצלך.$"

Help_Text_AnswerWhatAreSafariRules::
    .string "משחק הספארי נגמר כשעברת\n"
    .string "מרחק מסוים או כשזרקת את\l"
    .string "כל כדורי הספארי.\l"
    .string "פתח את התפריט כדי לראות\l"
    .string "כמה צעדים וכדורים נשארו.$"

Help_Text_AnswerWantToEndSafari::
    .string "אם תרצה לסיים את משחק\n"
    .string "הספארי מוקדם, פתח את התפריט\l"
    .string "ובחר ”פרישה” בראש הרשימה.$"

Help_Text_AnswerWhatIsAGym::
    .string "מכוני הפוקימון מופעלים\n"
    .string "בידי ליגת הפוקימון והם\l"
    .string "מתקני אימון למאמנים.\l"
    .string "הם פזורים בערים ובעיירות\l"
    .string "בכל הארץ. בראש כל מכון עומד\l"
    .string "מנהיג, מאמן מיומן מאוד.\l"
    .string "נצח אותו וקבל תג.$"

Help_Text_UsingPokedex::
    .string " שימוש ב”פוקדקס”$"

Help_Text_UsingPokemon::
    .string " שימוש ב”פוקימון”$"

Help_Text_UsingSummary::
    .string "  שימוש ב”סיכום”$"

Help_Text_UsingSwitch::
    .string "  שימוש ב”החלף”$"

Help_Text_UsingItem::
    .string "  שימוש ב”פריט”$"

Help_Text_UsingBag::
    .string " שימוש ב”תיק”$"

Help_Text_UsingAnItem::
    .string "  שימוש בפריט$"

Help_Text_UsingKeyItem::
    .string "  שימוש בפריט מפתח$"

Help_Text_UsingPokeBall::
    .string "  שימוש בפוקיבול$"

Help_Text_UsingPlayer::
    .string " שימוש ב”{PLAYER}”$"

Help_Text_UsingSave::
    .string " שימוש ב”שמירה”$"

Help_Text_UsingOption::
    .string " שימוש ב”אפשרויות”$"

Help_Text_UsingPotion::
    .string "    שימוש בשיקוי$"

Help_Text_UsingTownMap::
    .string "    שימוש במפת העיר$"

Help_Text_UsingTM::
    .string "    שימוש במ”מ$"

Help_Text_UsingHM::
    .string "    שימוש במ”נ$"

Help_Text_UsingMoveOutsideOfBattle::
	.string "שימוש במהלך מחוץ לקרב$"

Help_Text_RidingBicycle::
	.string "    רכיבה על האופניים$"

Help_Text_EnteringName::
	.string "הזנת שם$"

Help_Text_UsingPC::
	.string "שימוש במחשב$"

Help_Text_UsingBillsPC::
	.string " שימוש ב”מחשב של {STR_VAR_1}”$"

Help_Text_UsingWithdraw::
	.string "  שימוש ב”משוך”$"

Help_Text_UsingDeposit::
	.string "  שימוש ב”הפקד”$"

Help_Text_UsingMove::
	.string "  שימוש ב”הזז”$"

Help_Text_MovingItems::
	.string "  הזזת פריטים$"

Help_Text_UsingPlayersPC::
	.string " שימוש ב”המחשב של {PLAYER}”$"

Help_Text_UsingWithdrawItem::
	.string "  שימוש ב”משוך פריט”$"

Help_Text_UsingDepositItem::
	.string "  שימוש ב”הפקד פריט”$"

Help_Text_UsingMailbox::
	.string "  שימוש ב”תיבת דואר”$"

Help_Text_UsingProfOaksPC::
	.string " שימוש ב”המחשב של פרו' אוק”$"

Help_Text_OpeningMenu::
	.string "פתיחת התפריט$"

Help_Text_UsingFight::
	.string " שימוש ב”הילחם”$"

Help_Text_UsingPokemon2::
	.string " שימוש ב”פוקימון”$"

Help_Text_UsingShift::
	.string "  שימוש ב”החלפה”$"

Help_Text_UsingSummary2::
	.string "  שימוש ב”סיכום”$"

Help_Text_UsingBag2::
	.string " שימוש ב”תיק”$"

Help_Text_ReadingPokedex::
	.string " קריאה ב”פוקדקס”$"

Help_Text_UsingHomePC::
	.string "שימוש במחשב שבבית$"

Help_Text_UsingItemStorage::
	.string "שימוש במערכת אחסון הפריטים$"

Help_Text_UsingWithdrawItem2::
	.string "  שימוש ב”משוך פריט”$"

Help_Text_UsingDepositItem2::
	.string "  שימוש ב”הפקד פריט”$"

Help_Text_UsingMailbox2::
	.string "שימוש בתיבת הדואר$"

Help_Text_UsingRun::
	.string " שימוש ב”לברוח”$"

Help_Text_RegisterKeyItem::
	.string "  ”רשום” פריט מפתח$"

Help_Text_UsingBall::
	.string " שימוש ב”כדור”$"

Help_Text_UsingBait::
	.string " שימוש ב”פיתיון”$"

Help_Text_UsingRock::
	.string " שימוש ב”אבן”$"

Help_Text_UsingHallOfFame::
	.string " שימוש ב”היכל התהילה”$"

Help_Text_HowToUsePokedex::
	.string "{CIRCLE_1} בחר ”פוקדקס” בתפריט.\n"
	.string "{CIRCLE_2} בחר פוקימון בעזרת פקודות\n"
	.string "   כמו ”רשימת פוקימון”,\n"
	.string "   ”בתי גידול פוקימון”\n"
	.string "   ו”חיפוש”.\n"
	.string "{CIRCLE_3} בחר פוקימון כדי לקבל\n"
	.string "   מידע מפורט.$"

Help_Text_HowToUsePokemon::
	.string "{CIRCLE_1} בחר ”פוקימון” בתפריט.\n"
	.string "{CIRCLE_2} בחר פוקימון מהקבוצה שלך.\n"
	.string "{CIRCLE_3} בחר ”סיכום”, ”החלף”\n"
	.string "   או ”פריט”.$"

Help_Text_HowToUseSummary::
	.string "{CIRCLE_1} בחר ”סיכום”.\n"
	.string "{CIRCLE_2} לחץ שמאלה או ימינה על {PLUS}\n"
	.string "   בפד השליטה כדי לראות:\n"
	.string "   ”מידע פוקימון”\n"
	.string "   ”כישורי פוקימון”\n"
	.string "   ”מהלכים ידועים”$"

Help_Text_HowToUseSwitch::
	.string "{CIRCLE_1} בחר את הפוקימון שברצונך\n"
	.string "   להחליף.\n"
	.string "{CIRCLE_2} בחר ”החלף”.\n"
	.string "{CIRCLE_3} בחר את הפוקימון שיבוא\n"
	.string "   במקומו.\n"
	.string "הפוקימון שבצד שמאל של המסך\n"
	.string "יוצא ראשון לקרב.$"

Help_Text_HowToUseItem::
	.string "{CIRCLE_1} בחר ”פריט”.\n"
	.string "{CIRCLE_2} בחר ”תן” כדי למסור\n"
	.string "   לפוקימון פריט להחזיק,\n"
	.string "   או ”קח” כדי לקחת פריט.\n"
	.string "פוקימון יכול להחזיק\n"
	.string "פריט אחד בלבד!$"

Help_Text_HowToUseBag::
	.string "{CIRCLE_1} בחר ”תיק” בתפריט.\n"
	.string "{CIRCLE_2} לחץ שמאלה או ימינה על {PLUS}\n"
	.string "   בפד השליטה כדי לעבור בין:\n"
	.string "   ”פריטים”\n"
	.string "   ”פריטי מפתח”\n"
	.string "   ”פוקיבולים”\n"
	.string "   לחץ למעלה או למטה לבחור פריט.$"

Help_Text_HowToUseAnItem::
	.string "{CIRCLE_1} בחר את כיס ”פריטים”.\n"
	.string "{CIRCLE_2} לחץ למעלה או למטה על {PLUS}\n"
	.string "   בפד השליטה לבחירת פריט.\n"
	.string "{CIRCLE_3} בחר ”השתמש” כדי להשתמש\n"
	.string "   בפריט שנבחר.\n"
	.string "יש פריטים שאי אפשר להשתמש בהם\n"
	.string "בכל מקום או בכל מצב.$"

Help_Text_HowToUseKeyItem::
	.string "{CIRCLE_1} בחר את כיס ”פריטי מפתח”.\n"
	.string "{CIRCLE_2} לחץ למעלה או למטה על {PLUS}\n"
	.string "   בפד השליטה לבחירת הפריט.\n"
	.string "{CIRCLE_3} בחר ”השתמש” כדי להשתמש\n"
	.string "   בפריט המפתח שנבחר.$"

Help_Text_HowToUsePokeBall::
	.string "{CIRCLE_1} בזמן קרב מול פוקימון פראי,\n"
	.string "   פתח את כיס ”פוקיבולים”\n"
	.string "   בתיק.\n"
	.string "{CIRCLE_2} לחץ למעלה או למטה על {PLUS}\n"
	.string "   בפד השליטה לבחירת פוקיבול.\n"
	.string "{CIRCLE_3} בחר ”השתמש” כדי לזרוק\n"
	.string "   את הפוקיבול שנבחר.$"

Help_Text_HowToUsePlayer::
	.string "{CIRCLE_1} בחר ”{PLAYER}” בתפריט.\n"
	.string "{CIRCLE_2} כרטיס המאמן שלך מוצג עם\n"
	.string "   המידע הבסיסי. לחץ על הכפתור A\n"
	.string "   כדי להפוך את הכרטיס.\n"
	.string "{CIRCLE_3} בצד השני של הכרטיס\n"
	.string "   יש מידע נוסף ומגוון.$"

Help_Text_HowToUseSave::
	.string "{CIRCLE_1} בחר ”שמירה” בתפריט.\n"
	.string "{CIRCLE_2} בחר ”כן” וההתקדמות שלך\n"
	.string "   תישמר בקובץ השמירה.\n"
	.string "אחרי השמירה אפשר לכבות\n"
	.string "את המשחק ולהמשיך בפעם הבאה\n"
	.string "מהנקודה שבה שמרת.$"

Help_Text_HowToUseOption::
	.string "{CIRCLE_1} בחר ”אפשרויות” בתפריט.\n"
	.string "{CIRCLE_2} לחץ למעלה או למטה על {PLUS}\n"
	.string "   בפד השליטה לבחירת הגדרה,\n"
	.string "   ואז לחץ שמאלה או ימינה\n"
	.string "   כדי לשנות אותה.\n"
	.string "{CIRCLE_3} בסיום בחר ”ביטול” או לחץ\n"
	.string "   על הכפתור B.$"

Help_Text_HowToUsePotion::
	.string "{CIRCLE_1} פתח את התפריט.\n"
	.string "{CIRCLE_2} לחץ למעלה או למטה על {PLUS}\n"
	.string "   בפד השליטה ובחר ”תיק”.\n"
	.string "{CIRCLE_3} בחר ”שיקוי” בכיס\n"
	.string "   ”פריטים”.\n"
	.string "{CIRCLE_4} בחר ”השתמש”.\n"
	.string "{CIRCLE_5} בחר את הפוקימון לריפוי.$"

Help_Text_HowToUseTownMap::
	.string "{CIRCLE_1} פתח את התפריט.\n"
	.string "{CIRCLE_2} לחץ למעלה או למטה על {PLUS}\n"
	.string "   בפד השליטה ובחר ”תיק”.\n"
	.string "{CIRCLE_3} לחץ שמאלה או ימינה כדי\n"
	.string "   לפתוח את כיס ”פריטי מפתח”,\n"
	.string "   ואז בחר ”מפת העיר”.\n"
	.string "{CIRCLE_4} בחר ”השתמש” לפתיחת המפה.$"

Help_Text_HowToUseTM::
	.string "{CIRCLE_1} פתח את התפריט.\n"
	.string "{CIRCLE_2} פתח את כיס ”פריטי מפתח”\n"
	.string "   שב”תיק”.\n"
	.string "{CIRCLE_3} ”פתח” את תיק המ”מ.\n"
	.string "{CIRCLE_4} בחר ”השתמש” במ”מ.\n"
	.string "{CIRCLE_5} בחר פוקימון שיכול ללמוד\n"
	.string "   את המהלך שבמ”מ.$"

Help_Text_HowToUseHM::
	.string "{CIRCLE_1} פתח את התפריט.\n"
	.string "{CIRCLE_2} פתח את כיס ”פריטי מפתח”\n"
	.string "   שב”תיק”.\n"
	.string "{CIRCLE_3} ”פתח” את תיק המ”מ.\n"
	.string "{CIRCLE_4} בחר ”השתמש” במ”נ.\n"
	.string "{CIRCLE_5} בחר פוקימון שיכול ללמוד אותו.\n"
	.string "קשה למחוק מהלך של מ”נ, אז היזהר!$"

Help_Text_HowToUseMoveOutsideOfBattle::
	.string "{CIRCLE_1} פתח את התפריט.\n"
	.string "{CIRCLE_2} בחר ”פוקימון”.\n"
	.string "{CIRCLE_3} בחר פוקימון שיודע\n"
	.string "   מהלך נסתר. המהלכים שאפשר\n"
	.string "   להשתמש בהם מופיעים בכחול.\n"
	.string "   בחר את המהלך הרצוי כדי לנפץ\n"
	.string "   מכשול, לעוף, לגלוש ועוד.$"

Help_Text_HowToRideBicycle::
	.string "{CIRCLE_1} פתח את התפריט, פתח את\n"
	.string "   כיס ”פריטי מפתח” שב”תיק”\n"
	.string "   ובחר ”אופניים”.\n"
	.string "{CIRCLE_2} בחירה ב”השתמש” תעלה\n"
	.string "   אותך על האופניים. אפשר גם\n"
	.string "   לבחור ”רשום” לשימוש מהיר\n"
	.string "   בלחיצה על כפתור סלקט.$"

Help_Text_HowToEnterName::
	.string "{CIRCLE_1} הזז את הסמן לאות הרצויה\n"
	.string "   עם {PLUS} בפד השליטה, ואז לחץ\n"
	.string "   על הכפתור A כדי להזין.\n"
	.string "{CIRCLE_2} לחץ על הכפתור B כדי למחוק.\n"
	.string "{CIRCLE_3} לחץ על כפתור סלקט כדי\n"
	.string "   להחליף בין סוגי האותיות.\n"
	.string "{CIRCLE_4} סיים בלחיצה על ”אישור”.$"

Help_Text_HowToUsePC::
	.string "{CIRCLE_1} גש למרכז פוקימון, עמוד מול\n"
	.string "   המחשב ולחץ על הכפתור A.$"

Help_Text_HowToUseBillsPC::
	.string "{CIRCLE_1} בחר ”מחשב של {STR_VAR_1}” במחשב.\n"
	.string "{CIRCLE_2} בחר באחת משלוש האפשרויות\n"
	.string "   העליונות כדי להיכנס למערכת\n"
	.string "   אחסון הפוקימונים.\n"
	.string "אם תתפוס פוקימון ויש לך כבר\n"
	.string "שישה בקבוצה, הוא יישלח\n"
	.string "אוטומטית לתיבה במערכת!$"

Help_Text_HowToUseWithdraw::
	.string "{CIRCLE_1} בחר פוקימון בתיבה הפתוחה\n"
	.string "   עם {PLUS} בפד השליטה.\n"
	.string "{CIRCLE_2} בחר ”משוך” כדי להוציא\n"
	.string "   אותו מהתיבה ולהוסיף\n"
	.string "   לקבוצה שלך.\n"
	.string "אי אפשר למשוך פוקימון אם כבר\n"
	.string "יש איתך שישה!$"

Help_Text_HowToUseDeposit::
	.string "{CIRCLE_1} בחר פוקימון מהקבוצה שלך\n"
	.string "   עם {PLUS} בפד השליטה.\n"
	.string "{CIRCLE_2} בחר ”הפקד”.\n"
	.string "{CIRCLE_3} בחר תיבה ולחץ על הכפתור A\n"
	.string "   כדי לאחסן את הפוקימון.\n"
	.string "אם יש איתך רק פוקימון אחד,\n"
	.string "אי אפשר לאחסן אותו!$"

Help_Text_HowToUseMove::
	.string "{CIRCLE_1} בחר פוקימון בתיבה הפתוחה.\n"
	.string "{CIRCLE_2} בחר ”הזז” כדי להרים אותו\n"
	.string "   ולהזיז אותו לכל מקום עם\n"
	.string "   {PLUS} בפד השליטה.\n"
	.string "{CIRCLE_3} הזז את הפוקימון אל שם\n"
	.string "   התיבה ולחץ שמאלה או ימינה\n"
	.string "   כדי להעביר לתיבה אחרת.$"

Help_Text_HowToMoveItems::
	.string "{CIRCLE_1} פוקימון שמוצג בעמעום יכול\n"
	.string "   לקבל פריט: בחר אותו ולחץ\n"
	.string "   על הכפתור A.\n"
	.string "{CIRCLE_2} פוקימון שמוצג בבירור יכול\n"
	.string "   למסור את הפריט שהוא מחזיק\n"
	.string "   לפוקימון אחר, או להחזיר\n"
	.string "   אותו לתיק עם הכפתור A.$"

Help_Text_HowToUsePlayersPC::
	.string "{CIRCLE_1} בחר ”המחשב של {PLAYER}” במחשב.\n"
	.string "{CIRCLE_2} בחר ”אחסון פריטים”\n"
	.string "   או ”תיבת דואר”.\n"
	.string "אם התיק שלך מלא אפשר לאחסן\n"
	.string "פריטים במחשב שלך, וגם למשוך\n"
	.string "משם פריטים שאחסנת.$"

Help_Text_HowToUseWithdrawItem::
	.string "{CIRCLE_1} בחר ”משוך פריט”.\n"
	.string "{CIRCLE_2} בחר את הפריט למשיכה.\n"
	.string "{CIRCLE_3} הפריט יימשך ויונח\n"
	.string "   בכיס הפריטים שבתיק.\n"
	.string "   אפשר גם למסור אותו ישירות\n"
	.string "   לפוקימון שיחזיק אותו.$"

Help_Text_HowToUseDepositItem::
	.string "{CIRCLE_1} בחר ”הפקד פריט”.\n"
	.string "{CIRCLE_2} בחר בתיק את הפריט להפקדה\n"
	.string "   בעזרת {PLUS} בפד השליטה.\n"
	.string "{CIRCLE_3} כדי להפקיד יותר מפריט\n"
	.string "   אחד, הזן את הכמות\n"
	.string "   בעזרת {PLUS} בפד השליטה,\n"
	.string "   ואז לחץ על הכפתור A.$"

Help_Text_HowToUseMailbox::
	.string "כשלוקחים דואר מפוקימון,\n"
	.string "הוא עובר לתיבת הדואר. בלי\n"
	.string "דואר אי אפשר להשתמש בה.\n"
	.string "{CIRCLE_1} בחר ב”המחשב של {PLAYER}”.\n"
	.string "{CIRCLE_2} בחר ב”תיבת דואר” כדי לקרוא\n"
	.string "   דואר או לתת לפוקימון.$"

Help_Text_HowToUseProfOaksPC::
	.string "{CIRCLE_1} בחר ב”המחשב של פרופ' אוק”.\n"
	.string "{CIRCLE_2} פרופ' אוק יעריך את\n"
	.string "   הפוקדקס שלך.\n"
	.string "ההערכות שלו ייתנו לך רמזים\n"
	.string "לתפיסת עוד פוקימונים!$"

Help_Text_HowToOpenMenu::
	.string "{CIRCLE_1} לחץ על כפתור {START_BUTTON}.\n"
	.string "{CIRCLE_2} התפריט ייפתח בצד ימין.\n"
	.string "{CIRCLE_3} לפי המצב, בתפריט יופיעו\n"
	.string "   כותרות שונות.\n"
	.string "לפעמים התפריט לא ייפתח,\n"
	.string "למשל בזמן שיחה, פעולה\n"
	.string "או קרב.$"

Help_Text_HowToUseFight::
	.string "{CIRCLE_1} בחר ב”הילחם”.\n"
	.string "{CIRCLE_2} בחר אחד מהמהלכים שמוצגים,\n"
	.string "והמהלך הזה יופעל!$"

Help_Text_HowToUsePokemon2::
	.string "{CIRCLE_1} בחר ב”פוקימון”.\n"
	.string "{CIRCLE_2} בחר את הפוקימון מהקבוצה\n"
	.string "   שבו אתה רוצה להשתמש.\n"
	.string "{CIRCLE_3} אם יש איתך שני פוקימונים\n"
	.string "   או יותר, אפשר להחליף\n"
	.string "   ביניהם עם ”החלפה”. בדוק\n"
	.string "   נתונים עם ”סיכום”.$"

Help_Text_HowToUseShift::
	.string "פקודה זו מחליפה את הפוקימון\n"
	.string "שבקרב באחר מהקבוצה שלך.\n"
	.string "{CIRCLE_1} בחר את הפוקימון שיישלח.\n"
	.string "{CIRCLE_2} בחר ב”החלפה”.\n"
	.string "{CIRCLE_3} הפוקימון שבחרת יחליף\n"
	.string "   מקום עם הפוקימון שבקרב!$"

Help_Text_HowToUseSummary2::
	.string "{CIRCLE_1} בחר ב”סיכום”.\n"
	.string "{CIRCLE_2} לחץ שמאלה או ימינה על {PLUS}\n"
	.string "   בפד השליטה כדי לעבור בין:\n"
	.string "   ”מידע פוקימון”\n"
	.string "   ”כישורי פוקימון”\n"
	.string "   ”מהלכים ידועים”$"

Help_Text_HowToUseBag2::
	.string "{CIRCLE_1} בחר ב”תיק”.\n"
	.string "{CIRCLE_2} לחץ שמאלה או ימינה על {PLUS}\n"
	.string "   בפד השליטה כדי לעבור בין:\n"
	.string "   ”פריטים”\n"
	.string "   ”פריטי מפתח”\n"
	.string "   ”פוקיבולים”\n"
	.string "   לחץ מעלה או מטה לבחירה.$"

Help_Text_HowToReadPokedex::
	.string "{CIRCLE_1} פוקימונים שתפסת מסומנים\n"
	.string "   בסימן פוקיבול ברשימת\n"
	.string "   הפוקדקס.\n"
	.string "{CIRCLE_2} פוקימון שנתפס מספק\n"
	.string "   כמות גדולה של מידע.\n"
	.if REVISION < 1
	.string "{CIRCLE_3} בחר ב”אזור” כדי להציג את\n"
	.string "   מפת העיר עם אזורי המחיה.$"
	.else
	.string "{CIRCLE_3} בחר ב”נתון הבא” כדי להציג\n"
	.string "   את מפת העיר ואזורי המחיה.$"
	.endif

Help_Text_HowToUseHomePC::
	.string "{CIRCLE_1} גש למחשב שבבית ולחץ על\n"
	.string "   הכפתור A.\n"
	.string "{CIRCLE_2} המחשב יידלק.\n"
	.string "{CIRCLE_3} בחר ב”אחסון פריטים” או\n"
	.string "   ב”תיבת דואר”.$"

Help_Text_HowToUseItemStorage::
	.string "{CIRCLE_1} בחר ב”משוך פריט” כדי למשוך\n"
	.string "   פריט ששמור במחשב שלך.\n"
	.string "{CIRCLE_2} בחר ב”הפקד פריט” כדי\n"
	.string "   להעביר פריט מהתיק אל המחשב.$"

Help_Text_HowToUseWithdrawItem2::
	.string "{CIRCLE_1} בחר ב”משוך פריט”.\n"
	.string "{CIRCLE_2} בחר את הפריט למשיכה.\n"
	.string "{CIRCLE_3} הפריט יימשך וייכנס\n"
	.string "   לכיס הפריטים שבתיק.\n"
	.string "   אפשר גם לתת אותו ישירות\n"
	.string "   לפוקימון שיחזיק אותו.$"

Help_Text_HowToUseDepositItem2::
	.string "{CIRCLE_1} בחר ב”הפקד פריט”.\n"
	.string "{CIRCLE_2} בחר בעזרת {PLUS} בפד השליטה\n"
	.string "   את הפריט מהתיק שיופקד.\n"
	.string "{CIRCLE_3} אם התיק ריק, אי אפשר\n"
	.string "   להשתמש בפקודה הזו!$"

Help_Text_HowToUseMailbox2::
	.string "כשלוקחים דואר מפוקימון,\n"
	.string "הוא עובר לתיבת הדואר. בלי\n"
	.string "דואר אי אפשר להשתמש בה.\n"
	.string "{CIRCLE_1} בחר דואר לפי השם כדי לקרוא\n"
	.string "   אותו או לתת לפוקימון.$"

Help_Text_HowToUseRun::
	.string "אי אפשר ”לברוח” מקרב\n"
	.string "מול מאמן!\n"
	.string "{CIRCLE_1} אפשר ”לברוח” מפוקימון פראי.\n"
	.string "{CIRCLE_2} הסיכוי לברוח גדל אם\n"
	.string "   הפוקימון שבקרב מהיר.$"

Help_Text_HowToRegisterKeyItem::
	.string "אפשר לרשום פריט מפתח\n"
	.string "ולהשתמש בו מיד בכפתור סלקט!\n"
	.string "{CIRCLE_1} פתח את כיס ”פריטי מפתח”.\n"
	.string "{CIRCLE_2} בחר את פריט המפתח ואז\n"
	.string "   בחר ב”רשום”.$"

Help_Text_HowToUseBall::
	.string "{CIRCLE_1} בחר כדי לזרוק את הכדור\n"
	.string "   המיוחד של אזור הספארי.\n"
	.string "כשפוקימון פראי מופיע, זרוק\n"
	.string "כדורי ספארי כדי לתפוס אותו!$"

Help_Text_HowToUseBait::
	.string "{CIRCLE_1} בחר כדי לזרוק את המזון\n"
	.string "   המיוחד של אזור הספארי.\n"
	.string "זהו מזון פוקימון מגולגל\n"
	.string "לכדור שקל לאכול. פוקימון\n"
	.string "פראי עשוי להימשך לפיתיון\n"
	.string "שנזרק, ולא לברוח!$"

Help_Text_HowToUseRock::
	.string "{CIRCLE_1} בחר כדי לזרוק אבן שמונחת\n"
	.string "   על הקרקע באזור הספארי.\n"
	.string "זריקת אבן על פוקימון עלולה\n"
	.string "לגרום לו לברוח, אבל קל יותר\n"
	.string "לתפוס אותו!$"

Help_Text_HowToUseHallOfFame::
	.string "{CIRCLE_1} בחר ב”היכל התהילה” במחשב.\n"
	.string "{CIRCLE_2} אפשר לצפות בפוקימונים\n"
	.string "   שנכנסו להיכל התהילה.$"

Help_Text_HP::
	.string "נ”ח$"

Help_Text_EXP::
	.string "נק”נ {RIGHT_PAREN}נקודות נסיון{LEFT_PAREN}$"

Help_Text_Moves::
	.string "מהלכים$"

Help_Text_Attack::
	.string "התקפה$"

Help_Text_Defense::
	.string "הגנה$"

Help_Text_SpAtk::
	.string "התק' מיוחדת$"

Help_Text_SpDef::
	.string "הגנ' מיוחדת$"

Help_Text_Speed::
	.string "מהירות$"

Help_Text_Level::
	.string "רמה {RIGHT_PAREN}רמת הפוקימון{LEFT_PAREN}$"

Help_Text_Type::
	.string "סוג$"

Help_Text_OT::
	.string "מאמן מקורי$"

Help_Text_Item::
	.string "פריט$"

Help_Text_Ability::
	.string "יכולת$"

Help_Text_Money::
	.string "כסף$"

Help_Text_MoveType::
	.string "סוג מהלך$"

Help_Text_Nature::
	.string "אופי$"

Help_Text_IDNo::
	.string "מספר מזהה$"

Help_Text_PP::
	.string "נקודות כוח$"

Help_Text_Power::
	.string "עוצמה$"

Help_Text_Accuracy::
	.string "דיוק$"

Help_Text_FNT::
	.string "התעלפות$"

Help_Text_Items::
	.string "פריטים$"

Help_Text_KeyItems::
	.string "פריטי מפתח$"

Help_Text_PokeBalls::
	.string "פוקיבולים$"

Help_Text_Pokedex::
	.string "פוקדקס$"

Help_Text_PlayTime::
	.string "זמן משחק$"

Help_Text_Badges::
	.string "תגים$"

Help_Text_TextSpeed::
	.string "מהירות טקסט$"

Help_Text_BattleScene::
	.string "סצנת קרב$"

Help_Text_BattleStyle::
	.string "סגנון קרב$"

Help_Text_Sound::
	.string "צליל$"

Help_Text_ButtonMode::
	.string "מצב כפתורים$"

Help_Text_Frame::
	.string "מסגרת$"

Help_Text_Cancel2::
	.string "ביטול$"

Help_Text_TM::
	.string "מ”מ$"

Help_Text_HM::
	.string "מ”נ$"

Help_Text_HMMove::
	.string "מהלך מ”נ$"

Help_Text_Evolution::
	.string "התפתחות$"

Help_Text_StatusProblem::
	.string "בעיית סטטוס$"

Help_Text_Pokemon::
	.string "פוקימון$"

Help_Text_IDNo2::
	.string "מספר מזהה$"

Help_Text_Money2::
	.string "כסף$"

Help_Text_Badges2::
	.string "תגים$"

Help_Text_DefineHP::
	.string "מד הנ”ח מציג את חיוניות\n"
	.string "הפוקימון. אם הנ”ח יורדות\l"
	.string "לאפס, הוא מתעלף ולא\l"
	.string "יכול להילחם. לכן המטרה\l"
	.string "בקרב היא לאפס את הנ”ח\l"
	.string "של היריב. רפא פוקימון פצוע\l"
	.string "במרכז פוקימון או עם פריט.$"

Help_Text_DefineEXP::
	.string "נקודות נסיון נצברות\n"
	.string "לפוקימון שמשתתף בקרב\l"
	.string "ומנצח בו. כשנצברות\l"
	.string "מספיק נקודות, הפוקימון\l"
	.string "עולה רמה. מד הנסיון\l"
	.string "מציג את הנקודות שנצברו\l"
	.string "והוא מתאפס בעליית רמה.$"

Help_Text_DefineMoves::
	.string "פוקימון יכול ללמוד עד\n"
	.string "ארבעה מהלכים שונים. יש\l"
	.string "מהלכי התקפה ומהלכים\l"
	.string "בעלי השפעות מיוחדות.\l"
	.string "כל מין פוקימון לומד\l"
	.string "מהלכים אחרים, וחלקם\l"
	.string "נלמדים מפריטים.$"

Help_Text_DefineAttack::
	.string "התקפה מציינת את עוצמת\n"
	.string "מהלכי ההתקפה. ככל שהיא\l"
	.string "גבוהה יותר, המהלך חזק\l"
	.string "יותר. היא חלה על מהלכים\l"
	.string "מסוגי רגיל, רעל, אדמה,\l"
	.string "תעופה, חרק, קרב, סלע,\l"
	.string "רוח ופלדה.$"

Help_Text_DefineDefense::
	.string "הגנה מציינת את עמידות\n"
	.string "הפוקימון בפני התקפות\l"
	.string "פיזיות. ככל שהיא גבוהה\l"
	.string "יותר, הנזק שייגרם קטן.$"

Help_Text_DefineSpAtk::
	.string "התק' מיוחדת מציינת את\n"
	.string "עוצמת מהלכי ההתקפה\l"
	.string "המיוחדים. ככל שהיא גבוהה\l"
	.string "יותר, המהלך חזק יותר.\l"
	.string "היא חלה על מהלכים\l"
	.string "מסוגי אש, מים, חשמל, עשב,\l"
	.string "קרח, פסיכי, דרקון ואפל.$"

Help_Text_DefineSpDef::
	.string "הגנ' מיוחדת מציינת את\n"
	.string "עמידות הפוקימון בפני\l"
	.string "התקפות מיוחדות.\l"
	.string "ככל שהיא גבוהה יותר,\l"
	.string "הנזק שייגרם קטן יותר.$"

Help_Text_DefineSpeed::
	.string "מהירות מציינת את זריזות\n"
	.string "הפוקימון. אם היא גבוהה\l"
	.string "מזו של היריב, הפוקימון\l"
	.string "יפעל לפניו בקרב.$"

Help_Text_DefineLevel::
	.string "רמה מציינת את הגדילה\n"
	.string "והחוזק של הפוקימון.\l"
	.string "בדרך כלל, בעליית רמה\l"
	.string "נתונים כמו נ”ח, התקפה\l"
	.string "והגנה עולים והוא מתחזק.\l"
	.string "לפעמים הפוקימון לומד\l"
	.string "מהלך חדש בעליית רמה.$"

Help_Text_DefineType::
	.string "פוקימונים ומהלכים\n"
	.string "מחולקים לסוגים. לכל סוג\l"
	.string "יש יתרון מול סוגים\l"
	.string "מסוימים וחיסרון מול\l"
	.string "אחרים. כמו במשחק אבן, נייר\l"
	.string "ומספריים: מים חזק מול אש\l"
	.string "וחלש מול עשב.$"

Help_Text_DefineOT::
	.string "מאמן מקורי הוא המאמן\n"
	.string "הראשון שתפס את הפוקימון\l"
	.string "הנבחר.\l"
	.string "גם אם הפוקימון יוחלף,\l"
	.string "שם המאמן המקורי לא ישתנה.$"

Help_Text_DefineItem::
	.string "כל פוקימון יכול להחזיק\n"
	.string "פריט אחד. יש פריטים\l"
	.string "שהפוקימון משתמש בהם\l"
	.string "אוטומטית במצבים מסוימים.\l"
	.string "כדי לתת פריט, בחר אותו\l"
	.string "בתיק ולחץ ”תן”.$"

Help_Text_DefineAbility::
	.string "לכל פוקימון יש יכולת\n"
	.string "מיוחדת. יש יכולות רבות,\l"
	.string "חלקן פועלות בקרב\l"
	.string "וחלקן מחוצה לו. היכולות\l"
	.string "משתנות ממין למין, ולחלק\l"
	.string "מהמינים יש יותר מאחת.$"

Help_Text_DefineMoney::
	.string "בכל ניצחון בקרב מול\n"
	.string "מאמן אתה מקבל כסף פרס.\l"
	.string "חסוך אותו כדי לקנות\l"
	.string "בחנויות הפוקימון!$"

Help_Text_DefineMoveType::
	.string "גם מהלכים מחולקים לסוגים.\n"
	.string "אם פוקימון משתמש במהלך\l"
	.string "מהסוג שלו, עוצמת\l"
	.string "המהלך גדלה. ואם לסוג\l"
	.string "המהלך יש יתרון מול\l"
	.string "המטרה, גם האפקטיביות\l"
	.string "שלו גדלה.$"

Help_Text_DefineNature::
	.string "לכל פוקימון יש אופי\n"
	.string "משלו. נראה שהאופי\l"
	.string "משפיע על האופן שבו\l"
	.string "הפוקימון גדל בעליית רמה.$"

Help_Text_DefineIDNo::
	.string "המספר המזהה הוא מספר\n"
	.string "מיוחד שניתן לך כמאמן.\l"
	.string "יחד עם שם המאמן הוא\l"
	.string "מזהה במדויק את המאמן\l"
	.string "המקורי.\l"
	.string "המספר לא משתנה גם אם\l"
	.string "הפוקימון יוחלף.$"

Help_Text_DefinePP::
	.string "נקודות כוח מציינות\n"
	.string "כמה פעמים אפשר להשתמש\l"
	.string "במהלך מסוים בקרב.\l"
	.string "כמו נ”ח, אפשר לחדש אותן\l"
	.string "במרכז פוקימון או עם\l"
	.string "פריטים.$"

Help_Text_DefinePower::
	.string "עוצמה מציינת את חוזק\n"
	.string "ההתקפה. ככל שהמספר\l"
	.string "גבוה יותר, הנזק ליריב\l"
	.string "גדול יותר!$"

Help_Text_DefineAccuracy::
	.string "דיוק מציין את הסיכוי\n"
	.string "שהמהלך יפגע ביריב.\l"
	.string "ככל שהמספר גבוה יותר,\l"
	.string "כך גדל הסיכוי לפגיעה.$"

Help_Text_DefineFNT::
	.string "פוקימון מתעלף כאשר\n"
	.string "הנ”ח שלו יורדות לאפס.\l"
	.string "במצב הזה הוא אינו\l"
	.string "יכול להשתתף בקרב.\l"
	.string "רפא פוקימון מעולף במרכז\l"
	.string "פוקימון או עם פריט.$"

Help_Text_DefineItems::
	.string "פריטים רגילים שנקנים\n"
	.string "בחנות נכנסים לכיס הפריטים.\l"
	.string "אפשר להשתמש בהם, לתת\l"
	.string "אותם לפוקימון או להשליך.$"

Help_Text_DefineKeyItems::
	.string "פריטים חשובים שאתה מוצא\n"
	.string "או מקבל מאנשים נכנסים\l"
	.string "לכיס פריטי המפתח.\l"
	.string "אפשר להשתמש בהם או לרשום\l"
	.string "אותם לשימוש מיידי בכפתור\l"
	.string "סלקט. אחרי הרישום אפשר\l"
	.string "להשתמש בלי לפתוח את התיק.$"

Help_Text_DefinePokeBalls::
	.string "פוקיבולים משמשים לתפיסת\n"
	.string "פוקימונים פראיים, והם\l"
	.string "נכנסים לכיס פוקה-כדורים.\l"
	.string "אפשר לקנות אותם בחנות\l"
	.string "הפוקימון, להשתמש בהם,\l"
	.string "לתת אותם לפוקימון\l"
	.string "או להשליך אותם.$"

Help_Text_DefinePokedex::
	.string "זה מציין כמה מיני\n"
	.string "פוקימון תפסת או פיתחת\l"
	.string "ורשמת בפוקדקס.\l"
	.string "השתדל לתפוס פוקימונים\l"
	.string "מכל הסוגים!$"

Help_Text_DefinePlayTime::
	.string "זהו הזמן הכולל שבו\n"
	.string "שיחקת במשחק הזה.$"

Help_Text_DefineBadges::
	.string "כאן נרשמים ומוצגים תגי\n"
	.string "ליגת הפוקימון שזכית בהם.\l"
	.string "תג מתקבל על ניצחון על\l"
	.string "מנהיגי מכון בערים שונות.$"

Help_Text_DefineTextSpeed::
	.string "אפשר לכוון את מהירות\n"
	.string "הצגת הטקסט. בחר: איטי,\l"
	.string "בינוני או מהיר.$"

Help_Text_DefineBattleScene::
	.string "אפשר להפעיל או לכבות\n"
	.string "את אנימציית הקרב.$"

Help_Text_DefineBattleStyle::
	.string "אפשר לבחור אם מאמן יוכל\n"
	.string "להחליף פוקימון אחרי\l"
	.string "שהיריב שלו התעלף.\l"
	.string "בחר ב”החלפה” אם תרצה\l"
	.string "לקבל הזדמנות להחליף\l"
	.string "פוקימון במצב הזה.$"

Help_Text_DefineSound::
	.string "אפשר לבחור בין פלט קול\n"
	.string "מונו לבין סטריאו.$"

Help_Text_DefineButtonMode::
	.string "בחר ב”עזרה” כדי להציג\n"
	.string "הודעות עזרה בכפתור L או R.\l"
	.string "בחר ב”RL” כדי לדפדף\l"
	.string "בדפי הפוקדקס ובכיסי התיק\l"
	.string "בעזרת הכפתורים L ו-R.\l"
	.string "בחר ב”A=L” כדי שכפתור L\l"
	.string "יפעל כמו כפתור A.$"

Help_Text_DefineFrame::
	.string "אפשר לבחור את עיצוב\n"
	.string "המסגרת בחלק מהתפריטים.\l"
	.string "בחר מה שאתה אוהב.$"

Help_Text_DefineCancel2::
	.string "ההגדרות ישתנו לפי\n"
	.string "הבחירות המסומנות באדום,\l"
	.string "ותחזור לתפריט.$"

Help_Text_DefineTM::
	.string "מ”מ, מכונת מהלכים, היא\n"
	.string "מכשיר שמלמד מהלך לפוקימון.\l"
	.string "יש סוגים רבים שלה.\l"
	.string "אפשר ללמד מהלך רק\l"
	.string "לפוקימון שמסוגל להשתמש בו.\l"
	.string "מ”מ נשברת אחרי שימוש אחד.$"

Help_Text_DefineHM::
	.string "מ”נ, מכונה נסתרת, היא\n"
	.string "מכשיר שמלמד מהלך נסתר.\l"
	.string "אפשר ללמד מהלך נסתר רק\l"
	.string "לפוקימון שמסוגל להשתמש בו.\l"
	.string "בניגוד למ”מ, אפשר להשתמש\l"
	.string "במ”נ שוב ושוב. קשה מאוד\l"
	.string "לפוקימון לשכוח מהלך כזה.$"

Help_Text_DefineHMMove::
	.string "מהלכים נסתרים חשובים\n"
	.string "במיוחד להרפתקה שלך.\l"
	.string "כדי להשתמש במהלך כזה\l"
	.string "מחוץ לקרב, פתח את תפריט\l"
	.string "”פוקימון” ובחר בפוקימון\l"
	.string "שיודע אותו. גם פוקימון\l"
	.string "מעולף יכול להשתמש בו.$"

Help_Text_DefineEvolution::
	.string "יש פוקימונים מסוימים אשר\n"
	.string "עוברים שינוי גדול שנקרא\l"
	.string "התפתחות, כשהם מגיעים לרמה\l"
	.string "מסוימת. ההתפתחות משנה את\l"
	.string "צורתם, את שמם, ולפעמים גם\l"
	.string "את המהלכים שהם לומדים.\l"
	.string "חלק מהם מתפתחים גם בלי עליית רמה.$"

Help_Text_DefineStatusProblem::
	.string "בעיות סטטוס כוללות:\n"
	.string "שינה: אי אפשר לבצע מהלך.\l"
	.string "רעל: אובדן נ”ח מתמשך.\l"
	.string "שיתוק: עלול למנוע מהלכים.\l"
	.string "כוויה: נ”ח והתקפה יורדים.\l"
	.string "קרח: אי אפשר לבצע מהלך.\l"
	.string "אפשר לרפא אותן בעזרת פריטים.$"

Help_Text_DefinePokemon::
	.string "פוקימון הוא השם של יצורים\n"
	.string "מופלאים שחיים בכל פינה\l"
	.string "בעולם הזה.\l"
	.string "אנשים מגדלים אותם כחיות\l"
	.string "מחמד, משתמשים בהם לקרבות ועוד.$"

Help_Text_DefineIDNo2::
	.string "המספר המזהה הוא מספר מיוחד\n"
	.string "שניתן לך כמאמן.\l"
	.string "יחד עם שם המאמן המקורי,\l"
	.string "המספר המזהה מאפשר לזהות\l"
	.string "את המאמן במדויק.\l"
	.string "המספר המזהה לא משתנה גם\l"
	.string "אם הפוקימון מוחלף.$"

Help_Text_DefineMoney2::
	.string "בכל פעם שאתה מנצח מאמן\n"
	.string "בקרב, אתה מקבל פרס כספי.\l"
	.string "חסוך את הכסף כדי ליהנות\l"
	.string "מקניות בחנויות פוקימון!$"

Help_Text_DefineBadges2::
	.string "כאן מוצג מספר התגים של\n"
	.string "ליגת הפוקימון שזכית בהם.\l"
	.string "השג תגים בניצחון על מנהיגי\l"
	.string "מכונים בערים ובעיירות.$"

Help_Text_TheHelpSystem::
	.string "מערכת העזרה$"

Help_Text_TheGame::
	.string "המשחק$"

Help_Text_WirelessAdapter::
	.string "מתאם אלחוטי$"

Help_Text_GameFundamentals1::
	.string "יסודות המשחק 1$"

Help_Text_GameFundamentals2::
	.string "יסודות המשחק 2$"

Help_Text_GameFundamentals3::
	.string "יסודות המשחק 3$"

Help_Text_WhatArePokemon::
	.string "מה הם פוקימונים?$"

Help_Text_DescTheHelpSystem::
	.string "הודעות העזרה משתנות לפי\n"
	.string "מידת ההתקדמות שלך במשחק.\l"
	.string "הן נועדו לעזור לך\l"
	.string "בדיוק כשצריך. אם יש\l"
	.string "משהו שאינו ברור לך,\l"
	.string "פנה אל מערכת העזרה!$"

Help_Text_DescTheGame::
	.string "אתה הדמות הראשית,\n"
	.string "וחוקר את עולם הפוקימונים!\l"
	.string "על ידי שיחה עם אנשים\l"
	.string "ופתרון חידות, דרכים חדשות\l"
	.string "נפתחות לך. שאף למטרה יחד\l"
	.string "עם הפוקימונים הנהדרים שלך!$"

Help_Text_DescWirelessAdapter::
	.string "המשחק הזה מתקשר בחיבור\n"
	.string "אלחוטי עם המתאם האלחוטי.\p"
	.string "שחק אלחוטית בכל מקום,\n"
	.string "בכל זמן ועם כולם!\p"
	.string "כדאי לשחק כשהמתאם\n"
	.string "האלחוטי תמיד מחובר!$"

Help_Text_DescGameFundamentals1::
	.string "בקר בכל עיר ועיירה, צעד\n"
	.string "בכל דרך, חקור כל מערה\l"
	.string "והתמודד עם כל אתגר בדרך\l"
	.string "להיות המאמן הגדול ביותר\l"
	.string "של הפוקימון!$"

Help_Text_DescGameFundamentals2::
	.string "בהרפתקה שלך תיתקל במכשולים\n"
	.string "רבים. אפשר להתגבר על כל\l"
	.string "מכשול על ידי פעולה כלשהי\l"
	.string "או פתרון חידות. יש מכשולים\l"
	.string "שמושפעים ממשהו שקורה\l"
	.string "הרחק משם.$"

Help_Text_DescGameFundamentals3::
	.string "חלק מהמכשולים בדרך שלך\n"
	.string "ייעלמו כשהפוקימונים שלך\l"
	.string "ילמדו מהלכים מסוימים.$"

Help_Text_DescWhatArePokemon::
	.string "פוקימונים הם יצורי פלא\n"
	.string "עטופי מסתורין. אפשר לפגוש\l"
	.string "אותם בכל העולם…בעשב\l"
	.string "גבוה, במערות, בים ועוד.\l"
	.string "נראה שהם מתרגלים לציית\l"
	.string "למאמנים שתפסו אותם.$"

Help_Text_UsingTypeMatchupList::
	.string "שימוש ברשימת התאמת סוגים$"

Help_Text_OwnMoveDark::
	.string "סוג המהלך שלי: אפל$"

Help_Text_OwnPokemonDark::
	.string "סוג הפוקימון שלי: אפל$"

Help_Text_OwnMoveRock::
	.string "סוג המהלך שלי: סלע$"

Help_Text_OwnPokemonRock::
	.string "סוג הפוקימון שלי: סלע$"

Help_Text_OwnMovePsychic::
	.string "סוג המהלך שלי: פסיכי$"

Help_Text_OwnPokemonPsychic::
	.string "סוג הפוקימון שלי: פסיכי$"

Help_Text_OwnMoveFighting::
	.string "סוג המהלך שלי: קרב$"

Help_Text_OwnPokemonFighting::
	.string "סוג הפוקימון שלי: קרב$"

Help_Text_OwnMoveGrass::
	.string "סוג המהלך שלי: עשב$"

Help_Text_OwnPokemonGrass::
	.string "סוג הפוקימון שלי: עשב$"

Help_Text_OwnMoveGhost::
	.string "סוג המהלך שלי: רוח$"

Help_Text_OwnPokemonGhost::
	.string "סוג הפוקימון שלי: רוח$"

Help_Text_OwnMoveIce::
	.string "סוג המהלך שלי: קרח$"

Help_Text_OwnPokemonIce::
	.string "סוג הפוקימון שלי: קרח$"

Help_Text_OwnMoveGround::
	.string "סוג המהלך שלי: אדמה$"

Help_Text_OwnPokemonGround::
	.string "סוג הפוקימון שלי: אדמה$"

Help_Text_OwnMoveElectric::
	.string "סוג המהלך שלי: חשמל$"

Help_Text_OwnPokemonElectric::
	.string "סוג הפוקימון שלי: חשמל$"

Help_Text_OwnMovePoison::
	.string "סוג המהלך שלי: רעל$"

Help_Text_OwnPokemonPoison::
	.string "סוג הפוקימון שלי: רעל$"

Help_Text_OwnMoveDragon::
	.string "סוג המהלך שלי: דרקון$"

Help_Text_OwnPokemonDragon::
	.string "סוג הפוקימון שלי: דרקון$"

Help_Text_OwnMoveNormal::
	.string "סוג המהלך שלי: רגיל$"

Help_Text_OwnPokemonNormal::
	.string "סוג הפוקימון שלי: רגיל$"

Help_Text_OwnMoveSteel::
	.string "סוג המהלך שלי: פלדה$"

Help_Text_OwnPokemonSteel::
	.string "סוג הפוקימון שלי: פלדה$"

Help_Text_OwnMoveFlying::
	.string "סוג המהלך שלי: תעופה$"

Help_Text_OwnPokemonFlying::
	.string "סוג הפוקימון שלי: תעופה$"

Help_Text_OwnMoveFire::
	.string "סוג המהלך שלי: אש$"

Help_Text_OwnPokemonFire::
	.string "סוג הפוקימון שלי: אש$"

Help_Text_OwnMoveWater::
	.string "סוג המהלך שלי: מים$"

Help_Text_OwnPokemonWater::
	.string "סוג הפוקימון שלי: מים$"

Help_Text_OwnMoveBug::
	.string "סוג המהלך שלי: חרק$"

Help_Text_OwnPokemonBug::
	.string "סוג הפוקימון שלי: חרק$"

Help_Text_HowToUseTypeMatchupList::
	.string "ההתאמה בין סוג המהלך\n"
	.string "לסוג הפוקימון היריב\l"
	.string "קובעת את אפקטיביות המהלך:\l"
	.string "{CIRCLE_DOT}: סופר אפקטיבי!\l"
	.string "{TRIANGLE}: לא מאוד אפקטיבי\l"
	.string "{BIG_MULT_X}: לא אפקטיבי בכלל\l"
	.string "בשאר ההתאמות אין שינוי.$"

Help_Text_TypeMatchupOwnMoveDark::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: פסיכי, רוח\p"
	.string "   {TRIANGLE}: קרב, אפל, פלדה$"

Help_Text_TypeMatchupOwnPokemonDark::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: קרב, חרק\p"
	.string "   {TRIANGLE}: רוח, אפל\p"
	.string "   {BIG_MULT_X}: פסיכי$"

Help_Text_TypeMatchupOwnMoveRock::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: אש, קרח, תעופה, חרק\p"
	.string "   {TRIANGLE}: קרב, אדמה, פלדה$"

Help_Text_TypeMatchupOwnPokemonRock::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: מים, עשב, קרב,\n"
	.string "       אדמה, פלדה\p"
	.string "   {TRIANGLE}: רגיל, אש, רעל, תעופה$"

Help_Text_TypeMatchupOwnMovePsychic::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: קרב, רעל\p"
	.string "   {TRIANGLE}: פסיכי, פלדה\p"
	.string "   {BIG_MULT_X}: אפל$"

Help_Text_TypeMatchupOwnPokemonPsychic::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: חרק, רוח, אפל\p"
	.string "   {TRIANGLE}: קרב, פסיכי$"

Help_Text_TypeMatchupOwnMoveFighting::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: רגיל, קרח, סלע, אפל, פלדה\p"
	.string "   {TRIANGLE}: רעל, תעופה, פסיכי, חרק\p"
	.string "   {BIG_MULT_X}: רוח$"

Help_Text_TypeMatchupOwnPokemonFighting::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: תעופה, פסיכי\p"
	.string "   {TRIANGLE}: חרק, סלע, אפל$"

Help_Text_TypeMatchupOwnMoveGrass::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: מים, אדמה, סלע\p"
	.string "   {TRIANGLE}: אש, עשב, רעל, תעופה,\n"
	.string "       חרק, דרקון, פלדה$"

Help_Text_TypeMatchupOwnPokemonGrass::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: אש, קרח, רעל, תעופה, חרק\p"
	.string "   {TRIANGLE}: מים, חשמל, עשב, אדמה$"

Help_Text_TypeMatchupOwnMoveGhost::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: פסיכי, רוח\p"
	.string "   {TRIANGLE}: אפל, פלדה\p"
	.string "   {BIG_MULT_X}: רגיל$"

Help_Text_TypeMatchupOwnPokemonGhost::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: רוח, אפל\p"
	.string "   {TRIANGLE}: רעל, חרק\p"
	.string "   {BIG_MULT_X}: רגיל, קרב$"

Help_Text_TypeMatchupOwnMoveIce::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: עשב, אדמה, תעופה, דרקון\p"
	.string "   {TRIANGLE}: אש, מים, קרח, פלדה$"

Help_Text_TypeMatchupOwnPokemonIce::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: אש, קרב, סלע, פלדה\p"
	.string "   {TRIANGLE}: קרח$"

Help_Text_TypeMatchupOwnMoveGround::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: אש, חשמל, רעל, סלע,\n"
	.string "       פלדה\p"
	.string "   {TRIANGLE}: עשב, חרק\n"
	.string "   {BIG_MULT_X}: תעופה$"

Help_Text_TypeMatchupOwnPokemonGround::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: מים, עשב, קרח\p"
	.string "   {TRIANGLE}: רעל, סלע\p"
	.string "   {BIG_MULT_X}: חשמל$"

Help_Text_TypeMatchupOwnMoveElectric::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: מים, תעופה\p"
	.string "   {TRIANGLE}: חשמל, עשב, דרקון\p"
	.string "   {BIG_MULT_X}: אדמה$"

Help_Text_TypeMatchupOwnPokemonElectric::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: אדמה\p"
	.string "   {TRIANGLE}: חשמל, תעופה, פלדה$"

Help_Text_TypeMatchupOwnMovePoison::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: עשב\p"
	.string "   {TRIANGLE}: רעל, אדמה, סלע, רוח\p"
	.string "   {BIG_MULT_X}: פלדה$"

Help_Text_TypeMatchupOwnPokemonPoison::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: אדמה, פסיכי\p"
	.string "   {TRIANGLE}: עשב, קרב, רעל, חרק$"

Help_Text_TypeMatchupOwnMoveDragon::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: דרקון\p"
	.string "   {TRIANGLE}: פלדה$"

Help_Text_TypeMatchupOwnPokemonDragon::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: קרח, דרקון\p"
	.string "   {TRIANGLE}: אש, מים, חשמל, עשב$"

Help_Text_TypeMatchupOwnMoveNormal::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {TRIANGLE}: סלע, פלדה\p"
	.string "   {BIG_MULT_X}: רוח$"

Help_Text_TypeMatchupOwnPokemonNormal::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: קרב\p"
	.string "   {BIG_MULT_X}: רוח$"

Help_Text_TypeMatchupOwnMoveSteel::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: קרח, סלע\p"
	.string "   {TRIANGLE}: אש, מים, חשמל, פלדה$"

Help_Text_TypeMatchupOwnPokemonSteel::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: אש, קרב, אדמה\n"
	.string "   {TRIANGLE}: רגיל, עשב, קרח, תעופה,\l"
	.string "       פסיכי, חרק, סלע, רוח,\l"
	.string "       דרקון, אפל, פלדה\l"
	.string "   {BIG_MULT_X}: רעל$"

Help_Text_TypeMatchupOwnMoveFlying::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: עשב, קרב, חרק\p"
	.string "   {TRIANGLE}: חשמל, סלע, פלדה$"

Help_Text_TypeMatchupOwnPokemonFlying::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: חשמל, קרח, סלע\p"
	.string "   {TRIANGLE}: עשב, קרב, חרק\p"
	.string "   {BIG_MULT_X}: אדמה$"

Help_Text_TypeMatchupOwnMoveFire::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: עשב, קרח, חרק, פלדה\p"
	.string "   {TRIANGLE}: אש, מים, סלע, דרקון$"

Help_Text_TypeMatchupOwnPokemonFire::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: מים, אדמה, סלע\p"
	.string "   {TRIANGLE}: אש, עשב, קרח, חרק, פלדה$"

Help_Text_TypeMatchupOwnMoveWater::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: אש, אדמה, סלע\p"
	.string "   {TRIANGLE}: מים, עשב, דרקון$"

Help_Text_TypeMatchupOwnPokemonWater::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: חשמל, עשב\p"
	.string "   {TRIANGLE}: אש, מים, קרח, פלדה$"

Help_Text_TypeMatchupOwnMoveBug::
	.string "השפעה על פוקימון היריב:\p"
	.string "   {CIRCLE_DOT}: עשב, פסיכי, אפל\p"
	.string "   {TRIANGLE}: אש, קרב, רעל,\n"
	.string "       תעופה, רוח, פלדה$"

Help_Text_TypeMatchupOwnPokemonBug::
	.string "השפעת מהלך היריב עליך:\p"
	.string "   {CIRCLE_DOT}: אש, תעופה, סלע\p"
	.string "   {TRIANGLE}: עשב, קרב, אדמה$"

