Trade_Text_LookingForMonWannaTradeForMon::
	.string "אני מחפש את הפוקימון\n"
	.string "{STR_VAR_1}!\p"
	.string "רוצה להחליף אחד תמורת\n"
	.string "{STR_VAR_2} שלי?$"

Trade_Text_AwwOhWell::
	.string "אווו!\n"
	.string "טוב, נו...$"

Trade_Text_WhatThatsNoMon::
	.string "מה?\n"
	.string "זה לא {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "היי, תודה!$"

Trade_Text_IsntMyOldMonGreat::
	.string "ה{STR_VAR_2} הישן שלי נהדר,\n"
	.string "נכון?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "שלום! במקרה יש לך\n"
	.string "{STR_VAR_1}?\p"
	.string "תסכים להחליף אותו תמורת\n"
	.string "{STR_VAR_2} שלי?$"

Trade_Text_WellIfYouDontWantTo::
	.string "טוב, אם אתה לא רוצה...$"

Trade_Text_ThisIsntMon::
	.string "הממ?\n"
	.string "זה לא {STR_VAR_1}.\p"
	.string "תחשוב עליי אם תמצא אחד.$"

Trade_Text_Thanks::
	.string "תודה!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "ה{STR_VAR_2} שהחלפתי איתך,\n"
	.string "הוא התחזק?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "היי!\n"
	.string "יש לך {STR_VAR_1}?\p"
	.string "רוצה להחליף אותו תמורת\n"
	.string "{STR_VAR_2} שלי?$"

Trade_Text_ThatsTooBad::
	.string "איזה באסה.$"

Trade_Text_ThisIsNoMon::
	.string "...זה לא {STR_VAR_1}.\p"
	.string "אם תמצא אחד, תחליף איתי.$"

Trade_Text_ThanksYoureAPal::
	.string "תודה, אתה חבר אמיתי!$"

Trade_Text_HowIsMyOldMon::
	.string "איך ה{STR_VAR_2} הישן שלי?\n"
	.string "ה{STR_VAR_1} שלי מסתדר נהדר!$"
