gOtherText_NewName::
    .string "שם חדש$"

gNameChoice_Green::
    .string "אופיר$"

gNameChoice_Red::
    .string "אביה$"

gNameChoice_Leaf::
    .string "רולי$"

gNameChoice_Fire::
    .string "נועה$"

gNameChoice_Gary::
    .string "גארי$"

gNameChoice_Kaz::
    .string "קאז$"

gNameChoice_Toru::
    .string "טורו$"

gNameChoice_Ash::
    .string "אש$"

gNameChoice_Kene::
    .string "קאנה$"

gNameChoice_Geki::
    .string "גקי$"

gNameChoice_Jak::
    .string "ג'ק$"

gNameChoice_Janne::
    .string "ג'אן$"

gNameChoice_Jonn::
    .string "ג'וני$"

gNameChoice_Kamon::
    .string "קאמון$"

gNameChoice_Karl::
    .string "קארל$"

gNameChoice_Taylor::
    .string "טיילור$"

gNameChoice_Oscar::
    .string "אוסקר$"

gNameChoice_Hiro::
    .string "הירו$"

gNameChoice_Max::
    .string "מקס$"

gNameChoice_Jon::
    .string "ג'ון$"

gNameChoice_Ralph::
    .string "ראלף$"

gNameChoice_Kay::
    .string "קיי$"

gNameChoice_Tosh::
    .string "טוש$"

gNameChoice_Roak::
    .string "רואק$"

gNameChoice_Omi::
    .string "אומי$"

gNameChoice_Jodi::
    .string "ג'ודי$"

gNameChoice_Amanda::
    .string "אמנדה$"

gNameChoice_Hillary::
    .string "הילרי$"

gNameChoice_Makey::
    .string "מייקי$"

gNameChoice_Michi::
    .string "מיצ'י$"

gNameChoice_Paula::
    .string "פאולה$"

gNameChoice_June::
    .string "ג'ון$"

gNameChoice_Cassie::
    .string "קאסי$"

gNameChoice_Rey::
    .string "ריי$"

gNameChoice_Seda::
    .string "סדה$"

gNameChoice_Kiko::
    .string "קיקו$"

gNameChoice_Mina::
    .string "מינה$"

gNameChoice_Norie::
    .string "נורי$"

gNameChoice_Sai::
    .string "סאי$"

gNameChoice_Momo::
    .string "מומו$"

gNameChoice_Suzi::
    .string "סוזי$"

gControlsGuide_Text_Intro::
    .string "הסבר על הכפתורים השונים\n"
    .string "לפי סדר החשיבות שלהם.$"

gControlsGuide_Text_DPad::
    .string "מזיז את הדמות הראשית.\n"
    .string "גם משמש כדי לבחור בין\n"
    .string "אפשרויות שונות.$"

gControlsGuide_Text_AButton::
    .string "משמש כדי לאשר בחירה, לבדוק\n"
    .string "דברים, לשוחח, ולגלול טקסט.$"

gControlsGuide_Text_BButton::
    .string "משמש כדי לצאת, לבטל בחירה\n"
    .string "ולבטל מצב.$"

gControlsGuide_Text_StartButton::
    .string "לחץ על כפתור זה כדי לפתוח\n"
    .string "את התפריט.$"

gControlsGuide_Text_SelectButton::
    .string "משמש כדי להזיז חפצים וכדי\n"
    .string "להשתמש בחפצים שמורים.$"

gControlsGuide_Text_LRButtons::
    .string "אם אתה צריך עזרה תוך כדי\n"
    .string "המשחק, תלחץ על כפתורים אלו.$"

gOakSpeech_Text_AskPlayerGender::
    .string "עכשיו תגיד לי. אתה בן?\n"
    .string "או שאת בת?$"

gPikachuIntro_Text_Page1::
    .string "בעולם שאתה הולך להיכנס אליו\n"
    .string "אתה תצא להרפתקה גדולה,\n"
    .string "ואתה הגיבור המרכזי.\n"
    .string "\n"
    .string "תדבר עם אנשים ותבדוק דברים\n"
    .string "בכל מקום שאליו תלך, אם זה בערים,\n"
    .string "דרכים או מערות. תאסוף מידע ורמזים\n"
    .string "מכל מקור אפשרי.$"

gPikachuIntro_Text_Page2::
    .string "דרכים חדשות יפתחו בפניך על ידי\n"
    .string "עזרה לאנשים, התגברות על אתגרים,\n"
    .string "ופתירת תעלומות.\n"
    .string "\n"
    .string "לפעמים אתה תהיה מאותגר על ידי\n"
    .string "אחרים, ותותקף על ידי פוקימונים.\n"
    .string "תהיה אמיץ ותמשיך להתקדם קדימה.$"

gPikachuIntro_Text_Page3::
    .string "אנחנו מקווים שתוך כדי ההרפתקה שלך\n"
    .string "תתחבר לכל מיני אנשים ותרגיש את\n"
    .string "עצמך משתפר. זו המטרה הכי גדולה שלנו..\n"
    .string "\n"
    .string "תלחץ על כפתור A\n"
    .string "ובוא נתחיל בהרפתקה!!$"

gOakSpeech_Text_WelcomeToTheWorld::
    .string "שלום!\n"
    .string "אני שמח לפגוש אותך!\p"
    .string "ברוך הבא לעולם הפוקימונים!\p"
    .string "שמי הוא פרופסור אוק.\p"
    .string "אתה גם יכול לקרוא לי\n"
    .string "פרופסור הפוקימונים.\p$"

gOakSpeech_Text_ThisWorld::
    .string "$"

gOakSpeech_Text_IsInhabitedFarAndWide::
    .string "בכל רחבי העולם הזה\n"
    .string "יש פוקימונים.\p$"

gOakSpeech_Text_IStudyPokemon::
    .string "חלק מהאנשים מתייחסים\n"
	.string "לפוקימונים כחיות מחמד.\n"
    .string "יש כאלה שאוהבים להילחם בעזרתם.\p"
    .string "ואני...\p"
    .string "העבודה שלי היא ללמוד על פוקימונים.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
    .string "אבל קודם, ספר לי\n"
    .string "קצת על עצמך.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
    .string "בוא נתחיל עם השם.\n"
    .string "מה השם שלך?\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
    .string "נכון..\n"
    .string "שמך הוא {PLAYER}.$"

gOakSpeech_Text_WhatWasHisName::
    .string "זה הנכד שלי.\p"
    .string "הוא ואתה יריבים\n"
    .string "מאז שהייתם תינוקות.\p"
    .string "תוכל להזכיר לי את השם שלו?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
    .string "השם של היריב שלך, מה הוא היה?$"

gOakSpeech_Text_ConfirmRivalName::
    .string "אמ.. קראו לו {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
    .string "נכון! עכשיו נזכרתי!\n"
    .string "קוראים לו {RIVAL}!\p$"

gOakSpeech_Text_LetsGo::
    .string "{PLAYER}!\p"
    .string "ההרפתקה האישית שלך\n"
    .string "עומדת להתחיל!\p"
    .string "עולם מלא בחלומות והרפתקאות\n"
    .string "עם פוקימונים מחכה!\n"
	.string "קדימה בוא נצא לדרך!$"
