Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "פוקי דוד: הפוקימון המהיר יותר\n"
	.string "מבין השניים תוקף ראשון.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "נראה שהרטטה שלי היה מהיר\n"
	.string "יותר מהפידג'י.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "הפוקימונים תוקפים בתורות\n"
	.string "ומורידים נקודות חיים אחד לשני.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "הרטטה שלי הוריד את נקודות החיים\n"
	.string "של היריב לאפס, אז הוא ניצח!\p"
	.string "הפוקימונים שהשתתפו בקרב\n"
	.string "מקבלים נקודות נסיון.\p"
	.string "כשפוקימון צובר מספיק נקודות\n"
	.string "נסיון, הוא עולה רמה.\p"
	.string "עליית רמה הופכת את הפוקימון שלך\n"
	.string "לחזק יותר מקודם.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "פוקי דוד: אוי לא...\n"
	.string "הרטטה שלי הורעל...\p"
	.string "אם פוקימון מורעל, הוא מאבד\n"
	.string "נקודות חיים בהדרגה.$"

Pokedude_Text_HealStatusRightAway::
	.string "אם פוקימון מפתח בעיית סטטוס,\n"
	.string "רפא אותו מיד.$"

Pokedude_Text_UsingItemTakesTurn::
	.string "שימוש בפריט על פוקימון לוקח\n"
	.string "תור שלם, בכל זאת.\p"
	.string "עכשיו, זה התור של היריב!$"

Pokedude_Text_YayWeManagedToWin::
	.string "יש!\n"
	.string "הצלחנו לנצח!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "פוקי דוד: המהלך בועות הוא\n"
	.string "התקפה מסוג מים.\p"
	.string "האודיש שנתקף הוא פוקימון\n"
	.string "מסוג דשא/רעל.\p"
	.string "התקפת המים נספגת על ידי\n"
	.string "הפוקימון מסוג דשא...\p"
	.string "כתוצאה מכך, המהלך לא יעיל\n"
	.string "במיוחד, וגורם רק חצי מהנזק הרגיל.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "אוי, זה לא טוב!\p"
	.string "מהלך הספיגה שראית עכשיו\n"
	.string "הוא מהלך מסוג דשא.\p"
	.string "פוליוואג הוא פוקימון מסוג מים.\p"
	.string "לכן, ספיגה הופך ליעיל במיוחד,\n"
	.string "מכפיל את הנזק.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "זה לא יהיה קל לנצח\n"
	.string "עם התאמה כזאת...\p"
	.string "בוא ננסה להחליף פוקימונים!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "החלפת פוקימונים פנימה והחוצה\n"
	.string "לוקחת תור שלם.\p"
	.string "עכשיו, זה התור של היריב.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "בטרפרי הוא פוקימון מסוג\n"
	.string "חרק/מעופף.\p"
	.string "נגד פוקימון זה, התקפה\n"
	.string "מסוג דשא...\p"
	.string "...גורמת רק חצי מהנזק הרגיל\n"
	.string "על פוקימון מסוג חרק...\p"
	.string "...וגם גורמת רק חצי מהנזק\n"
	.string "על פוקימון מסוג מעופף.\p"
	.string "לכן, בטרפרי, בתור פוקימון\n"
	.string "חרק/מעופף, מקבל רק רבע מהנזק\l"
	.string "הרגיל.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "אודיש הוא פוקימון מסוג\n"
	.string "דשא/רעל.\p"
	.string "התקפה מסוג מעופף או פסיכי\n"
	.string "יעילה במיוחד נגדו.\p"
	.string "אחד מסוגי ההתקפות האלה יגרום\n"
	.string "כפול מהנזק הרגיל.\p"
	.string "טוב, בוא נתחיל!$"

Pokedude_Text_YeahWeWon::
	.string "כן!\n"
	.string "ניצחנו!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "פוקי דוד: כשאתה מנסה לתפוס\n"
	.string "פוקימון, אל תזרוק פוקכדורים\l"
	.string "מיד.\p"
	.string "קודם, אתה צריך להחליש אותו\n"
	.string "על ידי הורדת נקודות החיים שלו.$"

Pokedude_Text_BestIfTargetStatused::
	.string "אוקיי, זה אמור להיות מספיק טוב.\p"
	.string "אבל, אם זה אפשרי, הכי טוב\n"
	.string "אם למטרה יש בעיית סטטוס.\p"
	.string "למשל, יהיה קל יותר לתפוס\n"
	.string "אם הוא ישן או משותק.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "זה יהפוך את הפוקימון להרבה\n"
	.string "יותר קל לתפיסה!\p"
	.string "אה, כן. אם אתה משתק פוקימון,\n"
	.string "אתה לא יכול להרדים אותו בנוסף\l"
	.string "לשיתוק.\p"
	.string "במילים אחרות, אתה לא יכול לשים\n"
	.string "כפל בעיות סטטוס, בסדר?$"

Pokedude_Text_LetMeThrowBall::
	.string "אוקיי!\n"
	.string "תן לי לזרוק את הפוקכדור שלי!$"

Pokedude_Text_PickBestKindOfBall::
	.string "לפני שאתה זורק פוקכדור,\n"
	.string "שקול את המצב ואת הסוג\l"
	.string "של הפוקימון, ובחר את סוג\l"
	.string "הכדור שיעבוד הכי טוב.$"
