PokedexRating_Text_HowIsPokedexComingAlong::
	.string "אוק: טוב לראות אותך!\n"
	.string "איך מתקדם הפוקדקס שלך?\p"
	.string "הנה, תן לי להסתכל.$"

PokedexRating_Text_SeenXOwnedY::
	.string "ההתקדמות שעשית\n"
	.string "בפוקדקס שלך היא:\p"
	.string "{STR_VAR_1} פוקימונים נראו ו-\n"
	.string "{STR_VAR_2} פוקימונים בבעלותך.\p"
	.string "{FONT_NORMAL}הדירוג של פרופ' אוק:$"

PokedexRating_Text_LessThan10::
	.string "יש לך עוד הרבה מה לעשות.\p"
	.string "היכנס לכל שטח דשא שאתה\n"
	.string "רואה וחפש פוקימונים!$"

PokedexRating_Text_LessThan20::
	.string "נראה שאתה בכיוון הנכון!\p"
	.string "נתתי לאחד מהעוזרים שלי את\n"
	.string "המכונה הנסתרת הבזק. וודא שאתה מקבל אותה!$"

PokedexRating_Text_LessThan30::
	.string "הפוקדקס שלך עדיין יכול להיות\n"
	.string "מלא יותר!\p"
	.string "נסה לתפוס מינים נוספים של\n"
	.string "פוקימונים!$"

PokedexRating_Text_LessThan40::
	.string "טוב, ניכר שאתה משתדל מאוד!\p"
	.string "נתתי לאחד מהעוזרים שלי\n"
	.string "גלאי פריטים. וודא שאתה אוסף אותו!$"

PokedexRating_Text_LessThan50::
	.string "הפוקדקס שלך מתקדם די\n"
	.string "טוב!\p"
	.string "נתתי לאחד מהעוזרים שלי\n"
	.string "מטבע קמע. וודא שאתה מקבל אותו!$"

PokedexRating_Text_LessThan60::
	.string "אה, סוף סוף עברת את ה-05\n"
	.string "מינים!\p"
	.string "נתתי לאחד מהעוזרים שלי\n"
	.string "חולק נסיון. וודא שאתה מקבל אותו!$"

PokedexRating_Text_LessThan70::
	.string "הוהו! זה הופך לפוקדקס\n"
	.string "די מכובד!$"

PokedexRating_Text_LessThan80::
	.string "טוב מאוד!\p"
	.string "אני חושב שתאסוף עוד יותר\n"
	.string "פוקימונים אם תלך לדוג!$"

PokedexRating_Text_LessThan90::
	.string "נפלא! תן לי לנחש... אתה\n"
	.string "אוהב לאסוף דברים, נכון?$"

PokedexRating_Text_LessThan100::
	.string "אני מתרשם!\n"
	.string "זה בטח היה קשה לעשות!$"

PokedexRating_Text_LessThan110::
	.string "סוף סוף הגעת ל-001 מינים!\n"
	.string "לא מאמין כמה טוב אתה!$"

PokedexRating_Text_LessThan120::
	.string "יש לך אפילו את הצורות המפותחות\n"
	.string "של פוקימונים! מדהים!$"

PokedexRating_Text_LessThan130::
	.string "מצוין! סחור עם חברים כדי\n"
	.string "להשיג עוד!$"

PokedexRating_Text_LessThan140::
	.string "יוצא מן הכלל!\n"
	.string "הפכת למקצוען אמיתי בזה!$"

PokedexRating_Text_LessThan150::
	.string "אין לי מה להגיד יותר!\n"
	.string "אתה פרופסור הפוקימונים עכשיו!$"

PokedexRating_Text_Complete::
	.string "הפוקדקס שלך הושלם לחלוטין!\n"
	.string "מזל טוב!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "והפוקדקס הלאומי שלך הוא:\p"
	.string "{STR_VAR_1} פוקימונים נראו ו-\n"
	.string "{STR_VAR_2} פוקימונים בבעלותך.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "אני מצפה לראות\n"
	.string "אותך ממלא את הפוקדקס הלאומי!$"

PokedexRating_Text_YouveCompletedDex::
	.string "סוף סוף...\p"
	.string "סוף סוף השלמת את\n"
	.string "הפוקדקס!\p"
	.string "זה מפואר!\n"
	.string "באמת, זה הישג מדהים!$"

PokedexRating_Text_Wroooaaarrr::
	.string "ווורררררוווווואאאאאררררר!$"

PokedexRating_Text_HaHa::
	.string "הא הא...$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "תודה, {PLAYER}!\n"
	.string "תודה רבה, באמת!\l"
	.string "הפכת את החלום שלי למציאות!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "אוק: אה, ברוך הבא!\p"
	.string "ספר לי, איך מתקדם הפוקדקס\n"
	.string "שלך?\p"
	.string "וואהאהא!\p"
	.string "למעשה, אני יודע איך הוא, אבל אני\n"
	.string "אוהב לראות אותו בכל זאת!\p"
	.string "בוא נראה...$"
