@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "הממ…\n"
	.string "וואלה…$"

PalletTown_Text_OhLookLook::
	.string "היי!\n"
	.string "תראה, תראה!$"

PalletTown_Text_ReadItReadIt::
	.string "תקרא, תקרא!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "טיפים למאמנים\p"
	.string "לחץ על כפתור ההתחל כדי\n"
	.string "לפתוח את התפריט!$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "שלטים הם שימושיים נכון?$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "תראה, תראה!\p"
	.string "העתקתי את מה שכתוב על אחד\n"
	.string "מהשלטים של הטיפים למאמנים!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "טיפים למאמנים\p"
	.string "לחץ על כפתור ההתחל כדי\n"
	.string "לפתוח את התפריט!$"
