CeladonCity_GameCorner_Text_TryPokemonPrinter::
	.string "זוהי מדפסת פוקימון!\p"
	.string "היא יכולה להדפיס תמונה של הפוקימון\n"
	.string "שלך על גב כרטיס המאמן שלך.\p"
	.string "זה עולה רק ¥05.\n"
	.string "תרצה לנסות?$"

CeladonCity_GameCorner_Text_DontHaveEnoughMoney::
	.string "אין לך מספיק כסף.$"

CeladonCity_GameCorner_Text_ChoosePrintType::
	.string "בחר את סוג ההדפסה בבקשה.$"

CeladonCity_GameCorner_Text_BigSmileForPhoto::
	.string "חיוך גדול לתמונה, בבקשה!\n"
	.string "שלוש... שתיים... אחת...\p"
	.string "הבזק!$"

CeladonCity_GameCorner_Text_PrintIsReadyCheckTrainerCard::
	.string "ההדפסה של הפוקימון שלך מוכנה!\n"
	.string "בדוק את כרטיס המאמן שלך.$"

FourIsland_House2_Text_WishICouldShowOffStickers::
	.string "חיחי...\n"
	.string "אספתי המון מדבקות.\l"
	.string "הלוואי שיכולתי להראות אותן...$"

FourIsland_House2_Text_GiveYouStickerIfYouBrag::
	.string "הו, מצוין!\n"
	.string "הגעת למקום הנכון!\p"
	.string "תראה, תראה! רואה? רואה?\n"
	.string "אלה המדבקות שלי!\l"
	.string "תראה כמה יש לי!\p"
	.string "אני בטוחה שאתה רוצה כמה.\n"
	.string "אני בטוחה שכן!\p"
	.string "אתן לך מדבקה אם תוכל לספר\n"
	.string "לי משהו מדהים על\l"
	.string "עצמך.\p"
	.string "במה תתפאר?$"

FourIsland_House2_Text_BragAboutSomethingForMe::
	.string "תתפאר במשהו בשבילי.\n"
	.string "אתן לך מדבקה.$"

FourIsland_House2_Text_BragAboutWhatToday::
	.string "הו, היי!\n"
	.string "הנה מגיע המתרברב.\p"
	.string "במה אתה הולך להתפאר\n"
	.string "היום?$"

FourIsland_House2_Text_WowHoFLowest::
	.string "וואו, נכנסת\n"
	.string "להיכל התהילה.\p"
	.string "זה די טוב, כן!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowHoFLow::
	.string "וואו, נכנסת להיכל\n"
	.string "התהילה הרבה פעמים!\p"
	.string "זה מרשים, כן!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowHoFHigh::
	.string "וואו! נכנסת להיכל\n"
	.string "התהילה כל כך הרבה פעמים?\l"
	.string "זה ממש מדהים, כן!\p"
	.string "אתה שולט בליגת הפוקימון!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowHoFHighest::
	.string "לא יאומן! נכנסת להיכל\n"
	.string "התהילה כל כך הרבה פעמים?\p"
	.string "אתה יותר ממדהים, כן!\n"
	.string "זהו, אני חייבת לתת לך את זה.$"

FourIsland_House2_Text_HoFStickerApplied::
	.string "מדבקת היכל התהילה הודבקה\n"
	.string "על כרטיס המאמן.$"

FourIsland_House2_Text_ComeBackWithBetterStoryHoF::
	.string "הממ...\p"
	.string "תחזור עם סיפור טוב יותר בפעם\n"
	.string "הבאה, בסדר?$"

FourIsland_House2_Text_LivingLegendHoF::
	.string "אוי, לא, אי אפשר.\p"
	.string "אתה כבר כמעט אגדה חיה.\n"
	.string "לא נשארו לי מדבקות לתת.$"

FourIsland_House2_Text_WowEggsLowest::
	.string "וואו, יש ביצי פוקימון?\n"
	.string "לא ידעתי את זה!\p"
	.string "זה די טוב, כן!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowEggsLow::
	.string "בקעת כל כך הרבה ביצים?\n"
	.string "אתה באמת אוהב אותן!\p"
	.string "זה מרשים, כן!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowEggsHigh::
	.string "וואו! בקעת המון\n"
	.string "ביצים!\p"
	.string "אתה מכונת בקיעת ביצים!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowEggsHighest::
	.string "מ... בקעת כל כך הרבה ביצים?\p"
	.string "מה עומד מאחורי האהבה שלך לביצים?\n"
	.string "זה יותר ממדהים, כן!\p"
	.string "אתה פשוט מדהים מדי, אני אומרת לך.\n"
	.string "זהו, אני חייבת לתת לך את זה.$"

FourIsland_House2_Text_EggStickerApplied::
	.string "מדבקת הביצה הודבקה\n"
	.string "על כרטיס המאמן.$"

FourIsland_House2_Text_ComeBackWithBetterStoryEggs::
	.string "הממ...\p"
	.string "תחזור עם סיפור טוב יותר בפעם\n"
	.string "הבאה, בסדר?$"

FourIsland_House2_Text_LivingLegendEggs::
	.string "אוי, לא, אי אפשר.\p"
	.string "אתה כבר כמעט אגדה חיה.\n"
	.string "לא נשארו לי מדבקות לתת.$"

FourIsland_House2_Text_WowLinkWinsLowest::
	.string "וואו, היה לך הצלחה\n"
	.string "בקרבות קישור?\p"
	.string "אתה די חזק, כן!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowLinkWinsLow::
	.string "ניצחת את החברים שלך הרבה\n"
	.string "בקרבות קישור, הא?\p"
	.string "אתה מרשים בחוזקך, כן!\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowLinkWinsHigh::
	.string "וואו! ניצחת את החברים שלך\n"
	.string "מספר מפחיד של פעמים.\p"
	.string "איבדת חברים בגלל זה?\n"
	.string "אתן לך אחת מאלה.$"

FourIsland_House2_Text_WowLinkWinsHighest::
	.string "מ... וואו מטורף!\n"
	.string "ניצחת מספר פעמים שמטריף את הדעת!\p"
	.string "זה פשוט מדהים אותי לחשוב\n"
	.string "על כמה חזק אתה.\p"
	.string "אתה סיוט אמיתי!\n"
	.string "זהו, אני חייבת לתת לך את זה.$"

FourIsland_House2_Text_VictoryStickerApplied::
	.string "מדבקת הניצחון הודבקה\n"
	.string "על כרטיס המאמן.$"

FourIsland_House2_Text_ComeBackWithBetterStoryLinkWins::
	.string "הממ...\p"
	.string "תחזור עם סיפור טוב יותר בפעם\n"
	.string "הבאה, בסדר?$"

FourIsland_House2_Text_LivingLegendLinkWins::
	.string "אוי, לא, אי אפשר.\p"
	.string "אתה כבר כמעט אגדה חיה.\n"
	.string "לא נשארו לי מדבקות לתת.$"
