VSSeeker_Text_BatteryNotChargedNeedXSteps::
	.string "הסוללה לא טעונה מספיק.\p"
	.string "מספר הצעדים הנדרשים לטעינה\n"
	.string "מלאה של הסוללה: {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_NoTrainersWithinRange::
	.string "אין מאמנים בטווח שיכולים\n"
	.string "להילחם...\p"
	.string "גלאי הקרב כובה.{PAUSE_UNTIL_PRESS}$"

VSSeeker_Text_TrainersNotReady::
	.string "נראה שהמאמנים האחרים\n"
	.string "לא מוכנים לקרב.\p"
	.string "נחכה לפעם אחרת.{PAUSE_UNTIL_PRESS}$"

Route3_Text_ColtonRematchIntro::
	.string "היי!\n"
	.string "ראיתי אותך ביער וירידיאן!$"

Route3_Text_BenRematchIntro::
	.string "היי! אני אוהב מכנסיים קצרים!\n"
	.string "הם נוחים וקל ללבוש אותם!\p"
	.string "גם אתה צריך ללבוש מכנסיים קצרים!$"

Route3_Text_JaniceRematchIntro::
	.string "סליחה!\n"
	.string "אתה ממשיך להסתכל עליי, נכון?$"

Route3_Text_GregRematchIntro::
	.string "אתה מאמן, נכון?\n"
	.string "בוא נתחיל מיד!$"

Route3_Text_SallyRematchIntro::
	.string "המבט הזה שאתה נותן בי...\n"
	.string "הוא כל כך מסקרן!$"

Route3_Text_CalvinRematchIntro::
	.string "היי! מה לא בסדר איתך?\n"
	.string "אתה עדיין לא לובש מכנסיים קצרים!$"

Route3_Text_JamesRematchIntro::
	.string "אני אלחם בך עם הפוקימונים\n"
	.string "שהתחלתי לגדל.$"

Route3_Text_RobinRematchIntro::
	.string "איי!\n"
	.string "דחפת אותי?$"

Route4_Text_CrissyRematchIntro::
	.string "אני תמיד תופסת פוקימוני פטריות\n"
	.string "בהר ירח.$"

Route6_Text_RickyRematchIntro::
	.string "הו! אתה הילד הסקרן ההוא\n"
	.string "שהאזין לנו!$"

Route6_Text_NancyRematchIntro::
	.string "סליחה! לא אמרתי לך שזאת\n"
	.string "שיחה פרטית?\p"
	.string "אתה לא אמור להקשיב,\n"
	.string "חסר נימוס שכמוך!$"

Route6_Text_KeigoRematchIntro::
	.string "אני מנסה למצוא משהו טוב\n"
	.string "שהוא לא פוקימון חרק, אבל...$"

Route6_Text_JeffRematchIntro::
	.string "הא?\n"
	.string "אתה רוצה להתמודד איתי שוב?$"

Route6_Text_IsabelleRematchIntro::
	.string "אני?\n"
	.string "טוב, בסדר. אני אשחק הפעם.$"

Route6_Text_ElijahRematchIntro::
	.string "היי, מזמן לא ראינו!\n"
	.string "השתפרת?$"

Route8_Text_AidanRematchIntro::
	.string "אתה טוב בפוקימון, אבל איך\n"
	.string "הציון שלך בכימיה?$"

Route8_Text_StanRematchIntro::
	.string "בסדר!\n"
	.string "בוא נשחק עוד משחק!$"

Route8_Text_GlennRematchIntro::
	.string "צריך אסטרטגיה כדי לנצח\n"
	.string "בקרבות.\p"
	.string "אתה מיישם את העצה שלי?$"

Route8_Text_PaigeRematchIntro::
	.string "אספתי הרבה נידורן.\n"
	.string "אני לא רוצה שהם יתפתחו, אבל...$"

Route8_Text_LeslieRematchIntro::
	.string "בית הספר כיף, אבל אני עדיין חושבת\n"
	.string "שפוקימונים כיפיים גם.$"

Route8_Text_AndreaRematchIntro::
	.string "מיאו ופרסיאן כל כך חמודים,\n"
	.string "מיאו, מיאו, מיאו!$"

Route8_Text_MeganRematchIntro::
	.string "אולי אנחנו נראים מטופשים כשאנחנו\n"
	.string "עומדים ככה, אבל אני עדיין יכולה\l"
	.string "להילחם.$"

Route8_Text_RichRematchIntro::
	.string "אני משוטט, משחק ומשתולל!\n"
	.string "אני בסדרת ניצחונות!$"

Route8_Text_JuliaRematchIntro::
	.string "מה חמוד, עגול ופרוותי\n"
	.string "בפוקימונים?\p"
	.string "אתה כבר יודע, נכון?$"

Route8_Text_RicardoRematchIntro::
	.string "האופניים שלי עדיין מתעצבנים, אחי.$"

Route8_Text_JarenRematchIntro::
	.string "בסדר, ילד!\n"
	.string "אל תצפה לרחמים הפעם!$"

Route8_Text_EliRematchIntro::
	.string "אלי: כוח התאומים שלנו נהיה אפילו\n"
	.string "יותר טוב!$"

Route8_Text_AnneRematchIntro::
	.string "אן: כוח התאומים שלנו התחזק!$"

Route9_Text_AliciaRematchIntro::
	.string "להילחם שוב?\n"
	.string "הפעם, אתה שלי!$"

Route9_Text_ChrisRematchIntro::
	.string "לא שכחתי שהיית עם\n"
	.string "הפוקימונים היפים האלה.$"

Route9_Text_DrewRematchIntro::
	.string "אני עובר במנהרת הסלע כדי להגיע\n"
	.string "ללבנדר...\p"
	.string "אבל כולם עוצרים אותי\n"
	.string "בדרך...$"

Route9_Text_CaitlinRematchIntro::
	.string "אל תעז לזלזל בי היום!\n"
	.string "אנחנו משחקים ברצינות!$"

Route9_Text_JeremyRematchIntro::
	.string "בוואהאהא!\n"
	.string "מעולה! שוב השתעממתי!$"

Route9_Text_BriceRematchIntro::
	.string "האהאהא!\n"
	.string "קשוח קטן, כמו תמיד!$"

Route9_Text_BrentRematchIntro::
	.string "קמתי מוקדם כל יום כדי לאמן\n"
	.string "את הפוקימונים שלי מגלמים!$"

Route9_Text_AlanRematchIntro::
	.string "האהאהאהא!\n"
	.string "אני אנצח הפעם!$"

Route9_Text_ConnerRematchIntro::
	.string "קדימה נצחו, פוקימוני החרק הסופר\n"
	.string "שלי!$"

Route10_Text_MarkRematchIntro::
	.string "וואו, באת לפה שוב?\n"
	.string "אולי אתה פוקימניאק גם?\l"
	.string "רוצה לראות את האוסף שלי?$"

Route10_Text_ClarkRematchIntro::
	.string "הא-האהאה-אה-הא!\n"
	.string "אני לא מפסיק להתעטש!$"

Route10_Text_HermanRematchIntro::
	.string "היי, ילד!\n"
	.string "הראיתי לך את הפוקימונים שלי?$"

Route10_Text_HeidiRematchIntro::
	.string "יצאתי למכון פוקימונים שוב.\p"
	.string "...אבל הפסדתי כרגיל.$"

Route10_Text_TrentRematchIntro::
	.string "אה!\n"
	.string "האוויר בהר הזה טעים!\l"
	.string "הוא כל כך טוב, אני לא יכול לעזוב!$"

Route10_Text_CarolRematchIntro::
	.string "הראש שלי מתחיל להסתחרר.\n"
	.string "טיילתי יותר מדי זמן...$"

Route11_Text_HugoRematchIntro::
	.string "ניצחון, הפסד או תיקו!\n"
	.string "עכשיו לקרב חוזר!$"

Route11_Text_JasperRematchIntro::
	.string "תחרות היא הריגוש האולטימטיבי.\n"
	.string "אני עדיין לא יכול להפסיק!$"

Route11_Text_EddieRematchIntro::
	.string "אתה יודע, נכון?\n"
	.string "בוא נתחיל, אבל בלי לרמות!$"

Route11_Text_BraxtonRematchIntro::
	.string "היי שם!\p"
	.string "אבל תיזהר!\n"
	.string "אני עדיין מניח כאן כבלים!$"

Route11_Text_DillonRematchIntro::
	.string "נהייתי מאמן לפני זמן מה.\n"
	.string "אבל, אני חושב שאני יכול לנצח.$"

Route11_Text_DirkRematchIntro::
	.string "פוואהאהא!\n"
	.string "מעולם לא הפסדתי!\p"
	.string "...ואם כן, שכחתי\n"
	.string "מזה לגמרי!$"

Route11_Text_DarianRematchIntro::
	.string "מעולם לא ניצחתי...\p"
	.string "אולי נגזר עליי להישאר\n"
	.string "ככה...$"

Route11_Text_YasuRematchIntro::
	.string "אני הכי טוב בכיתה שלי.\n"
	.string "אני מתאמן כל בוקר וערב!$"

Route11_Text_BernieRematchIntro::
	.string "שים לב לכבלים חשופים!$"

Route11_Text_DaveRematchIntro::
	.string "גידלתי את הפוקימונים שלי בקפידה.\n"
	.string "הם אמורים להיות מוכנים עכשיו.\l"
	.string "הפעם, הם גם אמורים לנצח.$"

Route12_Text_NedRematchIntro::
	.string "כן!\n"
	.string "תפסתי משהו, הנה!\l"
	.string "ז-זה יכול להיות האמיתי!$"

Route12_Text_ChipRematchIntro::
	.string "סוף סוף הגעת.\n"
	.string "דיג זה משחק של סבלנות.$"

Route12_Text_JustinRematchIntro::
	.string "עדיין לא מצאתי אבן ירח...\n"
	.string "מצאת אחת?$"

Route12_Text_LucaRematchIntro::
	.string "חשמל תמיד היה המומחיות שלי.\p"
	.string "אני לא יודע כלום על פוקימונים\n"
	.string "של הים, בכל זאת.$"

Route12_Text_HankRematchIntro::
	.string "המשוגע לדיג נגד ילד הפוקימון!\n"
	.string "סיבוב נוסף, קרב!$"

Route12_Text_ElliotRematchIntro::
	.string "אני אוהב דיג, אל תבין אותי לא\n"
	.string "נכון. אבל, הלוואי שהיה לי יותר\l"
	.string "עבודה... ...קשה לוותר על דיג!$"

Route12_Text_AndrewRematchIntro::
	.string "מה דג?\p"
	.string "לעולם לא תדע אלא אם תנצח\n"
	.string "אותי!$"

Route12_Text_JesRematchIntro::
	.string "ג'ס: אני אנצח היום פה ואציע\n"
	.string "נישואים לג'יה שלי.$"

Route12_Text_GiaRematchIntro::
	.string "ג'יה: היי, ג'ס...\n"
	.string "חיכיתי הרבה זמן עכשיו.\p"
	.string "אם ננצח היום, אני אתחתן איתך!$"

Route13_Text_SebastianRematchIntro::
	.string "פוקימוני הציפור שלי זוכרים אותך!$"

Route13_Text_SusieRematchIntro::
	.string "אני רוצה להיות המאמנת הכי טובה\n"
	.string "בזמן שאני ילדה!$"

Route13_Text_ValerieRematchIntro::
	.string "וואו!\n"
	.string "השגת עוד תגים מגניבים!$"

Route13_Text_GwenRematchIntro::
	.string "הפוקימונים החמודים שגידלתי רוצים\n"
	.string "להתוודע אליך מחדש.$"

Route13_Text_AlmaRematchIntro::
	.string "רוקנתי את החסכונות שלי\n"
	.string "וקניתי עוד קרבוס.$"

Route13_Text_PerryRematchIntro::
	.string "אני לא הולך להפסיד הפעם.\n"
	.string "הרוח נושבת לכיוון שלי!$"

Route13_Text_LolaRematchIntro::
	.string "או, חזרת?\p"
	.string "בטח, אני אשחק שוב איתך,\n"
	.string "מותק.$"

Route13_Text_SheilaRematchIntro::
	.string "אתה לא יכול לשכוח שנלחמת\n"
	.string "איתי?$"

Route13_Text_JaredRematchIntro::
	.string "מה אתה בוהה בי?$"

Route13_Text_RobertRematchIntro::
	.string "אני תמיד הולך עם פוקימוני ציפור.\n"
	.string "הקדשתי את עצמי אליהם.$"

Route14_Text_CarterRematchIntro::
	.string "השתמשתי בטי.אמים כדי ללמד\n"
	.string "מהלכים טובים לפוקימונים שלי.$"

Route14_Text_MitchRematchIntro::
	.string "פוקימוני הציפור שלי צריכים להיות\n"
	.string "מוכנים לקרב הפעם.$"

Route14_Text_BeckRematchIntro::
	.string "אתה משתמש בטי.אמים על פוקימונים?\n"
	.string "סתם להחזיק אותם זה חסר תועלת.$"

Route14_Text_MarlonRematchIntro::
	.string "לימדת את פוקימוני הציפור שלך\n"
	.string "איך לעוף?\p"
	.string "תוכל לדאות איתו לשמיים!\n"
	.string "נסה את זה.$"

Route14_Text_DonaldRematchIntro::
	.string "האגדה על המיראז'ים המכונפים...\n"
	.string "שמעת עליה, נכון?$"

Route14_Text_BennyRematchIntro::
	.string "אני באמת לא מתלהב מזה, אבל בסדר.\n"
	.string "בוא נתחיל!$"

Route14_Text_LukasRematchIntro::
	.string "היי!\n"
	.string "אני זוכר אותך!\p"
	.string "קדימה, קדימה.\n"
	.string "בוא נלך, בוא נלך, בוא נלך!$"

Route14_Text_IsaacRematchIntro::
	.string "אתה פה שוב, הא?\n"
	.string "תשתוק ותילחם.$"

Route14_Text_GeraldRematchIntro::
	.string "אנחנו רוכבים כאן בגלל\n"
	.string "המרחבים הפתוחים.$"

Route14_Text_MalikRematchIntro::
	.string "קרב פוקימונים, נכון?\n"
	.string "מגניב! קרב!$"

Route14_Text_KiriRematchIntro::
	.string "קירי: ג'אן, אני מקווה שננצח היום.$"

Route14_Text_JanRematchIntro::
	.string "ג'אן: קירי, יאללה!\n"
	.string "בוא ננצח בטוח הפעם!$"

Route15_Text_KindraRematchIntro::
	.string "אני אמשיך להילחם עם הפוקימונים\n"
	.string "שקיבלתי בהחלפות.$"

Route15_Text_BeckyRematchIntro::
	.string "אתה נראה עדין, אז אני חושבת שאני\n"
	.string "יכולה לנצח אותך.\p"
	.string "אני אנסה עוד פעם!$"

Route15_Text_EdwinRematchIntro::
	.string "כשאני שורק, פוקימוני ציפור\n"
	.string "מתאספים סביבי.\p"
	.string "הם מדהים חמודים!$"

Route15_Text_ChesterRematchIntro::
	.string "המממ? הציפורים שלי רועדות!\n"
	.string "רגע, אתה לא המאמן ההוא...$"

Route15_Text_GraceRematchIntro::
	.string "אוי, אתה קטנצ'יק חמוד!\n"
	.string "ממש כמו פוקימון מתוק!\l"
	.string "אני זוכרת אותך עכשיו!$"

Route15_Text_OliviaRematchIntro::
	.string "אני מגדלת פוקימונים להגנה\n"
	.string "כי אני גרה לבד.\p"
	.string "זה לא השתנה.$"

Route15_Text_ErnestRematchIntro::
	.string "היי, ילד! בוא הנה!\n"
	.string "השגתי את אלה מאיזה לוזר!$"

Route15_Text_AlexRematchIntro::
	.string "תן את כל הכסף שלך כשתפסיד\n"
	.string "לי, ילד!$"

Route15_Text_CeliaRematchIntro::
	.string "מה מגניב ומה קורה?\n"
	.string "החלפת פוקימונים, כמובן.$"

Route15_Text_YazminRematchIntro::
	.string "רוצה לשחק עם הפוקימונים שלי\n"
	.string "שוב?$"

Route15_Text_MyaRematchIntro::
	.string "מיה: היי, אנחנו ממשיכים להיפגש,\n"
	.string "נכון?\p"
	.string "תעזור לי לאמן את אחי הקטן\n"
	.string "שוב?$"

Route15_Text_RonRematchIntro::
	.string "רון: אחותי נהייתה יותר\n"
	.string "חזקה...$"

Route16_Text_LaoRematchIntro::
	.string "מה אתה רוצה?$"

Route16_Text_KojiRematchIntro::
	.string "אופניים יפים!\n"
	.string "תן אותם מהר!$"

Route16_Text_LukeRematchIntro::
	.string "צא לשחק, עכברון קטן.\n"
	.string "אני אטפל בך כמו שצריך!$"

Route16_Text_HideoRematchIntro::
	.string "היי, חכה שנייה!\n"
	.string "אל תקרא לי ואז תברח!$"

Route16_Text_CamronRematchIntro::
	.string "אני מרגיש רעב ורע!\n"
	.string "אני ממש צריך שק אגרוף!$"

Route16_Text_RubenRematchIntro::
	.string "היי, שם!\n"
	.string "יהיה לנו זמן טוב!$"

Route16_Text_JedRematchIntro::
	.string "ג'ד: באת לראות את האהבה שלנו,\n"
	.string "שלא יודעת גבולות?$"

Route16_Text_LeaRematchIntro::
	.string "לאה: לפעמים, העוצמה של\n"
	.string "האהבה שלנו מפחידה אותי.$"

Route17_Text_RaulRematchIntro::
	.string "אמרתי לך, אין התעשרות מהירה\n"
	.string "בקרבות עם ילדים.$"

Route17_Text_IsaiahRematchIntro::
	.string "אני מאוד גאה בגוף שלי, ילדון.\n"
	.string "בוא!$"

Route17_Text_VirgilRematchIntro::
	.string "יצאת לטיול?$"

Route17_Text_BillyRematchIntro::
	.string "אנחנו רוכבים!\n"
	.string "אנחנו שולטים בכבישים, גבר!$"

Route17_Text_NikolasRematchIntro::
	.string "וולטורב הולך להחשמל אותך\n"
	.string "ברצינות היום!$"

Route17_Text_ZeekRematchIntro::
	.string "העליתי רמה לפוקימון שלי, אבל הוא\n"
	.string "בכלל לא מתפתח. למה?$"

Route17_Text_JamalRematchIntro::
	.string "אההה! אני באמת צריך להתאמן\n"
	.string "ולהוריד קצת שומן ברצינות!$"

Route17_Text_CoreyRematchIntro::
	.string "תהיה מורד!$"

Route17_Text_JaxonRematchIntro::
	.string "כן, אלה אופניים יפים!\n"
	.string "איך הם מתנהגים?$"

Route17_Text_WilliamRematchIntro::
	.string "תסתלק מפה, ילד!\n"
	.string "אני גמור!$"

Route18_Text_WiltonRematchIntro::
	.string "בדקתי כל אזור עשבי\n"
	.string "בשביל פוקימונים חדשים.\p"
	.string "אבל זה לא תמיד קל...$"

Route18_Text_RamiroRematchIntro::
	.string "קורוקוקוקו!\n"
	.string "קריאת הציפור שלי משתפרת?$"

Route18_Text_JacobRematchIntro::
	.string "הזהרתי אותך קודם, זה השטח שלי!\p"
	.string "אני לא רוצה שתסתובב פה.$"

Route19_Text_RichardRematchIntro::
	.string "אני כמעט מחומם לצאת\n"
	.string "לשחייה.$"

Route19_Text_ReeceRematchIntro::
	.string "חכה! תאט!\n"
	.string "מה אם יהיה לך התקף לב?$"

Route19_Text_MatthewRematchIntro::
	.string "אני אוהב לשחות!\n"
	.string "אני מניח שאתה מהטיפוס שגולש.$"

Route19_Text_DouglasRematchIntro::
	.string "מה מעבר לאופק?\n"
	.string "ראית?$"

Route19_Text_DavidRematchIntro::
	.string "ניסיתי לצלול בשביל פוקימונים שוב,\n"
	.string "אבל זה לא הלך כמו קודם.$"

Route19_Text_TonyRematchIntro::
	.string "אני מסתכל על הים כדי לשכוח את כל\n"
	.string "הדברים הרעים שקרו.\p"
	.string "...כמו להפסיד לך בפעם שעברה!$"

Route19_Text_AnyaRematchIntro::
	.string "אתה תמיד מקבל לרכב על\n"
	.string "הפוקימונים שלך...\p"
	.string "זה נראה כל כך מרגיע.\n"
	.string "אני יכולה לקבל אותו אם אנצח?$"

Route19_Text_AliceRematchIntro::
	.string "שחייה זה נהדר!\n"
	.string "כוויות שמש לא!$"

Route19_Text_AxleRematchIntro::
	.string "המים האלה מסוכנים!\n"
	.string "אתה לא צריך לחזור לכאן!$"

Route19_Text_ConnieRematchIntro::
	.string "שחיתי לכאן עם החברים שלי...\n"
	.string "אני עייפה...\l"
	.string "אנחנו חייבים להילחם שוב?$"

Route19_Text_LiaRematchIntro::
	.string "ליה: אתה יודע שאחי בדיוק\n"
	.string "הפך למאמן, נכון?\p"
	.string "אני רוצה לעשות אותו טוב יותר, אז\n"
	.string "אני צריכה את עזרתך שוב.$"

Route19_Text_LucRematchIntro::
	.string "לוק: אחותי הגדולה לימדה אותי הכל\n"
	.string "על פוקימונים.\p"
	.string "מעניין אם אני טוב יותר?$"

Route20_Text_BarryRematchIntro::
	.string "המים רדודים כאן.\n"
	.string "יש הרבה אנשים שוחים.$"

Route20_Text_ShirleyRematchIntro::
	.string "אתה מקנא שאני\n"
	.string "בחופשה בסיפום?$"

Route20_Text_TiffanyRematchIntro::
	.string "אני אוהבת לצוף עם הדגים\n"
	.string "כאן בין הגלים.$"

Route20_Text_IreneRematchIntro::
	.string "היית בחופשה גם כן?$"

Route20_Text_DeanRematchIntro::
	.string "תראה את המבנה הגופני שלי!\p"
	.string "הוא אפילו יותר חזק מאי פעם!$"

Route20_Text_DarrinRematchIntro::
	.string "למה אתה רוכב על פוקימון?\n"
	.string "עוד לא למדת לשחות?$"

Route20_Text_RogerRematchIntro::
	.string "רכבתי על פוקימון הציפור שלי לכאן.$"

Route20_Text_NoraRematchIntro::
	.string "החבר שלי נתן לי פנינים גדולות.\n"
	.string "והן גדלו עוד יותר!$"

Route20_Text_MissyRematchIntro::
	.string "שחיתי לכאן מאי סינבר.\n"
	.string "זה לא היה קל, כמו שאמרתי.$"

Route20_Text_MelissaRematchIntro::
	.string "בסינבר, במערב, יש מעבדה\n"
	.string "לפוקימונים.\p"
	.string "אבא שלי עובד שם.$"

Route21_North_Text_RonaldRematchIntro::
	.string "אתה רוצה לדעת אם הדגים\n"
	.string "נושכים?$"

Route21_North_Text_WadeRematchIntro::
	.string "תפסתי שלל גדול שוב!\n"
	.string "רוצה להתמודד עוד פעם?$"

Route21_North_Text_SpencerRematchIntro::
	.string "הים מטהר את גופי ונשמתי!$"

@ Unused trainer from RB that had a rematch intro added
Route21_North_Text_CueBallRematchIntro::
	.string "きょうも　およぎに\n"
	.string "きちまったぜ$"

Route21_South_Text_JackRematchIntro::
	.string "תפסתי את הפוקימונים שלי בים.\n"
	.string "ושם אני מאמן אותם.$"

Route21_South_Text_JeromeRematchIntro::
	.string "כרגע, אני באמצע עוד תחרות\n"
	.string "טריאתלון!$"

Route21_South_Text_RolandRematchIntro::
	.string "אהה!\n"
	.string "תרגיש את השמש והרוח!$"

Route21_South_Text_ClaudeRematchIntro::
	.string "היי, תפסיק כבר.\n"
	.string "אתה תמיד מבריח את הדגים!$"

Route21_South_Text_NolanRematchIntro::
	.string "תעשה לי חברה עד שאתפוס משהו.$"

Route21_North_Text_LilRematchIntro::
	.string "ליל: הא? קרב שוב? איאן, אתה לא\n"
	.string "יכול לעשות את זה לבד?$"

Route21_North_Text_IanRematchIntro::
	.string "איאן: אחותי עדיין עצלנית.\n"
	.string "תעזור לי להכניס אותה לכושר!$"

Route25_Text_JoeyRematchIntro::
	.string "לא אפסיד כשאני כאן!$"

Route25_Text_DanRematchIntro::
	.string "אבא לקח אותי למסיבה מדהימה על\n"
	.string "האס.אס אן בעיר ורמיליון.$"

Route25_Text_FlintRematchIntro::
	.string "אני בחור מגניב.\n"
	.string "יש לי חברה!\p"
	.string "אני אראה לה כמה אני מגניב\n"
	.string "בטוח הפעם!$"

Route25_Text_KelseyRematchIntro::
	.string "היי!\n"
	.string "החבר שלי מגניב!\l"
	.string "הכושר שלי טוב היום!$"

Route25_Text_ChadRematchIntro::
	.string "הייתה לי הרגשה...\n"
	.string "ידעתי שאצטרך להילחם בך שוב!$"

Route25_Text_HaleyRematchIntro::
	.string "לחברה שלי יש הרבה פוקימונים\n"
	.string "חמודים. אני כל כך מקנאה!$"

Route25_Text_FranklinRematchIntro::
	.string "רק התאמנתי על הר מון,\n"
	.string "אבל עדיין יש לי דלק במיכל!$"

Route25_Text_NobRematchIntro::
	.string "משוגע לפוקימונים גר על הכף.\n"
	.string "ראית את האוסף שלו?$"

Route25_Text_WayneRematchIntro::
	.string "אתה הולך לראות את ביל שוב?\n"
	.string "קודם, אנחנו נלחמים!$"

Route24_Text_ShaneRematchIntro::
	.string "ראיתי את המבצע שלך מהדשא!$"

Route24_Text_EthanRematchIntro::
	.string "בסדר!\n"
	.string "אני אמחץ אותך!$"

Route24_Text_ReliRematchIntro::
	.string "אתה תמיד נראה כל כך עסוק...\n"
	.string "אתה לא מתעייף?$"

Route24_Text_TimmyRematchIntro::
	.string "אתה באמת חייב לאהוב לבוא\n"
	.string "לגשר הנאגט.$"

Route24_Text_AliRematchIntro::
	.string "הפעם שנלחמנו...\p"
	.string "למרות שהייתי השני בתור,\n"
	.string "הייתי הכי טוב, נכון?$"

Route24_Text_CaleRematchIntro::
	.string "אנשים קוראים לזה גשר\n"
	.string "הנאגט!\p"
	.string "כבר ניצחת אותנו, אז אתה\n"
	.string "לא יכול לקחת את האתגר...\p"
	.string "...אבל, אתה מוזמן להילחם איתנו\n"
	.string "שוב.$"

OneIsland_TreasureBeach_Text_AmaraRematchIntro::
	.string "שוכבת לאחור, מתנדנדת עם הגלים...\n"
	.string "אני לא שמה לב לזמן חולף...$"

OneIsland_KindleRoad_Text_MariaRematchIntro::
	.string "מזג האוויר נהדר!\n"
	.string "אני אשתדל לא לקלקל אותו.$"

OneIsland_KindleRoad_Text_AbigailRematchIntro::
	.string "כוויות השמש שלי מתחילות לכאוב...$"

OneIsland_KindleRoad_Text_FinnRematchIntro::
	.string "ההר של ציפור האש מטיל\n"
	.string "צל ענק...$"

OneIsland_KindleRoad_Text_GarrettRematchIntro::
	.string "יש לי הרגשה חזקה שאני\n"
	.string "יכול לנצח הפעם!$"

OneIsland_KindleRoad_Text_TommyRematchIntro::
	.string "חכה! חכה שנייה!\n"
	.string "אני בטוח שתפסתי משהו גדול!$"

OneIsland_KindleRoad_Text_SharonRematchIntro::
	.string "תעזור לי שוב עם\n"
	.string "האימון שלי?$"

OneIsland_KindleRoad_Text_TanyaRematchIntro::
	.string "לא פספסנו אף יום אימונים\n"
	.string "עדיין!$"

OneIsland_KindleRoad_Text_SheaRematchIntro::
	.string "כל בוקר, לפני ארוחת הבוקר,\n"
	.string "אני שוחה מסביב לאי הזה...\l"
	.string "שלוש פעמים!$"

OneIsland_KindleRoad_Text_HughRematchIntro::
	.string "תתלבש מתאים לקרב! תוריד את הבגדים\n"
	.string "הקלילים האלה, אמרתי!$"

OneIsland_KindleRoad_Text_BryceRematchIntro::
	.string "אתה יודע, הכל טעים\n"
	.string "כשאתה בטבע.$"

OneIsland_KindleRoad_Text_ClaireRematchIntro::
	.string "אכלתי יותר מדי שוב, אז תילחם\n"
	.string "איתנו בשביל קצת התעמלות?$"

OneIsland_KindleRoad_Text_KiaRematchIntro::
	.string "קיה: אחי הגדול ואני עושים\n"
	.string "שילוב מדהים!\p"
	.string "לא נפסיד הפעם!$"

OneIsland_KindleRoad_Text_MikRematchIntro::
	.string "מיק: ביחד עם קיה, אנחנו\n"
	.string "לא מפחדים מכלום!\p"
	.string "נוכיח לך את זה הפעם!$"

ThreeIsland_BondBridge_Text_NikkiRematchIntro::
	.string "האם עלינו להילחם שוב?$"

ThreeIsland_BondBridge_Text_VioletRematchIntro::
	.string "מאיפה באת, ולאן\n"
	.string "אתה הולך?$"

ThreeIsland_BondBridge_Text_AmiraRematchIntro::
	.string "אני רוצה לשחות בלי גלגל\n"
	.string "ההצלה שלי בקרוב.$"

ThreeIsland_BondBridge_Text_AlexisRematchIntro::
	.string "יש, יש!\n"
	.string "פוקימון!$"

ThreeIsland_BondBridge_Text_TishaRematchIntro::
	.string "אוי, לא, לא אמרתי לך כבר?\n"
	.string "בבקשה, תתרחק ממני!$"

ThreeIsland_BondBridge_Text_JoyRematchIntro::
	.string "ג'וי: נהיינו חזקים יותר!\n"
	.string "הרבה הרבה!$"

ThreeIsland_BondBridge_Text_MegRematchIntro::
	.string "מג: לא תוכל לנצח אותנו היום!$"

FiveIsland_WaterLabyrinth_Text_AlizeRematchIntro::
	.string "אוי, שלום!\p"
	.string "אתה מגדל את הפוקימונים שלך\n"
	.string "בסביבה טובה?$"

FiveIsland_ResortGorgeous_Text_DaisyRematchIntro::
	.string "עם הידיים האלה, אני אצור\n"
	.string "את הניצחון שלי היום.$"

FiveIsland_ResortGorgeous_Text_CelinaRematchIntro::
	.string "אני חייבת לחזור על עצמי?\n"
	.string "אני מנסה לצייר.\l"
	.string "בבקשה תצא מטווח הראייה שלי!$"

FiveIsland_ResortGorgeous_Text_RaynaRematchIntro::
	.string "לא התקדמתי בכלל... אני עדיין לא\n"
	.string "מצליחה למצוא את הזווית הנכונה...$"

FiveIsland_ResortGorgeous_Text_JackiRematchIntro::
	.string "אוה, אתה תיתן לי עוד\n"
	.string "הזדמנות להתחרות איתך?$"

FiveIsland_ResortGorgeous_Text_GillianRematchIntro::
	.string "הם כמעט סיימו לבנות את\n"
	.string "הבריכה לפוקימונים שלי.\p"
	.string "אתה חייב לקפוץ לביקור.$"

FiveIsland_ResortGorgeous_Text_DestinRematchIntro::
	.string "אני רץ טוב.\n"
	.string "נהייתי אפילו מהיר יותר!$"

FiveIsland_ResortGorgeous_Text_TobyRematchIntro::
	.string "אני אומר, חבר!\n"
	.string "בוא נהנה מהזמן שלנו ביחד!$"

FiveIsland_MemorialPillar_Text_MiloRematchIntro::
	.string "אני הבכור מאחי הציפורים.\n"
	.string "זוכר אותי?\p"
	.string "נכון, אני זה שאוהב\n"
	.string "ציפורים בגלל המקורים שלהן!$"

FiveIsland_MemorialPillar_Text_ChazRematchIntro::
	.string "אני הבן האמצעי של אחי\n"
	.string "הציפורים.\p"
	.string "אני זה שאוהב כנפיים.\n"
	.string "בוא נילחם שוב!$"

FiveIsland_MemorialPillar_Text_HaroldRematchIntro::
	.string "אני הצעיר מבין אחי הציפורים.\p"
	.string "אני אוהב ציפורים בגלל הנוצות שלהן.\n"
	.string "לא חשבתי שאראה אותך שוב!$"

SixIsland_OutcastIsland_Text_TylorRematchIntro::
	.string "עדיין אין לי מזל בכלל.\n"
	.string "קרב יהיה שינוי קצב נחמד!$"

SixIsland_OutcastIsland_Text_MymoRematchIntro::
	.string "נשימה... נשימה...\p"
	.string "שחיתי לכאן מהנמל של האי השישי\n"
	.string "בפעם אחת שוב.$"

SixIsland_OutcastIsland_Text_NicoleRematchIntro::
	.string "אתה תמיד מגיע בזמן שאני\n"
	.string "שוחה.$"

SixIsland_OutcastIsland_Text_AvaRematchIntro::
	.string "אווה: בוא נעשה עוד קרב\n"
	.string "ימי שניים-על-שניים היום!$"

SixIsland_OutcastIsland_Text_GebRematchIntro::
	.string "גב: אחותי הגדולה ואני הרבה\n"
	.string "יותר חזקים מקודם!$"

SixIsland_GreenPath_Text_JaclynRematchIntro::
	.string "...הא?\p"
	.string "אני מדמיינת את הבית שלי, אבל\n"
	.string "טלפורט תמיד מביא אותי לכאן!$"

SixIsland_WaterPath_Text_RoseRematchIntro::
	.string "או, שלום.\n"
	.string "רוח נעימה נושבת שוב.$"

SixIsland_WaterPath_Text_EdwardRematchIntro::
	.string "חהחה, אני מתאמן בסתר\n"
	.string "שוב.$"

SixIsland_WaterPath_Text_SamirRematchIntro::
	.string "מה, נמאס לך לראות\n"
	.string "שחיינים כמוני?\p"
	.string "אה, אל תשנא!\n"
	.string "תילחם איתי שוב.$"

SixIsland_WaterPath_Text_DeniseRematchIntro::
	.string "אנחה...\n"
	.string "החבר שלי עסוק שוב...$"

SixIsland_WaterPath_Text_EarlRematchIntro::
	.string "נו, תגיד לי, איפה נמצאים\n"
	.string "ההרים באזורים האלה?$"

SixIsland_WaterPath_Text_MiuRematchIntro::
	.string "מיו: שלום, פוקימון!\n"
	.string "הגיע הזמן לשחק שוב!$"

SixIsland_WaterPath_Text_MiaRematchIntro::
	.string "מיה: שלום, פוקימון!\n"
	.string "הגיע הזמן להילחם שוב!$"

SixIsland_RuinValley_Text_StanlyRematchIntro::
	.string "נראה שיש עוד הרבה סודות\n"
	.string "שעדיין לא נפתרו בעולם הזה.$"

SixIsland_RuinValley_Text_FosterRematchIntro::
	.string "היי, לא נפגשנו בעבר?\n"
	.string "מה הביא אותך לחזור?$"

SixIsland_RuinValley_Text_LarryRematchIntro::
	.string "נאמר שיש אבנים מסתוריות\n"
	.string "באי הזה.\p"
	.string "גילית משהו מאז\n"
	.string "שנפגשנו בפעם האחרונה?$"

SixIsland_RuinValley_Text_DarylRematchIntro::
	.string "קרב חוזר איתך, כל כך גבוה!$"

SixIsland_RuinValley_Text_HectorRematchIntro::
	.string "אני די מכיר את השטח\n"
	.string "באזורים האלה.$"

SevenIsland_TrainerTower_Text_DarioRematchIntro::
	.string "חשתי בהתקרבות שלך.$"

SevenIsland_TrainerTower_Text_RodetteRematchIntro::
	.string "במקום כלשהו באי הזה, פוקימונים\n"
	.string "מוזרים ישנים.$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahRematchIntro::
	.string "קיאהאהא!\p"
	.string "לחזור לא ישנה כלום.\n"
	.string "אני אזרוק אותך בקלות!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonRematchIntro::
	.string "הו! אתה חבר במועדון המעריצים\n"
	.string "שלי, נכון?$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasRematchIntro::
	.string "האי הזה גדול מדי...\n"
	.string "לסייר במקום זה סחיבה...$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineRematchIntro::
	.string "אני לא סולחת לאנשים שמתעללים\n"
	.string "בפוקימונים!$"

SevenIsland_SevaultCanyon_Entrance_Text_EveRematchIntro::
	.string "איב: אני אצוות עם ג'ון\n"
	.string "ונילחם ביחד שוב.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonRematchIntro::
	.string "ג'ון: כשאני עם איב, זה מרגיש\n"
	.string "כאילו לעולם לא נפסיד, אף פעם.$"

SevenIsland_SevaultCanyon_Text_CyndyRematchIntro::
	.string "בוא נעשה עוד קרב.\n"
	.string "הכושר שלי בשיאו!$"

SevenIsland_SevaultCanyon_Text_EvanRematchIntro::
	.string "זה לא משנה אם במקרה יש לך\n"
	.string "את הפוקימונים הכי חזקים...\p"
	.string "זה לא אומר כלום אם אתה לא\n"
	.string "יודע איך להשתמש בהם כמו שצריך!$"

SevenIsland_SevaultCanyon_Text_JacksonRematchIntro::
	.string "אני עובד כדי להגן על הסביבה.\n"
	.string "בתמורה, הטבע מגן עליי!$"

SevenIsland_SevaultCanyon_Text_KatelynRematchIntro::
	.string "בכל פעם שאנחנו נפגשים, יש לך את\n"
	.string "הנעליים המגניבות האלה.$"

SevenIsland_SevaultCanyon_Text_LeroyRematchIntro::
	.string "בטח נהיית חזק יותר.\n"
	.string "תן לי להילחם בך, בבקשה!$"

SevenIsland_SevaultCanyon_Text_MichelleRematchIntro::
	.string "קיבלתי את החינוך הכי טוב אפשרי\n"
	.string "כדי להיות חזקה ככה.\p"
	.string "לא אפסיד הפעם.\n"
	.string "בשום פנים ואופן!$"

SevenIsland_SevaultCanyon_Text_LexRematchIntro::
	.string "לקס: יקירתי ניה, ביחד\n"
	.string "אנחנו בטוח ננצח!$"

SevenIsland_SevaultCanyon_Text_NyaRematchIntro::
	.string "ניה: לא אאכזב את המנטור שלי\n"
	.string "לקס! אנחנו הולכים לנצח!$"

SevenIsland_TanobyRuins_Text_BrandonRematchIntro::
	.string "גילית משהו על\n"
	.string "חדר האבן הזה?$"

SevenIsland_TanobyRuins_Text_BenjaminRematchIntro::
	.string "אומרים שפוקימון מיסטי ישן\n"
	.string "בפנים כאן.$"

SevenIsland_TanobyRuins_Text_EdnaRematchIntro::
	.string "המורה שלי מראה לי איך\n"
	.string "לצייר עוד.$"

SevenIsland_TanobyRuins_Text_CliffordRematchIntro::
	.string "היום, בנוסף לשיעור שלנו,\n"
	.string "באנו לראות את החדר שוב.$"
