Text_FirstShouldRestoreMonsHealth::
	.string "קודם כל, כדאי שתרפא את\n"
	.string "הפוקימונים שלך לבריאות מלאה.$"

Text_MonsHealedShouldBuyPotions::
	.string "הפוקימונים שלך רופאו\n"
	.string "לבריאות מושלמת.\p"
	.string "אם האנרגיה של הפוקימונים שלך,\n"
	.string "נ”ח, נמוכה, בבקשה בוא לבקר אותנו.\p"
	.string "אם אתה מתכנן ללכת רחוק בשטח,\n"
	.string "כדאי שתקנה כמה שיקויים\l"
	.string "בחנות הפוקימונים.\p"
	.string "אנחנו מאחלים לך הצלחה!$"

Text_MonsHealed::
	.string "הפוקימונים שלך רופאו\n"
	.string "לבריאות מושלמת.\p"
	.string "אנחנו מאחלים לך הצלחה!$"

Text_HadQuiteAnExperienceTakeRest::
	.string "אמא: {PLAYER}!\n"
	.string "ברוך הבא הביתה.\p"
	.string "נשמע שעברת חוויה\n"
	.string "לא פשוטה.\p"
	.string "אולי כדאי שתנוח\n"
	.string "קצת.$"

Text_MomExplainHPGetPotions::
	.string "אמא: או, טוב! אתה והפוקימונים\n"
	.string "שלך נראים נהדר.\p"
	.string "פרופסור אלון סיפר לי עכשיו.\p"
	.string "הוא אמר שהאנרגיה של הפוקימונים\n"
	.string "נמדדת ב-נ”ח.\p"
	.string "אם הפוקימונים שלך מאבדים נ”ח,\n"
	.string "אתה יכול לרפא אותם בכל\l"
	.string "מרכז פוקימונים.\p"
	.string "אם אתה מתכוון לנסוע רחוק,\n"
	.string "מאמן חכם מצטייד בשיקויים\l"
	.string "בחנות הפוקימונים.\p"
	.string "תעשה אותי גאה, מותק!\p"
	.string "תיזהר!$"

Text_WhitedOutLostMoney::
	.string "ל{PLAYER} נגמרו הפוקימונים\n"
	.string "הכשירים לקרב!\p"
	.string "{PLAYER} נכנס לפאניקה ואיבד\n"
	.string "¥{STR_VAR_1}…\p"
	.string "… … … …\p"
	.string "{PLAYER} התעלף!$"

Text_WhitedOut::
	.string "ל{PLAYER} נגמרו הפוקימונים\n"
	.string "הכשירים לקרב!\p"
	.string "{PLAYER} התעלף!$"
