SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
    .string "באי הזה קורים אירועים שונים\n"
    .string "תלוי בחיבורים.\p"
    .string "מה הם החיבורים האלה?\p"
    .string "את זה תצטרך לגלות\n"
    .string "בעצמך.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
    .string "הגעת לכאן במעבורת\n"
    .string "סיגאלופ?\p"
    .string "יש לפחות עשר ספינות\n"
    .string "מהירות כאלה.\p"
    .string "אבל אני לא יודע לאן\n"
    .string "כולן מפליגות.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
    .string "אם אתה בטוח בעצמך, כדאי\n"
    .string "שתבדוק את מגדל המאמנים.$"
