SevenIsland_SevaultCanyon_Text_CyndyIntro::
    .string "הכושר שלי בשיא!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
    .string "הא?\n"
    .string "משהו לא בסדר כאן…$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
    .string "במצב שלי עכשיו, אולי כדאי\n"
    .string "שאדחה את מגדל המאמנים…$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
    .string "לא משנה אם יש לך במקרה\n"
    .string "את הפוקימונים הכי חזקים…\p"
    .string "זה לא שווה כלום אם אתה לא\n"
    .string "יודע להשתמש בהם כמו שצריך!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
    .string "אתה ממש מומחה בזה.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
    .string "רואים אותם מדי פעם,\n"
    .string "מאמנים עם פוקימונים אדירים\l"
    .string "שאין להם מושג מה לעשות.\p"
    .string "לפני שמאמנים פוקימונים,\n"
    .string "המאמנים עצמם צריכים לגדול.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
    .string "אני פועל להגן על הסביבה.\n"
    .string "ובתמורה, הטבע מגן עלי!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
    .string "וואו! אתה חזק!\n"
    .string "אולי תגן גם עלי?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
    .string "מרחוק, מבין הכוכבים, כדור\n"
    .string "הארץ שלנו הוא רק טיפת מים.\p"
    .string "אבל אנחנו רוצים לשמור על\n"
    .string "טיפת המים הזאת למען כולם.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
    .string "הנעליים שלך ממש\n"
    .string "מגניבות.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
    .string "אתה ממש חזק, למרות\n"
    .string "המראה החמוד שלך.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
    .string "אמא שלך קנתה לך את נעלי\n"
    .string "הריצה המגניבות האלה?\p"
    .string "היא בטח מעריצה אותך.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
    .string "אתה נראה חזק.\n"
    .string "בוא נילחם, בבקשה!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
    .string "ידעתי!\n"
    .string "אתה חזק בדיוק כמו שחשבתי!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
    .string "צורת הלחימה שלך נתנה לי\n"
    .string "המון מידע שימושי.\p"
    .string "תודה רבה לך!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
    .string "קיבלתי את החינוך הטוב ביותר\n"
    .string "כדי להיות חזקה כל כך.\p"
    .string "אני לא רוצה להפסיד לאף אחד!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
    .string "תודה לך. אני מרגישה שההפסד\n"
    .string "מולך שחרר אותי.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
    .string "משום מה אני מתרגזת נורא\n"
    .string "מכל דבר קטן.\p"
    .string "אני ארגיע את עצמי עם\n"
    .string "נשימות עמוקות.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
    .string "לקס: ניה יקירתי, ביחד\n"
    .string "אנחנו יכולים לנצח!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
    .string "לקס: כנראה שהייתי\n"
    .string "רשלן מדי…$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
    .string "לקס: אני חושב שזו הייתה\n"
    .string "חוויה טובה בשביל ניה.\p"
    .string "אני אסיר תודה לך.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
    .string "לקס: אפשר לבקש שתילחם\n"
    .string "בשנינו בו זמנית?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
    .string "ניה: אשתדל מאוד כדי לא\n"
    .string "להכביד על המנטור שלי, לקס!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
    .string "ניה: אוי לא…\n"
    .string "אני כל כך מצטערת, אני…$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
    .string "ניה: אני חושבת שאני צריכה\n"
    .string "עוד הרבה ניסיון והדרכה\l"
    .string "אצל לקס…\p"
    .string "…אז לקס, בבקשה, אפשר\n"
    .string "להישאר איתך ככה?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
    .string "ניה: סליחה, אבל אפשר שנילחם\n"
    .string "בסגנון שניים על שניים?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
    .string "קניון סבולט\n"
    .string "חורבות טאנובי לפניך$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
    .string "להתאמן לבד זה בהחלט\n"
    .string "לא דבר רע.\p"
    .string "אבל גם לא רע לשאוף לפסגה\n"
    .string "יחד עם שותף.\p"
    .string "אפילו ברונו…\n"
    .string "הוא התאמן פעם עם בחור\l"
    .string "בשם ברולי.$"
