OneIsland_Text_BillLetsGoSeeCelio::
    .string "ביל: הגענו!\n"
    .string "זהו אי 1.\p"
    .string "יש כאן כמה איים,\n"
    .string "וזה אחד מהם.\p"
    .string "חבר שלי, סליו, שלח את הסירה\n"
    .string "שתאסוף אותי לכאן.\p"
    .string "הוא אחראי לבדו על רשת\n"
    .string "המחשבים של האי.\p"
    .string "…למה אני בכלל מספר לך את זה?\n"
    .string "בוא פשוט נלך לראות את סליו!$"

Text_WhereDoYouWantToSail::
    .string "אהוי, שם!\n"
    .string "לאן תרצה להפליג?$"

OneIsland_Text_LuckyToHaveCelioHere::
    .string "אנחנו על אי קטן\n"
    .string "באמצע שום מקום.\p"
    .string "יש לנו מזל שיש כאן בחור\n"
    .string "צעיר והגון כמו סליו.\p"
    .string "הנכדה שלי הייתה נרגשת\n"
    .string "מהחבר של סליו.\p"
    .string "משהו על פוקימניאק\n"
    .string "מפורסם?\p"
    .string "לא בטוח מה זה אומר, אבל\n"
    .string "סליו הוא ממש גבר!$"

OneIsland_Text_HavePCLinkageWithKanto::
    .string "הנכדה שלי הייתה נרגשת\n"
    .string "מפריצת דרך חדשה.\p"
    .string "היא אמרה שיש לנו עכשיו\n"
    .string "חיבור מחשבים לאנשים בקאנטו.\p"
    .string "לא בטוח מה זה אומר, אבל\n"
    .string "סליו הוא ממש גבר!$"

OneIsland_Text_HavePCLinkageWithHoenn::
    .string "הנכדה שלי הייתה נרגשת\n"
    .string "מפריצת דרך חדשה.\p"
    .string "היא אמרה שסוף סוף יש לנו\n"
    .string "חיבור מחשבים לאנשים בהואן.\p"
    .string "לא בטוח מה זה אומר, אבל\n"
    .string "סליו הוא ממש גבר.\p"
    .string "הוא יהיה בעל מצוין\n"
    .string "לנכדה שלי!$"

OneIsland_Text_IslandSign::
    .string "אי 1\n"
    .string "כאן חברים נפגשים$"

OneIsland_Text_PokemonNetCenterSign::
    .string "מרחיבים את עולם הפוקימון!\n"
    .string "מרכז הרשת של הפוקימון$"

@ Unused
OneIsland_Text_ReturnToCinnabar::
    .string "グレンタウンに　もどりますか？$"

OneIsland_Text_IsntWarmClimateHereGreat::
    .string "היי, באת לטייל?\n"
    .string "האקלים החמים כאן נהדר, לא?$"

