Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
    .string "שלום! זוכר אותי?\n"
    .string "אני אחד מעוזריו של פרופ' אוק.\p"
    .string "אם לפוקדקס שלך יש נתונים מלאים\n"
    .string "על עשר מינים, אני אמור לתת\l"
    .string "לך פרס.\p"
    .string "פרופ' אוק הפקיד אותי עם\n"
    .string "מ”נ50 עבורך.\p"
    .string "אז, {PLAYER}, תן לי לשאול אותך.\p"
    .string "האם אספת נתונים על לפחות\n"
    .string "עשרה סוגי פוקימונים?$"

Route2_EastBuilding_Text_GreatHereYouGo::
    .string "מעולה! תפסת או היה לך\n"
    .string "{STR_VAR_3} סוגי פוקימונים!\p"
    .string "מזל טוב!\n"
    .string "הנה זה!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
    .string "{PLAYER} קיבל את מ”נ50\n"
    .string "מהעוזר.$"

Route2_EastBuilding_Text_ExplainHM05::
    .string "מ”נ50 מכיל את המהלך הנסתר\n"
    .string "פלאש.\p"
    .string "פלאש מאיר אפילו את המערות\n"
    .string "והמבוכים החשוכים ביותר.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
    .string "ברגע שפוקימון לומד את פלאש, תוכל\n"
    .string "לעבור במנהרת הרוק.$"
