Route17_Text_RaulIntro::
    .string "אין דרך להתעשר מהר\n"
    .string "מקרבות עם ילדים.$"

Route17_Text_RaulDefeat::
    .string "נשרפתי!$"

Route17_Text_RaulPostBattle::
    .string "אפשר למצוא דברים טובים שנפלו\n"
    .string "בשביל האופניים.\p"
    .string "יש כסף טוב באיסוף שלהם ומכירתם.$"

Route17_Text_IsaiahIntro::
    .string "אני מאוד גאה בגוף שלי, ילד.\n"
    .string "בוא נראה מה יש לך!$"

Route17_Text_IsaiahDefeat::
    .string "וווו!$"

Route17_Text_IsaiahPostBattle::
    .string "הייתי יכול להדוף אותך מכאן\n"
    .string "עם הבטן שלי!$"

Route17_Text_VirgilIntro::
    .string "אתה בדרך לפוקסיה?$"

Route17_Text_VirgilDefeat::
    .string "התרסקתי ונשרפתי!$"

Route17_Text_VirgilPostBattle::
    .string "אני אוהב לרוץ במורד!$"

Route17_Text_BillyIntro::
    .string "אנחנו רוכבי אופניים!\n"
    .string "אנחנו שולטים בכבישים!$"

Route17_Text_BillyDefeat::
    .string "נשרפתי!$"

Route17_Text_BillyPostBattle::
    .string "אתה מחפש הרפתקה?$"

Route17_Text_NikolasIntro::
    .string "תן לוולטורב לחשמל אותך!$"

Route17_Text_NikolasDefeat::
    .string "נוטרלתי!$"

Route17_Text_NikolasPostBattle::
    .string "מצאתי את הוולטורב שלי במפעל\n"
    .string "הכוח הנטוש.$"

Route17_Text_ZeekIntro::
    .string "שדרגתי את הפוקימון שלי,\n"
    .string "אבל הוא לא מתפתח. למה?$"

Route17_Text_ZeekDefeat::
    .string "למה, אתה!$"

Route17_Text_ZeekPostBattle::
    .string "אולי חלק מהפוקימונים צריכים\n"
    .string "אבני אלמנט כדי להתפתח.$"

Route17_Text_JamalIntro::
    .string "אני צריך קצת פעילות גופנית!$"

Route17_Text_JamalDefeat::
    .string "פוו!\n"
    .string "אימון טוב!$"

Route17_Text_JamalPostBattle::
    .string "אני בטוח שהורדתי משקל עכשיו!$"

Route17_Text_CoreyIntro::
    .string "תהיה מרדן!$"

Route17_Text_CoreyDefeat::
    .string "אההההה!$"

Route17_Text_CoreyPostBattle::
    .string "תמיד תהיה מוכן להילחם על\n"
    .string "האמונות שלך!$"

Route17_Text_JaxonIntro::
    .string "אופניים יפות!\n"
    .string "איך הם מתמודדים?$"

Route17_Text_JaxonDefeat::
    .string "לעזאזל!$"

Route17_Text_JaxonPostBattle::
    .string "המורד מקשה על ההיגוי.$"

Route17_Text_WilliamIntro::
    .string "לך מפה, ילד!\n"
    .string "אני מותש!$"

Route17_Text_WilliamDefeat::
    .string "אתה מרוצה?$"

Route17_Text_WilliamPostBattle::
    .string "אני חייב לתפוס קצת שינה!$"

Route17_Text_WatchOutForDiscardedItems::
    .string "זו הודעה.\p"
    .string "שימו לב לפריטים שנזרקו.$"

Route17_Text_SameSpeciesGrowDifferentRates::
    .string "טיפים למאמן\p"
    .string "כל פוקימון הוא ייחודי.\p"
    .string "אפילו פוקימונים מאותו מין ורמה\n"
    .string "מתפתחים בקצב שונה.$"

Route17_Text_PressBToStayInPlace::
    .string "טיפים למאמן\p"
    .string "לחץ על כפתור B כדי להישאר במקום\n"
    .string "כשאתה על מדרון.$"

Route17_Text_RouteSign::
    .string "דרך 71\n"
    .string "עיר סלדון - עיר פוקסיה$"

Route17_Text_DontThrowGameThrowBalls::
    .string "זו הודעה!\p"
    .string "אל תזרוק את המשחק, זרוק פוקיבול\n"
    .string "במקום!$"

Route17_Text_CyclingRoadSign::
    .string "שביל האופניים\n"
    .string "סיום המדרון כאן!$"
