Route5_PokemonDayCare_Text_WantMeToRaiseMon::
    .string "אני מנהל שירות מעון יום.\p"
    .string "רוצה שאני אגדל אחד\n"
    .string "מהפוקימונים שלך?$"

Route5_PokemonDayCare_Text_ComeAgain::
    .string "בוא שוב.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
    .string "איזה פוקימון כדאי לי לגדל?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
    .string "בסדר.\n"
    .string "בוא בכל עת שתרצה.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
    .string "בסדר, אטפל ב\n"
    .string "{STR_VAR_1} שלך לזמן מה.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
    .string "בוא לראות אותי בעוד זמן מה.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
    .string "כבר חזרת?\p"
    .string "{STR_VAR_1} שלך צריך לבלות\n"
    .string "עוד קצת זמן אצלי.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
    .string "אתה חייב לי ¥{STR_VAR_2} עבור\n"
    .string "החזרת הפוקימון הזה.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
    .string "תודה!\n"
    .string "הנה הפוקימון שלך.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
    .string "{PLAYER} קיבל את {STR_VAR_1}\n"
    .string "בחזרה מהאיש במעון היום.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
    .string "אה? יש לך רק פוקימון\n"
    .string "אחד איתך.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
    .string "אם תשאיר לי את הפוקימון הזה,\n"
    .string "עם מה תלחם?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
    .string "{STR_VAR_1} שלך גדל הרבה.\n"
    .string "כן, הרבה, הייתי אומר.\p"
    .string "תן לי לראות… לפי הרמה, הוא גדל\n"
    .string "ב-{STR_VAR_2}.\p"
    .string "אני לא נהדר?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
    .string "אתה לא יכול לקחת את הפוקימון הזה\n"
    .string "אם אין לך מקום עבורו.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
    .string "אין לך מספיק כסף.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
    .string "רוצה שאבדוק את הפוקימונים שלך?$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
    .string "מצטער, אבל אני לא יכול לקבל\n"
    .string "פוקימון עם מהלך נסתר.$"
