SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
    .string "קיאהאהא!\n"
    .string "אעיף אותך בלי מאמץ!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
    .string "צ'ה!\n"
    .string "חזק מדי בשבילי!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
    .string "מה אמרת?\n"
    .string "שאני לא מתנהגת לפי המראה?\p"
    .string "חה, זה חלק מהאסטרטגיה שלי!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
    .string "שלום שלום!\n"
    .string "אתה במועדון המעריצים שלי?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
    .string "אה, אז אתה לא מעריץ…\p"
    .string "טוב, אפשר לשנות את זה.\n"
    .string "תן לי לשיר לך!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
    .string "לללה…\n"
    .string "כשאני שולח את הפוקימונים שלי,\l"
    .string "כל הבנות צורחות ומריעות!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
    .string "האי הזה גדול מדי…\n"
    .string "לא קל לסייר בכל השטח.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
    .string "אה-הא…$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
    .string "מאמנים מהעיר כמוך,\n"
    .string "הם באמת קשוחים.\p"
    .string "אתה בדרך למגדל,\n"
    .string "נכון?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
    .string "אני מענישה אנשים שמתעללים\n"
    .string "בפוקימונים!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
    .string "אתה לא נראה מאמן\n"
    .string "בעייתי.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
    .string "אם תתייחס לפוקימונים שלך\n"
    .string "בטוב לב, הם יבינו.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
    .string "איב: אני אצטרף לג'ון\n"
    .string "ונילחם ביחד.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
    .string "איב: אני וג'ון הפסדנו.\n"
    .string "חיחיחי.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
    .string "איב: אני אתאמן יותר קשה\n"
    .string "יחד עם ג'ון.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
    .string "איב: אני רוצה להילחם בך\n"
    .string "יחד עם ג'ון.\p"
    .string "תחזור עם שני פוקימונים, טוב?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
    .string "ג'ון: כשאני עם איב, מרגיש\n"
    .string "שאנחנו לא יכולים להפסיד.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
    .string "ג'ון: כשאני עם איב,\n"
    .string "זה לא מרגיש כמו הפסד!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
    .string "ג'ון: כשאני עם איב אני\n"
    .string "מרחף, בין אם ניצחתי או לא.\p"
    .string "זה קסום!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
    .string "ג'ון: אם זה עם איב, אשמח\n"
    .string "להילחם בך.\p"
    .string "אז הייתי רוצה שזה יהיה\n"
    .string "קרב שניים על שניים.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
    .string "הכניסה לקניון סבולט\p"
    .string "מאמנים מתבקשים לא לפגוע\n"
    .string "בצמחייה שבקניון.$"

