Route12_Text_MonSprawledOutInSlumber::
    .string "פוקימון נמצא\n"
    .string "בשינה עמוקה ונוחה.$"

Text_SnorlaxWokeUp::
    .string "סנורלאקס התעורר!\n"
    .string "הוא תקף בזעם עצבני!$"

Text_SnorlaxReturnedToMountains::
    .string "סנורלאקס נרגע.\n"
    .string "הוא פיהק יקום ענק…\l"
    .string "וחזר להרים.$"

Text_WantToUsePokeFlute::
    .string "רוצה להשתמש בחליל?$"

Text_PlayedPokeFlute::
    .string "{PLAYER} ניגן בחליל.$"

Route12_Text_NedIntro::
    .string "כן!\n"
    .string "היה לי דג על הקו!$"

Route12_Text_NedDefeat::
    .string "צ'ח!\n"
    .string "רק איזה דג קטן…$"

Route12_Text_NedPostBattle::
    .string "חכה!\n"
    .string "החוט שלי נתפס!$"

Route12_Text_ChipIntro::
    .string "היה סבלני.\n"
    .string "דיג זה משחק של המתנה.$"

Route12_Text_ChipDefeat::
    .string "הדג הזה ברח!$"

Route12_Text_ChipPostBattle::
    .string "עם מוט יותר טוב, הייתי תופס\n"
    .string "פוקימונים טובים יותר…$"

Route12_Text_JustinIntro::
    .string "אני מחפש אבן ירח.\n"
    .string "מצאת אחד?$"

Route12_Text_JustinDefeat::
    .string "איי!$"

Route12_Text_JustinPostBattle::
    .string "הייתי יכול לגרום לפוקימון שלי\n"
    .string "להתפתח עם Mאבן ירח.\l"
    .string "הייתי מנצח אז, אני בטוח.$"

Route12_Text_LucaIntro::
    .string "חשמל זה ההתמחות שלי.\n"
    .string "אני לא מבין כלום בפוקימונים\l"
    .string "מהים, למרות.$"

Route12_Text_LucaDefeat::
    .string "הייתי מנותק!$"

Route12_Text_LucaPostBattle::
    .string "מים מוליכים חשמל, אז אתה\n"
    .string "צריך להכות את פוקימוני הים.$"

Route12_Text_HankIntro::
    .string "הדיג שוטה מול ילד פוקימון!$"

Route12_Text_HankDefeat::
    .string "נגעת יותר מידי!$"

Route12_Text_HankPostBattle::
    .string "אני מניח שאתה טוב במה שאתה אוהב.\n"
    .string "טוב, ניצחת אותי בפוקימונים,\l"
    .string "אבל אתה לא טוב ממני בדיג.$"

Route12_Text_ElliotIntro::
    .string "אני אוהב לדוג, אל תבין אותי לא\n"
    .string "נכון. אבל יהיה טוב אם היה לי גם\l"
    .string "יותר עבודה.$"

Route12_Text_ElliotDefeat::
    .string "זה לא קל…$"

Route12_Text_ElliotPostBattle::
    .string "זה בסדר.\n"
    .string "להפסיד כבר לא מפריע לי.$"

Route12_Text_AndrewIntro::
    .string "מה יש לדוג?\n"
    .string "אף פעם לא יודע מה אתה יכול\l"
    .string "לתפוס!$"

Route12_Text_AndrewDefeat::
    .string "החמצתי את זה!$"

Route12_Text_AndrewPostBattle::
    .string "מה, מגיקארפ?\n"
    .string "אני תופס אותם כל הזמן, ברור.\l"
    .string "אבל, כמה שהם חלשים.$"

Route12_Text_RouteSign::
    .string "דרך 21\n"
    .string "צפון לעיר לאבנדר$"

Route12_Text_SportfishingArea::
    .string "אזור דיג ספורט$"

Route12_Text_JesIntro::
    .string "ג'ס: אם אני אנצח, אני הולך\n"
    .string "להציע נישואין לגיה.$"

Route12_Text_JesDefeat::
    .string "ג'ס: אל תראה לי, למה לא יכולת\n"
    .string "לתת לנו לנצח?$"

Route12_Text_JesPostBattle::
    .string "ג'ס: גיה, סלחי לי,\n"
    .string "אהובתי!$"

Route12_Text_JesNotEnoughMons::
    .string "ג'ס: גיה ואני, נישאר יחד לנצח.\n"
    .string "לא נלחם עד שיהיה לך\l"
    .string "שני פוקימונים משלך.$"

Route12_Text_GiaIntro::
    .string "גיה: היי, ג'ס…\n"
    .string "אם ננצח, אני אתחתן איתך!$"

Route12_Text_GiaDefeat::
    .string "גיה: אה, למה?$"

Route12_Text_GiaPostBattle::
    .string "גיה: ג'ס, אתה מטומטם!\n"
    .string "הרס את זה!$"

Route12_Text_GiaNotEnoughMons::
    .string "גיה: אני לא יכולה להילחם\n"
    .string "בלי ג'ס שלי!\l"
    .string "לא היה לך עוד פוקימון?$"
