SaffronCity_Gym_Text_SabrinaIntro::
    .string "הייתה לי חזון על הגעתך.\p"
    .string "יש לי כוחות על-חושיים מאז\n"
    .string "שהייתי ילדה.\p"
    .string "זה התחיל כש- כפית שהשלכתי\n"
    .string "בטעות התכופפה.\p"
    .string "אני לא אוהבת להילחם, אבל אם\n"
    .string "אתה רוצה, אראה לך את כוחותיי!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "ההפסד הזה מזעזע אותי!\n"
    .string "אבל הפסד הוא הפסד.\p"
    .string "אני מודה, לא עבדתי מספיק קשה\n"
    .string "כדי לנצח.\p"
    .string "הניצחון שלך זיכה אותך ב\n"
    .string "תג ביצת הביצה.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "כוח על-חושי הוא לא משהו שיש רק\n"
    .string "למעט אנשים.\p"
    .string "לכולם יש כוח על-חושי.\n"
    .string "אנשים פשוט לא מבינים את זה.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "תג הביצה מאפשר לפוקימונים\n"
    .string "עד רמה 07 לציית לך.\p"
    .string "פוקימונים חזקים יותר יהפכו\n"
    .string "לפראיים, ויגרמו להתעלם מהוראותיך\l"
    .string "בקרב.\p"
    .string "פשוט אל תעלה את הרמה של\n"
    .string "הפוקימונים שלך יותר מדי כדי למנוע\l"
    .string "את הבעיה הזאת.\p"
    .string "חכה, בבקשה קח את ה-מ”מ הזה איתך.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} קיבל את מ”מ40 מסברינה.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "מ”מ40 הוא מחשבה שקטה.\p"
    .string "זה גורם לפוקימון להתרכז ולהעלות\n"
    .string "את התקפה מיוחדת ואת הגנה מיוחדת.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "התיק שלך מלא בפריטים אחרים.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "סברינה צעירה ממני בהרבה,\n"
    .string "אבל היא זכתה לכבוד שלי.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "לא מספיק טוב!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "בקרב של שווים, מי שיש לו\n"
    .string "את הרצון החזק יותר מנצח.\p"
    .string "אם אתה רוצה לנצח את סברינה,\n"
    .string "התרכז ותניע את עצמך לניצחון.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "הכוח שלנו שלא נראה מפחיד אותך?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "לא ראיתי את זה בא!\p"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "פוקימוני פסיכי מפחדים רק מרוחות\n"
    .string "ומחרקים!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "פוקימונים נראים כמו\n"
    .string "המאמנים שלהם.\p"
    .string "הפוקימונים שלך בטח קשוחים אז!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "ידעתי את זה!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "יש לי עוד הרבה מה ללמוד...\p"
    .string "אני חייבת לשלוט בכוח העל-חושי\l"
	.string"וללמד את זה\n"
    .string "לפוקימונים שלי...$"

SaffronCity_Gym_Text_TyronIntro::
    .string "אתה מבין, נכון?\p"
    .string "שכוח לבד אינו מספיק כדי\n"
    .string "לנצח בעולם הפוקימונים?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "אני לא מאמין לזה!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "סברינה פשוט הביסה את מאסטר\n"
    .string "הקראטה מהדוג'ו שליד.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "אתה ואני, הפוקימונים שלנו יילחמו!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "הפסדתי אחרי הכל!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "ידעתי שזה הולך לקרות.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "סברינה צעירה, אבל היא גם\n"
    .string "המנהיגה המיומנת שלנו.\p"
    .string "לא תגיע אליה בקלות!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "או! הובסתי!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "היו שני מכוני פוקימונים פעם\n"
    .string "בסאפרון.\p"
    .string "הדוג'ו של הלוחמים שליד איבד\n"
    .string "את מעמדו כמכון, אבל.\p"
    .string "פשוט חיסלנו אותם כשהחלטנו על מכון\n"
    .string "אחד.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "מכון הפוקימונים בסאפרון מפורסם\n"
    .string "באימונים של כוח על-חושי.\p"
    .string "אתה רוצה לראות את סברינה, נכון?\n"
    .string "אני יודע!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "אררר!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "נכון! השתמשתי בטלפתיה כדי\n"
    .string "לקרוא את מחשבותיך!$"

SaffronCity_Gym_Text_GymGuyAdvice::
    .string "יו!\n"
    .string "אלוף בדרך!\p"
    .string "הפוקימונים של סברינה משתמשים\n"
    .string "בכוח על-חושי במקום בכוח פיזי.\p"
    .string "פוקימוני קראטה חלשים במיוחד\n"
    .string "נגד פוקימוני פסיכי.\p"
    .string "הם יושמדו לפני שהם\n"
    .string "יצליחו להכות!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
    .string "כוח על-חושי, הא?\p"
    .string "אם היה לי את זה, הייתי עושה הון\n"
    .string "במכונות המזל!$"

SaffronCity_Gym_Text_GymStatue::
    .string "מכון הפוקימונים בסאפרון\n"
    .string "מנהיגה: סברינה\p"
    .string "מאמנים מנצחים:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים בסאפרון\n"
    .string "מנהיגה: סברינה\p"
    .string "מאמנים מנצחים:\n"
    .string "{RIVAL}, {PLAYER}$"
