PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "איזה זקן מפוקפק סחף אותי לקנות\n"
    .string "את הפוקימון הדג המוזר הזה!\p"
    .string "הוא ממש חלש וזה עלה לי ¥005!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "דברים טובים יכולים לקרות אם תגדל\n"
    .string "פוקימונים בהתמדה.\p"
    .string "אפילו החלשים יכולים להפתיע\n"
    .string "אם לא תוותר עליהם.$"
