Text_ExplosionTeach::
    .string "אתה מסוגל לדמיין?\n"
    .string "מה יקרה אם הר הגעש יתפרץ?\p"
    .string "הפיצוץ יהיה הסוף שלנו.\n"
    .string "מפחיד, נכון?\p"
    .string "אז כשאנחנו כבר מפוחדים,\n"
    .string "רוצה שאלמד את המהלך פיצוץ?$"

Text_ExplosionDeclined::
    .string "כן, אתה צודק.\n"
    .string "זה מפחיד מדי.$"

Text_ExplosionWhichMon::
    .string "אתה ממש אמיץ!\p"
    .string "איזה פוקימון ילמד את\n"
    .string "המהלך פיצוץ?$"

Text_ExplosionTaught::
    .string "להשתמש בפיצוץ על הר הגעש\n"
    .string "הזה…\p"
    .string "איזה ריגוש מפחיד!$"

@ Below 4 are unused JP versions of the above texts
Text_ExplosionTeachJP::
    .string "こ　この　かざんが\n"
    .string "もし　だいばくはつ　したら\l"
    .string "お　おれら　ひとたまりも\l"
    .string "ないなあ　‥ブルブル！\p"
    .string "こ　こわい　ついでに\n"
    .string "だいばくはつ　でも　おぼえてみる？$"

Text_ExplosionDeclinedJP::
    .string "や　やっぱ　こわいもんな\n"
    .string "ブルブル$"

Text_ExplosionWhichMonJP::
    .string "つ　つよきだね！\n"
    .string "じゃあ　どの　ポケモンに　する？$"

Text_ExplosionTaughtJP::
    .string "かざんで　だいばくはつを‥\n"
    .string "す　すごい　スリル！$"

MtEmber_Exterior_Text_WellTryDiggingHere::
    .string "בוא הנה.\n"
    .string "ננסה לחפור כאן.\p"
    .string "האוצר שהמפקדים מדברים\n"
    .string "עליו אמור להיות כאן.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
    .string "מה ל…?\n"
    .string "אתה מפריע. תסתלק מכאן.$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
    .string "אוף, סוף סוף פרצנו פנימה.\n"
    .string "קדימה לציד האוצרות!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
    .string "כל אוצר שנמצא מועבר\n"
    .string "בחזרה למחסן, הבנת?\p"
    .string "…אה, ומה הסיסמאות?\n"
    .string "במחסן רוקט, כלומר.$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
    .string "מה, שכחת את הסיסמה?\n"
    .string "יש בעצם שתיים.\p"
    .string "הראשונה היא “גולדין צריך\n"
    .string "בול עץ.”\p"
    .string "והשנייה היא…$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
    .string "היי!\n"
    .string "החטטן הזה מקשיב לנו!$"

MtEmber_Exterior_Text_Grunt1Intro::
    .string "צותת לנו כל הזמן,\n"
    .string "נכון?$"

MtEmber_Exterior_Text_Grunt1Defeat::
    .string "הא, מה?$"

MtEmber_Exterior_Text_Grunt1PostBattle::
    .string "למה היית חייב לנצח?$"

MtEmber_Exterior_Text_Grunt2Intro::
    .string "מנסה להתערב לנו באוצר?\n"
    .string "אל תבנה על זה!$"

MtEmber_Exterior_Text_Grunt2Defeat::
    .string "רגע!\n"
    .string "אבל איך?$"

MtEmber_Exterior_Text_Grunt2PostBattle::
    .string "תחטוף שכחה פתאומית\n"
    .string "ותשכח כל מה ששמעת!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
    .string "איזו נסיגה…\n"
    .string "נצטרך להתארגן מחדש.\p"
    .string "אתה! אל תעז אפילו לחשוב\n"
    .string "להיכנס לכאן!\p"
    .string "אם אתה יודע מה טוב בשבילך,\n"
    .string "אל תחשוב על זה בכלל!$"

MtEmber_Exterior_Text_LoganIntro::
    .string "הר געש פעיל הוא כזה שמתפרץ,\n"
    .string "או עומד להתפרץ.$"

MtEmber_Exterior_Text_LoganDefeat::
    .string "אוף… זה היה חם!\n"
    .string "הזיעה מתפרצת ממני!$"

MtEmber_Exterior_Text_LoganPostBattle::
    .string "אומרים שיש בעולם יותר\n"
    .string "מ-005,1 הרי געש פעילים.\p"
    .string "עצם המחשבה עליהם גורמת לי\n"
    .string "להרגיש חם ונמס מבפנים!$"

MtEmber_Exterior_Text_BethIntro::
    .string "אתה יודע איך נוצרות מערות\n"
    .string "בתוך הרי געש?$"

MtEmber_Exterior_Text_BethDefeat::
    .string "אצ'ה!\n"
    .string "אתה טוב בצורה מדהימה!$"

MtEmber_Exterior_Text_BethPostBattle::
    .string "כשהלבה על פני המאגמה\n"
    .string "מתקשה, והמאגמה שבפנים\l"
    .string "זורמת החוצה, נשארים חללים.$"

MtEmber_Exterior_Text_JocelynIntro::
    .string "התאמנתי כדי לאחות\n"
    .string "את הלב השבור שלי…\p"
    .string "לפחות התחזקתי פיזית!\n"
    .string "הי-יה!$"

MtEmber_Exterior_Text_JocelynDefeat::
    .string "נראה לי שהגזמתי…$"

MtEmber_Exterior_Text_JocelynPostBattle::
    .string "הצורה שבה אתה נלחם\n"
    .string "מזכירה לי את מי שזרק אותי…$"

