SilphCo_7F_Text_HaveMonForSavingUs::
    .string "אה! היי! אתה לא צוות רוקט!\n"
    .string "הגעת להציל אותנו?\l"
    .string "תודה רבה לך!\p"
    .string "אני רוצה שתיקח את הפוקימון הזה\n"
    .string "כדי להציל אותנו.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
    .string "{PLAYER} קיבל לפרס\n"
    .string "מעובד סילף!$"

SilphCo_7F_Text_ExplainLapras::
    .string "זה לפרס.\n"
    .string "הוא פוקימון חכם מאוד.\p"
    .string "שמנו אותו במעבדה שלנו, אבל הוא\n"
    .string "יהיה הרבה יותר טוב איתך.\p"
    .string "אני חושב שתהיה מאמן טוב ללפרס!\p"
    .string "הוא שוחה מצוין.\n"
    .string "הוא ייקח אותך על המים!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
    .string "הבוס של צוות רוקט הלך\n"
    .string "לחדר הישיבות!\p"
    .string "האם הנשיא שלנו בסדר?\n"
    .string "אני דואג.$"

SilphCo_7F_Text_OhNo::
    .string "あ‥　もう　もてないぞ$"

SilphCo_7F_Text_SavedAtLast::
    .string "たすかったよ　ありがと！$"

SilphCo_7F_Text_RocketsAfterMasterBall::
    .string "צוות רוקט רדפו אחרי ה\n"
    .string "מאסטרבול, שתופס כל פוקימון.$"

SilphCo_7F_Text_CanceledMasterBallProject::
    .string "הפסקנו את פרויקט המאסטרבול\n"
    .string "בגלל צוות רוקט.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
    .string "זה יהיה רע אם צוות רוקט\n"
    .string "ישתלטו על ארגון סילף או\p"
	.string "על הפוקימונים שלנו.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
    .string "וואו!\p"
    .string "הצלחת להבריח את צוות רוקט לבד\n"
    .string "ממך?$"

SilphCo_7F_Text_ReallyDangerousHere::
    .string "אתה!\n"
    .string "זה מאוד מסוכן פה!\p"
    .string "הגעת להציל אותי?\n"
    .string "אתה לא יכול!$"

SilphCo_7F_Text_ThankYouSoMuch::
    .string "תודה רבה לך!$"

SilphCo_7F_Text_Grunt3Intro::
    .string "או, לא!\n"
    .string "אני מריח עכבר קטן!$"

SilphCo_7F_Text_Grunt3Defeat::
    .string "הפסקת חשמל!$"

SilphCo_7F_Text_Grunt3PostBattle::
    .string "אתה לא תמצא את הבוס שלי רק\n"
    .string "על ידי חיפוש מהיר!$"

SilphCo_7F_Text_JoshuaIntro::
    .string "ההה!\p"
    .string "טעיתם לחשוב שאני עובד ארגון סילף?$"

SilphCo_7F_Text_JoshuaDefeat::
    .string "אני גמור!$"

SilphCo_7F_Text_JoshuaPostBattle::
    .string "למרות גילך, אתה מאמן\n"
    .string "מיומן!$"

SilphCo_7F_Text_Grunt1Intro::
    .string "אני אחד מ4 האחים של צוות רוקט!\n"
    .string "$"

SilphCo_7F_Text_Grunt1Defeat::
    .string "אהה!\n"
    .string "אחים, אני הפסדתי!$"

SilphCo_7F_Text_Grunt1PostBattle::
    .string "לא משנה.\n"
    .string "האחים שלי ינצחו אותי!$"

SilphCo_7F_Text_Grunt2Intro::
    .string "ילד פולש?\n"
    .string "זה בטח אתה!$"

SilphCo_7F_Text_Grunt2Defeat::
    .string "טוב!\n"
    .string "הפסדתי!$"

SilphCo_7F_Text_Grunt2PostBattle::
    .string "לך הביתה לפני שהבוס שלי\n"
    .string "יתעצבן!$"

SilphCo_7F_Text_RivalWhatKeptYou::
    .string "{RIVAL}: מה לקח לך כל כך הרבה\n"
    .string "זמן, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
    .string "{RIVAL}: חחח! חשבתי שתגיע אם\n"
    .string "אחכה פה!\p"
    .string "נראה שצוות רוקט האטו אותך\n"
    .string "אבל אני לא אכפת לי!\p"
    .string "ראיתי אותך בסאפרון, אז החלטתי\n"
    .string "לראות אם השתפרת!$"

SilphCo_7F_Text_RivalDefeat::
    .string "אה, לא!\n"
    .string "אז אתה מוכן לבוס\l"
    .string "של צוות רוקט!$"

SilphCo_7F_Text_RivalVictory::
    .string "{RIVAL}“おまえなあ‥\p"
    .string "こんな　うでまえじゃ\n"
    .string "まだまだ‥\l"
    .string "いちにんまえ　とは　いえないぜ$"

SilphCo_7F_Text_RivalPostBattle::
    .string "ובכן, {PLAYER}!\n"
    .string "אני עולה וממשיך!\p"
    .string "אני בודק את הפוקידקס שלי, ואני\n"
    .string "מתחיל לראות מה חזק ואיך הם\l"
    .string "מתפתחים!\p"
    .string "אני גאון או לא?\p"
    .string "אני הולך לליגה של פוקימון כדי\n"
    .string "להעיף את הארבעה האליטה.\p"
    .string "אני אהיה מאמן החזק ביותר בעולם!\p"
    .string "{PLAYER}, טוב, בהצלחה לך!\n"
    .string "אל תדאג!\l"
    .string "נתראה!$"

SilphCo_7F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 7$"
