SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
    .string "הרה, הרה, הרקרוס!\n"
    .string "גדול ומבריק, מלך החרקים!\l"
    .string "אוהבת, חייבת, הרקרוס!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
    .string "אייייי!\n"
    .string "זה הרקרוס!\p"
    .string "בבקשה, בבקשה, אפשר למדוד\n"
    .string "כמה הוא גדול?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
    .string "אייי, זה {STR_VAR_2} אינץ'!\n"
    .string "מעולם לא ראיתי דבר כזה!\l"
    .string "מגיע לך פרס!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
    .string "אני רוצה לראות הרקרוס הרבה\n"
    .string "הרבה יותר גדול מזה.\p"
    .string "אוי, כמה שאני מעריצה\n"
    .string "הרקרוסים גדולים!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
    .string "הא? המדידה הזאת, {STR_VAR_2} אינץ'…\n"
    .string "אוף! זה בדיוק כמו קודם.$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
    .string "אוי, זה רק {STR_VAR_2} אינץ'.\n"
    .string "ההרקרוס הקודם היה גדול יותר.\p"
    .string "הוא היה {STR_VAR_3} אינץ', הכי גדול\n"
    .string "שהבאת לי אי פעם.$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
    .string "אוי, לא! זה לא מתאים!\p"
    .string "הרקרוס נראה הרבה יותר שרירי\n"
    .string "וקשוח, ויש לו קרן מהממת!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
    .string "התיק שלך מלא.\n"
    .string "הפרס שלי לא ייכנס.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
    .string "ההרקרוס הכי גדול שמדדתי\n"
    .string "עד עכשיו הוא:\p"
    .string "{STR_VAR_3} אינץ'!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
    .string "זו איזושהי טבלה ריקה.\p"
    .string "יש בה מקום לרשום\n"
    .string "שיאים מסוג כלשהו.$"

