ViridianCity_Gym_Text_GiovanniIntro::
    .string "פואהאהא! זה\n"
    .string "המחבוא שלי!\p"
    .string "תכננתי להחיות את צוות רוקט כאן!\p"
    .string "אבל, אתה תפסת אותי שוב!\l"
    .string "כך יהיה! הפעם אני מסיר את כל\l"
    .string "המעברוקים!\p"
    .string "פעם נוספת, אתה תתמודד מול\l"
    .string "ג'ובאני, המאמן החזק מכולם!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

ViridianCity_Gym_Text_GiovanniDefeat::
    .string "הא!\n"
    .string "זה באמת היה קרב רציני! ניצחת!\l"
    .string "כהוכחה, קבל את תג האדמה!"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
    .string "לאחר שהובסתי,\n"
    .string "אני לא יכול להסתכל לפקודיי!\l"
    .string "בעיניים! צוות רוקט חוסל לנצח!\p"
    .string "אקדיש את חיי ללימודי פוקימונים!\p"
    .string "הבה נתראה שוב ביום מן הימים!\l"
    .string "להתראות!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
    .string "תג האדמה\n"
    .string "גורם לפוקימונים מכל הרמות לציית!\p"
    .string "זו הוכחה להיותך מאמן\l"
    .string "פוקימונים מומחה!\p"
    .string "עם זה, אתה יכול להכנס\l"
    .string "לליגת הפוקימונים!\p"
    .string "זו מתנתי לרגל האתגר הבא שלך,\l"
    .string "ליגת הפוקימונים!$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
    .string "{PLAYER} קיבל\n"
    .string "מ”מ62!$"

ViridianCity_Gym_Text_ExplainTM26::
    .string "מ”מ62 מכיל את רעש אדמה!\n"
    .string "מתקפה עוצמתית שגורמת לרעידה אדירה!\p"
    .string "הכנתי את זה בזמן שהייתי מנהל\l"
    .string "המכון כאן, לפני יותר מדי זמן...$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
    .string "אין לך מספיק\n"
    .string "מקום לזה!$"

ViridianCity_Gym_Text_YujiIntro::
    .string "הא! בטח נגמר\n"
    .string "לך הקיטור עד עכשיו!$"

ViridianCity_Gym_Text_YujiDefeat::
    .string "נגמר\n"
    .string "לי הדלק!\p$"

ViridianCity_Gym_Text_YujiPostBattle::
    .string "אתה צריך אנרגיה\n"
    .string "כדי לעמוד מול מנהל המכון!$"

ViridianCity_Gym_Text_AtsushiIntro::
    .string "רררואר! אני\n"
    .string "בונה בתוכי זעם!$"

ViridianCity_Gym_Text_AtsushiDefeat::
    .string "ווארג!\p$"

ViridianCity_Gym_Text_AtsushiPostBattle::
    .string "אני עדיין לא\n"
    .string "ראוי!$"

ViridianCity_Gym_Text_JasonIntro::
    .string "פוקימונים ואני,\n"
    .string "מייצרים מוזיקה נבילת ביחד!$"

ViridianCity_Gym_Text_JasonDefeat::
    .string "אתם\n"
    .string "בהרמוניה מושלמת!\p$"

ViridianCity_Gym_Text_JasonPostBattle::
    .string "אתה יודע\n"
    .string "מיהו מנהל המכון?$"

ViridianCity_Gym_Text_KiyoIntro::
    .string "קרטה היא אמנות\n"
    .string "הלחימה הטובה ביותר!$"

ViridianCity_Gym_Text_KiyoDefeat::
    .string "אפצ'י!\p$"

ViridianCity_Gym_Text_KiyoPostBattle::
    .string "אילו רק הפוקימונים\n"
    .string "שלי היו טובים בקראטה כמוני...$"

ViridianCity_Gym_Text_WarrenIntro::
    .string "למאמן המוכשר באמת,\n"
    .string "יש סגנון בקרב!$"

ViridianCity_Gym_Text_WarrenDefeat::
    .string "איבדתי\n"
    .string "אחיזה!\p$"

ViridianCity_Gym_Text_WarrenPostBattle::
    .string "המנהל יגער בי!$"

ViridianCity_Gym_Text_TakashiIntro::
    .string "אני מלך הקרטה!\n"
    .string "גורלך טמון בי!$"

ViridianCity_Gym_Text_TakashiDefeat::
    .string "איה!\p$"

ViridianCity_Gym_Text_TakashiPostBattle::
    .string "ליגת הפוקימונים?\n"
    .string "אתה? אל תתבליין!$"

ViridianCity_Gym_Text_ColeIntro::
    .string "הפוקימון שלך ישתפן\n"
    .string "ברגע שאצליף בו בו השוט שלי!$"

ViridianCity_Gym_Text_ColeDefeat::
    .string "יאוץ'!\n"
    .string "הצלפת!\p$"

ViridianCity_Gym_Text_ColePostBattle::
    .string "חכה! סתם הייתי\n"
    .string "פזיז!$"

ViridianCity_Gym_Text_SamuelIntro::
    .string "מכון ורידיאן היה\n"
    .string "סגור הרבה זמן, אבל עכשיו המנהל\l"
    .string "שלנו חזר!$"

ViridianCity_Gym_Text_SamuelDefeat::
    .string "הובסתי?\p$"

ViridianCity_Gym_Text_SamuelPostBattle::
    .string "אתה יכול להמשיך\n"
    .string "לליגת הפוקימונים על ידי הבסת\l"
    .string "מנהל המכון שלנו!$"

ViridianCity_Gym_Text_GymGuyAdvice::
    .string "יו! אלוף חדש\n"
    .string "בדרך!\p"
    .string "אפילו אני לא יודע מיהו מנהל\l"
    .string "מכון ורידיאן!\p"
    .string "זה יהיה הקרב הקשוח ביותר מבין\l"
    .string "כל מנהלי המכונים!\p"
    .string "שמעתי שהמאמנים כאן אוהבים\l"
    .string "פוקימוני אדמה!$"

ViridianCity_Gym_Text_GymGuyPostVictory::
    .string "לא נכון!\n"
    .string "ג'ובאני היה מנהיג המכון של העיר?$"

ViridianCity_Gym_Text_GymStatue::
    .string "מכון הפוקימונים ורידיאן\n"
    .string "מנהיג: ?\p"
    .string "מאמנים שניצחו: {RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים ורידיאן\n"
    .string "מנהיג: ?\p"
    .string "מאמנים שניצחו: {RIVAL}, {PLAYER}$"
