RocketHideout_B1F_Text_Grunt1Intro::
    .string "מי אתה?\n"
    .string "איך הגעת לכאן?$"

RocketHideout_B1F_Text_Grunt1Defeat::
    .string "אוי!\n"
    .string "הובסתי!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
    .string "לעזאזל... אתה מזלזל בצוות\n"
    .string "רוקט, נכון?$"

RocketHideout_B1F_Text_Grunt2Intro::
    .string "פרצת למבצע של צוות רוקט?\n"
    .string "איזה חוצפה!$"

RocketHideout_B1F_Text_Grunt2Defeat::
    .string "בום!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
    .string "אתה לא תצא מזה,\n"
    .string "ילדון!$"

RocketHideout_B1F_Text_Grunt3Intro::
    .string "התראת פולש!$"

RocketHideout_B1F_Text_Grunt3Defeat::
    .string "אני לא יכול!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
    .string "משקפת סילף? חה!\n"
    .string "אני לא יודע איפה זה.$"

RocketHideout_B1F_Text_Grunt4Intro::
    .string "למה באת לכאן?$"

RocketHideout_B1F_Text_Grunt4Defeat::
    .string "זה לא יעבוד!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
    .string "בסדר, אני אדבר... קח את המעלית כדי\n"
    .string "לראות את הבוס שלי.$"

RocketHideout_B1F_Text_Grunt5Intro::
    .string "האם הלכת לאיבוד, עכבר קטן?$"

RocketHideout_B1F_Text_Grunt5Defeat::
    .string "למה...?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
    .string "אוי לא, הרעש הזה איכשהו פתח\n"
    .string "את הדלת!$"
