SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
    .string "אני לא מצליח להבין איך\n"
    .string "נכנסים לשם.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
    .string "שתדע לך, אני מצאתי את\n"
    .string "המקום הזה.\p"
    .string "אל תסתכל עליי בקנאה, טוב?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
    .string "הדלת לא זזה בכלל.\n"
    .string "לבדוק אותה ביסודיות?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
    .string "{PLAYER} הניח לדלת.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
    .string "במבט מקרוב, יש כמה\n"
    .string "נקודות על הדלת…$"

SixIsland_RuinValley_Text_DoorIsOpen::
    .string "הדלת נפתחה.$"

SixIsland_RuinValley_Text_StanlyIntro::
    .string "נראה שיש עוד הרבה סודות\n"
    .string "לא פתורים בעולם הזה.$"

SixIsland_RuinValley_Text_StanlyDefeat::
    .string "הממ…$"

SixIsland_RuinValley_Text_StanlyPostBattle::
    .string "אני ממליץ שגם אתה תחשוב\n"
    .string "פעם ביום על הסודות\l"
    .string "והתעלומות של העולם שלנו.$"

SixIsland_RuinValley_Text_FosterIntro::
    .string "מעניין אותי, מה גרם לך\n"
    .string "לבוא לכאן?$"

SixIsland_RuinValley_Text_FosterDefeat::
    .string "עבר כל כך הרבה זמן מאז\n"
    .string "שנלחמתי, החושים שלי קהו.$"

SixIsland_RuinValley_Text_FosterPostBattle::
    .string "יש כמה חורבות\n"
    .string "באיי סבי.\p"
    .string "רובן מתוארכות לתקופה\n"
    .string "רחוקה מאוד.$"

SixIsland_RuinValley_Text_LarryIntro::
    .string "אומרים שיש אבנים מסתוריות\n"
    .string "באי הזה.\p"
    .string "אני חושד שזה קשור\n"
    .string "לחורבות שכאן.$"

SixIsland_RuinValley_Text_LarryDefeat::
    .string "אה, מעניין.$"

SixIsland_RuinValley_Text_LarryPostBattle::
    .string "החורבות ההן שם…\p"
    .string "לא הצלחתי למצוא שום דרך\n"
    .string "להיכנס פנימה.$"

SixIsland_RuinValley_Text_DarylIntro::
    .string "קרב איתך, כל כך גבוה למעלה!$"

SixIsland_RuinValley_Text_DarylDefeat::
    .string "אוי, כמה כואב להפסיד לך\n"
    .string "כל כך בקלות!$"

SixIsland_RuinValley_Text_DarylPostBattle::
    .string "תחווה את השמחה שבטיפוס!$"

SixIsland_RuinValley_Text_HectorIntro::
    .string "אני מכיר די טוב את השטח\n"
    .string "באזור הזה.$"

SixIsland_RuinValley_Text_HectorDefeat::
    .string "אתה לא צריך ללחוץ עליי ככה.\n"
    .string "אני אשמח לספר לך.$"

SixIsland_RuinValley_Text_HectorPostBattle::
    .string "הדלת של החורבות…\n"
    .string "יש עליה תבניות מוזרות\l"
    .string "חרוטות מבחוץ.\p"
    .string "אבל אני לא יודע\n"
    .string "מה הן אומרות.$"
