VictoryRoad_2F_Text_DawsonIntro::
    .string "אם אתה יכול לעבור כאן, אתה יכול\n"
    .string "ללכת לפגוש את רבעיית העילית.$"

VictoryRoad_2F_Text_DawsonDefeat::
    .string "לא!\n"
    .string "לא ייאמן!$"

VictoryRoad_2F_Text_DawsonPostBattle::
    .string "אני יכול לנצח אותך כשמדובר ב\n"
    .string "ידע על פוקימונים!$"

VictoryRoad_2F_Text_DaisukeIntro::
    .string "זהו זה- דרך הניצחון.\n"
    .string "זהו המבחן האחרון למאמנים!$"

VictoryRoad_2F_Text_DaisukeDefeat::
    .string "אטצ'ו!$"

VictoryRoad_2F_Text_DaisukePostBattle::
    .string "אם תיתקע, נסה להזיז כמה\n"
    .string "סלעים מסביב.$"

VictoryRoad_2F_Text_NelsonIntro::
    .string "אה, אז אתה רוצה לאתגר את\n"
    .string "רבעיית העילית?$"

VictoryRoad_2F_Text_NelsonDefeat::
    .string "תפסת אותי!$"

VictoryRoad_2F_Text_NelsonPostBattle::
    .string "{RIVAL} גם עבר כאן.$"

VictoryRoad_2F_Text_VincentIntro::
    .string "בוא!\n"
    .string "אני אכה אותך!$"

VictoryRoad_2F_Text_VincentDefeat::
    .string "היכיתי!$"

VictoryRoad_2F_Text_VincentPostBattle::
    .string "הרווחת את הזכות להיות על\n"
    .string "דרך הניצחון…$"

VictoryRoad_2F_Text_GregoryIntro::
    .string "האם דרך הניצחון קשה מדי?$"

VictoryRoad_2F_Text_GregoryDefeat::
    .string "עבודה טובה!$"

VictoryRoad_2F_Text_GregoryPostBattle::
    .string "הרבה מאמנים מוותרים על\n"
    .string "האתגר כאן וחוזרים הביתה.$"

@ Unused, old text for Moltres
VictoryRoad_2F_Text_Gyaoo::
    .string "ギヤーオ！$"
