SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
    .string "הספארי זון עצום, לא תגיד?\p"
    .string "מנהיג מכון פושיה, קוגה,\n"
    .string "פוקד את האזור מדי פעם.\p"
    .string "בזכותו, אנחנו יכולים לשחק כאן\n"
    .string "ודעתנו שכולנו בטוחים.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
    .string "השלכת אבנים על פוקימונים עשויה\n"
    .string "לגרום להם לברוח, אבל הם יהיו\l"
    .string "קל יותר לתפוס.$"

SafariZone_West_Text_BaitMakesMonStickAround::
    .string "השתמש במזון כדי לגרום לפוקימונים\n"
    .string "להישאר קרוב אם הם עסוקים באכילה.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
    .string "הלכתי הרבה, אבל לא ראיתי\n"
    .string "פוקימונים שרציתי.$"
