SSAnne_Deck_Text_ShipDepartingSoon::
    .string "המסיבה נגמרה.\n"
    .string "הספינה תצא בקרוב.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
    .string "פיו!\n"
    .string "שפשוף הסיפון זה עבודה קשה!$"

SSAnne_Deck_Text_FeelSeasick::
    .string "אורפ… אני מרגיש חולה…\p"
    .string "היה לי מחלת ים, אז יצאתי\n"
    .string "לקחת קצת אוויר…$"

SSAnne_Deck_Text_EdmondIntro::
    .string "היי, חבר!\p"
    .string "בוא נרקוד קצת!$"

SSAnne_Deck_Text_EdmondDefeat::
    .string "אתה מרשים!$"

SSAnne_Deck_Text_EdmondPostBattle::
    .string "כמה סוגי פוקימונים אתה חושב\n"
    .string "שיש בעולם הגדול הזה?$"

SSAnne_Deck_Text_TrevorIntro::
    .string "אהוי, שם!\n"
    .string "יש לך מחלת ים?$"

SSAnne_Deck_Text_TrevorDefeat::
    .string "פשוט הייתי רשלני!$"

SSAnne_Deck_Text_TrevorPostBattle::
    .string "אבא שלי אמר שיש 001 סוגי\n"
    .string "פוקימונים. אני חושב שיש יותר.$"
