FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
    .string "לורליי: תורידו את הידיים\n"
    .string "המלוכלכות מפוקימוני המערה!\p"
    .string "תעשו מה שאני אומרת, אחרת\n"
    .string "תתמודדו איתי!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
    .string "אווו, תשתקי, גברת, ותעזבי\n"
    .string "אותנו בשקט.\p"
    .string "שלא יתאדו לך המשקפיים\n"
    .string "מרוב עצבים!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
    .string "לורליי: {PLAYER}?!\n"
    .string "מה אתה עושה כאן?\p"
    .string "לא, נשלים פערים אחר-כך.\n"
    .string "כרגע אני צריכה את עזרתך.\p"
    .string "עזור לי לגרש את הציידים האלה\n"
    .string "לפני שיעשו עוד נזק.\p"
    .string "הם תופסים כאן פוקימונים\n"
    .string "ואז מוכרים אותם!\p"
    .string "אתה מוכן?\n"
    .string "אתה תטפל בזה שם, בבקשה!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
    .string "מ-מה?!\p"
    .string "מי אמר שאסור לנו לעשות מה\n"
    .string "שבא לנו עם הפוקימונים שתפסנו?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
    .string "לא תכננו את זה!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
    .string "לורליי: פחח.\n"
    .string "חלשים באופן מחפיר.\p"
    .string "אתה!\n"
    .string "תגיד לי!\p"
    .string "לאן לקחתם את הפוקימונים\n"
    .string "שתפסתם?\p"
    .string "אני שמה סוף לכנופיה שלכם\n"
    .string "אחת ולתמיד!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
    .string "ב-בחיים לא!\n"
    .string "אני לא מספר לך את זה!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
    .string "לורליי: אם לא תדבר,\n"
    .string "נקפיא אותך לגמרי.\p"
    .string "הלפרס שלי זועם על מה\n"
    .string "שעשיתם לחברים שלו.\p"
    .string "קדימה, לפרס!\n"
    .string "קרן קרח…$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
    .string "וואאה! בסדר!\n"
    .string "אני אדבר!\p"
    .string "הפוקימונים נמצאים במחסן\n"
    .string "רוקט שבאי 5.\p"
    .string "הנה! אמרתי את זה!\n"
    .string "אנחנו הולכים עכשיו!\p"
    .string "…אבל אני בספק אם תצליח\n"
    .string "בכלל להיכנס למחסן רוקט!\p"
    .string "חהחהחהחה!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
    .string "{PLAYER}, תודה לך.\n"
    .string "אבל זה נורא…\p"
    .string "נולדתי וגדלתי כאן,\n"
    .string "באיים האלה.\p"
    .string "לא היה לי מושג שהפושעים\n"
    .string "הנוראיים האלה משוטטים כאן…$"

