SSAnne_2F_Room2_Text_BrooksIntro::
    .string "התחרות מול הצעירים\n"
    .string "שומרת עליי צעיר.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
    .string "קרב טוב!\n"
    .string "אה, אני מרגיש צעיר שוב!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
    .string "לפני 51 שנה, הייתי\n"
    .string "מנצח!$"

SSAnne_2F_Room2_Text_DaleIntro::
    .string "תראה מה דגתי!$"

SSAnne_2F_Room2_Text_DaleDefeat::
    .string "נגמרו לי!$"

SSAnne_2F_Room2_Text_DalePostBattle::
    .string "מסיבה?\p"
    .string "המסיבה בספינת התענוגות\n"
    .string "כנראה כבר הסתיימה.$"
