FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
    .string "לורליי: יש משהו שמעיק\n"
    .string "עליי מאוד.\p"
    .string "אם יקרה משהו באי\n"
    .string "שבו נולדתי…\p"
    .string "לא אדע על כך בכלל אם אהיה\n"
    .string "בליגת הפוקימון.\p"
    .string "אני תוהה אם זה הופך אותי\n"
    .string "לחסרת אחריות כלפי הבית שלי…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
    .string "לורליי: אז הצלחת לפתור את\n"
    .string "כל הבעיות כאן?\p"
    .string "זה נפלא.\p"
    .string "זה אומר שאין שום סיבה שאני\n"
    .string "אהיה כאן כל הזמן.\p"
    .string "תודה לך…\p"
    .string "אני אחזור לליגת הפוקימון\n"
    .string "בעוד זמן קצר.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
    .string "אני לא יודעת מה יקרה\n"
    .string "בעתיד, אבל…\p"
    .string "אני אעשה מה שאני יכולה כאן\n"
    .string "ועכשיו. זה כל מה שאפשר.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
    .string "שפע של בובות פוקימון ממולאות!$"

