Route4_Text_TrippedOverGeodude::
    .string "איי! מעדתי על פוקימון סלעי,\n"
    .string "גיאודוד!$"

Route4_Text_CrissyIntro::
    .string "באתי להר הירח בחיפוש אחר\n"
    .string "פוקימון פטריות.$"

Route4_Text_CrissyDefeat::
    .string "אחרי כל מה שעשיתי כדי לתפוס אותם!$"

Route4_Text_CrissyPostBattle::
    .string "אולי אין כאן יותר פטריות.\p"
    .string "אני חושבת שתפסתי את כולן.$"

Route4_Text_MtMoonEntrance::
    .string "הר הירח\n"
    .string "כניסה למנהרה$"

Route4_Text_RouteSign::
    .string "דרך 4\n"
    .string "הר הירח - עיר סרוליאן$"

Text_MegaPunchTeach::
    .string "מכה של עוצמה שאגה!\p"
    .string "מלאה בכוח הרסני!\p"
    .string "כשאתה במצב רע,\n"
    .string "מגה פאנץ' הוא ההתקפה האולטימטיבית!\l"
    .string "אתה מסכים, נכון?\p"
    .string "עכשיו!\n"
    .string "תן לי ללמד אותה לפוקימון שלך!$"

Text_MegaPunchDeclined::
    .string "תחזור כשתבין את הערך של מגה פאנץ'.$"

Text_MegaPunchWhichMon::
    .string "בסדר!\n"
    .string "איזה פוקימון ילמד אותו?$"

Text_MegaPunchTaught::
    .string "עכשיו, אנחנו חברים בדרך של\n"
    .string "אגרוף!\p"
    .string "אתה צריך ללכת לפני שיראה אותך\n"
    .string "השוטה שמאמין רק בבעיטות הטיפשיות\l"
    .string "שלו שם.$"

Text_MegaKickTeach::
    .string "בעיטה של עוצמה פראית!\p"
    .string "מלאה בכוח הרסני!\p"
    .string "כשאתה במצב רע,\n"
    .string "מגה קיק הוא ההתקפה האולטימטיבית!\l"
    .string "אתה מסכים, נכון?\p"
    .string "בסדר!\n"
    .string "אני אלמד אותה לפוקימון שלך!$"

Text_MegaKickDeclined::
    .string "תחזור כשתבין את הערך של מגה קיק.$"

Text_MegaKickWhichMon::
    .string "בסדר!\n"
    .string "איזה פוקימון רוצה ללמוד אותו?$"

Text_MegaKickTaught::
    .string "עכשיו, אנחנו בני ברית בדרך\n"
    .string "של בעיטה!\p"
    .string "אתה צריך לרוץ לפני שיראה אותך\n"
    .string "השוטה שמאמין רק באגרופים הפשוטים\l"
    .string "שלו שם.$"

Route4_Text_PeopleLikeAndRespectBrock::
    .string "וואו, זה תג הסלע!\n"
    .string "קיבלת אותו מברוק, נכון?\p"
    .string "ברוק מגניב. הוא לא רק חזק.\n"
    .string "אנשים אוהבים ומכבדים אותו.\p"
    .string "אני רוצה להיות מנהיג מכון\n"
    .string "כמוהו.$"
