VermilionCity_Text_GrimerMultipliesInSludge::
    .string "אנחנו זהירים לגבי זיהום כאן.\p"
    .string "שמענו שגריימר מתרבה בבוצה רעילה.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
    .string "ראית את הס.ס. אן עוגנת בנמל?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
    .string "אז הס.ס. אן הפליגה?\p"
    .string "היא תחזור לורמיליון בערך בתקופה\n"
    .string "הזו בשנה הבאה.$"

VermilionCity_Text_BuildingOnThisLand::
    .string "אני מקים בניין על השטח הזה.\n"
    .string "הוא כולו בבעלותי.\p"
    .string "הפוקימון שלי מהדק את הקרקע\n"
    .string "כדי להכין את היסודות.$"

VermilionCity_Text_Machop::
    .string "מאצ'ופ: גרוה! גוגוגוה!$"

VermilionCity_Text_MachopStompingLandFlat::
    .string "מאצ'ופ מהדק את הקרקע.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
    .string "הס.ס. אן היא אוניית קרוז יוקרתית\n"
    .string "ומפורסמת.\p"
    .string "היא מבקרת בורמיליון פעם בשנה.$"

VermilionCity_Text_CitySign::
    .string "עיר ורמיליון\n"
    .string "נמל השקיעות המרשימות$"

VermilionCity_Text_SnorlaxBlockingRoute12::
    .string "הודעה!\p"
    .string "ייתכן שדרך 21 חסומה על ידי\n"
    .string "פוקימון ישן.\p"
    .string "עיקוף דרך מערת רוק לעיר לבנדר.\p"
    .string "משטרת ורמיליון$"

VermilionCity_Text_PokemonFanClubSign::
    .string "מועדון מעריצי פוקימון\n"
    .string "כל חובבי הפוקימון מוזמנים!$"

VermilionCity_Text_GymSign::
    .string "מכון פוקימון ורמיליון\n"
    .string "מנהיג: לוטננט סרג'\l"
    .string "האמריקאי החשמלי!$"

VermilionCity_Text_VermilionHarbor::
    .string "נמל ורמיליון$"

VermilionCity_Text_WelcomeToTheSSAnne::
    .string "ברוכים הבאים לס.ס. אן!$"

VermilionCity_Text_DoYouHaveATicket::
    .string "ברוכים הבאים לס.ס. אן!\p"
    .string "סלח לי, יש לך כרטיס?$"

VermilionCity_Text_FlashedSSTicket::
    .string "{FONT_NORMAL}{PLAYER} הראה את כרטיס הס.ס. אן!\p"
    .string "{FONT_MALE}נהדר!\n"
    .string "ברוך הבא לס.ס. אן!$"

VermilionCity_Text_DontHaveNeededSSTicket::
    .string "ל{FONT_NORMAL}{PLAYER} אין את כרטיס הס.ס. אן\n"
    .string "הדרוש.\p"
    .string "{FONT_MALE}סליחה!\p"
    .string "צריך כרטיס כדי לעלות לסיפון.$"

VermilionCity_Text_TheShipSetSail::
    .string "האונייה הפליגה.$"

VermilionCity_Text_BoardSeagallopTriPass::
    .string "אה, יש לך את כרטיס המעבר המשולש.\p"
    .string "רוצה לעלות למעבורת סיגאלופ?$"

VermilionCity_Text_Seagallop7Departing::
    .string "בסדר, הכול מסודר.\p"
    .string "מעבורת סיגאלופ המהירה 7 תצא\n"
    .string "מיידית.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
    .string "אה, יש לך את כרטיס הקשת.\p"
    .string "רוצה לעלות למעבורת סיגאלופ?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
    .string "וואו! זה כרטיס מיסטי!\n"
    .string "זה נדיר מאוד.\p"
    .string "נשמח לקחת אותך ל-נמל האבן בכל עת.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
    .string "וואו! זה כרטיס אורורה!\n"
    .string "זה נדיר מאוד.\p"
    .string "נשמח לקחת אותך ל-אי הנולד בכל עת.$"

VermilionCity_Text_BoardSeagallopFerry::
    .string "רוצה לעלות למעבורת סיגאלופ?$"

VermilionCity_Text_Seagallop10Departing::
    .string "בסדר, הכול מסודר לך\n"
    .string "לעלות למעבורת מיוחדת.\p"
    .string "מעבורת סיגאלופ המהירה 01 תצא\n"
    .string "מיידית.$"

VermilionCity_Text_Seagallop12Departing::
    .string "בסדר, הכול מסודר לך\n"
    .string "לעלות למעבורת מיוחדת.\p"
    .string "מעבורת סיגאלופ המהירה 21 תצא\n"
    .string "מיידית.$"

VermilionCity_Text_Route2AideHasPackageForYou::
    .string "או, שלום, {PLAYER}!\n"
    .string "מה שלומך?\p"
    .string "זה אני, אחד מהעוזרים של פרופ' אוק.\p"
    .string "פגשת את העוזר השני?\p"
    .string "הוא אמר שיש לו חבילה מפרופ' אוק\n"
    .string "בשבילך, {PLAYER}.\p"
    .string "הוא אמר שיחפש אותך באזור דרך 2,\n"
    .string "{PLAYER}.\p"
    .string "אם אתה באזור דרך 2,\n"
    .string "בבקשה חפש אותו.$"
