@ All Trainer Tower text (Lobby and Roof) is interleaved here

TrainerTower_Lobby_Text_WelcomeToTrainerTower::
    .string "שלום!\p"
    .string "ברוך הבא למגדל המאמנים,\n"
    .string "שאליו נוהרים מאמנים מכל מקום!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
    .string "מאמנים מכל העולם\n"
    .string "מתאספים כאן לקרבות.\p"
    .string "רגע, בואו נראה…\p"
    .string "כרגע יש כאן מאמנים רק\n"
    .string "עד קומה {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
    .string "מאמנים מחכים לאתגר שלך\n"
    .string "עד הקומה השמינית.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
    .string "רוצה להתמודד מול\n"
    .string "המאמנים שמחכים?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
    .string "אוקיי, אני מפעילה את השעון,\n"
    .string "אז תן את כל כולך.\p"
    .string "למקומות…\p"
    .string "היכון…\p"
    .string "צא!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
    .string "תבוא לבקר אותנו שוב!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
    .string "חבל מאוד.\p"
    .string "אני חושבת שהשקעת מאמץ\n"
    .string "אדיר בקרבות שלך.\p"
    .string "בבקשה תחזור ותנסה שוב!$"

TrainerTower_Lobby_Text_GiveItYourBest::
    .string "אני מקווה שתיתן את המיטב.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
    .string "כשהמאמנים מתחלפים במקומות,\n"
    .string "נוצרת כאן צפיפות גדולה.\p"
    .string "כדי להימנע מהמהומה העברנו\n"
    .string "את דלפק הקבלה לכאן.\p"
    .string "אני מתנצלת על אי הנוחות.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
    .string "שלום…\p"
    .string "אני הבעלים של המגדל הזה…\p"
    .string "איך שהשמיים נוסקים מעל\n"
    .string "הגג הזה…\p"
    .string "וליטוף הרוחות כאן למעלה…\p"
    .string "הכל כל כך מושלם…\p"
    .string "והדרך שבה נלחמת…\n"
    .string "גם היא הייתה מושלמת…$"

TrainerTower_Roof_Text_ThisIsForYou::
    .string "זה בשבילך…$"

TrainerTower_Roof_Text_DoneItInRecordTime::
    .string "הו!\n"
    .string "מדהים!\p"
    .string "נפלא איך שהגעת לכאן\n"
    .string "במהירות כזאת.\p"
    .string "למען האמת, עשית את זה\n"
    .string "בזמן שיא…\p"
    .string "אדאג שהשיא שלך יירשם\n"
    .string "אצל דלפק הקבלה.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
    .string "נדמה לי שלקחת את הזמן\n"
    .string "בדרך לכאן…$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
    .string "מה שהייתי רוצה לראות זה\n"
    .string "זמן טוב יותר ממך…\p"
    .string "אני סומך עליך.\p"
    .string "עד אז, להתראות…$"

TrainerTower_Text_XMinYZSec::
    .string "{STR_VAR_1}דק' {STR_VAR_3}.{STR_VAR_2}שנ'$"

TrainerTower_Lobby_Text_HereAreTheResults::
    .string "せいせきひょうです$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
    .string "זהו קרב שניים על שניים.\p"
    .string "אי אפשר להילחם בלי\n"
    .string "לפחות שני פוקימונים.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
    .string "כאן במגדל המאמנים יש\n"
    .string "אירוע שנקרא מרוץ נגד הזמן.\p"
    .string "נמדוד כמה מהר תצליח להגיע\n"
    .string "מדלפק הקבלה אל הבעלים\l"
    .string "שעל הגג.\p"
    .string "הזמנים הטובים ביותר יירשמו\n"
    .string "על לוח הזמנים.\p"
    .string "נסה להתחרות עם חברים ולראות\n"
    .string "מי מסיים הכי מהר.\p"
    .string "לא תקבל כאן נקודות נסיון\n"
    .string "או כסף על ניצחונות.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
    .string "תודה שהתחרית!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
    .string "באתי לראות כמה אני טובה.\p"
    .string "מעניין אילו מאמנים\n"
    .string "מחכים לי שם?\p"
    .string "זה ממש מלחיץ!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
    .string "הוף, הוף…\n"
    .string "הוף…\p"
    .string "תשכח מקרבות! המדרגות האלה…\n"
    .string "הן קשות יותר מכל קרב…$"
