CeladonCity_Gym_Text_ErikaIntro::
    .string "שלום. מזג האוויר\n"
    .string "היום נפלא, הלא כך? כל כך נעים\l"
    .string "בחוץ.\p"
    .string "...אה... נדמה שנרדמתי. ברוך הבא.\p"
    .string "שמי הוא אריקה. אני מנהיגת מכון\l"
    .string "סלדון.\p"
    .string "אני מלמדת את האומנות של סידור\l"
    .string "זרי פרחים. הפוקימונים שלי הם\l"
    .string "מסוג דשא.\p"
    .string "אה, אני מצטערת, לא היה לי מושג\l"
    .string "שרצית לאתגר אותי.\p"
    .string "בסדר גמור, אך אני לא אפסיד.$"

CeladonCity_Gym_Text_ErikaDefeat::
    .string "הו!\n"
    .string "אני מודה בתבוסתי.\p"
    .string "אתה חזק להפליא.\p"
    .string "עלי להעניק לך את תג הקשת בענן.\p$"

CeladonCity_Gym_Text_ErikaPostBattle::
    .string "אתה אוסף מידע על\n"
    .string "פוקימונים? עלי לומר שזה מרשים.\p"
    .string "לעולם לא הייתי תופסת פוקימון\l"
    .string "שנראה בעיני לא מושך.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
    .string "בעזרת תג הקשת\n"
    .string "בענן, פוקימונים עד רמה 05 יצייתו\l"
    .string "לך.\p"
    .string "התג גם מאפשר לפוקימונים להשתמש\l"
    .string "בעוצמה בזמן קרב וגם מחוץ לקרב.\p"
    .string "בבקשה, קח גם את זה.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
    .string "{PLAYER} קיבל\n"
    .string "את מ“מ91 מאריקה.$"

CeladonCity_Gym_Text_ExplainTM19::
    .string "מ”מ91 מכיל את\n"
    .string "המהלך יניקת על.\p"
    .string "הפוקימון יונק נ”פ\n"
    .string "מהפוקימון היריב, כך שחצי מהנזק\l"
    .string "שנגרם ליריב מרפא את הפוקימון שלך!$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
    .string "כדאי שתפנה מקום\n"
    .string "בתיק בשביל זה.$"

_CeladonGymBattleText2::
    .string "היי!\p"
    .string "אסור לך להיות פה!$"

CeladonCity_Gym_Text_KayDefeat::
    .string "אתה אלים\n"
    .string "מדי!\p$"

CeladonCity_Gym_Text_KayPostBattle::
    .string "פיכס!\n"
    .string "אני מקווה שאריקה תכסח לך ת'ברוקה!$"

CeladonCity_Gym_Text_BridgetIntro::
    .string "בדיוק התחלתי\n"
    .string "להשתעמם.$"

CeladonCity_Gym_Text_BridgetDefeat::
    .string "האיפור\n"
    .string "שלי!\p$"

CeladonCity_Gym_Text_BridgetPostBattle::
    .string "פוקימונים מסוג דשא\n"
    .string "חזקים נגד אלה מסוג מים!\p"
    .string "יש להם יתרון גם על סוגי הסלע\l"
    .string "והאדמה!$"

CeladonCity_Gym_Text_TinaIntro::
    .string "אתה ממש מציצן,\n"
    .string "אה?$"

CeladonCity_Gym_Text_TinaDefeat::
    .string "אני\n"
    .string "המומה!\p$"

CeladonCity_Gym_Text_TinaPostBattle::
    .string "אה, לא הצצת?\n"
    .string "כל הזמן מסתובבים פה מציצנים!$"

CeladonCity_Gym_Text_TamiaIntro::
    .string "קלוט את פוקימוני\n"
    .string "הדשא שלי!\p"
    .string "כל כך קל לגדל אותם!$"

CeladonCity_Gym_Text_TamiaDefeat::
    .string "לא!\p$"

CeladonCity_Gym_Text_TamiaPostBattle::
    .string "במכון הזה, אנחנו\n"
    .string "משתמשות רק בפוקיימוני דשא!\p"
    .string "הם גם עוזרים לנו לסדר זרי פרחים!$"

CeladonCity_Gym_Text_LisaIntro::
    .string "אל תכניס פוקימוני\n"
    .string "אש או חרק לכאן!$"

CeladonCity_Gym_Text_LisaDefeat::
    .string "אוח!\n"
    .string "אתה!\p$"

CeladonCity_Gym_Text_LisaPostBattle::
    .string "המנהיגה שלנו,\n"
    .string "אריקה - היא אולי שקטה, אבל היא\l"
    .string "מאוד מוכשרת!$"

CeladonCity_Gym_Text_LoriIntro::
    .string "נעים להכיר אותך.\n"
    .string "התחביב שלי הוא אימון פוקימונים.$"

CeladonCity_Gym_Text_LoriDefeat::
    .string "הו!\n"
    .string "ממש נפלא!\p$"

CeladonCity_Gym_Text_LoriPostBattle::
    .string "יש לי בליינד\n"
    .string "דייט בקרוב. אני צריכה ללמוד\l"
    .string "להיות יותר מנומסת.$"

CeladonCity_Gym_Text_MaryIntro::
    .string "ברוך הבא למכון סלדון!\p"
    .string "אל תעז להמעיט בערכו של הכוח הנשי!$"

CeladonCity_Gym_Text_MaryDefeat::
    .string "אה!\n"
    .string "הובסתי!\p$"

CeladonCity_Gym_Text_MaryPostBattle::
    .string "לא הבאתי את\n"
    .string "הפוקימונים החזקים שלי!\p"
    .string "חכה ותראה בפעם הבאה!$"


CeladonCity_Gym_Text_GymStatue::
    .string "מכון הפוקימונים סלדון\n"
    .string "מנהיג: אריקה\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים סלדון\n"
    .string "מנהיג: אריקה\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}, {PLAYER}$"

CeladonCity_Gym_Text_KayIntro::
    .string "אני אספר לך על המכון הזה.\p"
    .string "רק לנשים אמיתיות מותר להיכנס\n"
    .string "לכאן!$"
