CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
    .string "איזה משקה לתת לה?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
    .string "יאי!\p"
    .string "מים מינרלים!\p"
    .string "תודה רבה!\p"
    .string "אתה יכול לקבל ממני את זה!$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
    .string "יאי!\p"
    .string "משקה קל!\p"
    .string "תודה רבה!\p"
    .string "אתה יכול לקבל ממני את זה!$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
    .string "יאי!\p"
    .string "לימונדה!\p"
    .string "תודה רבה!\p"
    .string "אתה יכול לקבל ממני את זה!$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
    .string "אין לך מקום\n"
    .string "בתיק בשביל זה!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
    .string "לא, תודה!\n"
    .string "אני לא צמאה אחרי הכל!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
    .string "אחותי מאמנת, תאמין\n"
    .string "או לא.\p"
    .string "אבל, היא כל כך לא בוגרת,\l"
    .string "זה מטריף אותי!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
    .string "אני צמאה!\n"
    .string "אני רוצה משהו לשתות!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
    .string "אני צמאה!\n"
    .string "אני רוצה משהו לשתות!\p"
    .string "{FONT_NORMAL}לתת לה משקה?$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
    .string "קומת גג:\n"
    .string "מכונות ממכר$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
    .string "מכונת משקאות!\n"
    .string "הנה התפריט!\p$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
    .string "אופס, אין מספיק\n"
    .string "כסף!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
    .string "המכונה הוציאה פחית {STR_VAR_1}!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
    .string "אין יותר\n"
    .string "מקום לדברים!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
    .string "לא צמא!$"
	
Text_ReceivedItemFromLittleGirl::
    .string "{PLAYER} קיבל את {STR_VAR_2}\n"
    .string "מהילדה הקטנה.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
    .string "ממ61 מכיל את המהלך מסך אור.\p"
    .string "זה מהלך שמחליש את היוכלת המיוחדת\n"
    .string "של היריב שלך.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
    .string "ממ02 מכיל את המהלך מיגון.\p"
    .string "זה מהלך שמונע מהשפעות רעות כמו\n"
    .string "רעל מלפגוע בפוקימונים שלך.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
    .string "ממ33 מכיל את המהלך שיקוף.\p"
    .string "זה מהלך שמחליש את הכוח של מתקפות\n"
    .string "של היריב שלך.$"
