FuchsiaCity_House2_Text_DoYouLikeToFish::
    .string "אני אחיו הגדול של\n"
    .string "כהן הדיג!\p"
    .string "אני אוההההב לדוג!\p"
    .string "גם אתה אוהב לדוג?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
    .string "אדיר! אני\n"
    .string "אוהב את הסגנון שלך!\p"
    .string "קח את זה וצא לדוג, חבוב!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
    .string "{PLAYER} קיבל את החכה הטובה$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
    .string "הו... זה\n"
    .string "כל כך מאכזב...$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
    .string "שלום לך! {PLAYER}!\p"
    .string "איך הולך עם הדיג?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
    .string "הו לא!\p"
    .string "אין לך מקום למתנה שלי!$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
    .string "דייג זה דרך חיים!\n"
    .string "עם החכה הישנה הזו בטח הצלחת לתפוס\l"
    .string "רק מג'יקארפ נכון?\p"
    .string "עם החכה הטובה אתה יכול לתפוס\n"
    .string "פוקימונים הרבה יותר טובים.$"
