IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
    .string "יו!\n"
    .string "אלוף בהתהוות!\p"
    .string "בליגת הפוקימון תתמודד מול\n"
    .string "הרביעייה העילית בזה אחר זה.\p"
    .string "אם תפסיד, תצטרך להתחיל\n"
    .string "הכל מההתחלה!\p"
    .string "זהו זה!\n"
    .string "קדימה, תן בראש!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
    .string "מכאן ואילך תתמודד מול חברי\n"
    .string "הרביעייה העילית, אחד אחד.\p"
    .string "אם תנצח, תיפתח דלת אל\n"
    .string "המאמן הבא. בהצלחה!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
    .string "אני ממש מצטערת, אבל הגעת\n"
    .string "לכאן לחינם.\p"
    .string "לורליי מהרביעייה העילית\n"
    .string "לא נמצאת, אתה מבין.\p"
    .string "לכן ליגת הפוקימון\n"
    .string "סגורה לעת עתה.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
    .string "פוקימוני הרוח של אגתה\n"
    .string "חזקים בצורה מפחידה.\p"
    .string "אימנתי את פוקימוני הלחימה\n"
    .string "שלי עד המקסימום.\p"
    .string "ניגשתי לאגתה בביטחון מלא,\n"
    .string "והיא כיסחה אותנו.\p"
    .string "חוץ מזה, לזקנה הזאת יש\n"
    .string "פתיל ממש קצר.\p"
    .string "לא צריך הרבה כדי לגרום\n"
    .string "לגברת המפחידה הזאת לצרוח.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
    .string "אולי החברות ברביעייה העילית\n"
    .string "פשוט עוברת במשפחה.\p"
    .string "לפי מה ששמעתי, ללאנס יש\n"
    .string "בן דוד שהוא מנהיג מכון\l"
    .string "אי שם רחוק מכאן.$"

