CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
    .string "אה-יה!\p"
    .string "אני דוקטור חשוב!\p"
    .string "אני חוקר כאן מאובני פוקימון\l"
    .string "נדירים!\p"
    .string "אתה! יש לך מאובן בשבילי?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
    .string "לא! חבל!$"

_Lab4Text_75dd0::
    .string "אני לקחת קצת זמן!\p"
    .string "אתה לך להליכה לזמן מה!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
    .string "איפה היית?\p"
    .string "המאובן שלך חזר בחזרה לחיים!\p"
    .string "זה היה {STR_VAR_1} כמו שחשבתי!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
    .string "הו! זה {STR_VAR_2}!\p"
    .string "זה מאובן של {STR_VAR_1}, פוקימון\n"
    .string "שכבר נכחד!\p"
    .string "מכונת ההחייאה שלי\n"
    .string "תהפוך את הפוקימון הזה לחי שוב!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
    .string "אז! תמהר ותתן\n"
    .string "לי את זה!\p"
    .string "{PLAYER} מסר את\n"
    .string "{STR_VAR_2} לדוקטור המוזר!\p"
    .string "$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
    .string "אני לקחת קצת זמן!\p"
    .string "אתה לך להליכה לזמן מה!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
    .string "איי-יה! אתה בוא\n"
    .string "שוב!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
    .string "{PLAYER} את {STR_VAR_1}\n"
    .string "מהדוקטור.$"

Text_MetronomeTeach::
    .string "טיק-טיק-טיק!\n"
    .string "אני אלמד אותך מהלך שווה.\p"
    .string "תלמד אותו לאחד הפוקימונים שלך\n"
    .string "ותראה בעצמך!\p"
    .string "זה מהלך שנקרא פעמן.\n"
    .string "זה מעניין אותך?$"

Text_MetronomeDeclined::
    .string "אני אומר לך, זה מהלך ממש כיף!$"

Text_MetronomeWhichMon::
    .string "אוקיי!\n"
    .string "איזה פוקימון ללמד?$"

Text_MetronomeTaught::
    .string "טיק-טיק-טיק!\n"
    .string "זה הצליל של פעמן.\p"
    .string "זה גורם למוח של פוקימון להשתמש\n"
    .string "במהלכים שהוא אפילו לא מכיר.$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
    .string "ポケモン　いっぱいで　もてないね！$"

@ Unused
CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
    .string "ちょっと　じかん　かかるよ！\p"
    .string "そこらへんを　すこし\n"
    .string "ブラブラ　してくると　よろしー！$"
