Route15_Text_KindraIntro::
    .string "הרגע קיבלתי פוקימונים בהחלפות.\n"
    .string "אפשר לנסות אותם עליך?$"

Route15_Text_KindraDefeat::
    .string "לא מספיק טוב!$"

Route15_Text_KindraPostBattle::
    .string "אי אפשר לשנות כינוי של פוקימון\n"
    .string "שקיבלת בהחלפה.\p"
    .string "רק המאמן המקורי יכול לשנות את\n"
    .string "הכינוי.$"

Route15_Text_BeckyIntro::
    .string "אתה נראה עדין, אז אני חושבת שאוכל\n"
    .string "לנצח אותך.\p"
    .string "בוא ננסה!$"

Route15_Text_BeckyDefeat::
    .string "לא, טעות!$"

Route15_Text_BeckyPostBattle::
    .string "אני מפחדת מאופנוענים. הם נראים\n"
    .string "כל כך מכוערים ורעים!$"

Route15_Text_EdwinIntro::
    .string "כשאני שורק, אני יכול לזמן פוקימונים\n"
    .string "מעופפים.$"

Route15_Text_EdwinDefeat::
    .string "אוי!\n"
    .string "זה עצוב!$"

Route15_Text_EdwinPostBattle::
    .string "אולי אני לא מתאים לקרבות.\n"
    .string "כנראה אני לא הסוג הנכון.$"

Route15_Text_ChesterIntro::
    .string "הממ? הציפורים שלי רועדות!\n"
    .string "אתה טוב, נכון?$"

Route15_Text_ChesterDefeat::
    .string "כמו שחשבתי!$"

Route15_Text_ChesterPostBattle::
    .string "זה כל כך ברור, אתה צריך לדעת\n"
    .string "את זה, אבל…\p"
    .string "תנועות כמו רעידת אדמה ותהום\n"
    .string "לא משפיעות על פוקימונים מעופפים.$"

Route15_Text_GraceIntro::
    .string "או, אתה כזה חמוד!\n"
    .string "כמו פוקימון מתוק!$"

Route15_Text_GraceDefeat::
    .string "נראית כל כך חמוד, גם כן!$"

Route15_Text_GracePostBattle::
    .string "אני סולחת לך.\n"
    .string "אני יכולה להתמודד עם זה.\l"
    .string "אני ילדה גדולה עכשיו.$"

Route15_Text_OliviaIntro::
    .string "אני מגדלת פוקימונים להגנה\n"
    .string "כי אני גרה לבד.$"

Route15_Text_OliviaDefeat::
    .string "בשבילי פוקימונים זה לא עניין של\n"
    .string "ניצחון או הפסד.$"

Route15_Text_OliviaPostBattle::
    .string "אני אוהבת שהפוקימונים שלי מקדמים\n"
    .string "את פניי כשאני חוזרת הביתה.\p"
    .string "זה כל כך מרגיע.$"

Route15_Text_ErnestIntro::
    .string "היי, ילד! קדימה!\n"
    .string "הרגע קיבלתי את אלה ממפסידן כלשהו!$"

Route15_Text_ErnestDefeat::
    .string "למה לא?$"

Route15_Text_ErnestPostBattle::
    .string "החיים קצרים מדי.\n"
    .string "מגניב לחיות כמו פורע חוק.\l"
    .string "צוות רוקט שולטים!$"

Route15_Text_AlexIntro::
    .string "תן את כל הכסף שלך כשאתה מפסיד\n"
    .string "לי, ילד!$"

Route15_Text_AlexDefeat::
    .string "זה לא יכול להיות נכון!$"

Route15_Text_AlexPostBattle::
    .string "רק צחקתי לגבי הכסף.\n"
    .string "אל תיקח אותי ברצינות.$"

Route15_Text_CeliaIntro::
    .string "מה מגניב וחם עכשיו?\n"
    .string "להחליף פוקימונים!$"

Route15_Text_CeliaDefeat::
    .string "אמרתי להחליף!$"

Route15_Text_CeliaPostBattle::
    .string "אני מחליפה פוקימונים עם החברים\n"
    .string "שלי כל הזמן.$"

Route15_Text_YazminIntro::
    .string "רוצה לשחק עם הפוקימונים שלי?$"

Route15_Text_YazminDefeat::
    .string "הייתי חסרת סבלנות מדי!$"

Route15_Text_YazminPostBattle::
    .string "אלך להתאמן עם אנשים חלשים יותר.$"

Route15_Text_RouteSign::
    .string "נתיב 51\n"
    .string "מערבה לעיר פוקסיה$"

Route15_Text_MyaIntro::
    .string "מיה: אתה מושלם.\n"
    .string "תעזור לי לאמן את אחי הקטן?$"

Route15_Text_MyaDefeat::
    .string "מיה: רון, אתה חייב להתרכז!\n"
    .string "תתמקד במה שאתה עושה!$"

Route15_Text_MyaPostBattle::
    .string "מיה: אוקיי, נגביר את הקצב.\n"
    .string "אוסיף לתפריט האימונים שלנו!$"

Route15_Text_MyaNotEnoughMons::
    .string "מיה: רוצה לאתגר אותנו?\n"
    .string "תצטרך שני פוקימונים, אם כך.$"

Route15_Text_RonIntro::
    .string "רון: אחותי נעשית מפחידה כשאנחנו\n"
    .string "מפסידים.$"

Route15_Text_RonDefeat::
    .string "רון: אוי, לא, לא…\n"
    .string "אחותי, אני מצטער!$"

Route15_Text_RonPostBattle::
    .string "רון: אוי, איכס…\n"
    .string "הלוואי והייתה לי אחות נחמדה…$"

Route15_Text_RonNotEnoughMons::
    .string "רון: רצית להילחם עם\n"
    .string "האחות שלי ואני?\p"
    .string "אז תצטרך שני פוקימונים.$"
