CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
    .string "ברוך הבא!\p"
    .string "אם תרצה להחליף את האסימונים שלך\n"
    .string "בפרסים נפלאים, תוכל לעשות זאת\l"
    .string "בבניין הצמוד.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
    .string "ברוך הבא למשחקיית\n"
    .string "רוקט!\p"
    .string "אתה רוצה לקנות אסימונים?$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
    .string "תודה! הנה 05\n"
    .string "האסימונים שלך!$"

CeladonCity_GameCorner_Text_ComePlaySometime::
    .string "לא? בסדר.\n"
    .string "נשמח לראותך שוב!$"

CeladonCity_GameCorner_Text_CantAffordCoins::
    .string "אין לך מספיק\n"
    .string "כסף!$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
    .string "אופס! ארנק\n"
    .string "האסימונים שלך מלא.$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
    .string "אין לך ארנק\n"
    .string "לאסימונים!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
    .string "אל תספר לאף אחד.\p"
    .string "השמועה אומרת שצוות רוקט\l"
    .string "מנהל את המקום.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
    .string "אני חושבת שבמכונות\n"
    .string "המזל השונות יש סיכויים שונים.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
    .string "ילד, רוצה לשחק?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
    .string "{PLAYER} קיבל\n"
    .string "01 אסימונים!$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
    .string "אתה לא צריך את\n"
    .string "המטבעות שלי!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
    .string "לפעמים זוכים,\n"
    .string "לפעמים מפסידים.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
    .string "אני נהנית מאוד!$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
    .string "יו!\p"
    .string "יש לך דברים יותר טובים לעשות,\l"
    .string "אלופצ'יק!\p"
    .string "בראש מכון סלדון עומדת המנהיגה\n"
    .string "אריקה! היא משתמשת בפוקימונים מסוג\l"
    .string "דשא!\p"
    .string "היא אמנם נראית כנועה, אבל מראה\l"
    .string "יכול להטעות!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
    .string "אפשר להחליף את\n"
    .string "האסימונים שלך בפוקימונים נדירים.\p"
    .string "אבל, אני לא מצליח לזכות במספיק\l"
    .string "אסימונים!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
    .string "משחקי מזל מפחידים\n"
    .string "אותי! אפשר להתמכר כל-כך בקלות!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
    .string "מה הולך? רוצה קצת\n"
    .string "אסימונים?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
    .string "{PLAYER} קיבל\n"
    .string "02 אסימונים!$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
    .string "יש לך כבר המון\n"
    .string "אסימונים!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
    .string "אוף! אני צריך עוד\n"
    .string "אסימונים בשביל הפוקימון שאני\l"
    .string "רוצה!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
    .string "רגע, מה? אתה מסיח\n"
    .string "את דעתי! קח כמה אסימונים ו'סתלק!\l"
    .string "קישטה!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
    .string "{PLAYER} קיבל\n"
    .string "02 אסימונים!$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
    .string "יש לך אסימונים\n"
    .string "משלך!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
    .string "הסוד הוא שצריך\n"
    .string "להסתכל על הגלגלים מקרוב!$"

CeladonCity_GameCorner_Text_GruntIntro::
    .string "אני שומר על הפוסטר\n"
    .string "הזה! 'סתלק מכאן, או ש!$"

CeladonCity_GameCorner_Text_GruntDefeat::
    .string "אוף!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
    .string "המחבוא שלנו עלול\n"
    .string "להיחשף! כדאי שאלך להזהיר את הבוס!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
    .string "היי!\p"
    .string "יש מתג מאחורי הפוסטר!?\l"
    .string "קדימה, בוא נלחץ!$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
    .string "אופס! שכחת את\n"
    .string "הארנק לאסימונים!$"

CeladonCity_GameCorner_Text_OutOfOrder::
    .string "לא תקין!\n"
    .string "זה לא עובד.$"

CeladonCity_GameCorner_Text_OutToLunch::
    .string "יצאתי להפסקת צהריים\n"
    .string "זה שמור.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
    .string "יש פה מפתחות של מישהו!\n"
    .string "הוא בטח יחזור בקרוב.$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
    .string "נחוץ בשביל זה ארנק לאסימונים…$"
	
	CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
    .string "מכונת מזל!\n"
    .string "רוצה לשחק?$"
