SixIsland_WaterPath_Text_RoseIntro::
    .string "נתתי לרוח הנעימה להוביל אותי\n"
    .string "עד לכאן.$"

SixIsland_WaterPath_Text_RoseDefeat::
    .string "חיחי… אתה כל כך חמוד\n"
    .string "כשאתה נחוש.$"

SixIsland_WaterPath_Text_RosePostBattle::
    .string "אני רוצה ללכת ליער ששם,\n"
    .string "אבל…\p"
    .string "יש שם המון פוקימוני חרק.\n"
    .string "הם קצת מפחידים אותי.$"

SixIsland_WaterPath_Text_EdwardIntro::
    .string "אני מתאמן בסתר כדי שאף אחד\n"
    .string "לא יראה אותי.$"

SixIsland_WaterPath_Text_EdwardDefeat::
    .string "אף אחד לא ראה שהפסדתי, נכון?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
    .string "כלהטוטן, אני לא רוצה\n"
    .string "שאנשים ידעו כמה מאמץ השקעתי.$"

SixIsland_WaterPath_Text_SamirIntro::
    .string "מה, אתה רומז שנמאס לך\n"
    .string "לראות שחיינים כמוני?\p"
    .string "אוי, אל תהיה כזה!$"

SixIsland_WaterPath_Text_SamirDefeat::
    .string "אוי, לא, לא, לא.$"

SixIsland_WaterPath_Text_SamirPostBattle::
    .string "לא הצלחתי להיפטר מהסטיגמה\n"
    .string "של השחיינים…$"

SixIsland_WaterPath_Text_DeniseIntro::
    .string "החבר שלי תמיד עסוק, אז אני\n"
    .string "באה לשחות לבד.$"

SixIsland_WaterPath_Text_DeniseDefeat::
    .string "אוי, ידעתי שזה יקרה!$"

SixIsland_WaterPath_Text_DenisePostBattle::
    .string "כשאני לא יכולה להיות עם\n"
    .string "החבר שלי, אני מבלה עם\l"
    .string "הפוקימון שהוא נתן לי.$"

SixIsland_WaterPath_Text_EarlIntro::
    .string "תגיד לי, איפה ההרים\n"
    .string "באזור הזה?$"

SixIsland_WaterPath_Text_EarlDefeat::
    .string "הלכתי לאיבוד בזמן שהייתי\n"
    .string "עסוק בקרב!$"

SixIsland_WaterPath_Text_EarlPostBattle::
    .string "אין שום הרים\n"
    .string "באזור הזה?$"

SixIsland_WaterPath_Text_MiuIntro::
    .string "מיו: שלום, פוקימון!\n"
    .string "הגיע הזמן לשחק!$"

SixIsland_WaterPath_Text_MiuDefeat::
    .string "מיו: אוי, לא!\n"
    .string "אמא!$"

SixIsland_WaterPath_Text_MiuPostBattle::
    .string "מיו: אני מרגישה עצובה בפנים\n"
    .string "כשאנחנו מפסידים…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
    .string "מיו: מיה ואני תאומות.\n"
    .string "אנחנו רוצות להילחם יחד.$"

SixIsland_WaterPath_Text_MiaIntro::
    .string "מיה: שלום, פוקימון!\n"
    .string "הגיע הזמן להילחם!$"

SixIsland_WaterPath_Text_MiaDefeat::
    .string "מיה: אתה מרושע!\n"
    .string "לא יפה שניצחת!$"

SixIsland_WaterPath_Text_MiaPostBattle::
    .string "מיה: אוהה…\n"
    .string "אני מצטערת, פוקימון שלי…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
    .string "מיה: אוי, יש לך רק פוקימון\n"
    .string "אחד?\p"
    .string "אתה לא מרגיש בודד?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
    .string "דרושה!\n"
    .string "הקרן המושלמת!$"

SixIsland_WaterPath_Text_RouteSign::
    .string "דרך המים\n"
    .string "מובילה לעמק האבדון$"

