CinnabarIsland_Text_DoorIsLocked::
    .string "הדלת נעולה...$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
    .string "בליין ממכון\n"
    .string "סינאבאר הוא אדם משונה שחי באי\l"
    .string "כבר עשרות שנים.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
    .string "מדענים עורכים\n"
    .string "ניסויים בבניין השרוף.\l"
    .string "אתה יודע, זאת שקוראים לה\l"
    .string "אחוזת הפוקימונים$"

CinnabarIsland_Text_IslandSign::
    .string "האי סינאבאר\n"
    .string "העיירה הבוערת של מיווקה לוהטת$"

CinnabarIsland_Text_PokemonLab::
    .string "מעבדת הפוקימון$"

CinnabarIsland_Text_GymSign::
    .string "האי סינאבאר\n"
    .string "מכון הפוקימון מנהיג: בליין\p"
    .string "אלוף החידות חמום המח!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
    .string "הא?\n"
    .string "היי, זה לא {PLAYER}?!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
    .string "היי! זה אני - ביל.\n"
    .string "הרבה זמן לא התראינו!\p"
    .string "אני מקווה שאתה עדיין משתמש\n"
    .string "במערכת המחשב שלי.\p"
    .string "טוב, תקשיב, מכיוון שנפגשנו פה\n"
    .string "מה דעתך על לבלות איתי קצת זמן?\p"
    .string "יש אי קטן דרומה מפה\n"
    .string "שנקרא אי מספר 1.\p"
    .string "חבר שלי הזמין אותי,\n"
    .string "אז אני בדרכי לשם.\p"
    .string "מה אתה אומר?\n"
    .string "רוצה לבוא איתי?$"

CinnabarIsland_Text_AllRightLetsGo::
    .string "בסדר גמור.\n"
    .string "בוא נלך!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
    .string "אה, אתה עסוק?\p"
    .string "בסדר.\n"
    .string "בכל מקרה הסירה עדיין לא הגיעה.\p"
    .string "אני אחכה במרכז הפוקימונים שנמצא\n"
    .string "פה.\p"
    .string "בוא לראות אותי כשאתה מסיים את\n"
    .string "העיסוקים שלך.$"

CinnabarIsland_Text_MyPalsBoatArrived::
    .string "נראה שהסירה של חבר שלי\n"
    .string "בדיוק הגיעה.\p"
    .string "הוא שלח אותה במיוחד לסינאבאר\n"
    .string "כדי לאסוף אותי.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
    .string "היי, זה היה שייט די ארוך אה?\p"
    .string "נראה לי שסיילו החבר שלי נהנה\n"
    .string "איתך מאוד.\p"
    .string "אני בטוח שהוא יקבל אותך פה\n"
    .string "בשמחה אם תרצה לבקר שוב.\p"
    .string "אם יש לך תלת-מעבר אתה\n"
    .string "תמיד יכול לקחת מעבורת\l"
    .string "מהנמל בוורמיליון.\p"
    .string "תודה שהצטרפת אלי!$"
