OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
    .string "המ!\n"
    .string "אאאאאאאאאאח!\p"
    .string "אאאה! זה גן עדן!\n"
    .string "המים מחממים אותי עד העצם!\p"
    .string "כדאי שתקפוץ פנימה גם אתה.\p"
    .string "לך לאמצע, תירגע\n"
    .string "ותתחמם כמו שצריך!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
    .string "החלק האהוב עליי ברחצה\n"
    .string "מגיע מיד אחרי זה.\p"
    .string "אני נהנה מקערת מרק דגים\n"
    .string "שמחממת אותי גם מבפנים!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
    .string "המים חמימים בדיוק במידה.\n"
    .string "התחושה נפלאה…\p"
    .string "{PLAYER} והפוקימונים\n"
    .string "התרעננו לגמרי!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
    .string "אומרים שטבילה במעיין חם\n"
    .string "עושה טוב לגוף.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
    .string "תסתכל על הפנים שלי.\n"
    .string "רואה כמה העור שלי חלק?\p"
    .string "המים של המעיין החם שומרים\n"
    .string "לי על עור צעיר מהגיל שלי.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
    .string "אחרי יום אימונים הגון,\n"
    .string "אין כמו טבילה מרגיעה\l"
    .string "במעיין החם.\p"
    .string "ברונו, שהוא ותיק ממני,\n"
    .string "מבקר בספא מדי פעם.\p"
    .string "הוא בא לשקם פציעות,\n"
    .string "שלו ושל הפוקימונים שלו.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
    .string "מעיינות חמים והרי געש\n"
    .string "הולכים יד ביד.\p"
    .string "את ספא אמבר שכאן\n"
    .string "בניתי לפני שנים.\p"
    .string "חצבתי את הבריכה בידיים\n"
    .string "מתוך סלע ענק אחד.\p"
    .string "השתמשתי בזה אז.\n"
    .string "אני מניח שאוכל להיפרד ממנו.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
    .string "זה מנפץ סלעים כאילו היו\n"
    .string "עשויים מקרקרים.$"

