ThreeIsland_House2_Text_CantMakeThisSpoonBend::
    .string "אררררררגגגהה…\n"
    .string "קוואאאאה!\p"
    .string "…זה לא הולך! אני לא מצליח\n"
    .string "לכופף את הכפית הזאת במחשבה.\p"
    .string "אולי באמת אין לי שום\n"
    .string "כוחות פסיכיים.$"

ThreeIsland_House2_Text_IAdmireSabrina::
    .string "שמעת על המנהיגה של המכון\n"
    .string "בעיר סאפרון?\p"
    .string "היא משתמשת בפוקימונים\n"
    .string "מסוג פסיכי, נכון?\p"
    .string "אני מעריץ אותה, באמת שכן.\p"
    .string "שמעתי שהיא קרירה ורגועה,\n"
    .string "וגם יפהפייה.$"
