TwoIsland_Text_IslandSign::
    .string "אי 2\n"
    .string "אי שתי הברכות$"

TwoIsland_Text_JoyfulGameCornerSign::
    .string "המשחקיה העליזה\n"
    .string "דלג ונגוס!$"

TwoIsland_Text_DangerFastCurrent::
    .string "סכנה! זרם חזק!\n"
    .string "אסור לדוג או לגלוש!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
    .string "הו!\n"
    .string "שלום, ברוך הבא לחנות שלי!\p"
    .string "פתחנו אותה רק לאחרונה.\p"
    .string "המבחר שלנו מצומצם, אבל אני\n"
    .string "מקווה שנוכל לעזור לך.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
    .string "אין לי מילים לתאר כמה אני\n"
    .string "אסיר תודה לך על הצלת לוסטל.\p"
    .string "בזכות מה שעשית, אנשי אי 3\n"
    .string "שינו את היחס שלהם\l"
    .string "לאנשים מקאנטו.\p"
    .string "ואני, כידוע לך, מקאנטו.\p"
    .string "אנשי אי 3 עזרו לי\n"
    .string "להגדיל את המבחר בחנות.$"

TwoIsland_Text_HopeYouGiveItYourBest::
    .string "היי! אני נותן פה את כל כולי.\n"
    .string "אני מקווה שגם אתה, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
    .string "הו, שלום, {PLAYER}!\n"
    .string "ברוך הבא!\p"
    .string "התחלתי להביא פריטים מארצות\n"
    .string "רחוקות.\p"
    .string "הגיעו גם כמה פריטים נדירים.\n"
    .string "בוא תעיף מבט!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
    .string "הבחור ההוא שם עבר לכאן\n"
    .string "מהעיר סלדון.\p"
    .string "הוא פתח חנות יחד עם\n"
    .string "אחיו הצעיר.\p"
    .string "מעניין אם הוא בכלל ידע\n"
    .string "למה הוא נכנס.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
    .string "אחיו של בעל החנות התחיל\n"
    .string "לעבוד במשחקיה.\p"
    .string "הוא מנסה לגייס כסף כדי\n"
    .string "שיוכלו לקנות עוד סחורה.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
    .string "תשמע, תשמע.\n"
    .string "ידעת?\p"
    .string "מאמן מפורסם הגיע לאי\n"
    .string "לפני זמן לא רב.\p"
    .string "הוא אחד מהרביעייה העילית.\n"
    .string "שמו ברונו.\p"
    .string "הוא הלך מאוכזב כשגילה\n"
    .string "שכל חטיפי הזעם\l"
    .string "נמכרו.$"

TwoIsland_Text_BuyRareItemsHere::
    .string "מאמן שמבין עניין יודע\n"
    .string "לקנות כאן פריטים נדירים!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
    .string "יש זקנה שגרה בבקתה\n"
    .string "הרחק על החוף.\p"
    .string "היא נועצת מבט בפוקימונים.\n"
    .string "זה קצת מצמרר.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
    .string "בוינג! בוינג!\n"
    .string "ניסית כבר את משחק הקפיצות?\p"
    .string "הפוקימונים שאפשר לשלוח…\n"
    .string "בוינג!\p"
    .string "יש כאלה שעושים בוינג!\p"
    .string "ויש כאלה שעושים בוווווווינג!\p"
    .string "ידעת את זה?\n"
    .string "בוינג!$"

