TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
    .string "כבר ביקרת במשחקיה\n"
    .string "שלנו?\p"
    .string "אין טעם ללכת לשם לבד.\n"
    .string "חייבים לקחת חבר.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
    .string "לא הרבה אנשים גרים\n"
    .string "באי 2.\p"
    .string "יש שם זקנה אחת שגרה\n"
    .string "רחוק על החוף.\p"
    .string "היא שם כבר מאז שאני\n"
    .string "זוכר את עצמי.$"

