FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
    .string "סלפי: הו?\n"
    .string "אני מכירה אותך מאיפשהו?\p"
    .string "הו, אבל זה לא משנה.\p"
    .string "אני משועממת להחריד.\n"
    .string "בבקשה, שמע את משאלתי.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
    .string "אני רוצה לראות פוקימון.\n"
    .string "איזה יופי של {STR_VAR_1}.\p"
    .string "אני רוצה לראות אחד מיד.\n"
    .string "בבקשה, הגשם את משאלתי.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
    .string "סלפי: הו, נמאס לי מזה.\n"
    .string "נמאס לי לחכות לך.\p"
    .string "אסלח לך הפעם, אבל בבקשה\n"
    .string "אל תאכזב אותי בפעם הבאה.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
    .string "סלפי: הו, שלום לך.\p"
    .string "אלוהים אדירים. זה בטח\n"
    .string "ה{STR_VAR_1} שתפסת בשבילי.\p"
    .string "חיחי…\n"
    .string "יש בזה משהו שמזכיר אותך.\p"
    .string "תודה רבה לך.\p"
    .string "… …  … …  … …\n"
    .string "משהו לא בסדר?\p"
    .string "אתה יכול ללכת.\p"
    .string "… …  … …  … …\n"
    .string "הו, בסדר. עכשיו הבנתי.\p"
    .string "סבסטיאן!\n"
    .string "אני צריכה אותך כאן מיד!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
    .string "משרת: כן, גבירתי.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
    .string "סלפי: דאג לכך שהאדם הזה\n"
    .string "יקבל אות הוקרה.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
    .string "משרת: כרצונך,\n"
    .string "גבירתי.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
    .string "משרת: אני מודה לך מקרב לב\n"
    .string "על שהשמחת את הגברת סלפי.\p"
    .string "אנא קבל זאת כאות תודה ממנה…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
    .string "משרת: נראה שהתיק שלך\n"
    .string "מלא, לצערי.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
    .string "הו…\n"
    .string "כמה מאכזב.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
    .string "סלפי: אני מאחלת לך\n"
    .string "המון הצלחה.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
    .string "משרת: חיוכה של הגברת סלפי\n"
    .string "זוהר כמו השמש.\p"
    .string "אנא, אני מתחנן שתביא שמחה\n"
    .string "לגברת סלפי.$"

