Route16_Text_LaoIntro::
    .string "מה אתה רוצה?$"

Route16_Text_LaoDefeat::
    .string "אל תעז לצחוק עליי!$"

Route16_Text_LaoPostBattle::
    .string "אנחנו אוהבים להסתובב כאן.\n"
    .string "למה זה מפריע לך?$"

Route16_Text_KojiIntro::
    .string "אופניים נחמדים!\n"
    .string "תביא אותם לפה!$"

Route16_Text_KojiDefeat::
    .string "נוקאאוט!$"

Route16_Text_KojiPostBattle::
    .string "עזוב, מי צריך את האופניים שלך!$"

Route16_Text_LukeIntro::
    .string "צא לשחק, עכבר קטן!$"

Route16_Text_LukeDefeat::
    .string "אתה עכבר קטן!$"

Route16_Text_LukePostBattle::
    .string "אני שונא להפסיד!\n"
    .string "תתרחק ממני!$"

Route16_Text_HideoIntro::
    .string "היי, אתה בדיוק נתקעת בי!$"

Route16_Text_HideoDefeat::
    .string "בום!$"

Route16_Text_HideoPostBattle::
    .string "תמיד נהיה כאן, גם אם זה לא\n"
    .string "מוצא חן בעיניך.\p"
    .string "אתה יכול לעבור לוורמיליון\n"
    .string "אם תלך בפושיה לאורך החוף.$"

Route16_Text_CamronIntro::
    .string "אני רעב ועצבני!\n"
    .string "אני צריך שק אגרוף!$"

Route16_Text_CamronDefeat::
    .string "רע, רע, רע!$"

Route16_Text_CamronPostBattle::
    .string "אם אני כבר מחזיק פוקימונים, אז\n"
    .string "שיהיו פראיים.\p"
    .string "הייתי משתמש בהם כדי להשאיר את\n"
    .string "האויבים שלי מרוסקים.$"

Route16_Text_RubenIntro::
    .string "היי, מה קורה?\n"
    .string "בוא נעשה חיים!$"

Route16_Text_RubenDefeat::
    .string "אל תרגיז אותי!$"

Route16_Text_RubenPostBattle::
    .string "אני נהנה להטריד אנשים עם\n"
    .string "הפוקימונים המסריחים שלי.\p"
    .string "הם מעולים בלגרום לאנשים להיבהל.\n"
    .string "והם גם נושכים.$"

Route16_Text_MonSprawledOutInSlumber::
    .string "פוקימון שוכב רפוי ושקוע\n"
    .string "בשינה עמוקה ונעימה.$"

Route16_Text_CyclingRoadSign::
    .string "תהנו מהשיפוע!\n"
    .string "דרך האופניים$"

Route16_Text_RouteSign::
    .string "נתיב 61\n"
    .string "מעיר סלדון לעיר פוקסיה$"

Route16_Text_JedIntro::
    .string "ג'ד: האהבה שלנו היא ללא גבולות.\n"
    .string "אנחנו מאוהבים ואנחנו מראים את זה!$"

Route16_Text_JedDefeat::
    .string "ג'ד: הו, לא!\n"
    .string "האהבה שלי ראתה אותי מפסיד!$"

Route16_Text_JedPostBattle::
    .string "ג'ד: תקשיבי, ליה.\n"
    .string "את צריכה להתרכז פחות בי.$"

Route16_Text_JedNotEnoughMons::
    .string "ג'ד: יש לך רק פוקימון אחד?\n"
    .string "אין אהבה בלב שלך?$"

Route16_Text_LeaIntro::
    .string "ליה: לפעמים, העוצמה של\n"
    .string "האהבה שלנו מפחידה אותי.$"

Route16_Text_LeaDefeat::
    .string "ליה: הו! אבל ג'ד נראה מגניב\n"
    .string "אפילו כשהוא מפסיד!$"

Route16_Text_LeaPostBattle::
    .string "ליה: אהה, אני מצטערת.\n"
    .string "ג'ד כל כך מגניב.$"

Route16_Text_LeaNotEnoughMons::
    .string "ליה: הו, אין לך שני\n"
    .string "פוקימונים איתך?\p"
    .string "אתה לא מרגיש בודד?\n"
    .string "ואיך הפוקימונים שלך?$"
