CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "רק למאמנים\n"
    .string "מיומנים יש תגי מכונים.\p"
    .string "אני רואה שיש לך לפחות אחד.\p"
    .string "התגים אוצרים בחובם סודות מופלאים!$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "ובכן...\p"
    .string "איזה משמונת התגים עלי לתאר?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "חזור לבקר מתי\n"
    .string "שתרצה.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "נתון המתקפה של\n"
    .string "כל הפוקימונים יגדל מעט.\p"
    .string "בנוסף, התג יאפשר לך להשתמש במהלך\l"
    .string "הבזק מתי שתרצה.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "פוקימונים עד רמה\n"
    .string "03 יצייתו לך.\p"
    .string "מרמה 03 ומעלה לא תוכל להשתלט\l"
    .string "עליהם!\p"
    .string "בנוסף, התג יאפשר לך להשתמש במהלך\l"
    .string "חיתוך גם מחוץ לקרב.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "נתון המהירות של\n"
    .string "כל הפוקימונים יגדל מעט.\p"
    .string "בנוסף, התג יאפשר לך להשתמש במהלך\l"
    .string "תעופה מתי שתרצה.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "פוקימונים עד רמה\n"
    .string "05 יצייתו לך.\p"
    .string "מרמה 05 ומעלה לא תוכל להשתלט\l"
    .string "עליהם!\p"
    .string "בנוסף, התג יאפשר לך להשתמש במהלך\l"
    .string "עוצמה גם מחוץ לקרב.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "נתון ההגנה של\n"
    .string "כל הפוקימונים יגדל מעט.\p"
    .string "בנוסף, התג יאפשר לך להשתמש במהלך\l"
    .string "גלישה גם מחוץ לקרב.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "פוקימונים עד רמה\n"
    .string "07 יצייתו לך.\p"
    .string "מרמה 07 ומעלה לא תוכל להשתלט\l"
    .string "עליהם!\p"
    .string "בנוסף תוכל להשתמש במהלך “ריסוק\n"
    .string "סלע” מחוץ לקרב$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "נתון ההתקפה\n"
    .string "המיוחדת וההגנה המיוחדת של כל\l"
    .string "הפוקימונים יגדל מעט.\p"
    .string "בנוסף תוכל להשתמש במהלך “מפל מים”\n"
    .string "גם מחוץ לקרב$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "כל הפוקימונים\n"
    .string "יצייתו לך!$"
