ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
    .string "אתה יכול להשתמש\n"
    .string "במחשב שם בפינה.\p"
    .string "פקידת הקבלה אמרה לי. נחמד מצידה!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
    .string "יש מרכז פוקימון\n"
    .string "בכל עיר בהמשך בילך.\p"
    .string "הם גם לא מבקשים תשלום!$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
    .string "מרכז פוקימון מרפה את\n"
    .string "הפוקימונים שלך.\p"
    .string "הם יהפכו את הפוקימונים שלך\n"
    .string "לבריאים וחזקים.$"
