Route3_Text_TunnelFromCeruleanTiring::
    .string "אוף… אני צריך לקחת מנוחה…\n"
    .string "אח…\p"
    .string "המעבר מסרוליאן מתיש מאוד!$"

Route3_Text_ColtonIntro::
    .string "היי!\n"
    .string "ראיתי אותך ביער וירידיאן!$"

Route3_Text_ColtonDefeat::
    .string "ניצחת אותי שוב!$"

Route3_Text_ColtonPostBattle::
    .string "יש סוגי פוקימון נוספים חוץ\n"
    .string "מאלה שתמצא ביערות.$"

Route3_Text_BenIntro::
    .string "היי!\n"
    .string "אני אוהב מכנסיים קצרים!\p"
    .string "הם נוחים להפליא וקלים ללבישה!$"

Route3_Text_BenDefeat::
    .string "אני לא מאמין!$"

Route3_Text_BenPostBattle::
    .string "אתה משתמש במחשב של מרכז\n"
    .string "הפוקימון לאחסון הפוקימונים שלך?\p"
    .string "כל תיבה יכולה להכיל עד\n"
    .string "03 פוקימונים.$"

Route3_Text_JaniceIntro::
    .string "סלח לי!\n"
    .string "הסתכלת עליי, נכון?$"

Route3_Text_JaniceDefeat::
    .string "אתה מרושע!$"

Route3_Text_JanicePostBattle::
    .string "אתה לא צריך לבהות אם אתה\n"
    .string "לא רוצה להילחם!$"

Route3_Text_GregIntro::
    .string "אתה מאמן?\n"
    .string "בוא נתחיל מיד!$"

Route3_Text_GregDefeat::
    .string "אם היו לי פוקימונים חדשים,\n"
    .string "הייתי מנצח!$"

Route3_Text_GregPostBattle::
    .string "אם תיבת הפוקימונים במחשב\n"
    .string "מתמלאת, פשוט תעבור לתיבה אחרת.$"

Route3_Text_SallyIntro::
    .string "המבט שנתת לי…\n"
    .string "זה כל כך מסקרן!$"

Route3_Text_SallyDefeat::
    .string "תהיה נחמד!$"

Route3_Text_SallyPostBattle::
    .string "אתה יכול להימנע מקרבות אם\n"
    .string "לא תיתן למאמנים לראות אותך.$"

Route3_Text_CalvinIntro::
    .string "היי! אתה לא לובש מכנסיים\n"
    .string "קצרים! מה לא בסדר איתך?$"

Route3_Text_CalvinDefeat::
    .string "הפסדתי!\n"
    .string "הפסדתי! הפסדתי!$"

Route3_Text_CalvinPostBattle::
    .string "אני תמיד לובש מכנסיים קצרים,\n"
    .string "אפילו בחורף. זו המדיניות שלי.$"

Route3_Text_JamesIntro::
    .string "אני אלחם בך עם הפוקימונים\n"
    .string "שרק תפסתי.$"

Route3_Text_JamesDefeat::
    .string "נגמר כמו ארוחת ערב!$"

Route3_Text_JamesPostBattle::
    .string "פוקימונים מאומנים חזקים יותר\n"
    .string "מהפראיים.$"

Route3_Text_RobinIntro::
    .string "אהה!\n"
    .string "נגעת בי?$"

Route3_Text_RobinDefeat::
    .string "זהו זה?$"

Route3_Text_RobinPostBattle::
    .string "דרך 4 נמצא למרגלות\n"
    .string "הר הירח.$"

Route3_Text_RouteSign::
    .string "דרך 3\n"
    .string "הר הירח לפניך$"
