SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
    .string "לפוקימונים יש אופי משלהם,\n"
    .string "בדיוק כמו לבני אדם.\p"
    .string "לפיקאצ'ו שלי יש אופי חפוז,\n"
    .string "אז הוא גדל לפוקימון מהיר.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
    .string "יופי, ההכנות שלי הושלמו\n"
    .string "לקראת חקר החורבות.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
    .string "אני חייב לדוג באי 7.\p"
    .string "זה ישלים את סיבוב הדיג שלי\n"
    .string "בכל איי סווי.\p"
    .string "אבל כדאי שאצטייד קודם\n"
    .string "בכמה פוקיבולים.$"
