Text_DoubleEdgeTeach::
    .string "אתה יכול להיות גאה בעצמך,\n"
    .string "שבאת בדרך כל כך אמיצה:\l"
    .string "דרך הניצחון.\p"
    .string "כהכרה בהישג שלך,\n"
    .string "אני אלמד אותך את חרבפיפיות.\p"
    .string "האם אתה רוצה שאלמד את\n"
    .string "הטכניקה הזו?$"

Text_DoubleEdgeDeclined::
    .string "אני אלמד אותך את הטכניקה\n"
    .string "בכל זמן שתרצה.$"

Text_DoubleEdgeWhichMon::
    .string "לאיזה פוקימון עלי ללמד\n"
    .string "את ה-חרבפיפיות?$"

Text_DoubleEdgeTaught::
    .string "שמור על המוטיבציה הזו גם\n"
    .string "לגבי ליגת הפוקימונים!\p"
    .string "תנסה להכות אותם ולהפיל\n"
    .string "אותם!$"

VictoryRoad_3F_Text_GeorgeIntro::
    .string "שמעתי שמועות על ילד פלא.$"

VictoryRoad_3F_Text_GeorgeDefeat::
    .string "הם היו נכונות!$"

VictoryRoad_3F_Text_GeorgePostBattle::
    .string "אז, זה היית אתה שהביס את\n"
    .string "ג'יובאני מצוות רוקט?$"

VictoryRoad_3F_Text_AlexaIntro::
    .string "מאמנים חיים כדי לחפש יריבים\n"
    .string "חזקים יותר.$"

VictoryRoad_3F_Text_AlexaDefeat::
    .string "אוי!\n"
    .string "איזה חזק!$"

VictoryRoad_3F_Text_AlexaPostBattle::
    .string "על ידי קרב מול יריבים קשים,\n"
    .string "אתה מתחזק.$"

VictoryRoad_3F_Text_CarolineIntro::
    .string "אני אראה לך עד כמה אתה\n"
    .string "טוב. לא!$"

VictoryRoad_3F_Text_CarolineDefeat::
    .string "אני רותחת!$"

VictoryRoad_3F_Text_CarolinePostBattle::
    .string "הראית לי עד כמה הייתי טובה…$"

VictoryRoad_3F_Text_ColbyIntro::
    .string "רק הנבחרים יכולים לעבור כאן!$"

VictoryRoad_3F_Text_ColbyDefeat::
    .string "אני לא מאמין!$"

VictoryRoad_3F_Text_ColbyPostBattle::
    .string "כל המאמנים כאן בדרך ל\n"
    .string "ליגת בפוקימונים.\p"
    .string "אל תשחרר את המתח.$"

VictoryRoad_3F_Text_RayIntro::
    .string "ריי: יחד, אנחנו שניים שנועדו\n"
    .string "לגדולה!$"

VictoryRoad_3F_Text_RayDefeat::
    .string "ריי: אבסורד!\n"
    .string "זה לא יכול להיות!$"

VictoryRoad_3F_Text_RayPostBattle::
    .string "ריי: הובסתם אותנו.\n"
    .string "הגדולה נותרה מחוץ להישג יד…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
    .string "ריי: יחד, אנחנו שואפים לפסגה.\p"
    .string "אנחנו צריכים שתביא שני פוקימונים\n"
    .string "לקרב איתנו.$"

VictoryRoad_3F_Text_TyraIntro::
    .string "טירה: אנחנו מנסים להיות\n"
    .string "אלופים יחד.$"

VictoryRoad_3F_Text_TyraDefeat::
    .string "טירה: אוי, אבל…$"

VictoryRoad_3F_Text_TyraPostBattle::
    .string "טירה: לימדת אותי שכוח\n"
    .string "יכול להיות אינסופי בצורתו ובצבעיו.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
    .string "טירה: אתה לא יכול להילחם איתנו אם\n"
    .string "יש לך רק פוקימון אחד.$"
