FiveIsland_Text_IslandSign::
    .string "אי 5\n"
    .string "אי הזמן החולף$"

FiveIsland_Text_WeirdBuildingInMeadow::
    .string "אוי, איזה באסה. רציתי לשחק\n"
    .string "בשדה.\p"
    .string "אבל בנו עליו בניין מוזר,\n"
    .string "אז אי אפשר לשחק שם.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
    .string "לאחרונה נהיה כאן הרבה יותר\n"
    .string "עמוס.\p"
    .string "וגם לא תפסתי הרבה דגים\n"
    .string "טובים בזמן האחרון.$"

