ViridianForest_Text_FriendsItchingToBattle::
    .string "הגעתי לכאן עם\n"
    .string "כמה חברים!\p"
    .string "הם יצאו לכמה קרבות פוקימונים!$"

ViridianForest_Text_RickIntro::
    .string "הי! יש לך\n"
    .string "פוקימון! קדימה! בוא נילחם!$"

ViridianForest_Text_RickDefeat::
    .string "לא!\n"
    .string "קטרפי לא טוב מספיק!\p$"

ViridianForest_Text_RickPostBattle::
    .string "ששש! אתה תבריח\n"
    .string "את החרקים מכאן!$"

ViridianForest_Text_DougIntro::
    .string "יו! אתה לא יכול\n"
    .string "סתם לנוח כשאתה מאמן פוקימון!$"

ViridianForest_Text_DougDefeat::
    .string "אע?\n"
    .string "נגמרו לי הפוקימונים!\p$"

ViridianForest_Text_DougPostBattle::
    .string "לעזאזל! אני הולך\n"
    .string "לתפוס פוקימונים חזקים יותר!$"

ViridianForest_Text_SammyIntro::
    .string "הי, חכה!\n"
    .string "לאן אתה ממהר?$"

ViridianForest_Text_SammyDefeat::
    .string "ויתרתי! אתה טוב!\p$"

ViridianForest_Text_SammyPostBattle::
    .string "לפעמים אתה יכול\n"
    .string "למצוא חפצים על האדמה!\p"
    .string "אני מחפש חפץ שהפלתי!$"

ViridianForest_Text_AnthonyIntro::
    .string "אולי אני קטן, אבל אני לא אוהב\n"
    .string "כשמתייחסים אליי בקלות!$"

ViridianForest_Text_AnthonyDefeat::
    .string "אוי, חבל.\n"
    .string "שום דבר לא הלך כמו שצריך.$"

ViridianForest_Text_AnthonyPostBattle::
    .string "הפסדתי קצת מהקצבה שלי…$"

ViridianForest_Text_CharlieIntro::
    .string "ידעת שפוקימונים מתפתחים?$"

ViridianForest_Text_CharlieDefeat::
    .string "אוי!\n"
    .string "הפסדתי!$"

ViridianForest_Text_CharliePostBattle::
    .string "פוקימוני חרק מתפתחים מהר.\n"
    .string "הם ממש מהנים!$"

ViridianForest_Text_RanOutOfPokeBalls::
    .string "נגמרו לי\n"
    .string "הפוקיבולים לתפוס איתם פוקימונים!\p"
    .string "כדאי שתמיד יהיו לך כמה ספיירים!$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
    .string "טיפים למאמנים\p"
    .string "אם אתה רוצה להימנע מקרבות,\l"
    .string "תתרחק מהדשא!$"

ViridianForest_Text_UseAntidoteForPoison::
    .string "השתמש בנוגדן כדי\n"
    .string "לרפא הרעלה! אפשר לקנות אותם\l"
    .string "בפוקיוסק!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
    .string "טיפים למאמניםאם תיצור קשר דרך\n"
    .string "המחשב עם פרופ' אוק, הוא ייתן לך\l"
    .string "ציון על הפוקדקס שלך!$"

ViridianForest_Text_CantCatchOwnedMons::
    .string "טיפים למאמנים\p"
    .string "אסור לגנוב פוקימונים ממאמנים\l"
    .string "אחרים! תפוס פוקימונים רק בטבע!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
    .string "טיפים למאמנים\p"
    .string "החלש את הפוקימונים לפני שתנסה\l"
    .string "לתפוס אותם!\p"
    .string "אם הם בריאים, הם עלולים לברוח!$"

ViridianForest_Text_LeavingViridianForest::
    .string "יציאה\n"
    .string "מיער וירידיאן בהמשך הדרך:\l"
    .string "העיר פיוטר$"
