SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
    .string "אולי אני לא נראה משהו עכשיו,\n"
    .string "אבל כשהייתי צעיר…\p"
    .string "טסתי לכל מקום וקראתי תיגר\n"
    .string "על מאמנים בכל פינה.\p"
    .string "היום ההנאה היחידה שלי היא\n"
    .string "להיזכר בעבר בזמן\l"
    .string "שאני צופה בקרבות.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
    .string "רוח קלה נושבת\n"
    .string "סביב הארגז.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
    .string "אה!\n"
    .string "ברוך הבא, ידידי!\p"
    .string "תן לי לספר לך משהו. יש\n"
    .string "חדר סודי במרתף.\p"
    .string "מאמן בשם {STR_VAR_1}\n"
    .string "מחכה שם עכשיו.\p"
    .string "תגיד לי, באת כדי להתמודד\n"
    .string "מול {STR_VAR_1}, נכון?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
    .string "אוה…\n"
    .string "אתה לא רוצה להילחם…\p"
    .string "אני מבין, אני מבין.\n"
    .string "… …\p"
    .string "טוב, אם תשנה את דעתך,\n"
    .string "תחזור לכאן.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
    .string "אה!\n"
    .string "אתה תילחם בשבילי?\p"
    .string "אז היה שווה להזיז את\n"
    .string "הארגז הצידה.\p"
    .string "… …\n"
    .string "אבל יש בעיה קטנה אחת.\p"
    .string "החדר הסודי הזה לא בנוי\n"
    .string "חזק במיוחד.\p"
    .string "אפשר להגביל את הקרב\n"
    .string "לשלושה פוקימונים לכל צד?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
    .string "מצוין! לפני הקרב, תרצה\n"
    .string "לשמור את המשחק?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
    .string "בסדר גמור.\n"
    .string "אל תחסוך בכלום!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_1::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
    .string "הקרב הסתיים בתיקו.$"

SevenIsland_House_Room1_Text_DrawWasIt::
    .string "תיקו, אה?\p"
    .string "ובכל זאת, אני חייב לומר\n"
    .string "שזה היה מחזה ראוי.\p"
    .string "הייתי אומר שזה היה קרב נפלא\n"
    .string "עם עומק אמיתי!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_2::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
    .string "בראבו!\p"
    .string "בראבו, באמת!\n"
    .string "איזה קרב מדהים!\p"
    .string "הוא היה כל כך מדהים,\n"
    .string "שהעיניים שלי מתמלאות דמעות!\p"
    .string "הדקירות והחסימות של טכניקות\n"
    .string "שהופעלו במומחיות!\p"
    .string "התנגשות של כוח בכוח!\p"
    .string "כן!\n"
    .string "זה היה פשוט מרהיב!$"

@ Unused
SevenIsland_House_Room1_Text_StrVar1_3::
    .string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
    .string "חבל מאוד!\n"
    .string "אני מרגיש את האכזבה שלך.\p"
    .string "אבל דווקא האכזבה הזאת\n"
    .string "היא שתהפוך אותך לטוב יותר.\p"
    .string "השתמש בה, למד ממנה, ותן לה\n"
    .string "להניע אותך לשאוף לגדולה.\p"
    .string "אל תשכח את האכזבה הזאת\n"
    .string "והכפל את האימונים שלך!$"
