FiveIsland_House1_JPText_HusbandWentOffFishing::
    .string "こんばんの　おかずは\n"
    .string "ようい　しなくて　いいぞ！\p"
    .string "って　だんなが\n"
    .string "つりに　いったん　だけど‥\l"
    .string "しんじて　いいのかねえ$"

FiveIsland_House1_Text_HusbandWentOffFishing::
    .string "אין צורך להכין משהו\n"
    .string "לארוחת הערב היום!\p"
    .string "…זה מה שבעלי אמר כשהוא\n"
    .string "יצא לדוג היום.\p"
    .string "אני לא בטוחה שאפשר לסמוך\n"
    .string "עליו שיעמוד בהבטחה.$"

