MtMoon_B2F_Text_MiguelIntro::
    .string "היי, עצור!\p"
    .string "מצאתי את המאובנים האלה!\n"
    .string "הם שניהם שלי!$"

MtMoon_B2F_Text_MiguelDefeat::
    .string "בסדר!\n"
    .string "אני אשתף!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
    .string "כל אחד מאיתנו ייקח מאובן!\n"
    .string "בלי להיות חמדנים!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
    .string "בסדר גמור.\n"
    .string "אז המאובן הזה שלי!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
    .string "באי קנבר הרחוק,\n"
    .string "יש מעבדה לפוקימונים.\p"
    .string "הם חוקרים איך להחיות מאובנים.$"

MtMoon_B2F_Text_Grunt1Intro::
    .string "אנחנו, צוות רוקט, נמצא את\n"
    .string "המאובנים!\p"
    .string "להחיות פוקימונים מהם יכניס לנו\n"
    .string "עושר עצום!$"

MtMoon_B2F_Text_Grunt1Defeat::
    .string "אוף!\n"
    .string "עכשיו אני עצבני!$"

MtMoon_B2F_Text_Grunt1PostBattle::
    .string "עשית אותי עצבני!\n"
    .string "צוות רוקט יכניס אותך לרשימה\l"
    .string "השחורה!$"

MtMoon_B2F_Text_Grunt2Intro::
    .string "אנחנו, צוות רוקט, גנגסטרים\n"
    .string "של פוקימונים!\l"
    .string "אנחנו זורעים פחד עם הכוח שלנו!$"

MtMoon_B2F_Text_Grunt2Defeat::
    .string "הרסתי את זה!$"

MtMoon_B2F_Text_Grunt2PostBattle::
    .string "אוי ואבוי!\n"
    .string "החברים שלי לא יקבלו את זה!$"

MtMoon_B2F_Text_Grunt3Intro::
    .string "אנחנו מבצעים פה עבודה גדולה!\n"
    .string "תסתלק, ילד!$"

MtMoon_B2F_Text_Grunt3Defeat::
    .string "אז, אתה טוב…$"

MtMoon_B2F_Text_Grunt3PostBattle::
    .string "אם תמצא מאובן, תן לי אותו\n"
    .string "ותתחפף!$"

MtMoon_B2F_Text_Grunt4Intro::
    .string "ילדים קטנים לא צריכים להתעסק\n"
    .string "עם מבוגרים!\p"
    .string "זה עלול להיגמר רע!$"

MtMoon_B2F_Text_Grunt4Defeat::
    .string "אני ממש עצבני!$"

MtMoon_B2F_Text_Grunt4PostBattle::
    .string "פוקימונים חיו כאן הרבה לפני\n"
    .string "שבני האדם הגיעו.$"

MtMoon_B2F_Text_YouWantDomeFossil::
    .string "אתה רוצה את מאובן הכיפה?$"

MtMoon_B2F_Text_YouWantHelixFossil::
    .string "אתה רוצה את מאובן הסליל?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
    .string "השגת את מאובן הסליל!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
    .string "השגת את מאובן הכיפה!$"
