FiveIsland_LostCave_Room1_Text_LawsonIntro::
    .string "אאאאיייי!\p"
    .string "חשבתי שזו חורבה עתיקה.\n"
    .string "אבל המקום שורץ רוחות רפאים!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
    .string "אאאאיייי!\n"
    .string "רחמים!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
    .string "אני מנסה לצאת מכאן, אבל\n"
    .string "אני תמיד חוזר לאותו מקום.\p"
    .string "אולי מספר הסלעים\n"
    .string "הוא רמז…$"

