TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
    .string "נו, לאן נעלמה לוסטל\n"
    .string "היום?\p"
    .string "היא תמיד מביאה לי ארוחת\n"
    .string "צהריים בדיוק בשעה הזאת…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
    .string "המ? אתה, שם!\n"
    .string "אתה חבר של לוסטל?\p"
    .string "ראית את לוסטל במקרה?\n"
    .string "אין לי מושג איפה היא.\l"
    .string "היא הייתה אמורה להגיע מזמן.\p"
    .string "לוסטל היא חמודה - ירשה את\n"
    .string "המראה שלי - אז מה אם מישהו…\p"
    .string "מה אם קרה משהו\n"
    .string "ללוסטל שלי?!\p"
    .string "בבקשה, עזור לי למצוא אותה!\n"
    .string "לך לחפש אותה באי 3!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
    .string "הא? זאת נקראת משחקיה?\n"
    .string "יותר עלוב מזה כבר אין.\p"
    .string "הליצנים האלה…\p"
    .string "הם אמרו שהם יחכו לי באי,\n"
    .string "אז איפה הם?\p"
    .string "היי, אתה! יש כאן עוד אי 3\n"
    .string "חוץ מהאי הזה?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
    .string "תנסה להתעורר לפני שאתה\n"
    .string "קם מהמיטה, פרחח.\p"
    .string "זה אי 2!\p"
    .string "זוז! תוציא את האופנוע\n"
    .string "המלוכלך שלך מהמקום שלי!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
    .string "הא…\n"
    .string "אה, אה, הבנתי.\p"
    .string "צ'ה…\n"
    .string "האיים האלה מבלבלים…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
    .string "תראה מה קרה כאן.\n"
    .string "הפרחח הזה שרט לי את הרצפה.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
    .string "היי, תקשיב! אני מתחנן,\n"
    .string "אתה חייב ללכת לאי 3.\p"
    .string "אם יקרה משהו ללוסטל\n"
    .string "שלי…\p"
    .string "הבית שלי הוא זה עם הגג\n"
    .string "האדום באי 3.\p"
    .string "היא עוד עלולה להגיע לכאן,\n"
    .string "אז אני לא יכול לזוז מפה.\p"
    .string "בגלל זה אני מבקש ממך\n"
    .string "את הטובה הגדולה הזאת.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
    .string "אני מצטער.\n"
    .string "היום אין אצלנו משחקים.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
    .string "בקרוב נפעיל את המשחקים\n"
    .string "במיוחד בשבילך!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
    .string "אז אתה הצלת את לוסטל?\n"
    .string "איך אוכל להודות לך?\p"
    .string "לוסטל, מותק, סלחי לי!\p"
    .string "אבא לא ידע שפחדת\n"
    .string "ושהיית בצרה!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
    .string "לוסטל: זה בסדר, אבא.\n"
    .string "התיידדתי עם {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
    .string "הו, מה זה?\n"
    .string "אתה אומר שזה בשבילי?\p"
    .string "איך ידעת שאני מת על אבנים\n"
    .string "ואבני חן נדירות?\p"
    .string "אתה באמת יודע איך לשמח\n"
    .string "בן אדם.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
    .string "{PLAYER} מסר את המטאוריט\n"
    .string "לאבא של לוסטל.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
    .string "הו, הבנתי, זה מביל!\n"
    .string "תמסור לו תודה ממני!\p"
    .string "אתה יודע, היית מדהים.\n"
    .string "אני רוצה שתיקח את זה.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
    .string "{PLAYER} קיבל אבן ירח\n"
    .string "מאבא של לוסטל.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
    .string "בתיק שלך לא ייכנס עוד\n"
    .string "שום דבר…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
    .string "בסדר גמור, אני מפעיל את\n"
    .string "המשחקיה מיד.\p"
    .string "אתה חייב לבוא לבקר\n"
    .string "יחד עם חבר.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
    .string "תשמע, תשמע!\p"
    .string "בבקשה תראה לי שוב כמה\n"
    .string "אתה מגניב!$"
