Route22_Text_EarlyRivalIntro::
	.string "{RIVAL}: היי! {PLAYER}!\p"
	.string "אתה בדרך לליגת הפוקימונים?\n"
	.string "שכח מזה!\p"
	.string "כנראה שאין לך בכלל\n"
	.string "תגים, נכון?\p"
	.string "השומר לא ייתן לך לעבור\n"
	.string "בלעדיהן.\p"
	.string "דרך אגב, הפוקימונים שלך\n"
	.string "נהיו חזקים יותר?$"

Route22_Text_EarlyRivalDefeat::
	.string "אוף!\n"
	.string "פשוט היה לך מזל!$"

Route22_Text_EarlyRivalPostBattle::
	.string "שמעתי שליגת הפוקימונים מלאה\n"
	.string "במאמנים חזקים במיוחד.\p"
	.string "אני חייב להבין איך לעבור\n"
	.string "אותם.\p"
	.string "אתה צריך להפסיק לבזבז זמן\n"
	.string "ולצאת לדרך!$"


@ Translated in RB as "{RIVAL}: What? Why do I have 2 POKéMON? You should catch some more too!"
Route22_Text_RivalShouldCatchSomeMons::
	.string "{RIVAL}“なんだ？\n"
	.string "ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも\n"
	.string "つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
    .string "{RIVAL}: מה? {PLAYER}!\n"
    .string "איזו הפתעה לראות אותך כאן!\p"
    .string "אז אתה הולך לליגת פוקימון?\n"
    .string "אספת את כל התגים גם?\p"
    .string "זה מגניב!\p"
    .string "אז אני אתמודד איתך, {PLAYER},\n"
    .string "כחימום לליגת פוקימון!\p"
    .string "בוא נתחיל!$"

Route22_Text_LateRivalDefeat::
    .string "מה!?\p"
    .string "הייתי פשוט לא זהיר, אתה!$"

Route22_Text_LateRivalPostBattle::
    .string "זה הרפה אותי.\n"
    .string "אני מוכן לליגת פוקימון!\p"
    .string "{PLAYER}, אתה צריך יותר תרגול.\p"
    .string "אבל היי, אתה יודע את זה!\n"
    .string "אני יוצא מכאן. נתראה!$"


@ Translated in RB as "{RIVAL}: Hahaha! {PLAYER}! That's your best? You're nowhere near as good as me, pal! Go train some more! You loser!"
Route22_Text_LateRivalVictory::
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！\n"
	.string "それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！\n"
	.string "あははーッ！$"

Route22_Text_LeagueGateSign::
    .string "ליגת פוקימון\n"
    .string "שער קדמי$"

