OneIsland_TreasureBeach_Text_AmaraIntro::
    .string "לשכב ולהתנדנד עם הגלים…\n"
    .string "זה פשוט מושלם.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
    .string "הפסדתי…\n"
    .string "זו הרגשה נוראית.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
    .string "המים באזור הזה חמימים\n"
    .string "ונעימים להפליא.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
    .string "הזרם באוקיינוס שוטף דברים\n"
    .string "טובים אל החוף הזה.\p"
    .string "לכן אני בא לכאן לעיתים\n"
    .string "קרובות לחטט בחול.$"

