SilphCo_11F_Text_ThanksForSavingMeDearBoy::
    .string "נשיא: או, ילד יקר!\n"
    .string "תודה שהצלת את סילפ.\p"
    .string "אני לא אשכח לעולם שאתה הצלת אותנו\n"
    .string "ברגעי הסכנה.\p"
    .string "אני חייב להודות לך איכשהו.\p"
    .string "מכיוון שאני עשיר, אני יכול לתת לך\n"
    .string "כל דבר.\p"
    .string "הנה, אולי זה יתאים.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
    .string "נשיא: או, ילדה יקרה!\n"
    .string "תודה שהצלת את סילפ.\p"
    .string "אני לא אשכח לעולם שאתה הצלת אותנו\n"
    .string "ברגעי הסכנה.\p"
    .string "אני חייב להודות לך איכשהו.\p"
    .string "מכיוון שאני עשיר, אני יכול לתת לך\n"
    .string "כל דבר.\p"
    .string "הנה, אולי זה יתאים.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
    .string "{PLAYER} קיבל את המאסטרבול\n"
    .string "מהנשיא!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
    .string "נשיא: אתה לא יכול לקנות את זה\n"
    .string "בכל מקום.\p"
    .string "זהו המאסטרבול שלנו, אבטיפוס סודי.\p"
    .string "הוא יתפוס כל פוקימון ללא\n"
    .string "כישלון!\p"
    .string "אתה צריך לשמור על השימוש בו בסוד,\n"
    .string "למרות זאת.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
    .string "אין לך מקום לזה.$"

SilphCo_11F_Text_ThanksForRescuingUs::
    .string "מזכירה: תודה שהצלת אותנו\n"
    .string "כולנו, מהנשיא ועד לאחרים,\l"
    .string "חייבים לך תודה.$"

SilphCo_11F_Text_GiovanniIntro::
    .string "אה, {PLAYER}!\n"
    .string "אז נפגשנו שוב!\p"
    .string "הנשיא ואני דנים\n"
    .string "בעסקה חשובה.\p"
    .string "תשמור את האף שלך רחוק מעניין\n"
    .string "של מבוגרים…\p"
    .string "או שתתנסה בעולם של כאב!$"

SilphCo_11F_Text_GiovanniDefeat::
    .string "אררך!!\n"
    .string "הפסדתי שוב!?$"

SilphCo_11F_Text_GiovanniPostBattle::
    .string "קללה!\n"
    .string "הרסו את התוכניות שלנו עבור סילפ!\p"
    .string "אבל, צוות רוקט לא יפול!\p"
    .string "{PLAYER}! אל תשכח כי כל\n"
    .string "הפוקימונים קיימים עבור צוות רוקט!\p"
    .string "אני חייב ללכת, אך אשוב!$"

SilphCo_11F_Text_Grunt2Intro::
    .string "תעצור שם!\n"
    .string "אל תזוז!$"

SilphCo_11F_Text_Grunt2Defeat::
    .string "אל…\n"
    .string "בבקשה!$"

SilphCo_11F_Text_Grunt2PostBattle::
    .string "אז, אתה רוצה לראות את הבוס שלי?$"

SilphCo_11F_Text_Grunt1Intro::
    .string "חכה! יש לך פגישה\n"
    .string "עם הבוס שלי?$"

SilphCo_11F_Text_Grunt1Defeat::
    .string "גאאה!\n"
    .string "חוסלתי!$"

SilphCo_11F_Text_Grunt1PostBattle::
    .string "שמור על צעדיך… הבוס שלי אוהב את\n"
    .string "הפוקימונים שלו קשים!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
    .string "למסך יש פוקימונים עליו!$"

SilphCo_11F_Text_FloorSign::
    .string "סילפקו. משרד ראשי\n"
    .string "קומה 11$"
