PokemonMansion_Text_PressSecretSwitch::
    .string "מתג סודי!\p"
    .string "ללחוץ עליו?$"

PokemonMansion_Text_WhoWouldnt::
    .string "מי לא היה?$"

PokemonMansion_Text_NotQuiteYet::
    .string "עדיין לא!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "אני לא יכול לצאת!\n"
    .string "המקום הישן הזה הוא פאזל אחד גדול.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "אוי, לא!\n"
    .string "שק השלל שלי!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "המתגים כאן פותחים וסוגרים\n"
    .string "סטים מתחלף של דלתות.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "יומן: 5 ביולי\n"
    .string "גיאנה, דרום אמריקה\p"
    .string "פוקימון חדש התגלה עמוק\n"
    .string "בג'ונגל.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "יומן: 01 ביולי\n"
    .string "קראנו לפוקימון החדש\l"
    .string "שהתגלה, מייו.$"
