CinnabarIsland_Gym_Text_BlaineIntro::
    .string "אה!\p"
    .string "אני בליין! אני המנהיג של\l"
    .string "מכון סינאבאר!\p"
    .string "הפוקימונים הלוהטים שלי\l"
    .string "יבעירו כל אתגר שיעמוד בפניהם!\p"
    .string "חה! אני מקווה שהבאת רפא כויה!$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "אני...\n"
    .string "הפסדתי\p"
    .string "הרווחת ביושר את תג המגמה!{}$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "אש מתפרצת היא\n"
    .string "מתקפת האש האולטימטיבית!\p"
    .string "אל תבזבז אותה על פוקימוני מים!$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "חה!\p"
    .string "תג המגמה מגביר את\l"
    .string "היכולות המיוחדות של הפוקימון שלך!\p"
    .string "הנה תיקח גם את זה!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} קיבל\n"
    .string "{} !{}$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "מ”מ83 מכיל\n"
    .string "את המתקפה אש מתפרצת!\p"
    .string "למד פוקימון אש את המתקפה הזו!\p"
    .string "היא תתאים נביל לצ'רמיליון או\l"
    .string "לפוניטה!$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "פנה מקום בשביל\n"
    .string "המתנה הזו!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "אתה יודע כמה\n"
    .string "נשימת פוקימון אש חמה?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "יו!\n"
    .string "חם, חם, חם!\p$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "אש,\n"
    .string "או ליתר דיוק, בעירה...\p"
    .string "בלה, בלה, בלה, בלה...$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "הייתי גנב, אבל\n"
    .string "עברתי לדרך הישר כמאמן!$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "אני\n"
    .string "נכנע!\p$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "אני לא יכול\n"
    .string "להפסיק לגנוב פוקימונים של\l"
    .string "אנשים אחרים!$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "אתה לא תנצח!\n"
    .string "אני למדתי פוקימון אינספור שעות!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "ואא!\n"
    .string "הלמידה שלי לא הייתה טובה מספיק!\p$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "התיאוריות שלי\n"
    .string "מורכבות מידי עבורך!$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "אני פשוט נהנה\n"
    .string "להשתמש בפוקימוני אש!$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "אתה לוהט\n"
    .string "מדי!\p$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "הלוואי והיה\n"
    .string "פוקימון גנב! הייתי משתמש בו!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "אני יודע למה בליין\n"
    .string "נהפך למאמן!$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "או!\p$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "כשבליין היה אבוד\n"
    .string "בהרים, פוקימון ציפור אש נגלתה\l"
    .string "בפניו.\p"
    .string "האור שלה הראה לבליין את דרכו\l"
    .string "החדשה!$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "הייתי בהרבה\n"
    .string "מכונים, אבל זה המועדף עליי!$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "אווץ'!\n"
    .string "עשית לי כויה!\p$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "מעריצי פוקימוני אש\n"
    .string "כמונו אוהבים את\l"
    .string "פוניטה וניינטיילס!$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "אש לא אפקטיבית\n"
    .string "מול O2H!$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "הו!\n"
    .string "חוסלתי!\p$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "מים מנצח אש!\n"
    .string "אבל אש ממיס פוקימוני קרח!$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "יו! \n"
    .string "אלופצ'יק!\p"
    .string "בליין חמום המוח מומחה בפוקימוני\l"
    .string "אש!\p"
    .string "חסל אותו עם סוגי מים!\p"
    .string "וכדאי שתיקח איתך כמה רפא כויה!$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}! ניצחת\n"
    .string "את מומחה האש!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "מכון הפוקימונים סינאבאר\n"
    .string "מנהיג: בליין\p"
  .string "מאמנים שניצחו:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים סינאבאר\n"
    .string "מנהיג: בליין\p"
  .string "מאמנים שניצחו:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "מבחן על פוקימון!\p"
    .string "תצדוק, והדלת תיפתח\n"
    .string "לחדר הבא.\p"
    .string "תטעה, ותאלץ להתמודד מול מאמן!\p"
    .string "אם אתה רוצה לשמוא על הפוקימונים\n"
    .string "שלך לפני הקרב עם מנהיג המכון…\p"
    .string "אז כדאי שתצליח לענות נכון!\n"
    .string "בוא נתחיל!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "קטרפי מתפתח למטפוד?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "יש 9 תגים שמוכרים על ידי\n"
    .string "ליגת הפוקימונים?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "פוליוואג מתפתח 3 פעמים?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "מהלכים מסוג חשמל עובדים טוב\n"
    .string "נגד פוקימונים מסוג אדמה?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "פוקימונים מאותו הסוג ובאותה רמה\n"
    .string "הם לא זהים?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "מ“מ82 מכיל את המהלך חופרבראש?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "אתה צודק!\p"
    .string "תתקדם הלאה!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "מצטער!\n"
    .string "זו טעות!$"

