Route25_SeaCottage_Text_ImBillHelpMeOutPal::
    .string "שלום! אני פוקימון...\n"
    .string "...לא, אני לא!\p"
    .string "תקרא לי ביל!\n"
    .string "אני פוקמניאק אמיתי!\p"
    .string "היי!\n"
    .string "מה עם המבט הסקפטי הזה?\p"
    .string "אני לא מותח אותך, חבר.\p"
    .string "טעיתי בניסוי והתחברתי עם פוקימון!\p"
    .string "אז, מה דעתך?\n"
    .string "עזור לי כאן!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
    .string "שלום! אני פוקימון...\n"
    .string "...לא, אני לא!\p"
    .string "תקרא לי ביל!\n"
    .string "אני פוקמניאק אמיתי!\p"
    .string "היי!\n"
    .string "מה עם המבט הסקפטי הזה?\p"
    .string "אני לא מותח אותך, גברת.\p"
    .string "טעיתי בניסוי והתחברתי עם פוקימון!\p"
    .string "אז, מה דעתך?\n"
    .string "עזור לי כאן!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
    .string "חכה עד שאכנס לטלפורטר.\n"
    .string "כשאני שם, לך למחשב שלי\p"
    .string "והרץ את מערכת הפרדת התאים.$"

Route25_SeaCottage_Text_NoPleaseChief::
    .string "לא!?\n"
    .string "עכשיו אל תהיה כל כך קר!\p"
    .string "בוא, אתה חייב לעזור לאדם בצרות!\p"
    .string "מה אתה אומר, חבר?\n"
    .string "בבקשה?\l"
    .string "בסדר?\l"
    .string "טוב!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
    .string "לא!?\n"
    .string "עכשיו אל תהיה כל כך קר!\p"
    .string "בוא, אתה חייב לעזור לאדם בצרות!\p"
    .string "מה אתה אומר,?\n"
    .string "בבקשה?\l"
    .string "בסדר?\l"
    .string "טוב!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
    .string "ביל: יי הא!\n"
    .string "תודה, חבר! אני חייב לך אחת!\p"
    .string "אז, באת לראות את האוסף פוקימון\n"
    .string "שלי?\p"
    .string "לא?\n"
    .string "זה מאכזב.\p"
    .string "אני חייב להודות לך...\n"
    .string "הנה, אולי זה יעשה את העבודה.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
    .string "ביל: יי הא!\n"
    .string "תודה, גברת! אני חייב לך אחת!\p"
    .string "אז, באת לראות את האוסף פוקימון\n"
    .string "שלי?\p"
    .string "לא?\n"
    .string "זה מאכזב.\p"
    .string "אני חייב להודות לך...\n"
    .string "הנה, אולי זה יעשה את העבודה.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
    .string "{PLAYER} קיבל כרטיס ס.ס. מביל.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
    .string "יש לך יותר מדי דברים!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
    .string "ספינת השייט ס.ס. אן נמצאת בעיר\n"
    .string "ורמיליון.\p"
    .string "שמעתי שיש שם הרבה מאמנים על\n"
    .string "הסיפון, גם כן.\p"
    .string "הם הזמינו אותי למסיבה שלהם, אבל\n"
    .string "אני לא סובל מסיבות מפוארות.\p"
    .string "למה שלא תלך במקומי?\n"
    .string "לך ותהנה.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
    .string "ביל: רוצה לבדוק כמה מהפוקימונים\n"
    .string "הנדירים שלי במחשב שלי?\p"
    .string "לך, תבדוק את המחשב שלי.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
    .string "הטלפורטר מוצג על מסך המחשב.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
    .string "{PLAYER} התחיל את מערכת הפרדת\n"
    .string "התאים של הטלפורטר.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
    .string "רשימת הפוקימונים המועדפים על ביל!$"

Route25_SeaCottage_Text_SeeWhichMon::
    .string "איזה פוקימון אתה רוצה לראות?$"
