Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
    .string "האבק של הפוקימון שלי מאוחסן\n"
    .string "במגדל של הפוקימון.\p"
    .string "אתה יכול לקחת את המ”מ הזה.\n"
    .string "לא צריך אותו יותר…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
    .string "האבק של הפוקימון שלי מאוחסן\n"
    .string "במגדל של הפוקימון.\p"
    .string "את יכולה לקחת את המ”מ הזה.\n"
    .string "לא צריכה אותו יותר…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
    .string "{PLAYER} קיבל את מ”מ72\n"
    .string "מהילדה הקטנה.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
    .string "מ”מ72 הוא מהלך שנקרא חזור…\p"
    .string "אם תתייחס לפוקימון שלך טוב, הוא\n"
    .string "יחזיר לך את האהבה על ידי עבודה\l"
    .string "הכי קשה שלו בקרב.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
    .string "אין לך מקום לזה.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
    .string "בוא נראה מה יש במשקפת\n"
    .string "להראות…\p"
    .string "יש שם גבר דג במים!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
    .string "בוא נראה מה יש במשקפת\n"
    .string "להראות…\p"
    .string "זהו מגדל הפוקימון!$"
