CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
    .string "הגעתי לכאן כדי לבקר את המכון\n"
    .string "אבל הדלת נעולה.\p"
    .string "כנראה יש מפתח איפשהו.\p"
    .string "יכול להיות שהוא באחוזה השרופה\n"
    .string "הזו\p"
    .string "חבר של מנהיג המכון גר שם פעם\n"
    .string "או לפחות ככה שמעתי.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
    .string "אתה יכול לבטל\n"
    .string "התפתחות.\p"
    .string "כאשר פוקימון מתפתח, אתה יכול\n"
    .string "לעברוק את ההתפתחות ולהשאיר\l"
    .string "אותו כמו שהוא.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
    .string "יש לך חברים?\p"
    .string "פוקימונים שאתה מקבל בהחלפות\l"
    .string "גדלים מהר מאוד.\p"
    .string "אני חושב שזה שווה ניסיון!$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
    .string "ביל: היי, אני מחכה לך!\n"
    .string "מוכן לשוט לאי מספר 1?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
    .string "אה, עדיין עסוק?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
    .string "בסדר גמור.\n"
    .string "בוא נזוז!$"

