PokemonTower_2F_Text_RivalIntro::
    .string "{RIVAL}: היי, {PLAYER}!\n"
    .string "מה מביא אותך לכאן?\l"
    .string "האם הפוקימון שלך מת?\p"
    .string "היי! הוא חי!\p"
    .string "אני יכול לפחות לגרום לו להתעלף!\n"
    .string "בוא נתחיל!$"

PokemonTower_2F_Text_RivalDefeat::
    .string "מה?\n"
    .string "אתה רמאי!\p"
    .string "התאפקתי גם ככה!$"

@ Unused. Translated below
@ Aw, man! They really kicked the bucket! Weak! Do them a favor and raise them more properly.
PokemonTower_2F_Text_RivalVictory::
    .string "{RIVAL}: אה, אוף...!\n"
    .string "הם באמת נכשלו!\l"
    .string "חלשים!\l"
    .string "תגדל אותם יותר טוב!$"

PokemonTower_2F_Text_RivalPostBattle::
    .string "איך מתקדם הפוקידקס שלך?\n"
    .string "זה עתה תפסתי קיובון!\p"
    .string "אני לא מצליח למצוא את המרוואק\n"
    .string "הגדול. איפה הם יכולים להיות?\p"
    .string "אני בטוח שלא נשארו כאלה!\p"
    .string "טוב, אני חייב ללכת.\n"
    .string "יש לי הרבה להשיג,\l"
    .string "בניגוד אליך.\p"
    .string "נתראה!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
    .string "אפילו אנחנו לא הצלחנו לזהות\n"
    .string "את הרוחות התועות.\p"
    .string "משקפת סילף אולי תוכל\n"
    .string "לחשוף אותן.$"
