CeruleanCity_Gym_Text_MistyIntro::
    .string "היי, אתה חדש פה!\p"
    .string "מאמנים ששואפים להיות מקצוענים\l"
    .string "צריכים שתהיה להם גישה לפוקימונים!\p"
    .string "מה הגישה שלך כלפי\n"
    .string "תפיסת פוקימונים?\p"
    .string "הגישה שלי היא מתקפה בלתי פוסקת\l"
    .string "עם פוקימוני מים{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}!$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "מ”מ30 מלמד את\n"
    .string "המהלך זרם מים!\p"
    .string "השתמש בו על פוקימונים ימיים!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "תג הזהב גורם\n"
    .string "לפוקימונים עד רמה 03 לציית לך!\p"
    .string "זה כולל אפילו פוקימונים שקיבלת\l"
    .string "בהחלפה!\p"
    .string "ויש אפילו עוד, עכשיו אתה יכול\l"
    .string "להשתמש במהלך חיתוך גם מחוץ לקרב!\p"
    .string "אתה יכול לחתוך שיחים קטנים כדי\l"
    .string "לגשת לשבילים חדשים!\p"
    .string "אתה יכול גם לקחת את המ”מ האהוב\l"
    .string "עליי!$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} קיבל\n"
    .string "את מ”מ30 ממיסטי!$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "פנה מקום בתיק\n"
    .string "שלך!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "וואו! אתה\n"
    .string "חזק!\p"
    .string "אוקיי!\p"
    .string "אתה יכול לקחת את תג הזהב שיוכיח\l"
    .string "שניצחת אותי!$"

CeruleanCity_Gym_Text_DianaIntro::
    .string "אני מאתגרת מספיק\n"
    .string "בשבילך!\p"
    .string "מיסטי יכולה לחכות!$"

CeruleanCity_Gym_Text_DianaDefeat::
    .string "כיסחת אותי!\p$"

_CeruleanGymAfterBattleText1::
    .string "צריך להילחם נגד\n"
    .string "מאמנים אחרים כדי לגלות עד כמה חזק\l"
    .string "אתה באמת.$"

CeruleanCity_Gym_Text_LuisIntro::
    .string "שפריץ!\p"
    .string "הקרב הראשון הוא נגדי! בוא נילחם!$"

CeruleanCity_Gym_Text_LuisDefeat::
    .string "אין\n"
    .string "מצב!\p$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "מיסטי רק ממשיכה\n"
    .string "להשתפר!\p"
    .string "היא לא תפסיד מול מישהו כמוך!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
    .string "יו!\n"
    .string "אלופצ'יק!\p"
    .string "שמע עצה!\p"
    .string "מנהיגת המכון מיסטי, היא מקצוענית\l"
    .string "שמשתמשת רק בפוקימוני מים!\p"
    .string "אתה יכול לשתות לה את כל המים עם\l"
    .string "פוקימוני צמח!\p"
    .string "או שתהמם אותם עם חשמל!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
    .string "ניצחת את מיסטי!\n"
    .string "בול כמו שאמרתי!\p"
    .string "אחי, אתה ואני, אנחנו צוות די\l"
    .string "מוצלח!$"

CeruleanCity_Gym_Text_GymStatue::
    .string "מכון הפוקימונים סרוליאן\n"
    .string "מנהיג: מיסטי\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים סרוליאן\n"
    .string "מנהיג: מיסטי\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}, {PLAYER}$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "אתה צריך להתמודד מול מאמנים אחרים\n"
    .string "כדי להבין כמה טוב אתה באמת.$"
