FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "הו..\n"
    .string "הו, כן, אני מוחק המלהכים\p"
    .string "אני יכול לגרום לפוקימון לשכוח\n"
    .string "מהלך.\p"
    .string "תרצה שאעשה את זה?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "איזה פוקימון תרצה שישכח מהלך?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "איזה מהלך לגרום לו לשכוח?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} יודע רק מהלך אחד...\n"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "הם! לגרום ל{STR_VAR_1} לשכוח את\n"
    .string "{STR_VAR_2}?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "זה עבד מצויין!\p"
    .string "{STR_VAR_1} שכח לגמרי את המהלך\n"
    .string "{STR_VAR_2}.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "תבוא שוב אם יהיו עוד מהלכים\n"
    .string "שתרצה לשכוח.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "מה?\n"
    .string "לביצים אין מהלכים.$"

