Text_DreamEaterTeach::
    .string "פיהוק!\n"
    .string "כנראה נרדמתי בשמש.\p"
    .string "היה לי חלום מוזר על\n"
    .string "דראוזי שאוכל את החלום שלי.\p"
    .string "ואז…\n"
    .string "למדתי איך לאכול חלומות…\p"
    .string "אוי, זה מפחיד מדי!\p"
    .string "תן לי ללמד את זה לפוקימון כדי\n"
    .string "שאוכל לשכוח מזה!$"

Text_DreamEaterDeclined::
    .string "…נחירה…$"

Text_DreamEaterWhichMon::
    .string "איזה פוקימון רוצה ללמוד\n"
    .string "אכילת חלומות?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "אני…לא יכול לאכול…יותר…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "האגדה מספרת\n"
    .string "שקלפרי הן זן שמקורו מהירח!\p"
    .string "הן הופיעו אחרי שאבני ירח נפלו\l"
    .string "בהר הירח.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "אין כאן הרבה מאמני\n"
    .string "פוקימון רציניים!\p"
    .string "כולם כאן, כאילו, אספני חרקים וזה.\n"
    .string "אבל ברוק ממכון פיוטר ממש חזק\l"
    .string "בקטע של אימון!$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "כבר היית במוזיאון?$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "נכון שהמאובנים\n"
    .string "האלה מהר הירח פשוט מרהיבים?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "באמת?\n"
    .string "אתה פשוט חייב לבקר!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "הגענו! כרטיס כניסה\n"
    .string "עולה קצת כסף, אבל זה שווה את זה!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "פסססט!\n"
    .string "אתה יודע מה אני עושה?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "נכון מאוד! זו\n"
    .string "עבודה קשה!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "אני מרסס דוחה כדי\n"
    .string "להרחיק פוקימוני פרא מהגינה שלי!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "אתה מאמן, נכון?\n"
    .string "ברוק ישמח לפגוש אותך! הוא מחפש\l"
    .string "אתגר חדש! בוא אחרי!$"

PewterCity_Text_GoTakeOnBrock::
    .string "אם אתה קורץ מהחומר\n"
    .string "הנכון, לך ונסה להילחם בברוק!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "טיפים למאמנים\p"
    .string "כל פוקימון שמשתתף\n"
    .string "בקרב, אפילו אם רק לרגע, ירוויח\l"
    .string "נקודות נסיון!$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "שימו לב!\p"
    .string "כנופיית גנבים נצפתה גונבת\n"
    .string "מאובנים מהר הירח!\l"
    .string "אם יש בידיכם מידע שיסייע לתפוס את\l"
    .string "הגנבים, פנו למשטרת פיוטר!$"

PewterCity_Text_MuseumOfScience::
    .string "מוזיאון המדע\n"
    .string "העיר פיוטר$"

PewterCity_Text_GymSign::
    .string "העיר פיוטר\n"
    .string "מכון פוקימון מנהיג: ברוק\p"
    .string "מאמן פוקימון קשיח כאבן!$"

PewterCity_Text_CitySign::
    .string "העיר פיוטר\n"
    .string "עיר אפורה כסלע$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "או, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "אני שמח שהצלחתי לתפוס אותך.\n"
    .string "אני העוזר של פרופ' אוק.\p"
    .string "ביקשו ממני למסור לך את זה,\n"
    .string "אז הנה.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} קיבל\n"
    .string "נעלי ריצה מהעוזר.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} החליף את הנעליים\n"
    .string "בנעלי הריצה.$"

PewterCity_Text_ExplainRunningShoes::
    .string "לחץ על כפתור B כדי לרוץ.\n"
    .string "אבל רק איפה שיש מקום לרוץ!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "ובכן, אני חייב לחזור\n"
    .string "למעבדה.\p"
    .string "להתראות!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "מצורף מכתב…\p"
    .string "{PLAYER} יקירי,\p"
    .string "הנה זוג נעלי ריצה\n"
    .string "למתמודד האהוב שלי.\p"
    .string "זכור, תמיד אעודד אותך!\n"
    .string "לעולם אל תוותר!\p"
    .string "מאמא$"
