Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
    .string "שלום! זוכר אותי?\n"
    .string "אני אחד מהעוזרים של פרופ' אוק.\p"
    .string "אם לפוקדקס שלך יש נתונים מלאים על\n"
    .string "{STR_VAR_1} מינים, אני אמור להעניק\l"
    .string "לך פרס.\p"
    .string "פרופ' אוק הפקיד בידי את\n"
    .string "{STR_VAR_2} עבורך.\p"
    .string "אז, {PLAYER}, הרשה לי לשאול.\p"
    .string "האם אספת נתונים על לפחות\n"
    .string "{STR_VAR_1} סוגי פוקימונים?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
    .string "מצוין! תפסת או החזקת {STR_VAR_3}\n"
    .string "סוגי פוקימונים!\p"
    .string "מזל טוב!\n"
    .string "הנה לך!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
    .string "{PLAYER} קיבל את {STR_VAR_2}\n"
    .string "מהעוזר.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
    .string "משתף XP הוא פריט שניתן\n"
    .string "להחזיק על ידי פוקימון.\p"
    .string "הפוקימון יקבל חלק מנקודות הXP\n"
    .string "מבלי להשתתף בקרב.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
    .string "בוא נראה מה מראות המשקפות…\p"
    .string "ציפור גדולה ומבריקה עפה\n"
    .string "לעבר הים.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
    .string "בוא נראה מה מראות המשקפות…\p"
    .string "נראה שיש אי קטן באופק!$"
