Route25_Text_JoeyIntro::
    .string "מאמנים מקומיים באים לכאן כדי\n"
    .string "להתאמן.$"

Route25_Text_JoeyDefeat::
    .string "אתה טוב.$"

Route25_Text_JoeyPostBattle::
    .string "לכל הפוקימונים יש חולשות.\n"
    .string "אפילו לחזקים ביותר.\p"
    .string "זו הסיבה שעדיף לגדל פוקימונים\n"
    .string "מסוגים שונים.$"

Route25_Text_DanIntro::
    .string "אבא לקח אותי למסיבה נהדרת על\n"
    .string "הס.ס. אן בעיר ורמיליון.$"

Route25_Text_DanDefeat::
    .string "אני לא כועס!$"

Route25_Text_DanPostBattle::
    .string "על הס.ס. אן, ראיתי מאמנים\n"
    .string "מרחבי העולם.$"

Route25_Text_FlintIntro::
    .string "אני בחור מגניב.\n"
    .string "יש לי חברה!$"

Route25_Text_FlintDefeat::
    .string "אוי, נו…$"

Route25_Text_FlintPostBattle::
    .string "טוב, חברה שלי תרגיע אותי.$"

Route25_Text_KelseyIntro::
    .string "היי!\n"
    .string "החבר שלי מגניב!$"

Route25_Text_KelseyDefeat::
    .string "המצב הגופני שלי לא הכי טוב…$"

Route25_Text_KelseyPostBattle::
    .string "הלוואי שהחבר שלי היה טוב כמוך.$"

Route25_Text_ChadIntro::
    .string "הייתה לי תחושה…\n"
    .string "ידעתי שאני צריך להילחם בך!$"

Route25_Text_ChadDefeat::
    .string "ידעתי שגם אפסיד!$"

Route25_Text_ChadPostBattle::
    .string "אם הפוקימון שלך מתבלבל,\n"
    .string "החלף אותו.\p"
    .string "זו טקטיקה טובה.$"

Route25_Text_HaleyIntro::
    .string "לחברה שלי יש הרבה פוקימונים\n"
    .string "חמודים. אני כל כך מקנא!$"

Route25_Text_HaleyDefeat::
    .string "אני לא כל כך מקנא!$"

Route25_Text_HaleyPostBattle::
    .string "הגעת מהר מון?\n"
    .string "אפשר לקבל קלפרי?$"

Route25_Text_FranklinIntro::
    .string "הרגע ירדתי מהר מון,\n"
    .string "אבל עדיין יש לי דלק במיכל!$"

Route25_Text_FranklinDefeat::
    .string "עבדת קשה!$"

Route25_Text_FranklinPostBattle::
    .string "ארור!\n"
    .string "זובאט נשך אותי במערה.$"

Route25_Text_NobIntro::
    .string "אני בדרך לראות את אוסף\n"
    .string "הפוקמניאק בכף.$"

Route25_Text_NobDefeat::
    .string "תפסת אותי, וגם טוב,\n"
    .string "מדי!$"

Route25_Text_NobPostBattle::
    .string "הפוקמניאק בהחלט עומד בשמו.\p"
    .string "האוסף שלו כולל מינים נדירים רבים\n"
    .string "של פוקימון.$"

Route25_Text_WayneIntro::
    .string "אתה הולך לראות את ביל?\n"
    .string "קודם כל, נלחם!$"

Route25_Text_WayneDefeat::
    .string "אתה משהו.$"

Route25_Text_WaynePostBattle::
    .string "המסלול שמתחת הוא קיצור דרך לעיר\n"
    .string "סרוליאן.$"

Route25_Text_SeaCottageSign::
    .string "קוטג' ימי\n"
    .string "ביל גר כאן!$"

Route25_Text_MistyHighHopesAboutThisPlace::
    .string "הכף הזה הוא מקום מפורסם לדייטים.\p"
    .string "מיסטי, מנהיגת הג'ים, יש לה\n"
    .string "תקוות גדולות לגבי המקום הזה.$"

Route25_Text_AreYouHereAlone::
    .string "שלום, אתה כאן לבד?\p"
    .string "אם אתה בכף של סרוליאן…\n"
    .string "טוב, זה אמור להיות כזוג.$"
