ThreeIsland_Port_Text_WereKantoRiderFederation::
    .string "אנחנו התאחדות רוכבי קאנטו!\n"
    .string "וררום! ואוואוואוום! וררום!\p"
    .string "לאופנוע שלי אין כוח, אז אני\n"
    .string "חייב להשמיע רעשים בעצמי!$"

ThreeIsland_Port_Text_ForkOverMoney::
    .string "היי, היי, גברת!\n"
    .string "תשחררי קצת כסף לבילויים!$"

ThreeIsland_Port_Text_IllCallThePolice::
    .string "אאאאה!\p"
    .string "מ-מי אתם?!\n"
    .string "א… אני אקרא למשטרה!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
    .string "האופנוענים האלה…\n"
    .string "הם הלכו?\p"
    .string "אוי, תודה לאל!\n"
    .string "הם ממש הפחידו אותי!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
    .string "האופנוענים ברחו,\n"
    .string "ולוסטל נמצאה בשלום.\p"
    .string "הכול הסתדר לטובה!$"
