PalletTown_ProfessorOaksLab_Text_RivalGrampsIsntAround::
    .string "{RIVAL}: יו,\n"
    .string "{PLAYER}! סבא לא כאן!$"

PalletTown_ProfessorOaksLab_Text_RivalFedUpWithWaiting::
    .string "{RIVAL}: סבא!\n"
    .string "נו, נמאס לי כבר לחכות!$"

PalletTown_ProfessorOaksLab_Text_RivalNoFairWhatAboutMe::
    .string "{RIVAL}: היי!\n"
    .string "סבא! מה איתי?$"

PalletTown_ProfessorOaksLab_Text_RivalGoChoosePlayer::
    .string "{RIVAL}: חה,\n"
    .string "אני לא חמדן כמוך! נו, תבחר כבר,\l"
    .string "{PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_RivalIllTakeThisOneThen::
    .string "{RIVAL}: אז אני\n"
    .string "אקח את האחד הזה!$"

PalletTown_ProfessorOaksLab_Text_RivalReceivedMonFromOak::
    .string "{RIVAL} קיבל את {STR_VAR_1}\n"
    .string "מפרופסור אוק!$"

PalletTown_ProfessorOaksLab_Text_RivalMyMonLooksTougher::
    .string "{RIVAL}: הפוקימון\n"
    .string "שלי נראה הרבה יותר חזק.$"

PalletTown_ProfessorOaksLab_Text_RivalLetsCheckOutMons::
    .string "{RIVAL}: חכה\n"
    .string "רגע, {PLAYER}! בוא ננסה קצת\l"
    .string "את הפוקימונים החדשים שלנו!\p"
    .string "קדימה, אני מאתגר אותך לקרב!$"

PalletTown_ProfessorOaksLab_Text_RivalDefeat::
    .string "מה???\n"
    .string "אני לא מאמין! בחרתי את הפוקימון\l"
    .string "הלא נכון!\p$"

Text_RivalVictory::
    .string "{RIVAL}: כן! אני\n"
    .string "מדהים או מה?\p$"

PalletTown_ProfessorOaksLab_Text_RivalGoToughenMyMon::
    .string "{RIVAL}: בסדר!\n"
    .string "אני הולך לגרום לפוקימון שלי\l"
    .string "להילחם כדי שיהיה קצת יותר קשוח!\p"
    .string "{PLAYER}! סבא! נתרחרח אחר-כך!$"

PalletTown_ProfessorOaksLab_Text_RivalGramps::
    .string "{RIVAL}: סבא!$"

PalletTown_ProfessorOaksLab_Text_RivalWhatDidYouCallMeFor::
    .string "{RIVAL}: למה קראת\n"
    .string "לי?$"

PalletTown_ProfessorOaksLab_Text_RivalLeaveItToMeGramps::
    .string "{RIVAL}: אין בעיה,\n"
    .string "סבא! תשאיר את זה לי!$"

PalletTown_ProfessorOaksLab_Text_RivalTellSisNotToGiveYouMap::
    .string "{PLAYER}, לא נעים\n"
    .string "לי לומר, אבל אני\l"
    .string "לא צריך את עזרתך!\p"
    .string "יש לי רעיון! אני אבקש מאחותי\l"
    .string "לשאול ממנה מפה!\p"
    .string "אני אומר לה שלא תשאיל לך מפה,\l"
    .string "{PLAYER}! חה חה!$"

PalletTown_ProfessorOaksLab_Text_OakThreeMonsChooseOne::
    .string "אוק: {RIVAL}?\n"
    .string "תן לי להיזכר...\p"
    .string "אה, נכון, קראתי לך לכאן! חכה רגע!\p"
    .string "הנה, {PLAYER}!\p"
    .string "יש 3 פוקימונים על השולחן!\p"
    .string "איפה? חה חה!\p"
    .string "הם בתוך הפוקיבולים.\p"
    .string "הייתי מאמן פוקימון רציני בזמני!\p"
    .string "עכשיו כשאני מבוגר, נשארו לי רק 3,\l"
    .string "אבל אתה יכול לקחת אחד! בחר!$"

PalletTown_ProfessorOaksLab_Text_OakBePatientRival::
    .string "אוק: סבלנות,\n"
    .string "{RIVAL}! גם אתה תקבל אחד!$"

PalletTown_ProfessorOaksLab_Text_OakWhichOneWillYouChoose::
    .string "אוק: {PLAYER},\n"
    .string "בתוך שלושת הפוקיבולים האלו\l"
    .string "ישנם פוקימונים.\l"
    .string "איזה מהם תבחר לעצמך?$"

PalletTown_ProfessorOaksLab_Text_OakHeyDontGoAwayYet::
    .string "אוק: היי! עדיין\n"
    .string "לא בחרת!$"

PalletTown_ProfessorOaksLab_Text_OakChoosingCharmander::
    .string "אז אתה רוצה את\n"
    .string "פוקימון האש, צ'רמנדר?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingSquirtle::
    .string "אז אתה רוצה את\n"
    .string "פוקימון המים, סקווירטל?$"

PalletTown_ProfessorOaksLab_Text_OakChoosingBulbasaur::
    .string "אז אתה רוצה את\n"
    .string "פוקימון הדשא, בלבאזור?$"

PalletTown_ProfessorOaksLab_Text_OakThisMonIsEnergetic::
    .string "זה פוקימון\n"
    .string "מלא מרץ!\p$"

PalletTown_ProfessorOaksLab_Text_ReceivedMonFromOak::
    .string "{PLAYER} קיבל את {STR_VAR_1}\n"
    .string "מפרופסור אוק!$"

PalletTown_ProfessorOaksLab_Text_OakCanReachNextTownWithMon::
    .string "אוק: אם מופיע פוקימון בר,\n"
    .string "אתה יכול להילחם בו.\p"
    .string "עם הפוקימון לצידך אתה יכול\n"
    .string "להגיע לעיר הבאה בבטחה.$"

PalletTown_ProfessorOaksLab_Text_OakBattleMonForItToGrow::
    .string "אוק: {PLAYER},\n"
    .string "תאמן את הפוקימון\l"
    .string "הצעיר שלך בקרבות!$"

PalletTown_ProfessorOaksLab_Text_OakHaveSomethingForMe::
    .string "אוק: אה, {PLAYER}!\p"
    .string "מה שלום הפוקימון שנתתי לך?\p"
    .string "טוב, נראה שהוא אוהב אותך מאוד.\p"
    .string "כנראה שאתה מאמן פוקימונים מוכשר!\p"
    .string "מה? הבאת לי משהו?$"

PalletTown_ProfessorOaksLab_Text_DeliveredOaksParcel::
    .string "{PLAYER} מסר\n"
    .string "את החבילה של אוק.$"

PalletTown_ProfessorOaksLab_Text_OakCustomBallIOrdered::
    .string "אה! זה הפוקיבול\n"
    .string "המיוחד שהזמנתי! תודה לך!$"

PalletTown_ProfessorOaksLab_Text_OakHaveRequestForYouTwo::
    .string "אוק: יש לי בקשה\n"
    .string "עבור שניכם.$"

PalletTown_ProfessorOaksLab_Text_OakPokedexOnDesk::
    .string "על השולחן נמצאת\n"
    .string "ההמצאה החדשה שלי, הפוקדקס!\p"
    .string "הפוקדקס מתעד מידע לגבי פוקימונים\n"
    .string "שתפסתם או ראיתם! הוא אוטומטי\l"
    .string "לחלוטין!\p"
    .string "זה כמו אנציקלופדיה מתקדמת!$"

PalletTown_ProfessorOaksLab_Text_OakTakeTheseWithYou::
    .string "אוק: {PLAYER} ו{RIVAL}!\n"
    .string "קחו לכם אחד!$"

PalletTown_ProfessorOaksLab_Text_ReceivedPokedexFromOak::
    .string "{PLAYER} קיבל\n"
    .string "מאוק את הפוקדקס!$"

PalletTown_ProfessorOaksLab_Text_OakCatchMonsForDataTakeThese::
    .string "אוק: אם אתה רוצה\n"
    .string "לדעת פרטים מדויקים על\l"
    .string "פוקימון, עליך לעשות יותר מרק\l"
    .string "לראות אותו.\p"
    .string "עליך לתפוס אותו! השתמש באלה כדי\l"
    .string "לתפוס פוקימונים פראיים.$"

PalletTown_ProfessorOaksLab_Text_ReceivedFivePokeBalls::
    .string "{PLAYER} קיבל 5\n"
    .string "פוקיבולים!$"

PalletTown_ProfessorOaksLab_Text_OakExplainCatching::
    .string "כשפוקימונים פראי\n"
    .string "מופיע, הוא נחלת הכלל.\p"
    .string "כל מה שצריך הוא\n"
    .string "לזרוק עליו פוקיבול ולנסות לתפוס\l"
    .string "אותו!\p"
    .string "לא תמיד תצליח לתפוס את הפוקימון.\p"
    .string "פוקימון בריא יכול להימלט מהכדור.\l"
    .string "צריך לקוות למזל!$"

PalletTown_ProfessorOaksLab_Text_OakCompleteMonGuideWasMyDream::
    .string "החלום שלי תמיד\n"
    .string "היה...\p"
    .string "לכתוב מדריך מפורט על כל סוגי\l"
    .string "הפוקימון שיש!\p"
    .string "אבל אני כבר לא צעיר כמו שהייתי.\l"
    .string "זה כבר לא בשבילי.\p"
    .string "אז אני רוצה שאתם תגשימו את החלום\l"
    .string "שלי!\p"
    .string "קדימה, צאו לדרך!\p"
    .string "זה רגע משמעותי בהיסטוריה של\l"
    .string "פוקימון!$"

PalletTown_ProfessorOaksLab_Text_OakMonsAroundWorldWait::
    .string "פוקימונים בכל\n"
    .string "העולם ממתינים לך, {PLAYER}!$"

PalletTown_ProfessorOaksLab_Text_OakAddedNothingToPokedex::
    .string "היי, {PLAYER}!\n"
    .string "איך מתקדם לך עם הפוקידקס?\p"
    .string "{RIVAL} כבר תפס כמה פוקימונים והוסיף\n"
    .string "מידע עליהם.\p"
    .string "אז {PLAYER} בוא נעיף מבט על\n"
    .string "הפוקידקס שלך.\p"
    .string "מה קרה?\n"
    .string "לא הוספת שום מידע לפוקידקס.\p"
    .string "אני אתן לך את אלו,\n"
    .string "אז תשתדל קצת יותר.$"

PalletTown_ProfessorOaksLab_Text_OakComeSeeMeSometime::
    .string "אוק: בוא לבקר\n"
    .string "מדי פעם.\p"
    .string "אשמח לראות את ההתקדמות שלך\l"
    .string "בהשלמת הפוקדקס.$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
    .string "זה נראה כמו\n"
    .string "אנציקלופדיה, אבל כל הדפים ריקים!$"

PalletTown_ProfessorOaksLab_Text_ThoseArePokeBalls::
    .string "זה פוקיבול.\n"
    .string "יש בתוכו פוקימון!$"

PalletTown_ProfessorOaksLab_Text_OaksLastMon::
    .string "זה הפוקימון האחרון\n"
    .string "של פרופ' אוק!$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
    .string "לחץ על כפתור ההתחל כדי לפתוח\n"
    .string "את התפריט$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
    .string "דרך התפריט אפשר לשמור את המשחק.$"

PalletTown_ProfessorOaksLab_Text_AllMonTypesHaveStrongAndWeakPoints::
    .string "לכל סוגי הפוקימונים יש יתרונות\n"
    .string "וחולשות מול סוגים אחרים$"

PalletTown_ProfessorOaksLab_Text_EmailMessage::
    .string "יש פה הודעת מייל.\p"
    .string "...\p"
    .string "סוף סוף! המאמנים החזקים ביותר של\n"
    .string "ליגת הפוקימונים מוכנים\l"
    .string "להילחם במי שרוצה לתפוס את מקומם!\p"
    .string "מרכז ליגת הפוקימונים\n"
    .string "אינדיגו פלאטו\p"
    .string "פרופסור אוק, בבקשה תבקר אותנו שם!\n"
    .string "...$"

PalletTown_ProfessorOaksLab_Text_StudyAsOaksAide::
    .string "אני העוזר של\n"
    .string "פרופ' אוק. אני חוקר פוקימונים.$"

PalletTown_ProfessorOaksLab_Text_DaisyWillGroomMons::
    .string "היי {PLAYER}. אני בטוח שאתה והפוקימונים\n"
    .string "שלך כבר נהייתם חברים טובים.\p"
    .string "דרך אגב, אתה יודע לגבי דייזי?\p"
    .string "אם תראה לדייזי את הפוקימון שלך היא\n"
    .string "תדע להגיד לך כמה הוא אוהב אותך.\p"
    .string "לפעמים היא אפילו תטפל בו בשבילך.\p"
    .string "זה סוד, בבקשה אל תספר את זה לאף\n"
    .string "אחד.$"

PalletTown_ProfessorOaksLab_Text_OakIsAuthorityOnMons::
    .string "פרופ' אוק הוא\n"
    .string "ה-מומחה בכל מה שנוגע לפוקימון!\p"
    .string "מאמני פוקימון רבים רוחשים כלפיו\l"
    .string "כבוד רב!$"

PalletTown_ProfessorOaksLab_Text_OakSightingsOfRareMons::
    .string "לאחרונה נצפו פוקימונים\n"
    .string "מהמון זנים נדירים.\p"
    .string "אני מדבר על פוקימונים\n"
    .string "שמעולם לא נראו פה בקאנטו.\p"
    .string "הייתי שמח ללכת לראות אותם בעצמי,\n"
    .string "אבל אני כבר זקן מידי.\p"
    .string "מכיוון שאני לא יכול לעשות את זה,\n"
    .string "{PLAYER}, אני אשמח שתעשה זאת בשבילי.$"

PalletTown_ProfessorOaksLab_Text_RivalJustLetMeHandleEverything::
    .string "{RIVAL}: היי! שמעתי את זה!\p"
    .string "סבא מה נסגר עם זה שאתה\n"
    .string "מעדיף את {PLAYER} על פני?\p"
    .string "אני כבר הלכתי ותפסתי מלא\n"
    .string "פוקימונים, ועשיתי את זה מהר.\p"
    .string "אתה יכול לתת לי לטפל בהכל,\n"
    .string "לא צריך את {PLAYER}.$"

PalletTown_ProfessorOaksLab_Text_OakNeedYourHelpTooNeedToSeePokedexes::
    .string "אוק: אני יודע, אני יודע\n"
    .string "כמובן שאני צריך גם את עזרתך.\p"
    .string "שניכם, תביאו לי את הפוקדקסים שלכם.$"

PalletTown_ProfessorOaksLab_Text_OakTookBothPokedexUnits::
    .string "פרופ אוק לקח את שני הפוקדקסים.$"

PalletTown_ProfessorOaksLab_Text_OakNowTheseUnitsCanRecordMoreData::
    .string "… … …  … … …\p"
    .string "… … …  … … …\p"
    .string "ו... זהו!\p"
    .string "עכשיו הם יוכלו להקליט מידע\n"
    .string "על עוד המון פוקימונים.$"

PalletTown_ProfessorOaksLab_Text_PlayersPokedexWasUpgraded::
    .string "הפוקדקס של {PLAYER} שודרג!$"

PalletTown_ProfessorOaksLab_Text_OakMustReallyWorkToFillPokedex::
    .string "עכשיו, {PLAYER} ו{RIVAL}!\p"
    .string "אתם ממש חייבים למלא את\n"
    .string "הפוקדקסים שלכם.\p"
    .string "אני סומך עליכם שתהפכו אותם\n"
    .string "להכי מלאים וטובים בכל העולם!\p"
    .string "הרגע הזה יזכר כרגע חשוב מאוד\n"
    .string "בהיסטוריה של מדע הפוקימונים!$"

PalletTown_ProfessorOaksLab_Text_RivalIllCompleteThePokedex::
    .string "{RIVAL}: סבא, אל תתרגש יותר מידי.\p"
    .string "אני אמלא את הפוקדקס שלי,\n"
    .string "אין לך סיבה לדאוג.\p"
    .string "אני חושב שאתחיל ב-אי מספר 1.\p"
    .string "בכל מקרה אני הולך!$"

PalletTown_ProfessorOaksLab_Text_OakIsGoingToHaveRadioShow::
    .string "לפרופסור אוק הולכת להיות תוכנית\n"
    .string "רדיו בקרוב\p"
    .string "היא הולכת להיקרא סמינר הפוקימונים$"

PalletTown_ProfessorOaksLab_Text_OakFavorToAskYouPlayer::
    .string "או זה מצוין!\p"
    .string "{PLAYER} יש לי עוד בקשה חשובה עבורך.\n"
    .string "אני צריך שתקשיב לי טוב.$"
