FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
    .string "באי הזה גדלה מאמנת גדולה\n"
    .string "וחזקה מאוד.\p"
    .string "אני מתערב שגם אתה מכיר אותה.\n"
    .string "זו לורליי מהרביעייה העילית!\p"
    .string "כשלורליי הייתה קטנטונת,\n"
    .string "אני לימדתי אותה על פוקימון.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
    .string "איי סווי נמצאים באזור\n"
    .string "חם בדרך כלל.\p"
    .string "אבל יש חריג אחד שכדאי\n"
    .string "שתדע עליו.\p"
    .string "מערת מפל הקרח קפואה בגלל\n"
    .string "הפוקימונים שחיים בתוכה.$"

