@ Unclear where this is originally from
Route11_EastEntrance_1F_Text_BagIsFull::
    .string "{PLAYER}{KUN}の　バッグ\n"
    .string "いっぱい　みたい　だね$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
    .string "אתה לא חושב שזה קשה\n"
	  .string "לחשוב על שמות טובים לפוקימון?\p"
    .string "במיוחד אם תפסתם הרבה מהם?\n"
    .string "בעיר לאבנדר, יש אדם שמדרג\l"
	  .string "שמות לפוקימון.\p"
    .string "הוא אפילו יכול לעזור\n"
    .string "לך לשנות את שם הפוקימון שלך!$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
    .string "אם אתה מכוון להגיע\n"
	  .string "לעיר לאבנדר, \l"
	  .string "קח את מנהרת הסלע.\p"
    .string "אתה יכול להגיע למנהרת\n"
    .string "הסלע מעיר סרוליאן.$"


