Route9_Text_AliciaIntro::
    .string "יש לך פוקימונים איתך!\n"
    .string "אתה שלי!$"

Route9_Text_AliciaDefeat::
    .string "רימית אותי…$"

Route9_Text_AliciaPostBattle::
    .string "המנהרה שמגיעה היא חשוכה לגמרי\n"
    .string "בפנים.\p"
    .string "תצטרך פלאש כדי לעבור\n"
    .string "שם.$"

Route9_Text_ChrisIntro::
    .string "מי זה שהולך שם עם הפוקימונים\n"
    .string "הנאים האלה?$"

Route9_Text_ChrisDefeat::
    .string "נפל כמו אור!$"

Route9_Text_ChrisPostBattle::
    .string "תמשיך ללכת!$"

Route9_Text_DrewIntro::
    .string "אני לוקח את מנהרת הסלע כדי\n"
    .string "ללכת ללבנדר…$"

Route9_Text_DrewDefeat::
    .string "לא יכול למדוד…$"

Route9_Text_DrewPostBattle::
    .string "גם אתה הולך למנהרת הסלע?$"

Route9_Text_CaitlinIntro::
    .string "אל תעז לפטרוני אותי!$"

Route9_Text_CaitlinDefeat::
    .string "לא!\n"
    .string "אתה יותר מדי.$"

Route9_Text_CaitlinPostBattle::
    .string "אתה ברור שיש לך כשרון.\n"
    .string "בהצלחה לך!$"

Route9_Text_JeremyIntro::
    .string "בוהאהה!\n"
    .string "מעולה! הייתי משועמם!$"

Route9_Text_JeremyDefeat::
    .string "תמשיך להגיע!\p"
    .string "אה חכה.\n"
    .string "נגמרו לי הפוקימונים!$"

Route9_Text_JeremyPostBattle::
    .string "היה לך אומץ לעמוד מולי\n"
    .string "שם!$"

Route9_Text_BriceIntro::
    .string "האהאהאה!\n"
    .string "האם אתה לא קצת קשוח!$"

Route9_Text_BriceDefeat::
    .string "מה זה?$"

Route9_Text_BricePostBattle::
    .string "האהאהאה!\n"
    .string "ילדים צריכים להיות קשוחים!$"

Route9_Text_BrentIntro::
    .string "קמתי מוקדם כל יום כדי לגדל\n"
    .string "את הפוקימונים שלי מתוך גולם!$"

Route9_Text_BrentDefeat::
    .string "מה?\p"
    .string "איזה בזבוז זמן מוחלט!$"

Route9_Text_BrentPostBattle::
    .string "אני צריך לאסוף יותר מחרקים\n"
    .string "כדי להתחזק…$"

Route9_Text_AlanIntro::
    .string "האהאהאה!\n"
    .string "תביא את זה!$"

Route9_Text_AlanDefeat::
    .string "האהאהאה!\n"
    .string "ניצחת אותי ביושר!$"

Route9_Text_AlanPostBattle::
    .string "האהאהאה!\n"
    .string "אנחנו תמיד צוחקים!$"

Route9_Text_ConnerIntro::
    .string "צא, הפוקימונים החרקיים המעולים\n"
    .string "שלי!$"

Route9_Text_ConnerDefeat::
    .string "החרקים שלי…$"

Route9_Text_ConnerPostBattle::
    .string "אם אתה לא אוהב פוקימונים חרקיים,\n"
    .string "אתה מציק לי!$"

Route9_Text_RouteSign::
    .string "דרך 9\n"
    .string "עיר סרוליאן - מנהרת הסלע$"
