Route24_Text_JustEarnedFabulousPrize::
    .string "מזל טוב! ניצחת את חמשת המתמודדים\n"
    .string "שלנו! זכית בפרס מדהים!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
    .string "{PLAYER} קיבל נאגט מהמאמן\n"
    .string "המסתורי!$"

Route24_Text_YouDontHaveAnyRoom::
    .string "אין לך מקום נוסף!$"

Route24_Text_JoinTeamRocket::
    .string "דרך אגב, איך היית רוצה להצטרף\n"
    .string "לצוות רוקט? אנחנו קבוצה של פושעים\l"
    .string "מקצוענים שמתמחים בפוקימון!\p"
    .string "רוצה להצטרף?\p"
    .string "בטוח?\p"
    .string "בוא, תצטרף אלינו!\p"
    .string "אני אומר לך להצטרף!\p"
    .string "…אוקיי, אתה צריך שכנוע!\p"
    .string "אני אעשה לך הצעה שלא תוכל לסרב\n"
    .string "לה!$"

Route24_Text_RocketDefeat::
    .string "אהה!\n"
    .string "אתה טוב!$"

Route24_Text_YoudBecomeTopRocketLeader::
    .string "עם היכולות שלך, תהפוך למנהיג בכיר\n"
    .string "בצוות רוקט.\p"
    .string "בוא, תחשוב על ההזדמנות!\n"
    .string "אל תיתן להזדמנות הזאת להיעלם.$"

Route24_Text_ShaneIntro::
    .string "ראיתי את ההישג שלך מהדשא!$"

Route24_Text_ShaneDefeat::
    .string "חשבתי שלא!$"

Route24_Text_ShanePostBattle::
    .string "התחבאתי כי האנשים על הגשר הפחידו\n"
    .string "אותי.$"

Route24_Text_EthanIntro::
    .string "אוקיי! אני מס' 5!\n"
    .string "אני אכנע אותך!$"

Route24_Text_EthanDefeat::
    .string "וואו!\n"
    .string "יותר מדי!$"

Route24_Text_EthanPostBattle::
    .string "עשיתי את המיטב שלי. אין לי חרטות!$"

Route24_Text_ReliIntro::
    .string "אני מס' 4!\n"
    .string "מתעייף?$"

Route24_Text_ReliDefeat::
    .string "גם אני הפסדתי!$"

Route24_Text_ReliPostBattle::
    .string "עשיתי את המיטב שלי, אז אין לי\n"
    .string "חרטות!$"

Route24_Text_TimmyIntro::
    .string "הנה מס' 3!\n"
    .string "אני לא אהיה קל!$"

Route24_Text_TimmyDefeat::
    .string "או!\n"
    .string "כתוש שטוח!$"

Route24_Text_TimmyPostBattle::
    .string "עשיתי את המיטב שלי. אין לי חרטות!$"

Route24_Text_AliIntro::
    .string "אני השני!\n"
    .string "עכשיו זה רציני!$"

Route24_Text_AliDefeat::
    .string "איך יכולתי להפסיד?$"

Route24_Text_AliPostBattle::
    .string "עשיתי את המיטב שלי. אין לי חרטות!$"

Route24_Text_CaleIntro::
    .string "אנשים קוראים לזה גשר הנאגט! נצח\n"
    .string "אותנו חמישה מאמנים וזכה בפרס\l"
    .string "מדהים!\p"
    .string "חושב שאתה מסוגל?$"

Route24_Text_CaleDefeat::
    .string "וואו!\n"
    .string "דברים טובים!$"

Route24_Text_CalePostBattle::
    .string "עשיתי את המיטב שלי. אין לי חרטות!$"
