ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
    .string "זה נכון?\p"
    .string "החנות של סלדון גדולה\n"
    .string "פי כמה מהחנות הזאת?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
    .string "לפעמים אני קונה כאן תרופות.\p"
    .string "אבל הרבה אנשים מרפאים את\n"
    .string "הפוקימון שלהם בפירות מהיער.\p"
    .string "אחרי הכול, הפירות שם בחינם\n"
    .string "והם אף פעם לא נגמרים.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
    .string "האופנוענים האלה עמדו להרוס\n"
    .string "את חנות הפוקימונים הזאת.\p"
    .string "איזה מזל שהם החליטו לעזוב!$"
