ThreeIsland_BondBridge_Text_NikkiIntro::
    .string "הריח המלוח של הים…\n"
    .string "הוא מדגדג לי בלב.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
    .string "…מרחרחת, מרחרחת…\n"
    .string "משהו מריח לא נעים…$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
    .string "אולי הצחנה הזאת היא ריח\n"
    .string "הזיעה של הפוקימון שלך…$"

ThreeIsland_BondBridge_Text_VioletIntro::
    .string "לאן אתה ממהר\n"
    .string "כל כך?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
    .string "אתה מגדל פוקימונים\n"
    .string "נהדרים.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
    .string "אם תמשיך בדרך הזאת,\n"
    .string "תגיע בסוף ליער הפירות.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
    .string "אמא שלי אמרה שאני לא\n"
    .string "יכולה לשחות בלי גלגל ההצלה.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
    .string "וואאאה!\n"
    .string "וואאאה!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
    .string "השנה אני סוף סוף הולכת\n"
    .string "ללמוד לשחות!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
    .string "יש, יש!\n"
    .string "פוקימון!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
    .string "מה קורה עכשיו?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
    .string "ניצחתי עכשיו?\n"
    .string "או שהפסדתי?$"

ThreeIsland_BondBridge_Text_TishaIntro::
    .string "אוי לא, אל תתקרב לכאן!\n"
    .string "בבקשה, תתרחק ממני!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
    .string "טוב, ניצחת!\n"
    .string "עכשיו תוכל בבקשה ללכת?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
    .string "פוקימון נגס לי\n"
    .string "בבגד הים שלי.\p"
    .string "אני לא יכולה לצאת מהמים!$"

ThreeIsland_BondBridge_Text_JoyIntro::
    .string "ג'וי: נלמד אותך מה הפוקימון\n"
    .string "האהוב עלינו!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
    .string "ג'וי: אוהה…\n"
    .string "מג!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
    .string "ג'וי: היה כיף, נכון?\n"
    .string "אני מקווה שנילחם שוב!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
    .string "ג'וי: אני ממש רוצה להילחם\n"
    .string "יחד עם מג.\p"
    .string "פוקימון אחד זה לא מספיק.$"

ThreeIsland_BondBridge_Text_MegIntro::
    .string "מג: נראה לך מה הפוקימון\n"
    .string "האהוב עלינו.$"

ThreeIsland_BondBridge_Text_MegDefeat::
    .string "מג: אוהה…\n"
    .string "ג'וי!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
    .string "מג: ג'וי, היה כיף, נכון?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
    .string "מג: אני רוצה להילחם יחד\n"
    .string "עם ג'וי.\p"
    .string "פוקימון אחד זה לא מספיק.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "יער הפירות לפניך$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "גשר בונד\n"
    .string "נא לשמור על השקט במעבר.\p"
    .string "יער הפירות לפניך$"
