FiveIsland_ResortGorgeous_Text_DaisyIntro::
    .string "בידיים האלה אני יוצרת\n"
    .string "את הניצחון שלי!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
    .string "איזו בושה…\n"
    .string "אני מסמיקה…$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
    .string "אוי לא, שפופרות הצבע שלי\n"
    .string "התפזרו לכל עבר!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
    .string "סליחה!\n"
    .string "אני מנסה לצייר כאן.\l"
    .string "תזוז לי מהעיניים!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
    .string "ההפסד הזה…\n"
    .string "אני מרגישה שאני מחווירה…$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
    .string "ג'יליאן?\n"
    .string "תטי קצת את הראש…\l"
    .string "הנה! זה בדיוק המבט שרציתי!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
    .string "הממ…\n"
    .string "הזווית עדיין לא מדויקת…$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
    .string "אוי…\n"
    .string "מצב הרוח שלי אפור…$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
    .string "השמיים והים…\n"
    .string "הם כל כך הפכפכים.\p"
    .string "ההבעות המשתנות שלהם\n"
    .string "מקשות עליי ללכוד אותם.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
    .string "אני מבקרת בבית הנופש של\n"
    .string "חברה שלי, אם חייבים לדעת.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
    .string "אוי ואבוי, כמה חזק.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
    .string "נעים לי להילחם בנחת\n"
    .string "ברוח הים העדינה.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
    .string "אני שוקלת לבנות בריכה\n"
    .string "במיוחד בשביל פוקימונים.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
    .string "אוי, אלוהים אדירים!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
    .string "בריכה זה נחמד, אבל עליי\n"
    .string "לומר שחדר שמש עדיף.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
    .string "אני רץ טוב.\n"
    .string "אני ממש מהיר!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
    .string "אופס!\n"
    .string "נחפזתי!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
    .string "כשאני רץ עם הרוח, מרגיש\n"
    .string "לי שאני יכול לעוף!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
    .string "אני אומר לך, חיי הים כאן\n"
    .string "במלון מתאימים לי מאוד.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
    .string "איזו הפתעה!\n"
    .string "אתה בטח צוחק.$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
    .string "להתרגש מזה כל כך…\n"
    .string "איזה חוסר היגיון.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
    .string "סלפי: תודה לך.\p"
    .string "אתה יכול ללכת עכשיו.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
    .string "הבית של סלפי$"

