CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
    .string "השתמש בדוחה כדי\n"
    .string "להרחיק חרקים ופוקימונים חלשים.\p"
    .string "שים את הפוקימונים הכי חזקים שלך\n"
    .string "בראש הרשימה בשביל התוצאות\l"
    .string "הכי טובות!$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
    .string "ראית איזה\n"
    .string "ממתק נדיר?\p"
    .string "הוא אמורה לגרום לפוקימון לעלות\l"
    .string "רמה אחת!$"
