Route11_Text_HugoIntro::
    .string "נצח, הפסד או תיקו!$"

Route11_Text_HugoDefeat::
    .string "אהה!\n"
    .string "לא הלך בדרך שלי!$"

Route11_Text_HugoPostBattle::
    .string "פוקימון זה החיים!\n"
    .string "ולחיות זה לשחק משחקים!$"

Route11_Text_JasperIntro::
    .string "תחרות!\n"
    .string "אני לא יכול להפסיק!$"

Route11_Text_JasperDefeat::
    .string "היה לי סיכוי!$"

Route11_Text_JasperPostBattle::
    .string "לא יכול להיות פחדן בעולם\n"
    .string "של פוקימונים!$"

Route11_Text_EddieIntro::
    .string "יאללה, אבל אל תרמה!$"

Route11_Text_EddieDefeat::
    .string "מה?\n"
    .string "זה לא נכון!$"

Route11_Text_EddiePostBattle::
    .string "עשיתי את הכי טוב שלי.\n"
    .string "אין לי חרטות.$"

Route11_Text_BraxtonIntro::
    .string "היזהר!\n"
    .string "אני מניח כבלים!$"

Route11_Text_BraxtonDefeat::
    .string "זה היה חשמלי!$"

Route11_Text_BraxtonPostBattle::
    .string "תפיץ את הבשורה לשמור על אנרגיה!$"

Route11_Text_DillonIntro::
    .string "רק עכשיו הפכתי למאמן.\n"
    .string "אבל, אני חושב שאני יכול לנצח.$"

Route11_Text_DillonDefeat::
    .string "הפוקימונים שלי לא הצליחו לנצח…\n"
    .string "הם לא התפתח מספיק?$"

Route11_Text_DillonPostBattle::
    .string "מה עכשיו?\n"
    .string "תעזוב אותי!$"

Route11_Text_DirkIntro::
    .string "פוואהא!\n"
    .string "מעולם לא הפסדתי!$"

Route11_Text_DirkDefeat::
    .string "ההפסד הראשון שלי!$"

Route11_Text_DirkPostBattle::
    .string "הייתה לך רק מזל, זה הכל.$"

Route11_Text_DarianIntro::
    .string "מעולם לא ניצחתי לפני כן…$"

Route11_Text_DarianDefeat::
    .string "ציפיתי לזה…$"

Route11_Text_DarianPostBattle::
    .string "הייתי חסר מזל, כמו תמיד.$"

Route11_Text_YasuIntro::
    .string "אני הכי טוב בכיתה שלי.\n"
    .string "אני מתאמן כל בוקר.$"

Route11_Text_YasuDefeat::
    .string "אוי! הפוקימונים שלי צריכים להיות\n"
    .string "יותר חזקים!$"

Route11_Text_YasuPostBattle::
    .string "יש פוקימון שמנמן שיורד\n"
    .string "מההרים.\p"
    .string "אני בטוח שהוא יהיה חזק אם תוכל\n"
    .string "לתפוס אותו.$"

Route11_Text_BernieIntro::
    .string "היזהר מחוטים חיים!$"

Route11_Text_BernieDefeat::
    .string "וואו!\n"
    .string "אתה פקק חשמל!$"

Route11_Text_BerniePostBattle::
    .string "ובכן, כדאי לחזור לעבודה.$"

Route11_Text_DaveIntro::
    .string "גידלתי את הפוקימונים שלי בזהירות.\n"
    .string "הם אמורים להיות מוכנים עכשיו!$"

Route11_Text_DaveDefeat::
    .string "ביי ביי!\n"
    .string "תודה, ולהתראות!$"

Route11_Text_DavePostBattle::
    .string "צ'ח… אני צריך למצוא פוקימונים יותר\n"
    .string "חזקים!$"

Route11_Text_DiglettsCave::
    .string "מערת דיגלט$"
