SixIsland_OutcastIsland_Text_RocketIntro::
    .string "אין שום פוקימון נדיר\n"
    .string "באזור הזה! אף לא אחד!\p"
    .string "זה מוציא אותי מדעתי.\n"
    .string "אני אוציא את זה עליך!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
    .string "…האה?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
    .string "תגיד, לא ראית שום פוקימון\n"
    .string "נדיר, נכון?$"

SixIsland_OutcastIsland_Text_TylorIntro::
    .string "אין לי שום מזל בכלל.\n"
    .string "קרב יהיה שינוי קצב נחמד!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
    .string "לא, שום מזל בכלל…$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
    .string "אבל אני לא יכול לחזור הביתה\n"
    .string "בלי לתפוס משהו.$"

SixIsland_OutcastIsland_Text_MymoIntro::
    .string "הוף… הוף…\p"
    .string "שחיתי לכאן מהנמל של האי השישי\n"
    .string "בלי לעצור.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
    .string "הוף…\n"
    .string "הוף…$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
    .string "אני רק בחצי הדרך…\n"
    .string "אני גמור…$"

SixIsland_OutcastIsland_Text_NicoleIntro::
    .string "זה לא כזה קל לשלוח פוקימון\n"
    .string "בזמן שחייה, אתה יודע?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
    .string "לא הפסדתי לך בשחייה.\n"
    .string "זה לא מפריע לי בכלל.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
    .string "אתה בדרך לאי שנמצא\n"
    .string "מעבר לכאן?\p"
    .string "לא ראיתי שם שום דבר\n"
    .string "מעניין.$"

SixIsland_OutcastIsland_Text_AvaIntro::
    .string "אווה: בוא נעשה קרב ימי\n"
    .string "שניים על שניים!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
    .string "אווה: וואו, אתה מדהים!\n"
    .string "ועוד לבד לגמרי!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
    .string "אווה: אתה יודע, אני מעדיפה\n"
    .string "את הים על פני כל בריכה.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
    .string "אווה: אתה מאתגר אותנו\n"
    .string "לקרב?\p"
    .string "תצטרך לפחות שני פוקימונים\n"
    .string "בשביל זה.$"

SixIsland_OutcastIsland_Text_GebIntro::
    .string "גב: אחותי הגדולה, תעזרי לי!\n"
    .string "בבקשה תילחמי איתי!$"

SixIsland_OutcastIsland_Text_GebDefeat::
    .string "גב: וואו, אחותי הגדולה, הבחור\n"
    .string "הזה ממש טוב!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
    .string "גב: אני נאחז באחותי כי אני\n"
    .string "לא מגיע לקרקעית.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
    .string "גב: בבקשה תילחם נגדי\n"
    .string "ונגד אחותי!\p"
    .string "…אה, אין לך שני פוקימונים?$"
