Route14_Text_CarterIntro::
    .string "כדי ללמד פוקימונים תנועות טובות\n"
    .string "צריך להשתמש במ”מ.$"

Route14_Text_CarterDefeat::
    .string "עדיין לא מספיק טוב.$"

Route14_Text_CarterPostBattle::
    .string "יש לך מ”נ, נכון? קשה לפוקימונים\n"
    .string "לשכוח את התנועות האלו.$"

Route14_Text_MitchIntro::
    .string "הפוקימונים המעופפים שלי צריכים\n"
    .string "להיות מוכנים לקרב.$"

Route14_Text_MitchDefeat::
    .string "עדיין לא מוכנים!$"

Route14_Text_MitchPostBattle::
    .string "הפוקימונים המעופפים שלי צריכים\n"
    .string "ללמוד תנועות טובות יותר.$"

Route14_Text_BeckIntro::
    .string "יש מ”מ למכירה בחנות הכלבו\n"
    .string "של סלדון.\p"
    .string "מ”מ לא ממש נדירים, אבל לא להרבה\n"
    .string "אנשים יש מ”נ.$"

Route14_Text_BeckDefeat::
    .string "אוי, איזה באסה!$"

Route14_Text_BeckPostBattle::
    .string "נסה ללמד פוקימון תנועה שתואמת\n"
    .string "לסוג שלו.\p"
    .string "זה כנראה מגביר את הכוח של\n"
    .string "התנועה.$"

Route14_Text_MarlonIntro::
    .string "לימדת את הפוקימונים המעופפים שלך\n"
    .string "לעוף?\p"
    .string "תוכל לעוף איתם גבוה בשמיים!$"

Route14_Text_MarlonDefeat::
    .string "נפלתי בלהבות!$"

Route14_Text_MarlonPostBattle::
    .string "הפוקימונים המעופפים הם אהבתי\n"
    .string "היחידה. אני לא רוצה לגדל שום דבר\l"
    .string "אחר.$"

Route14_Text_DonaldIntro::
    .string "שמעת על האגדה של ציפורי\n"
    .string "האימים?$"

Route14_Text_DonaldDefeat::
    .string "למה?\n"
    .string "למה הפסדתי?$"

Route14_Text_DonaldPostBattle::
    .string "ובכן, ציפורי האימים הן הפוקימונים\n"
    .string "האגדיים.\p"
    .string "יש שלושה מהם: ארטיקונו,\n"
    .string "זאפדוס ומולטרס.$"

Route14_Text_BennyIntro::
    .string "אני לא בקטע, אבל בסדר.\n"
    .string "בוא נלך!$"

Route14_Text_BennyDefeat::
    .string "ידעתי!$"

Route14_Text_BennyPostBattle::
    .string "לנצח, להפסיד… זה חסר משמעות\n"
    .string "תחת השמיים הענקיים האלו.$"

Route14_Text_LukasIntro::
    .string "קדימה, קדימה.\n"
    .string "בוא נלך, בוא נלך, בוא נלך!$"

Route14_Text_LukasDefeat::
    .string "אוי!\n"
    .string "הפסדתי! לך מכאן!$"

Route14_Text_LukasPostBattle::
    .string "מה, מה, מה?\n"
    .string "מה אתה עדיין רוצה?$"

Route14_Text_IsaacIntro::
    .string "אני צריך להעביר את הזמן.\n"
    .string "תשתוק ותלחם.$"

Route14_Text_IsaacDefeat::
    .string "מה?\n"
    .string "אתה!?$"

Route14_Text_IsaacPostBattle::
    .string "לגדל פוקימונים זה מעצבן, אחי.$"

Route14_Text_GeraldIntro::
    .string "אנחנו רוכבים כאן בגלל\n"
    .string "המקומות הפתוחים.$"

Route14_Text_GeraldDefeat::
    .string "חיסול מוחלט!$"

Route14_Text_GeraldPostBattle::
    .string "מגניב שחיזקת את הפוקימונים שלך\n"
    .string "כל כך.\p"
    .string "הכוח צודק!\n"
    .string "ואתה יודע את זה!$"

Route14_Text_MalikIntro::
    .string "קרב פוקימונים?\n"
    .string "מגניב! בוא נילחם!$"

Route14_Text_MalikDefeat::
    .string "עפת אותי!$"

Route14_Text_MalikPostBattle::
    .string "אתה יודע מי ינצח, אתה ואני\n"
    .string "אחד על אחד!$"

Route14_Text_RouteSign::
    .string "נתיב 41\n"
    .string "מערבה אל עיר פוקסיה$"

Route14_Text_KiriIntro::
    .string "קירי: יאן, בוא ננסה באמת,\n"
    .string "באמת חזק ביחד.$"

Route14_Text_KiriDefeat::
    .string "קירי: יבבות…\n"
    .string "הפסדנו, נכון?$"

Route14_Text_KiriPostBattle::
    .string "קירי: הפסדנו בגללי?$"

Route14_Text_KiriNotEnoughMons::
    .string "קירי: נוכל להילחם אם יהיו לך\n"
    .string "שני פוקימונים.$"

Route14_Text_JanIntro::
    .string "יאן: קירי, קדימה!\n"
    .string "אנחנו חייבים להתאמץ!$"

Route14_Text_JanDefeat::
    .string "יאן: אי, אי, אי!\n"
    .string "לא הוגן!$"

Route14_Text_JanPostBattle::
    .string "יאן: קירי, אל תבכי!\n"
    .string "פשוט ננסה חזק יותר בפעם הבאה.$"

Route14_Text_JanNotEnoughMons::
    .string "יאן: רוצה להילחם?\n"
    .string "אין לך מספיק פוקימונים.$"
