ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "פיו! אני מנסה\n"
    .string "לשנן את הסיכומים שלי.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "אוקיי!\p"
    .string "השתדל לקרוא בקפידה את מה\l"
    .string "שכתוב על הלוח!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "בוא נבדוק את המחברת.\p"
    .string "עמוד ראשון...\p"
    .string "כדורי פוקימון משמשים לתפיסת\n"
    .string "פוקימונים.\p"
    .string "ניתן לשאת עד שישה פוקימונים\n"
    .string "בקבוצה שלך.\p"
    .string "אנשים שמגדלים ונלחמים\n"
    .string "בפוקימונים נקראים מאמנים.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "עמוד שני...\p"
    .string "פוקימון בריא עשוי להיות קשה\n"
    .string "לתפיסה, אז החליש אותו קודם.\p"
    .string "הרעל, שרוף, או גרום לו\n"
    .string "בעיה במצב כדי להחליש אותו.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "עמוד שלישי...\p"
    .string "מאמני פוקימון מחפשים אחרים\n"
    .string "כדי להיכנס לקרבות פוקימון.\p"
    .string "למאמנים, טעמו של הניצחון\n"
    .string "מתוק בהחלט.\p"
    .string "קרבות נערכים כל הזמן ב\n"
    .string "אולמות פוקימון בכל מקום.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "עמוד רביעי...\p"
    .string "המטרה הסופית של כל מאמני\n"
    .string "הפוקימון היא פשוטה.\p"
    .string "היא להביס את שמונת המאמנים\n"
    .string "הבכירים של אולמות הפוקימון.\p"
    .string "עשה זאת כדי לזכות בזכות להתמודד\n"
    .string "עם...\p"
    .string "ארבעת האליטה של ליגת הפוקימון!$"

ViridianCity_School_Text_TurnThePage::
    .string "להפוך את הדף?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "ילדה: היי!\n"
    .string "אל תסתכל על ההערות שלי!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "הלוח מציג את בעיות המצב\n"
    .string "של פוקימונים במהלך הקרב.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "איזה נושא אתה רוצה לקרוא?$"

ViridianCity_School_Text_ExplainSleep::
    .string "פוקימון לא יכול לתקוף כשהוא\n"
    .string "ישן.\p"
    .string "פוקימון יישאר ישן גם\n"
    .string "לאחר הקרב.\p"
    .string "השתמש במעורר כדי להעיר אחד\n"
    .string "מהשינה.$"

ViridianCity_School_Text_ExplainBurn::
    .string "כווייה מפחיתה את כוח ההתקפה.\n"
    .string "היא גם גורמת לאובדן HP מתמשך.\p"
    .string "כווייה נשארת לאחר הקרב. השתמש\n"
    .string "במשחה לכוויות כדי לרפא כווייה.$"

ViridianCity_School_Text_ExplainPoison::
    .string "כשהפוקימון מורעל, הבריאות שלו\n"
    .string "יורדת בהדרגה.\p"
    .string "הרעל נשאר לאחר הקרב.\n"
    .string "השתמש בנוגדן כדי לרפא את ההרעלה!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "פוקימון קפוא הופך\n"
    .string "לבלתי ניתן לתנועה.\p"
    .string "הוא נשאר קפוא גם לאחר\n"
    .string "שהקרב מסתיים.\p"
    .string "השתמש בתרופה להמסה כדי להפשיר את\n"
    .string "הפוקימון הקפוא.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "שיתוק מפחית את מהירות הפוקימון\n"
    .string "ויכול למנוע ממנו לנוע.\p"
    .string "השיתוק נשאר לאחר הקרב.\n"
    .string "השתמש בתרופה לשיתוק לטיפול.$"
