RockTunnel_1F_Text_LennyIntro::
    .string "המערה הזו ארוכה מאוד, ילד!$"

RockTunnel_1F_Text_LennyDefeat::
    .string "דוה!\n"
    .string "הניצחון שלך!$"

RockTunnel_1F_Text_LennyPostBattle::
    .string "תיזהר מאוניקס.\n"
    .string "הם מופיעים רק לפעמים.\p"
    .string "האוניקסים ברמות גבוהות יכולים\n"
    .string "לחנוק אותך!$"

RockTunnel_1F_Text_OliverIntro::
    .string "הממ.\n"
    .string "אולי אני אבוד כאן…$"

RockTunnel_1F_Text_OliverDefeat::
    .string "הירגע!\n"
    .string "מה אני עושה?\l"
    .string "לאן אני הולך?$"

RockTunnel_1F_Text_OliverPostBattle::
    .string "הפוקימון הישן בנתיב 21\n"
    .string "כפה עלי לקחת את הסיבוב הזה.$"

RockTunnel_1F_Text_LucasIntro::
    .string "זרים כמוך צריכים להראות לי\n"
    .string "כבוד!$"

RockTunnel_1F_Text_LucasDefeat::
    .string "אני מוותר!$"

RockTunnel_1F_Text_LucasPostBattle::
    .string "אתה מוכשר מספיק כדי לטפס!$"

RockTunnel_1F_Text_AshtonIntro::
    .string "קרב פוקימונים!\n"
    .string "מוכן, צא!$"

RockTunnel_1F_Text_AshtonDefeat::
    .string "המשחק נגמר!$"

RockTunnel_1F_Text_AshtonPostBattle::
    .string "טוב, אני אקבל זובאט בדרך!$"

RockTunnel_1F_Text_LeahIntro::
    .string "איי!\p"
    .string "אל תנסה משהו מצחיק בחושך!$"

RockTunnel_1F_Text_LeahDefeat::
    .string "היה יותר מדי חושך…$"

RockTunnel_1F_Text_LeahPostBattle::
    .string "ראיתי מאצ'ופ במערה הזו.$"

RockTunnel_1F_Text_DanaIntro::
    .string "הגעתי עד כאן בחיפוש אחרי\n"
    .string "פוקימונים בר.$"

RockTunnel_1F_Text_DanaDefeat::
    .string "אין לי עוד פוקימונים!$"

RockTunnel_1F_Text_DanaPostBattle::
    .string "נראית חמודה וחסרת מזיקה.\n"
    .string "הייתי כל כך טועה!$"

RockTunnel_1F_Text_ArianaIntro::
    .string "יש לך פוקימונים!\n"
    .string "בוא נתחיל!$"

RockTunnel_1F_Text_ArianaDefeat::
    .string "אתה משחק קשה!$"

RockTunnel_1F_Text_ArianaPostBattle::
    .string "פוו!\n"
    .string "אני כל כך מזיעה עכשיו.$"

RockTunnel_1F_Text_RouteSign::
    .string "מערת הסלע\n"
    .string "עיר סרוליאן - עיירת לבנדר$"
