CeladonCity_Restaurant_Text_TakingBreakRightNow::
    .string "הי!\p"
    .string "אנחנו בהפסקה כרגע.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
    .string "הפוקימונים שלי\n"
    .string "חלשים אז אני נאלצת לבקר במרכז\l"
    .string "הפוקימון לעיתים קרובות.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
    .string "פססט! יש מרתף\n"
    .string "נסתר מתחת למשחקיית רוקט...$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
    .string "לעיסה...\p"
    .string "האיש הזה שליד השולחן איבד את\l"
    .string "כל מה שהיה לו במכונות המזל.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
    .string "קדימה! צחק עלי!\p"
    .string "הפסדתי כל מה שהיה לי!\p"
    .string "סיימתי עם ההימורים. מהיום\l"
    .string "אני הולך בדרך הישר!\p"
    .string "קח! אני לא צריך את זה יותר!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
    .string "{PLAYER} קיבל\n"
    .string "את ארנק האסימונים$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
    .string "פנה קצת מקום\n"
    .string "בתיק שלך!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
    .string "תמיד חשבתי\n"
    .string "שאולי עוד אזכה בכסף שלי חזרה...$"

