TwoIsland_House_Text_TeachMonMoveForMushroom::
    .string "אני משוגע על מהלכי פוקימון.\p"
    .string "אני מכיר כל מהלך שפוקימונים\n"
    .string "לומדים בדרך לבגרות.\p"
    .string "אני גם משוגע על פטריות.\p"
    .string "תביא לי שתי פטריות קטנות,\n"
    .string "או פטרייה גדולה אחת.\p"
    .string "אם תעשה את זה בשבילי, אלמד\n"
    .string "מהלך לפוקימון אחד.$"

TwoIsland_House_Text_WantMeToTeachMove::
    .string "מרחרח, מרחרח…\n"
    .string "המ! יש לך ריח של פטריות!\p"
    .string "אתה רוצה שאלמד מהלך\n"
    .string "לאחד הפוקימונים שלך?$"

TwoIsland_House_Text_TutorWhichMon::
    .string "איזה פוקימון צריך שיעור?$"

TwoIsland_House_Text_TeachWhichMove::
    .string "איזה מהלך ללמד?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
    .string "מצטער…\p"
    .string "נראה שאין לי שום מהלך\n"
    .string "שאני יכול ללמד לפוקימון הזה.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
    .string "אז אצטרך פטרייה או שתיים.\n"
    .string "מה אתה הולך לתת לי?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
    .string "{PLAYER} מסר שתי\n"
    .string "פטריות קטנות בתמורה.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
    .string "{PLAYER} מסר פטרייה\n"
    .string "גדולה אחת בתמורה.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
    .string "אם הפוקימון שלך צריך ללמוד\n"
    .string "מהלך, אצטרך פטרייה או שתיים.$"

TwoIsland_House_Text_CantTeachAnEgg::
    .string "הא? אין אפילו מהלך אחד\n"
    .string "שאני יכול ללמד ביצה.$"

