SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
    .string "{PLAYER} מצא ספיר!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
    .string "פופו… פופופופו…\n"
    .string "ניחשתי נכון.\p"
    .string "צדקתי שעקבתי אחריך!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
    .string "ידעתי שיש כאן ספיר,\n"
    .string "אז הוא שייך לי!\p"
    .string "אני אמכור אותו לצוות רוקט\n"
    .string "בכסף רציני.\p"
    .string "…א-אל תסתכל עליי ככה!\p"
    .string "אם אתה רוצה אותו בחזרה,\n"
    .string "תיקח אותו אחרי שאמכור.\p"
    .string "אני אפילו אגלה לך אחת\n"
    .string "מהסיסמאות של המחסן\l"
    .string "של צוות רוקט.\p"
    .string "הסיסמה שאני מכיר למחסן היא\n"
    .string "“כן, לא, צ'נסי.”\p"
    .string "סיימתי.\n"
    .string "אל תחשוב עליי רעות!$"

