FiveIsland_MemorialPillar_Text_MiloIntro::
    .string "אני הבכור מבין אחי\n"
    .string "הציפורים.\p"
    .string "הדבר הכי טוב בציפורים…\n"
    .string "זה חייב להיות המקור.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
    .string "אוי, כל כך חד!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
    .string "אפשר לטוס מכאן\n"
    .string "לאי 4.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
    .string "אני האמצעי מבין אחי\n"
    .string "הציפורים.\p"
    .string "הדבר הכי טוב בציפורים…\n"
    .string "אלה חייבות להיות הכנפיים.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
    .string "נפנוף, נפנוף!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
    .string "היה בחור ממש קודר\n"
    .string "בכיוון הזה.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
    .string "אני הצעיר מבין אחי\n"
    .string "הציפורים.\p"
    .string "הדבר הכי טוב בציפורים…\n"
    .string "זו חייבת להיות הפלומה.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
    .string "פלומה כל כך נוחה…\n"
    .string "זה מרדים אותי…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
    .string "אני מתמלא אושר כשפוקימוני\n"
    .string "ציפור מתרפקים עליי בשובבות…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
    .string "קרצוף, קרצוף…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
    .string "שלום…\n"
    .string "הפוקימונים שלך נראים בריאים…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
    .string "כאן קברתי את האוניקס שלי…\n"
    .string "קראו לו טקטוניקס…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
    .string "“כאן טמון טקטוניקס” חרוט\n"
    .string "על אחד הסלעים.\p"
    .string "פחית לימונדה מונחת כמנחה\n"
    .string "לפני הקבר.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
    .string "רוצה להניח עוד לימונדה\n"
    .string "כמנחה?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
    .string "{PLAYER} הניח פחית לימונדה\n"
    .string "לפני הקבר.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
    .string "ת-תודה לך…\p"
    .string "זה היה המשקה האהוב על\n"
    .string "טקטוניקס שלי…\p"
    .string "אני בכלל לא מכיר אותך,\n"
    .string "אבל מעשה החסד שלך…\p"
    .string "הוא עודד אותי קצת.\p"
    .string "אפשר לבקש שתיקח את זה\n"
    .string "כאות תודה?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
    .string "תהיה טוב גם לפוקימונים\n"
    .string "שלך.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
    .string "אם אין לך מקום בשבילו,\n"
    .string "אשמור אותו עד הפעם הבאה.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
    .string "הו, זה אתה מאותו יום…\p"
    .string "עדיין שמור אצלי הדבר\n"
    .string "שרציתי לתת לך כאות תודה.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
    .string "קרצוף, קרצוף…\p"
    .string "… … …\n"
    .string "טקטוניקס…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
    .string "סלעים ואבנים מסודרים יפה\n"
    .string "כמצבת זיכרון.\p"
    .string "“כאן טמון טקטוניקס” חרוט\n"
    .string "על אחד הסלעים.$"

