Text_UltimateMoveThatMon::
    .string "שכללתי את מהלך העל\n"
    .string "של הסוג שלו…\p"
    .string "אך האם איש לא ינחיל אותו\n"
    .string "לדורות הבאים?\p"
    .string "…המ? המממ!\p"
    .string "א-אתה…\n"
    .string "ז-זה {STR_VAR_1}…$"

Text_JustMistaken::
    .string "…לא…\n"
    .string "פשוט טעיתי.$"

Text_AllowMeToTeachMonUltimateMove::
    .string "הו! זה הוא!\n"
    .string "זה הפוקימון!\p"
    .string "ה{STR_VAR_1} הזה ראוי\n"
    .string "ללמוד את מהלך העל שלי!\p"
    .string "תרשה לי?\p"
    .string "תרשה ל{STR_VAR_1} שלך\n"
    .string "ללמוד את {STR_VAR_2}?$"

Text_YouRejectIt::
    .string "גאאה! אתה מסרב?\n"
    .string "לא, לא אוותר!$"

Text_LetMeConferUltimateMove::
    .string "אתה מרשה?\p"
    .string "אם כך, אעניק את מהלך העל\n"
    .string "{STR_VAR_2} ל{STR_VAR_1} שלך.\p"
    .string "גררררה-אווווו!$"

Text_TaughtMove::
    .string "הא, הא, הא…\p"
    .string "לא חשבתי שאספיק ללמד את\n"
    .string "המהלך הזה בעודי בחיים…$"

Text_MakeBestUseOfMove::
    .string "אני מתחנן שתנצל את המהלך\n"
    .string "הזה היטב ותצבור כוח!$"

Text_PassedOnEverythingIKnow::
    .string "הא, הא, הא…\p"
    .string "עכשיו אין לי חרטות.\n"
    .string "העברתי את כל מה שידעתי.\p"
    .string "עכשיו אוכל לחיות בידיעה\n"
    .string "שמלאכתי הושלמה.$"

Text_FeelRejuvenated::
    .string "אחרי שהעברתי לך את הידע שלי,\n"
    .string "נגולה אבן מעל ליבי.\p"
    .string "למען האמת, אני מרגיש מחודש,\n"
    .string "כאילו חזרתי להיות צעיר!$"
