Route1_Text_WorkAtPokeMartTakeSample::
    .string "שלום!\n"
    .string "אני עובד בפוקימארט.\p"
    .string "זו רשת נוחה שמוכרת כל מיני\n"
    .string "פריטים.\p"
    .string "בבקשה, בקרו אותנו בעיר וירידיאן.\p"
    .string "אני יודע, אני אתן לך דוגמה.\n"
    .string "הנה, קח!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "בבקשה, תבואו לראות אותנו אם אתם\n"
    .string "צריכים פוקיבולים כדי לתפוס\l"
    .string "פוקימונים.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} שם את ה-תרופה בכיס\n"
    .string "הפריטים בתיק.$"

Route1_Text_CanJumpFromLedges::
    .string "רואים את הסלעים לאורך הדרך?\p"
    .string "זה קצת מפחיד, אבל אפשר לקפוץ\n"
    .string "מהם.\p"
    .string "אפשר להגיע חזרה לפאלט\n"
    .string "יותר מהר ככה.$"

Route1_Text_RouteSign::
    .string "דרך 1\n"
    .string "העיר פאלט - עיר וירידיאן$"
