Route12_FishingHouse_Text_DoYouLikeToFish::
    .string "אני אח של הגורו של הדיג.\n"
    .string "אני פשוט אוהב לדוג!\l"
    .string "לא יכול לעבור יום בלי זה.\l"
    .string "תגיד לי, אתה אוהב לדוג?$"

Route12_FishingHouse_Text_TakeThisAndFish::
    .string "מצוין! אני אוהב את הסגנון שלך.\n"
    .string "אני חושב שאנחנו יכולים להיות\l"
    .string "חברים. קח את זה ודוג, חבר צעיר!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
    .string "{PLAYER} קיבל את ה-סופר חכה מ\n"
    .string "האח של הגורו של הדיג.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
    .string "דיג זו דרך חיים!\n"
    .string "זה כמו השירה הכי טובה.\l"
    .string "מהים ועד הנהרות, צא לדוג את\l"
    .string "הגדול, חבר שלי.\l"
    .string "עכשיו, יש לי בקשה.\l"
    .string "אם תתפוס מג'יקארפ גדול\l"
    .string "עם המוט הזה, אני רוצה לראות אותו.\l"
    .string "כמה שאני אוהב לדוג, אני גם אוהב\l"
    .string "לראות מג'יקארפ ענקיים.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
    .string "אוי…\n"
    .string "זה מאכזב מאוד…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
    .string "שלום, {PLAYER}!\n"
    .string "האם דגת כבר?\l"
    .string "תנסה לדוג עם ה-סופר חכה ב\l"
    .string "כל מקור מים.\l"
    .string "תמצא פוקימונים שונים\l"
    .string "במקומות שונים.\l"
    .string "אה, ואל תשכח להביא לי\l"
    .string "מג'יקארפ ענקיים.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
    .string "אה? {PLAYER}?\n"
    .string "וואו, זה מג'יקארפ!\l"
    .string "תן לי לראות אותו, מהר!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
    .string "… … …וואו!\n"
    .string "{STR_VAR_2} אינצ'ים!\l"
    .string "יש לך הערכה נדירה\l"
    .string "לאספקטים הפואטיים של הדיג!\l"
    .string "אתה חייב לקחת את זה.\l"
    .string "אני מתעקש!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
    .string "אני מצפה לראות שיאים גדולים יותר\n"
    .string "ממך!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
    .string "הה?\n"
    .string "{STR_VAR_2} אינצ'ים?\l"
    .string "זה בדיוק בגודל של זה\l"
    .string "שראיתי לפני כן.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
    .string "המ…\n"
    .string "הזה הוא {STR_VAR_2} אינצ'ים.\l"
    .string "הוא לא מתאים ל-\l"
    .string "{STR_VAR_3} אינצ'ים שהבאת לפני כן.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
    .string "אה… זה לא נראה הרבה כמו\n"
    .string "מג'יקארפ.$"

Route12_FishingHouse_Text_NoRoomForGift::
    .string "אוי, לא!\n"
    .string "היה לי מתנה בשבילך, אבל אין לך\l"
    .string "מקום בשבילה.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
    .string "ה-מג'יקארפ הענק ביותר\n"
    .string "שאני אי פעם ראיתי…\l"
    .string "{STR_VAR_3} אינצ'ים!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
    .string "זו תרשים ריק כלשהו.\n"
    .string "יש בו מקום לרשום\l"
    .string "שיאים כלשהם.$"
