CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
    .string "אין דבר שאני לא יודע!\n"
    .string "בדיוק כמו שכתבתי על הלוח.\p"
    .string "אני מכיר את כל עולם הפוקימון\n"
    .string "שבתוך הגיים בוי אדוונס שלך!\p"
    .string "תיפגש עם החברים שלך\n"
    .string "ותיהנו מהחלפות פוקימונים!$"

CeladonCity_Condominiums_RoofRoom_Text_ObtainedAnEevee::
    .string "{PLAYER} קיבל איווי!$"

CeladonCity_Condominiums_RoofRoom_Text_BoxIsFull::
    .string "ポケモンが　いっぱいだ\n"
    .string "ボックスを　かえて　きなさい$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
    .string "הרצאות פוקימון\p"
    .string "לשחק עם מתאם אלחוטי$"

CeladonCity_Condominiums_RoofRoom_Text_ReadWhichHeading::
    .string "איזה נושא תרצה לקרוא?$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainWirelessClub::
    .string "מועדון הפוקימון האלחוטי נמצא\n"
    .string "בקומה העליונה בכל מרכז פוקימונים.\p"
    .string "בקר שם כדי להתחבר עם חברים שלך\n"
    .string "באמצעות מתאם אלחוטי.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainDirectCorner::
    .string "כדי להתחבר עם חבר בלבד\n"
    .string "לך לפינה הישירה.\p"
    .string "זה הדלפק הימני\n"
    .string "במועדון הפוקימון האלחוטי.\p"
    .string "היכנס לפינת ההחלפות או\n"
    .string "לקולוסאום עם חבריך.$"

CeladonCity_Condominiums_RoofRoom_Text_ExplainUnionRoom::
    .string "כדי להתחבר ולתקשר עם כל אחד,\n"
    .string "לך לחדר האיחוד.\p"
    .string "זה הדלפק השמאלי\n"
    .string "במועדון הפוקימון האלחוטי.\p"
    .string "לך לחדר האיחוד ותפגוש\n"
    .string "מאמנים אחרים.$"

CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
    .string "זה עלון על מ”מ.\p"
    .string "… …\p"
    .string "יש בסך הכל 05 מ”מ.\p"
    .string "יש גם 7 מ”נ\n"
    .string "שאפשר להשתמש בהם הרבה פעמים.\p"
    .string "חברת סילף.$"

