CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
    .string "אני כל-כך רוצה\n"
    .string "פוריגון!\p"
    .string "אבל, כל-כך קשה לזכות במשחקי מזל!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
    .string "זכיתי בשלל רב\n"
    .string "היום!$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
    .string "נחוץ בשביל זה ארנק לאסימונים…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
    .string "אנחנו מחליפים את האסימונים שלך\n"
    .string "בפרסים.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
    .string "איזה פרס תרצה?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
    .string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
    .string "אז, אתה רוצה את {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
    .string "אוקיי, מ“מ של המהלך {STR_VAR_2}\n"
    .string "זה מה שאתה רוצה?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
    .string "מצטער, אתה צריך עוד אסימונים\n"
    .string "כדי לקנות את זה.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
    .string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
    .string "あっ そう$"

