SixIsland_PatternBush_Text_BethanyIntro::
    .string "מעניין אותי, איך אתה מגדל\n"
    .string "את הפוקימונים שלך?$"

SixIsland_PatternBush_Text_BethanyDefeat::
    .string "אתה מגדל את הפוקימונים שלך\n"
    .string "עם המון אהבה!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
    .string "בדיוק כמו שאמא שלך גידלה\n"
    .string "אותך באהבה, כך כדאי שתגדל\l"
    .string "את הפוקימונים שלך.$"

SixIsland_PatternBush_Text_AllisonIntro::
    .string "אני פועלת לשמר כאן את\n"
    .string "האקולוגיה הטבעית של הפוקימון.$"

SixIsland_PatternBush_Text_AllisonDefeat::
    .string "אוי, בשביל מישהו כל כך צעיר,\n"
    .string "אתה פשוט אדיר!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
    .string "אני לא אומרת שאסור לך\n"
    .string "לתפוס פוקימונים.\p"
    .string "אני רק רוצה שאנשים יגדלו\n"
    .string "את הפוקימון שלהם באחריות.$"

SixIsland_PatternBush_Text_GarretIntro::
    .string "תפסתי פוקימון חרק שחי\n"
    .string "רק כאן באזור!$"

SixIsland_PatternBush_Text_GarretDefeat::
    .string "חחח…\n"
    .string "נכון שהפוקימון שלי מדהים?$"

SixIsland_PatternBush_Text_GarretPostBattle::
    .string "יש ליד הסבך בחורה שמודדת\n"
    .string "הרקרוסים בשביל מאמנים.$"

SixIsland_PatternBush_Text_JonahIntro::
    .string "אתה יודע, זה פשוט לא מרגיש\n"
    .string "נכון בלי פוקימוני חרק.$"

SixIsland_PatternBush_Text_JonahDefeat::
    .string "זה בסדר, גם להפסיד זה חלק\n"
    .string "מהקסם של הפוקימון.$"

SixIsland_PatternBush_Text_JonahPostBattle::
    .string "דרך אגב, “קסם” היא מילה\n"
    .string "מוזרה, אם חושבים על זה.\p"
    .string "זה כמו קיסם?\n"
    .string "או אולי כמו קסדה?$"

SixIsland_PatternBush_Text_VanceIntro::
    .string "כן, כן, כן!\n"
    .string "תראה כמה פוקימוני חרק!$"

SixIsland_PatternBush_Text_VanceDefeat::
    .string "הפסדתי בזמן שהייתי עדיין\n"
    .string "עסוק בחגיגות!$"

SixIsland_PatternBush_Text_VancePostBattle::
    .string "בפעם הבאה אני אביא לכאן\n"
    .string "את אחי הקטן.$"

SixIsland_PatternBush_Text_NashIntro::
    .string "תראה, תראה! יש תבניות\n"
    .string "מצחיקות על האדמה.$"

SixIsland_PatternBush_Text_NashDefeat::
    .string "מגניב בטירוף!$"

SixIsland_PatternBush_Text_NashPostBattle::
    .string "התבניות המצחיקות על האדמה…\p"
    .string "הן נראות כמו התבניות\n"
    .string "על הבגדים של סבא שלי.$"

SixIsland_PatternBush_Text_CordellIntro::
    .string "בטח אתה חושב שאני סתם\n"
    .string "איזה טיפוס, מה?$"

SixIsland_PatternBush_Text_CordellDefeat::
    .string "בטח אתה חושב שאני חלש,\n"
    .string "מה?$"

SixIsland_PatternBush_Text_CordellPostBattle::
    .string "אהה, אתם העירוניים באים הנה\n"
    .string "מצוחצחים עם כובע כזה בולט…\p"
    .string "מה דעתך לתת לי אותו?$"

SixIsland_PatternBush_Text_DaliaIntro::
    .string "קח נשימה עמוקה.\n"
    .string "נכון שהאוויר טעים?$"

SixIsland_PatternBush_Text_DaliaDefeat::
    .string "אם תרצה, אני יכולה ללמד\n"
    .string "אותך לנשום נכון.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
    .string "קודם כל, נשוף.\n"
    .string "תוציא את כל האוויר.\p"
    .string "כשאין לך יותר מה לנשוף,\n"
    .string "שאף את האוויר הנקי!\p"
    .string "נכון שזה מרענן?$"

SixIsland_PatternBush_Text_JoanaIntro::
    .string "אני מתה על פוקימוני חרק.\n"
    .string "בגלל זה אני כאן כל הזמן.\p"
    .string "אני הבחורה היחידה שכזאת?$"

SixIsland_PatternBush_Text_JoanaDefeat::
    .string "הפסדתי, ואני עדיין צוחקת.\n"
    .string "אני הבחורה היחידה שכזאת?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
    .string "אני אמשיך לאסוף\n"
    .string "פוקימוני חרק.\p"
    .string "אני הבחורה היחידה שכזאת?$"

SixIsland_PatternBush_Text_RileyIntro::
    .string "זה מקום טוב.\n"
    .string "אני אקים כאן את האוהל שלי.$"

SixIsland_PatternBush_Text_RileyDefeat::
    .string "התקפלתי…$"

SixIsland_PatternBush_Text_RileyPostBattle::
    .string "אני מתכוון לצפות כאן\n"
    .string "בשמי הלילה.$"

SixIsland_PatternBush_Text_MarcyIntro::
    .string "איכס!\n"
    .string "נראה לי שחרק עקץ אותי!$"

SixIsland_PatternBush_Text_MarcyDefeat::
    .string "זה לא היה חרק.\n"
    .string "חתכתי את הרגל בעשב.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
    .string "חתך קטן כזה…\n"
    .string "קצת רוק וזה יעבור!$"

SixIsland_PatternBush_Text_LaytonIntro::
    .string "שמת לב שיש משהו מוזר\n"
    .string "באזור הזה?$"

SixIsland_PatternBush_Text_LaytonDefeat::
    .string "הסתכלת טוב מסביב\n"
    .string "לרגליים שלך?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
    .string "יש כאן בסבך התבניות מקומות\n"
    .string "שבהם העשב לא צומח.\p"
    .string "מה יכולה להיות הסיבה\n"
    .string "לתופעה כזאת?$"

