SilphCo_10F_Text_GruntIntro::
    .string "ברוך הבא לקומה 01!\n"
    .string "איזה טוב מצידך להצטרף אלי!$"

SilphCo_10F_Text_GruntDefeat::
    .string "אני המום!$"

SilphCo_10F_Text_GruntPostBattle::
    .string "ניסיון טוב, אבל חדר הישיבות למעלה\n"
    .string "בקומה אחת.$"

SilphCo_10F_Text_TravisIntro::
    .string "די עם המשחקים המטופשים שלך!$"

SilphCo_10F_Text_TravisDefeat::
    .string "לא נשארו לי המשך!$"

SilphCo_10F_Text_TravisPostBattle::
    .string "האם אתה מרוצה מלהביס אותי?\n"
    .string "אז לך הביתה!$"

SilphCo_10F_Text_WaaaImScared::
    .string "ואאא!\n"
    .string "אני פוחד!$"

SilphCo_10F_Text_KeepMeCryingASecret::
    .string "לגבי זה שאני בוכה…\n"
    .string "בבקשה תשמור את זה בסוד.$"

SilphCo_10F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 01$"
