SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
    .string "{PLAYER}: שלום!\n"
    .string "אתה אוהב פוקימון?\p"
    .string "{PLAYER}: אה, לא, אני רק שאלתי.\p"
    .string "{PLAYER}: מה?\n"
    .string "אתה מוזר!\p"
    .string "חקיינית: הממ? להפסיק לחקות?\n"
    .string "אבל זה התחביב האהוב עלי!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
    .string "{PLAYER}: שלום.\n"
    .string "את בטח אוהבת פוקימון.\p"
    .string "{PLAYER}: לא, לא אני.\n"
    .string "אני שאלתי אותך.\p"
    .string "{PLAYER}: סליחה?\n"
    .string "את מוזרה!\l"
    .string " \l"
    .string "חקיינית: הממ? להפסיק לחקות?\l"
    .string "אבל זה התחביב האהוב עלי!$"

Text_MimicTeach::
    .string "וואו!\n"
    .string "בובה של פוקימון!\p"
    .string "בשבילי?\n"
    .string "תודה!\p"
    .string "אתה יודע מה?\n"
    .string "אני יכולה ללמד את המהלך 'חיקוי'.$"

Text_MimicDeclined::
    .string "אתה לא אוהב את 'חיקוי'? $"

Text_MimicWhichMon::
    .string "אני ממש אוהבת 'חיקוי'!\n"
    .string "איזה פוקימון הולך ללמוד אותו?$"

Text_MimicTaughtMale::
    .string "{PLAYER}: שלום!\n"
    .string "תודה על מקודם!\p"
    .string "{PLAYER}: סליחה?\p"
    .string "{PLAYER}: זה באמת כל כך כיף לחקות\n"
    .string "כל תנועה שלי?\p"
    .string "חקיינית: ברור!\n"
    .string "זה קורע מצחוק!$"

Text_MimicTaughtFemale::
    .string "{PLAYER}: שלום!\n"
    .string "תודה על מה שעשית בשבילנו.\p"
    .string "{PLAYER}: סליחה?\p"
    .string "{PLAYER}: זה באמת כל כך כיף לחקות\n"
    .string "את מה שאני אומרת ועושה?\p"
    .string "חקיינית: ברור!\n"
    .string "זה קורע מצחוק!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
    .string "にもつが　いっぱいね！$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
    .string "{PLAYER}“やあ！　こんにちは！\n"
    .string "きみ　ポケモン　すきかい？\p"
    .string "{PLAYER}“ぼく　じゃなくって\n"
    .string "きみに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥‥　えー　なんだよ！\n"
    .string "ヘンな　やつ　だなあ！\p"
    .string "モノマネむすめ“‥‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし　\n"
    .string "ものまね　しゅみ　なんだ　もん！”$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
    .string "{PLAYER}“こんにちは！\n"
    .string "ポケモン　すきなのね？\p"
    .string "{PLAYER}“わたし　じゃなくって\n"
    .string "あなたに　きいてるんだ　けど\p"
    .string "{PLAYER}“‥　えー　なんなの！\n"
    .string "おかしなこ　ねー！\p"
    .string "モノマネむすめ“‥　なに？\n"
    .string "ひとの　マネ　すんなって？\p"
    .string "だって　あたし\n"
    .string "ものまね　しゅみ　なんだ　もん！$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
    .string "דודו: גיייח!\p"
    .string "מראה יפה, תסתכלי עלי,\n"
    .string "תראי כמה יפה אני יכול להיות!$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
    .string "זהו פוקימון נדיר!\n"
    .string "מה? זו רק בובה!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
    .string "משחק שבו מריו חובש דלי\n"
    .string "על הראש!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
    .string "…\p"
    .string "הסודות שלי!\p"
    .string "כישרון: חיקוי!\n"
    .string "תחביב: איסוף בובות!\l"
    .string "פוקימון אהוב: קלפרי!$"


SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
    .string "？　みえないぞ‥$"
