PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "אמא: נכון...\n"
    .string "כל הילדים עוזבים את הבית יום אחד.\l"
    .string "אפילו אמרו את זה בטלוויזיה.\p"
    .string "אה נזכרתי, פרוספור אוק חיפש אותך,\n"
    .string "הוא נמצא בבית לידנו.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "אמא: נכון...\n"
    .string "כל הילדים עוזבים את הבית יום אחד.\l"
    .string "אפילו אמרו את זה בטלוויזיה.\p"
    .string "אה נזכרתי, פרוספור אוק חיפש אותך,\n"
    .string "הוא נמצא בבית לידנו.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "אמא: {PLAYER}!\n"
    .string "כדאי שתיקח מנוחה קצרה.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "אמא: יופי! אתה והפוקימון שלך\n"
    .string "נראים נהדר.\l"
    .string "תשמור על עצמך!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "יש סרט בטלוויזיה.\n"
    .string "ארבעה בנים הולכים על פסי רכבת.\l"
    .string "אני גם צריך ללכת.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "יש סרט בטלוויזיה.\n"
    .string "ילדה עם צמות הולכת על דרך.\l"
    .string "שבנויה מאבנים צהובות.\p"
    .string "אני גם צריכה ללכת.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "אופס... צד לא נכון$"

