Route16_House_Text_FoundMySecretRetreat::
    .string "אוי, לא.\n"
    .string "מצאת את המסתור הסודי שלי.\p"
    .string "בבקשה אל תספר לאף אחד שאני כאן.\n"
    .string "אני אפצה אותך בזה!$"

Route16_House_Text_ReceivedHM02FromGirl::
    .string "{PLAYER} קיבל/ה את מ”נ20\n"
    .string "מהילדה.$"

Route16_House_Text_ExplainHM02::
    .string "מ”נ20 הוא תעופה.\n"
    .string "זו תנועה נוחה במיוחד.\p"
    .string "בבקשה, תעשה בזה שימוש טוב.$"

Route16_House_Text_DontHaveAnyRoomForThis::
    .string "אין לך מקום לזה.$"

Route16_House_Text_Fearow::
    .string "פירואו: קוווין!$"
