PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
    .string "מגדל הפוקימון הוקם לזכר\n"
    .string "הפוקימונים שמתו.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
    .string "האם באת לחלוק כבוד?\p"
    .string "ברכתי על ליבך האוהב\n"
    .string "פוקימונים, בני.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
    .string "האם באת לחלוק כבוד?\p"
    .string "ברכתי על ליבך האוהב\n"
    .string "פוקימונים, בתי.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
    .string "באתי להתפלל עבור\n"
    .string "הקלפרי האהוב שלי.\p"
    .string "סניף!\n"
    .string "אני מוצף בדמעות…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
    .string "הגראולית' שלי…\n"
    .string "למה מתת?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
    .string "אני מתקשרת.\p"
    .string "יש רוחות שעושות צרות.\n"
    .string "אני חשה אותן גבוה במגדל.$"
