Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
    .string "סוגי הפוקימונים תואמים אחד לשני\n"
    .string "בצורות שונות.\p"
    .string "כל סוג חזק יותר בפני סוגים\n"
    .string "מסוימים וחלש יותר בפני אחרים.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
    .string "נוגט הוא חסר תועלת לגמרי.\n"
    .string "אז מכרתי אותו ב-¥0005.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
    .string "שמעתי שרוחות רפאים רודפות\n"
    .string "את עיר לאבנדר.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
    .string "אה… {PLAYER}!\n"
    .string "חיפשתי אותך!\p"
    .string "אני אחד מהעוזרים שתמיד נמצאים\n"
    .string "ליד פרופ' אוק.\p"
    .string "אם הפוקדקס שלך מכיל נתונים\n"
    .string "על עשרים מיני פוקימונים, אני אמור\l"
    .string "לתת לך פרס מפרופ' אוק.\p"
    .string "הוא הטיל עלי את המשימה הזו\n"
    .string "לתת לך את ה-אבן נצח.\p"
    .string "אז, {PLAYER}, תן לי לשאול אותך.\p"
    .string "האם אספת נתונים על לפחות\n"
    .string "עשרים סוגי פוקימונים?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
    .string "מעולה! אספת או תפס את\n"
    .string "{STR_VAR_3} סוגי פוקימונים!\p"
    .string "מזל טוב!\n"
    .string "הנה, קח את זה!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
    .string "{PLAYER} קיבל את ה-אבן נצח\n"
    .string "מהעוזר.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
    .string "הפיכת פוקימונים לאבולוציה בוודאי\n"
    .string "יכולה להוסיף לפוקדקס.\p"
    .string "אבל לפעמים, ייתכן שלא תרצה\n"
    .string "שהפוקימון שלך יתפתח.\p"
    .string "במקרה כזה, תן לפוקימון את ה-אבן\n"
    .string "נצח זה ימנע ממנו להתפתח על פי\l"
    .string "הפרופסור.$"
