SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
    .string "תשחק הרבה עם פוקימון\n"
    .string "ותחיה חיים ארוכים!\p"
    .string "קח לדוגמה את אגתה.\p"
    .string "היא קבעה שיא בתור החברה\n"
    .string "הכי מבוגרת ברביעייה העילית.\p"
    .string "היא נותנת לי השראה לגדולות.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
    .string "כדאי שאקנה דואר ואכתוב\n"
    .string "לו מכתב…$"

