CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: יו!\n"
    .string "{PLAYER}!\p"
    .string "אתה עדיין צולע לך שם?\p"
    .string "אני מתקדם יפה! תפסתי כל מיני\l"
    .string "פוקימונים חזקים וחכמים!\p"
    .string "קדימה, בוא נראה מה אתה תפסת,\l"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "היי!\n"
    .string "תרגיע! כבר ניצחת אותי!\p$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "פחה!\n"
    .string "אתה לא משתווה לגאונות שלי!\p$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: היי,\n"
    .string "נחש מה עשיתי?\p"
    .string "הלכתי לבית של ביל ושכנעתי אותו\n"
    .string "להראות לי את הפוקימונים\l"
    .string "הנדירים שלו!\p"
    .string "זה מילא לי הרבה דפים בפוקדקס!\p"
    .string "הרי ביל ידוע בתור פוקימניאק!\p"
    .string "הוא המציא את מערכת\n"
    .string "איחסון הפוקימונים שבמחשב!\p"
    .string "כדאי שתלך להודות לו, כי אתה משתמש\l"
    .string "בהמצאה שלו!\p"
    .string "טוב! נראה לי שכדאי\n"
    .string "שאני אתגלגל מכאן! נתרחרח אחר-כך!$"

CeruleanCity_Text_GruntIntro::
    .string "היי! צא מכאן!\n"
    .string "זאת לא החצר שלך! מה? אני?\p"
    .string "אני רק עובר אורח תמים! אתה לא\l"
    .string "מאמין לי?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} מצא\n"
    .string "מ”מ82!{}$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "כדאי שאני אסתלק\n"
    .string "לי עכשיו! ביי!{}$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "פנה קצת מקום\n"
    .string "כדי לקחת את זה!\p"
    .string "אסור לי לברוח עד שאני אתן לך את\l"
    .string "זה!$"

CeruleanCity_Text_GruntDefeat::
    .string "תפסיק!\n"
    .string "אני נכנע! אני אעזוב בשקט!\p$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "בסדר! אני אחזיר\n"
    .string "את המ”מ שגנבתי!\p$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "גם אתה מאמן?\n"
    .string "אספנות, קרבות... זה סגנון חיים\l"
    .string "קשוח.$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "השיח הזה שם שמול\n"
    .string "החנות מפריע בדרך.\p"
    .string "אולי יש דרך לעקוף אותו.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "אתה מחבר\n"
    .string "אנציקלופדיה על פוקימון? זה משעשע.$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "דיירי הבית הזה\n"
    .string "נשדדו.\p"
    .string "זה ברור כשמש שצוות רוקט עומד\l"
    .string "מאחורי הפשע הנתעב!\p"
    .string "צוות רוקט עושים בעיות אפילו עבור\l"
    .string "כוח המשטרה שלנו!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "אוקיי! סלוברו!\n"
    .string "השתמש בבום על- קולי!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "קדימה, סלוברו,\l"
    .string "תתרכז!$"

CeruleanCity_Text_SlowbroPunch::
    .string "סלוברו, תן מכה!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "לא! שוב פספסת!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "סלוברו, נסיגה!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "לא! זה לא מה\l"
    .string "שהתכוונתי!\p"
    .string "כל כך קשה לשלוט בפוקימונים!\p"
    .string "הצייתנות של הפוקימונים שלך\l"
    .string "תלויה ביכולות שלך בתור מאמן!$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "סלוברו מנמנם...$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "סלוברו מתעצל...$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "סלוברו הפנה את\n"
    .string "הגב...$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "סלוברו התעלם\n"
    .string "מהפקודה...$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "אני רוצה אופניים\n"
    .string "בצבע אדום אש!\p"
    .string "אני לא אוציא אותם מהבית, כדי שלא\l"
    .string "יתלכלכו!$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "זו היא מערת\n"
    .string "סרוליאן! בפנים חיים פוקימונים\l"
    .string "חזקים להחריד!\p"
    .string "האלוף של ליגת הפוקימון הוא\l"
    .string "היחיד שמורשה להיכנס!$"

CeruleanCity_Text_CitySign::
    .string "העיר סרוליאן\n"
    .string "אפופה בהילה כחולה ומסתורית$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "טיפים למאמנים\p"
    .string "לחיצה על כפתור B\n"
    .string "בזמן התפתחות תבטל את ההתפתחות.$"

CeruleanCity_Text_BikeShopSign::
    .string "עוברים מערות\n"
    .string "ומדשאות בקלות! חנות אופניים$"

CeruleanCity_Text_GymSign::
    .string "העיר סרוליאן\n"
    .string "מכון הפוקימון מנהיגה: מיסטי\p"
    .string "בת הים הנערית!$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "פטפטן רכלן שכמותך…\n"
    .string "הדבר הזה הוא מושלם.\p"
    .string "אני לא צריך אותו כי לא אכפת\n"
    .string "לי מאנשים אחרים.\p"
    .string "טוב הפעם אני באמת צריך ללכת.\n"
    .string "נתרחרח אחר-כך!$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "אם סלוברו לא היה שם, היית\n"
    .string "יכול לכרות את העץ הקטן בחיתוך.\p"
    .string "ככה היית יכול להגיע\n"
    .string "לצד השני.\p"
    .string "אבל אני חושב שיש\n"
    .string "דרך לעקוף אותו.$"
