CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
    .string "שלום! ברוך הבא\n"
    .string "לחנות האופניים.\p"
    .string "יש לנו זוג אופניים בדיוק בשבילך!$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
    .string "אלה אופניים ממש שווים!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
    .string "אני מצטער, אבל\n"
    .string "אין לך מספיק כסף!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
    .string "זה...\p"
    .string "שובר לאופניים!\p"
    .string "בסדר! הנה לך!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
    .string "{PLAYER} החליף את\n"
    .string "השובר לאופניים בעד זוג אופניים.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
    .string "נשמח לראותך\n"
    .string "שוב!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
    .string "אתה נהנה מהאופניים\n"
    .string "החדשים שלך?\p"
    .string "אתה יכול לרכב עליהם גם בשביל\l"
    .string "האופניים או בתוך מערות!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
    .string "כדאי שתפנה קצת\n"
    .string "מקום בשביל זה!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
    .string "אופניים עירוניות\n"
    .string "מספיקות לי בהחלט!\p"
    .string "הרי אי אפשר להרכיב\n"
    .string "סל קניות על אופני הרים!$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
    .string "האופניים האלה\n"
    .string "מגניבים, אבל הם יקרים בטירוף!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
    .string "וואו. האופניים שלך\n"
    .string "ממש מגניבים!$"

@ Unused
CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
    .string "ついに　はつばい！\p"
    .string "ドイツ　せい　さいこうきゅう\n"
    .string "おりたたみ　じてんしゃ！$"


