FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
    .string "הרבה פוקימונים כלואים\n"
    .string "בתוך המכלאה…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
    .string "דלת המכלאה פתוחה.\n"
    .string "נראה שהפוקימונים ברחו.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
    .string "באת לכאן בידיעה שזה\n"
    .string "המחסן של צוות רוקט?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
    .string "מה אתה חושב שאתה עושה?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
    .string "צוות רוקט התפרק?\n"
    .string "מאיזה כוכב אתה?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
    .string "הו, הפוקימונים שלך חזקים.\n"
    .string "מוכן למכור אותם?\p"
    .string "הו?\n"
    .string "רצית להילחם?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
    .string "הו, אבל…\n"
    .string "יותר מדי!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
    .string "נוכל לתת לך מחיר מעולה.\n"
    .string "תמכור לנו את הפוקימונים!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
    .string "שמעתי עליך\n"
    .string "מהאחרים.\p"
    .string "אבל אין סיכוי שילד כמוך\n"
    .string "מכיר את הבוס שלנו, ג'ובאני!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
    .string "אל… תעז… לצחוק…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
    .string "אל תתערב בענייני מבוגרים,\n"
    .string "פרחח קטן שכמותך!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
    .string "לא יודעת ולא אכפת לי אם מה\n"
    .string "שאני עושה נכון או לא…\p"
    .string "אני פשוט נותנת אמון בג'ובאני\n"
    .string "ועושה מה שאומרים לי.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
    .string "אני…\n"
    .string "אני מרוסקת…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
    .string "אתה פועל לפי האמונות\n"
    .string "והמוסר שלך.\p"
    .string "עכשיו אני מבינה…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
    .string "דאגתי שתוכל לחזור פנימה\n"
    .string "דרך שם.\p"
    .string "למה שלא תלך לנוח ולהתרענן\n"
    .string "לקראת מה שמחכה לך?\p"
    .string "המנהל שממתין בהמשך עולה\n"
    .string "עליי בהרבה כמאמן.\p"
    .string "כדאי שתתכונן היטב\n"
    .string "לאתגר קשה.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
    .string "מספיק עם זה שאתה\n"
    .string "משחק אותה גיבור, ילד.\p"
    .string "מפיץ שקרים על כך שצוות רוקט\n"
    .string "התפרק…\p"
    .string "זה ניסיון כל כך שקוף\n"
    .string "לזרוע בלבול בשורות שלנו.\p"
    .string "למזלנו, אנחנו לא בורים\n"
    .string "מספיק כדי להאמין לשקרי ילד!\p"
    .string "ועכשיו, אראה לך כמה מפחיד\n"
    .string "מבוגר כועס יכול להיות!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
    .string "אוף…\n"
    .string "היית חזק מדי…\p"
    .string "…\n"
    .string "ז-זה התג של ג'ובאני!\p"
    .string "אז זה נכון?\n"
    .string "צוות רוקט באמת התפרק?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
    .string "אנחנו ננטוש את המחסן הזה…\p"
    .string "אבל אל תחשוב שזה נגמר.\n"
    .string "אני לא אתן לזה להיות הסוף.\p"
    .string "אני אמצא את ג'ובאני.\n"
    .string "ואקים מחדש את צוות רוקט!\l"
    .string "אני אעשה זאת…\p"
    .string "עד אז, להתראות!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
    .string "על מסך המחשב יש דוח\n"
    .string "עם גרפים וטקסט.\p"
    .string "“השפעת גלים מגנטיים\n"
    .string "על התפתחות פוקימונים”…\p"
    .string "… … … … … …\p"
    .string "קשה מדי להבין את זה…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
    .string "כמעט הצלחתי למכור את\n"
    .string "הספיר בהון עתק…\p"
    .string "ואז היית חייב לבוא\n"
    .string "ולפוצץ לי את כל העסקה!\p"
    .string "פופו… פופופופו…\n"
    .string "לא אסלח לך לעולם!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
    .string "אח! לעזאזל!\n"
    .string "לעזאזל! לעזאזל!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
    .string "אם אני לא יכול למכור אותו,\n"
    .string "הוא חסר ערך! קדימה, קח!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
    .string "מה אתה רוצה עכשיו?\n"
    .string "קדימה, תסתלק, עזוב אותי.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
    .string "מה, שוב אתה?\p"
    .string "אתה… אתה לא הילד של ג'ובאני,\n"
    .string "נכון?\p"
    .string "לא, זה לא יכול להיות נכון!\n"
    .string "לילד של ג'ובאני יש שיער אדום.\p"
    .string "אין לך שום סיבה להציק לי.\n"
    .string "עזוב אותי בשקט!$"

