#include "global.h"
#include "constants/moves.h"

const u8 gMoveDescription_Pound[] = _("התקפה פיזית\nשמבוצעת עם\nזנב ארוך או\nרגל קדמית וכו'.");
const u8 gMoveDescription_KarateChop[] = _("היריב מותקף\nעם חיתוך חד.\nיש לו יחס גבוה\nשל פגיעה קריטית.");
const u8 gMoveDescription_DoubleSlap[] = _("היריב נסטר\nשוב ושוב, הלוך\nוחזור, פעמיים עד\nחמש פעמים.");
const u8 gMoveDescription_CometPunch[] = _("היריב מוכה עם\nמטר של אגרופים\nשפוגעים פעמיים עד\nחמש פעמים.");
const u8 gMoveDescription_MegaPunch[] = _("היריב מוכה\nעל ידי אגרוף שנזרק\nעם כוח שרירים\nעצום.");
const u8 gMoveDescription_PayDay[] = _("מטבעות רבים\nנזרקים על היריב.\nכסף מתקבל\nלאחר הקרב.");
const u8 gMoveDescription_FirePunch[] = _("היריב מוכה\nעם אגרוף אש.\nזה עלול להשאיר את\nהיריב עם כוויה.");
const u8 gMoveDescription_IcePunch[] = _("היריב מוכה\nעם אגרוף קרח.\nזה עלול להקפיא\nאת היריב.");
const u8 gMoveDescription_ThunderPunch[] = _("היריב מוכה\nעם אגרוף חשמלי.\nזה עלול לשתק\nאת היריב.");
const u8 gMoveDescription_Scratch[] = _("ציפורניים קשות,\nמחודדות וחדות\nשורטות את היריב.");
const u8 gMoveDescription_ViceGrip[] = _("צבתות ענקיות\nומרשימות אוחזות\nולוחצות את היריב.");
const u8 gMoveDescription_Guillotine[] = _("התקפת קריעה\nאכזרית עם צבתות.\nהיריב יתעלף\nאם זה פוגע.");
const u8 gMoveDescription_RazorWind[] = _("להבי רוח פוגעים\nביריב בתור ה-2.\nיש לו יחס גבוה\nשל פגיעה קריטית.");
const u8 gMoveDescription_SwordsDance[] = _("ריקוד פרוע של\nלחימה. זה מעלה\nבחדות את נתון\nההתקפה.");
const u8 gMoveDescription_Cut[] = _("התקפה בסיסית.\nניתן להשתמש בה\nלחתוך עצים דקים\nועשב.");
const u8 gMoveDescription_Gust[] = _("פוגע ביריב\nעם משב רוח\nשנוצר על ידי\nכנפיים.");
const u8 gMoveDescription_WingAttack[] = _("היריב מוכה\nעם כנפיים גדולות\nומרשימות פרושות.");
const u8 gMoveDescription_Whirlwind[] = _("היריב נאלץ להתחלף\nעם בן ברית. בטבע,\nהקרב מסתיים.");
const u8 gMoveDescription_Fly[] = _("מהלך של 2 תורים\nשפוגע בתור ה-2.\nהשתמש בו לעוף\nלכל עיר מוכרת.");
const u8 gMoveDescription_Bind[] = _("גוף ארוך או זרועות\nמשמשים לכבול את\nהיריב לשניים עד\nחמישה תורים.");
const u8 gMoveDescription_Slam[] = _("היריב מוכה\nעם זנב ארוך,\nגפנים וכו'.");
const u8 gMoveDescription_VineWhip[] = _("היריב מוכה\nעם גפנים דקות\nודמויות שוט.");
const u8 gMoveDescription_Stomp[] = _("היריב נרמס\nעם רגל גדולה.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_DoubleKick[] = _("שתי רגליים משמשות\nלבעיטה מהירה ביריב\nפעמיים בתור\nאחד.");
const u8 gMoveDescription_MegaKick[] = _("היריב מותקף\nעל ידי בעיטה\nעם כוח שרירים\nעצום.");
const u8 gMoveDescription_JumpKick[] = _("המשתמש קופץ גבוה,\nואז בועט. אם זה\nמחטיא, המשתמש\nפוגע בעצמו.");
const u8 gMoveDescription_RollingKick[] = _("בעיטה מהירה\nמסיבוב.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_SandAttack[] = _("הרבה חול נזרק\nבפני היריב, מפחית\nאת הדיוק שלו.");
const u8 gMoveDescription_Headbutt[] = _("המשתמש מוציא את\nראשו ונוגח.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_HornAttack[] = _("היריב נדקר\nעם קרן מחודדת\nכדי לגרום נזק.");
const u8 gMoveDescription_FuryAttack[] = _("היריב נדקר\nשוב ושוב עם\nקרן או מקור פעמיים\nעד חמש פעמים.");
const u8 gMoveDescription_HornDrill[] = _("הקרן מסתובבת\nכמו מקדחה לנגיחה.\nהיריב יתעלף\nאם זה פוגע.");
const u8 gMoveDescription_Tackle[] = _("התקפה פיזית\nשבה המשתמש\nמסתער, עם כל גופו,\nעל היריב.");
const u8 gMoveDescription_BodySlam[] = _("המשתמש מפיל את\nכל גופו על היריב.\nזה עלול לשתק\nאת היריב.");
const u8 gMoveDescription_Wrap[] = _("גוף ארוך או גפנים\nמשמשים לעטוף את\nהיריב לשניים עד\nחמישה תורים.");
const u8 gMoveDescription_TakeDown[] = _("התקפת הסתערות\nפזיזה עם כל הגוף\nשפוגעת גם במשתמש\nמעט.");
const u8 gMoveDescription_Thrash[] = _("המשתמש משתולל\nבמשך שניים עד\nשלושה תורים, ואז\nנהיה מבולבל.");
const u8 gMoveDescription_DoubleEdge[] = _("התנגשות פזיזה\nמסכנת חיים שפוגעת\nגם במשתמש\nמעט.");
const u8 gMoveDescription_TailWhip[] = _("המשתמש מנענע את\nזנבו בחמידות, גורם\nליריב להוריד את\nנתון ההגנה שלו.");
const u8 gMoveDescription_PoisonSting[] = _("היריב נדקר עם קוץ\nרעיל, וכו'. זה עלול\nלהרעיל את היריב.");
const u8 gMoveDescription_Twineedle[] = _("היריב נדקר פעמיים\nעם עוקצים מהרגליים\nהקדמיות. זה עלול\nלהרעיל את היריב.");
const u8 gMoveDescription_PinMissile[] = _("סיכות חדות נורות\nעל היריב ופוגעות\nפעמיים עד חמש\nפעמים בבת אחת.");
const u8 gMoveDescription_Leer[] = _("היריב מקבל\nמבט מאיים\nשמוריד את\nנתון ההגנה שלו.");
const u8 gMoveDescription_Bite[] = _("המשתמש נושך עם\nניבים אכזריים.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_Growl[] = _("המשתמש נוהם\nבצורה חמודה, גורם\nליריב להוריד את\nנתון ההתקפה שלו.");
const u8 gMoveDescription_Roar[] = _("היריב נאלץ להתחלף\nעם בן ברית. בטבע,\nהקרב מסתיים.");
const u8 gMoveDescription_Sing[] = _("שיר מרגיע\nבקול מרגיע\nמרדים את היריב\nלשינה עמוקה.");
const u8 gMoveDescription_Supersonic[] = _("המשתמש מייצר\nגלי קול מוזרים.\nזה עלול לבלבל את\nהיריב.");
const u8 gMoveDescription_SonicBoom[] = _("היריב מוכה עם\nגל הדף שתמיד\nגורם ל-20\nנקודות נזק.");
const u8 gMoveDescription_Disable[] = _("למשך כמה תורים, זה\nמונע מהיריב\nלהשתמש במהלך שהוא\nהשתמש בו לאחרונה.");
const u8 gMoveDescription_Acid[] = _("היריב מרוסס\nבחומצה קשה, ממיסת\nעור שעלולה להוריד\nאת ההגנה.");
const u8 gMoveDescription_Ember[] = _("היריב מותקף\nעם להבות קטנות.\nהיריב עלול לסבול\nמכוויה.");
const u8 gMoveDescription_Flamethrower[] = _("היריב נשרף\nבלהבות עזות.\nהיריב עלול לסבול\nמכוויה.");
const u8 gMoveDescription_Mist[] = _("קבוצת בני הברית\nמוגנת על ידי\nערפל שמונע\nהפחתות נתונים.");
const u8 gMoveDescription_WaterGun[] = _("היריב מוכה\nעם הרבה מים\nשנפלטים בכוח\nמהפה.");
const u8 gMoveDescription_HydroPump[] = _("נפח גדול של\nמים נורה על\nהיריב תחת לחץ\nגבוה.");
const u8 gMoveDescription_Surf[] = _("גל גדול מתרסק\nעל היריב.\nניתן גם להשתמש בו\nלחציית מים.");
const u8 gMoveDescription_IceBeam[] = _("היריב מוכה\nעם קרן קרח.\nזה עלול להקפיא את\nהיריב לחלוטין.");
const u8 gMoveDescription_Blizzard[] = _("היריב מופגז\nעם סופת שלג.\nזה עלול להקפיא את\nהיריב לחלוטין.");
const u8 gMoveDescription_Psybeam[] = _("קרן מוזרה\nנורית על היריב.\nזה עלול להשאיר את\nהיריב מבולבל.");
const u8 gMoveDescription_BubbleBeam[] = _("התזה של בועות\nפוגעת ביריב. זה\nעלול להוריד את\nהמהירות של היריב.");
const u8 gMoveDescription_AuroraBeam[] = _("קרן התקפה בצבעי\nהקשת. זה עלול\nלהוריד את נתון\nההתקפה של היריב.");
const u8 gMoveDescription_HyperBeam[] = _("התקפה מזיקה מאוד\nשגורמת למשתמש\nלנוח בתור\nהבא.");
const u8 gMoveDescription_Peck[] = _("היריב נדקר\nעם מקור או\nקרן מחודדים.");
const u8 gMoveDescription_DrillPeck[] = _("התקפת סיבוב\nעם המקור החד\nהפועל כמקדחה.");
const u8 gMoveDescription_Submission[] = _("התקפת הטלה פזיזה\nעם כל הגוף\nשפוגעת גם במשתמש\nמעט.");
const u8 gMoveDescription_LowKick[] = _("בעיטה נמוכה,\nמכשילה שגורמת יותר\nנזק ליריבים כבדים\nיותר.");
const u8 gMoveDescription_Counter[] = _("מהלך תגמול\nשמחזיר כל\nפגיעה פיזית עם\nכפל הנזק.");
const u8 gMoveDescription_SeismicToss[] = _("הטלה מונעת כבידה\nשגורמת נזק\nהתואם את רמת\nהמשתמש.");
const u8 gMoveDescription_Strength[] = _("היריב מוכה\nבכוח מקסימלי.\nניתן גם להשתמש\nלהזזת סלעים.");
const u8 gMoveDescription_Absorb[] = _("התקפה שסופגת\nחצי מהנזק שהיא\nגרמה כדי לשחזר\nנקודות חיים.");
const u8 gMoveDescription_MegaDrain[] = _("התקפה קשה שמנקזת\nחצי מהנזק שהיא\nגרמה כדי לשחזר\nנקודות חיים.");
const u8 gMoveDescription_LeechSeed[] = _("זרע נשתל על היריב\nכדי לגנוב קצת\nנקודות חיים למשתמש\nבכל תור.");
const u8 gMoveDescription_Growth[] = _("גופו של המשתמש\nנאלץ לגדול,\nמעלה את נתון\nההתקפה המיוחדת.");
const u8 gMoveDescription_RazorLeaf[] = _("היריב מוכה עם\nעלה חותך.\nיש לו יחס גבוה\nשל פגיעה קריטית.");
const u8 gMoveDescription_SolarBeam[] = _("מהלך של 2 תורים\nשמפוצץ את היריב\nעם אנרגיה שנספגה\nבתור ה-2.");
const u8 gMoveDescription_PoisonPowder[] = _("ענן של אבק\nרעיל מפוזר.\nזה עלול להרעיל את\nהיריב.");
const u8 gMoveDescription_StunSpore[] = _("אבק משתק\nמפוזר בפראות.\nזה עלול לשתק\nאת היריב.");
const u8 gMoveDescription_SleepPowder[] = _("אבק מרדים\nמפוזר בנפח גבוה\nסביב יריב.");
const u8 gMoveDescription_PetalDance[] = _("תקיפה בעלי כותרת,\n2 עד 3 תורים. אחר\nכך המשתמש מבולבל.");
const u8 gMoveDescription_StringShot[] = _("היריב נקשר\nעם חוטים שנורים\nמהפה כדי להפחית\nאת המהירות שלו.");
const u8 gMoveDescription_DragonRage[] = _("היריב מוכה עם\nגל הדף שתמיד\nגורם ל-40\nנקודות נזק.");
const u8 gMoveDescription_FireSpin[] = _("היריב נלכד בספירלה\nעזה של אש\nשמשתוללת שניים עד\nחמישה תורים.");
const u8 gMoveDescription_ThunderShock[] = _("התקפת הלם חשמלי\nשעלולה גם\nלהשאיר את היריב\nמשותק.");
const u8 gMoveDescription_Thunderbolt[] = _("התקפה חשמלית חזקה\nשעלולה גם\nלהשאיר את היריב\nמשותק.");
const u8 gMoveDescription_ThunderWave[] = _("הלם חשמלי חלש\nשבטוח יגרום לשיתוק\nאם הוא פוגע.");
const u8 gMoveDescription_Thunder[] = _("התקפת ברק\nאכזרית שעלולה\nגם להשאיר את היריב\nמשותק.");
const u8 gMoveDescription_RockThrow[] = _("היריב מותקף\nעם מטר של\nסלעים קטנים,\nקלים לזריקה.");
const u8 gMoveDescription_Earthquake[] = _("רעידת אדמה שפוגעת\nבכל הפוקימונים\nבקרב למעט\nהמשתמש.");
const u8 gMoveDescription_Fissure[] = _("היריב נופל\nלתוך סדק.\nהיריב מתעלף אם\nזה פוגע.");
const u8 gMoveDescription_Dig[] = _("התקפה שפוגעת\nבתור ה-2.\nניתן גם להשתמש\nליציאה ממבוכים.");
const u8 gMoveDescription_Toxic[] = _("מהלך שמרעיל\nקשות את היריב.\nנזק הרעל שלו\nמחמיר בכל תור.");
const u8 gMoveDescription_Confusion[] = _("התקפה טלקינטית\nחלשה שעלולה\nגם להשאיר את היריב\nמבולבל.");
const u8 gMoveDescription_Psychic[] = _("התקפה טלקינטית\nחזקה. עלולה גם\nלהוריד את ההגנה\nהמיוחדת של היריב.");
const u8 gMoveDescription_Hypnosis[] = _("הצעה היפנוטית\nמשמשת לגרום ליריב\nליפול לשינה\nעמוקה.");
const u8 gMoveDescription_Meditate[] = _("המשתמש מתבונן\nכדי להעיר את כוחו\nולהעלות את\nנתון ההתקפה שלו.");
const u8 gMoveDescription_Agility[] = _("המשתמש נרגע\nומקל על גופו\nכדי להעלות בחדות\nאת המהירות שלו.");
const u8 gMoveDescription_QuickAttack[] = _("התקפה כמעט\nבלתי נראית מהירה\nשבטוח תפגע\nראשונה.");
const u8 gMoveDescription_Rage[] = _("התקפה שנהיית\nחזקה יותר\nבכל פעם שהמשתמש\nמוכה בקרב.");
const u8 gMoveDescription_Teleport[] = _("השתמש בו לברוח\nמכל פוקימון בר.\nגם מעביר למרכז\nהפוקימונים האחרון.");
const u8 gMoveDescription_NightShade[] = _("התקפה עם\nתעתוע שגורמת\nנזק התואם\nאת רמת המשתמש.");
const u8 gMoveDescription_Mimic[] = _("המשתמש מעתיק את\nהמהלך האחרון\nשהיריב השתמש בו\nלשארית הקרב.");
const u8 gMoveDescription_Screech[] = _("צווחה קורעת\nאוזניים נפלטת כדי\nלהפחית בחדות את\nההגנה של היריב.");
const u8 gMoveDescription_DoubleTeam[] = _("המשתמש יוצר\nעותקים אשלייתיים\nשל עצמו כדי להעלות\nאת ההתחמקות שלו.");
const u8 gMoveDescription_Recover[] = _("מהלך ריפוי שמשחזר\nעד חצי מנקודות\nהחיים המלאות של\nהמשתמש.");
const u8 gMoveDescription_Harden[] = _("המשתמש מקשיח את\nכל השרירים בגופו\nכדי להעלות את נתון\nההגנה שלו.");
const u8 gMoveDescription_Minimize[] = _("המשתמש דוחס\nאת כל התאים בגופו\nכדי להעלות את\nההתחמקות שלו.");
const u8 gMoveDescription_Smokescreen[] = _("ענן מעורפל של\nעשן או דיו\nמפחית את\nהדיוק של היריב.");
const u8 gMoveDescription_ConfuseRay[] = _("היריב נחשף\nלקרן מרושעת\nשמעוררת\nבלבול.");
const u8 gMoveDescription_Withdraw[] = _("המשתמש מושך את\nגופו לתוך השריון\nהקשה, מעלה את\nנתון ההגנה שלו.");
const u8 gMoveDescription_DefenseCurl[] = _("המשתמש מתכרבל\nכדי להסתיר נקודות\nחולשה ולהעלות את\nנתון ההגנה שלו.");
const u8 gMoveDescription_Barrier[] = _("המשתמש יוצר\nקיר חזק שמעלה\nבחדות את נתון\nההגנה שלו.");
const u8 gMoveDescription_LightScreen[] = _("קיר של אור\nמפחית נזק מהתקפות\nהתקפה מיוחדת\nלחמישה תורים.");
const u8 gMoveDescription_Haze[] = _("מבטל את כל\nשינויי הנתונים\nבין כל הפוקימונים\nהמשתתפים בקרב.");
const u8 gMoveDescription_Reflect[] = _("קיר של אור\nמפחית נזק\nמהתקפות פיזיות\nלחמישה תורים.");
const u8 gMoveDescription_FocusEnergy[] = _("המשתמש לוקח נשימה\nעמוקה ומתרכז כדי\nלהעלות את יחס\nהמכה הקריטית שלו.");
const u8 gMoveDescription_Bide[] = _("המשתמש סופג\nהתקפות למשך שני\nתורים, ואז מכה\nבחזרה פי שניים.");
const u8 gMoveDescription_Metronome[] = _("מנענע אצבע\nומגרה את המוח\nלהשתמש בכל\nמהלך באקראי.");
const u8 gMoveDescription_MirrorMove[] = _("המשתמש מגיב למהלך\nהאחרון שהיריב\nהשתמש בו עם אותו\nמהלך.");
const u8 gMoveDescription_SelfDestruct[] = _("המשתמש מתפוצץ כדי\nלגרום נזק חמור,\nאפילו גורם לעצמו\nלהתעלף.");
const u8 gMoveDescription_EggBomb[] = _("ביצה גדולה\nנזרקת בכוח רב\nעל היריב כדי\nלגרום נזק.");
const u8 gMoveDescription_Lick[] = _("היריב נלקק ומוכה\nעם לשון ארוכה. זה\nעלול גם לשתק.");
const u8 gMoveDescription_Smog[] = _("היריב מותקף\nעם גזי פליטה.\nזה עלול גם להרעיל\nאת היריב.");
const u8 gMoveDescription_Sludge[] = _("בוץ רעיל\nנזרק על היריב.\nזה עלול להרעיל את\nהמטרה.");
const u8 gMoveDescription_BoneClub[] = _("היריב מוכה\nעם עצם המוחזקת\nביד. זה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_FireBlast[] = _("היריב מוכה עם\nלהבה עזה.\nזה עלול להשאיר את\nהמטרה עם כוויה.");
const u8 gMoveDescription_Waterfall[] = _("התקפת הסתערות\nחזקה. ניתן גם\nלהשתמש בה לטפס\nעל מפל.");
const u8 gMoveDescription_Clamp[] = _("היריב נתפס ונלחץ\nעל ידי הקונכייה של\nהמשתמש לשניים עד\nחמישה תורים.");
const u8 gMoveDescription_Swift[] = _("קרניים בצורת כוכב\nשלעולם לא מחטיאות\nנורות על כל\nהיריבים בקרב.");
const u8 gMoveDescription_SkullBash[] = _("המשתמש מעלה את\nההגנה שלו בתור\nה-1, ואז תוקף בתור\nה-2.");
const u8 gMoveDescription_SpikeCannon[] = _("קוצים חדים nנורים\nעל היריב כדי לפגוע\nפעמיים עד חמש\nפעמים.");
const u8 gMoveDescription_Constrict[] = _("היריב מותקף עם\nזרועות או גפנים\nארוכות. זה עלול\nלהוריד מהירות.");
const u8 gMoveDescription_Amnesia[] = _("שוכח על\nמשהו ומעלה\nבחדות את ההגנה\nהמיוחדת.");
const u8 gMoveDescription_Kinesis[] = _("המשתמש מסיח את\nדעת היריב על ידי\nכיפוף כף. זה עלול\nלהוריד דיוק.");
const u8 gMoveDescription_SoftBoiled[] = _("מרפא את המשתמש\nעד חצי מנקודות\nהחיים המלאות שלו.\nניתן לרפא בן ברית.");
const u8 gMoveDescription_HiJumpKick[] = _("בעיטת ברך קופצת\nחזקה. אם היא\nמחטיאה, המשתמש\nנפגע.");
const u8 gMoveDescription_Glare[] = _("המשתמש מפחיד\nאת היריב עם\nהעיצוב על בטנו\nכדי לגרום לשיתוק.");
const u8 gMoveDescription_DreamEater[] = _("סופג חצי מהנזק\nשהוא גרם ליריב\nישן כדי לשחזר\nנקודות חיים.");
const u8 gMoveDescription_PoisonGas[] = _("היריב מרוסס\nבענן של גז רעיל\nשעלול להרעיל\nאת היריב.");
const u8 gMoveDescription_Barrage[] = _("חפצים עגולים\nנזרקים על היריב\nכדי לפגוע פעמיים\nעד חמש פעמים.");
const u8 gMoveDescription_LeechLife[] = _("התקפה שסופגת\nחצי מהנזק שהיא\nגרמה כדי לשחזר\nנקודות חיים.");
const u8 gMoveDescription_LovelyKiss[] = _("המשתמש כופה\nנשיקה על היריב\nעם פנים מפחידות\nשגורמות לשינה.");
const u8 gMoveDescription_SkyAttack[] = _("מהלך התקפה בתור\nה-2 עם יחס פגיעה\nקריטית גבוה. היריב\nעלול להירתע.");
const u8 gMoveDescription_Transform[] = _("המשתמש הופך\nלהעתק של היריב\nעם אפילו אותה\nערכת מהלכים.");
const u8 gMoveDescription_Bubble[] = _("התזה של בועות\nפוגעת ביריב.\nזה עלול להוריד את\nנתון המהירות שלו.");
const u8 gMoveDescription_DizzyPunch[] = _("היריב מוכה\nעם אגרוף קצבי\nשעלול להשאיר\nאותו מבולבל.");
const u8 gMoveDescription_Spore[] = _("המשתמש מפזר\nפרצי נבגים עדינים\nשגורמים\nלשינה.");
const u8 gMoveDescription_Flash[] = _("פרץ של אור\nשמוריד את הדיוק\nשל היריב. זה גם\nמאיר מערות.");
const u8 gMoveDescription_Psywave[] = _("היריב מותקף\nעם גל אנרגיה חם\nמוזר שמשתנה\nבעוצמתו.");
const u8 gMoveDescription_Splash[] = _("המשתמש פשוט\nמתפלש ומתיז\nמסביב בלי שום\nהשפעה.");
const u8 gMoveDescription_AcidArmor[] = _("המשתמש נהפך לנוזל\nומעלה בחדות את\nההגנה שלו.");
const u8 gMoveDescription_Crabhammer[] = _("צבת גדולה\nמשמשת להכות את\nהיריב. יש לה יחס\nפגיעה קריטית גבוה.");
const u8 gMoveDescription_Explosion[] = _("המשתמש מתפוצץ\nכדי לגרום נזק נורא\nאפילו תוך כדי\nהתעלפות עצמית.");
const u8 gMoveDescription_FurySwipes[] = _("היריב נגרף\nעם טפרים או\nחרמשים חדים פעמיים\nעד חמש פעמים.");
const u8 gMoveDescription_Bonemerang[] = _("המשתמש זורק\nעצם שפוגעת ביריב\nפעם אחת, ואז שוב\nבחזרה.");
const u8 gMoveDescription_Rest[] = _("המשתמש ישן 2\nתורים, משחזר נק'\nחיים במלואן\nומתרפא.");
const u8 gMoveDescription_RockSlide[] = _("סלעים גדולים\nנזרקים על היריב.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_HyperFang[] = _("היריב מותקף\nעם ניבים חדים.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_Sharpen[] = _("המשתמש מפחית את\nספירת הפוליגונים\nשלו כדי לחדד קצוות\nולהעלות התקפה.");
const u8 gMoveDescription_Conversion[] = _("המשתמש משנה\nאת הסוג שלו כדי\nלהתאים לסוג של\nאחד ממהלכיו.");
const u8 gMoveDescription_TriAttack[] = _("התקפת 3 קרניים\nבו-זמנית שעלולה\nלשתק, לשרוף, או\nלהקפיא את היריב.");
const u8 gMoveDescription_SuperFang[] = _("המשתמש תוקף\nעם ניבים חדים\nומחצה את נקודות\nהחיים של היריב.");
const u8 gMoveDescription_Slash[] = _("היריב נחתך\nעם טפרים וכו'.\nיש לזה יחס\nפגיעה קריטית גבוה.");
const u8 gMoveDescription_Substitute[] = _("המשתמש יוצר\nפיתיון באמצעות\nרבע מנקודות החיים\nהמלאות שלו.");
const u8 gMoveDescription_Struggle[] = _("התקפה שמשתמשים\nבה רק אם אין\nנקודות כוח. זה גם\nפוגע במשתמש.");
const u8 gMoveDescription_Sketch[] = _("מהלך זה מעתיק\nאת המהלך האחרון\nשהיריב השתמש בו,\nואז נעלם.");
const u8 gMoveDescription_TripleKick[] = _("התקפת 3 בעיטות\nשנהיית חזקה יותר\nעם כל פגיעה\nמוצלחת.");
const u8 gMoveDescription_Thief[] = _("התקפה שעלולה\nלקחת את הפריט\nשהיריב מחזיק אם\nהמשתמש לא מחזיק.");
const u8 gMoveDescription_SpiderWeb[] = _("לוכד את היריב\nעם חוט דביק\nכך שהוא לא בורח\nאו מתחלף.");
const u8 gMoveDescription_MindReader[] = _("המשתמש חוזה את\nפעולת היריב כדי\nלהבטיח שההתקפה\nהבאה שלו תפגע.");
const u8 gMoveDescription_Nightmare[] = _("יריב ישן מוצג\nעם סיוט\nשגורם לנזק\nבכל תור.");
const u8 gMoveDescription_FlameWheel[] = _("המשתמש עושה\nהסתערות אש על\nהיריב. זה עלול\nלגרום לכוויה.");
const u8 gMoveDescription_Snore[] = _("התקפה שניתן\nלהשתמש בה רק\nבזמן שינה. עלולה\nלגרום להירתעות.");
const u8 gMoveDescription_Curse[] = _("מהלך שעובד\nבאופן שונה עבור\nסוג רוח וכל\nהסוגים האחרים.");
const u8 gMoveDescription_Flail[] = _("התקפה נואשת\nשנהיית חזקה יותר\nככל שיש פחות נק'\nחיים למשתמש.");
const u8 gMoveDescription_Conversion2[] = _("המשתמש משנה\nסוג כדי להפוך\nלעמיד להתקפה\nהאחרונה שספג.");
const u8 gMoveDescription_Aeroblast[] = _("מערבולת אוויר\nנורית על היריב.\nיש לה יחס\nפגיעה קריטית גבוה.");
const u8 gMoveDescription_CottonSpore[] = _("נבגים דמויי כותנה\nנדבקים ליריב,\nמורידים בחדות\nאת נתון המהירות.");
const u8 gMoveDescription_Reversal[] = _("התקפה מלאה שנהיית\nחזקה יותר ככל שיש\nפחות נקודות חיים\nלמשתמש.");
const u8 gMoveDescription_Spite[] = _("מהלך שחותך\n2 עד 5 נקודות כוח\nמהמהלך האחרון\nשהיריב השתמש בו.");
const u8 gMoveDescription_PowderSnow[] = _("מפוצץ את היריב\nעם משב שלג.\nזה עלול לגרום\nלקפיאה.");
const u8 gMoveDescription_Protect[] = _("מאפשר למשתמש\nלהתחמק מכל התקפה.\nעלול להיכשל אם\nמשתמשים ברצף.");
const u8 gMoveDescription_MachPunch[] = _("אגרוף שנזרק\nבמהירות מסנוורת.\nהוא בטוח\nלהכות ראשון.");
const u8 gMoveDescription_ScaryFace[] = _("מפחיד את היריב\nעם פנים מפחידות\nכדי להוריד בחדות\nאת המהירות.");
const u8 gMoveDescription_FaintAttack[] = _("המשתמש מתקרב\nליריב בצורה מפתה,\nואז מכה\nללא כישלון.");
const u8 gMoveDescription_SweetKiss[] = _("המשתמש מנשק\nאת היריב עם\nחמידות מתוקה\nשגורמת לבלבול.");
const u8 gMoveDescription_BellyDrum[] = _("המשתמש ממקסם את\nנתון ההתקפה במחיר\nשל חצי מנקודות\nהחיים המלאות.");
const u8 gMoveDescription_SludgeBomb[] = _("בוץ מלוכלך\nנזרק על היריב.\nזה עלול להרעיל\nאת המטרה.");
const u8 gMoveDescription_MudSlap[] = _("בוץ נזרק\nבפני היריב כדי\nלגרום נזק ולהוריד\nאת הדיוק שלו.");
const u8 gMoveDescription_Octazooka[] = _("דיו נורה\nבפני או בעיני\nהיריב כדי לפגוע\nולהוריד דיוק.");
const u8 gMoveDescription_Spikes[] = _("מלכודת קוצים\nמונחת סביב קבוצת\nהיריב כדי לפגוע\nביריבים שמתחלפים.");
const u8 gMoveDescription_ZapCannon[] = _("פרץ חשמלי\nנורה כמו תותח\nכדי לגרום נזק\nולשתק.");
const u8 gMoveDescription_Foresight[] = _("מבטל לחלוטין\nאת מאמצי היריב\nלהגביר את יכולתו\nלהתחמק.");
const u8 gMoveDescription_DestinyBond[] = _("אם המשתמש מתעלף,\nהיריב שמספק\nאת המכה הסופית\nגם מתעלף.");
const u8 gMoveDescription_PerishSong[] = _("כל לוחם ששומע\nזאת מתעלף\nתוך שלושה תורות\nאלא אם הוא מתחלף.");
const u8 gMoveDescription_IcyWind[] = _("רוח מקפיאה\nמשמשת להתקפה.\nהיא גם מורידה\nאת נתון המהירות.");
const u8 gMoveDescription_Detect[] = _("מאפשר למשתמש\nלהתחמק מכל התקפה.\nעלול להיכשל אם\nמשתמשים ברצף.");
const u8 gMoveDescription_BoneRush[] = _("המשתמש מכה\nאת היריב עם עצם\nביד פעמיים עד\nחמש פעמים.");
const u8 gMoveDescription_LockOn[] = _("המשתמש ננעל\nעל היריב, מה שהופך\nאת המהלך הבא\nלבטוח לפגוע.");
const u8 gMoveDescription_Outrage[] = _("המשתמש משתולל\nלמשך שניים עד\nשלושה תורות, ואז\nנהיה מבולבל.");
const u8 gMoveDescription_Sandstorm[] = _("סופת חול ל-5 תורות\nשפוגעת בכל\nהסוגים חוץ מסלע,\nאדמה, ופלדה.");
const u8 gMoveDescription_GigaDrain[] = _("התקפה קשה שסופגת\nחצי מהנזק שהיא\nגרמה כדי לשחזר\nנקודות חיים.");
const u8 gMoveDescription_Endure[] = _("המשתמש שורד כל\nפגיעה עם נק' חיים\nאחת. עלול להיכשל\nברצף.");
const u8 gMoveDescription_Charm[] = _("היריב מוקסם מהחן\nהחמוד של המשתמש,\nחותך בחדות את\nההתקפה שלו.");
const u8 gMoveDescription_Rollout[] = _("התקפת התגלגלות\nל-5 תורות שנהיית\nחזקה יותר עם\nכל פגיעה.");
const u8 gMoveDescription_FalseSwipe[] = _("התקפה מרוסנת\nשתמיד משאירה את\nהיריב עם לפחות\nנקודת חיים אחת.");
const u8 gMoveDescription_Swagger[] = _("מהלך שגורם\nליריב להתבלבל,\nאבל גם מעלה בחדות\nאת ההתקפה שלו.");
const u8 gMoveDescription_MilkDrink[] = _("מרפא את המשתמש\nעד חצי מנקודות\nהחיים המלאות. ניתן\nלרפא בן ברית.");
const u8 gMoveDescription_Spark[] = _("התקפת התחשמלות\nחשמלית שעלולה\nגם לשתק\nאת היריב.");
const u8 gMoveDescription_FuryCutter[] = _("התקפה שנהיית\nחזקה יותר\nעם כל פגיעה\nעוקבת.");
const u8 gMoveDescription_SteelWing[] = _("היריב מוכה עם כנפי\nפלדה. עשוי להעלות\nאת ההגנה של\nהמשתמש.");
const u8 gMoveDescription_MeanLook[] = _("היריב מקובע\nעם מבט מרושע\nשמונע ממנו\nלברוח.");
const u8 gMoveDescription_Attract[] = _("אם היריב מהמגדר\nהנגדי, הוא נעשה\nמאוהב ופחות נוטה\nלתקוף.");
const u8 gMoveDescription_SleepTalk[] = _("בזמן שינה, המשתמש\nמשתמש באקראי באחד\nמהמהלכים שהוא\nמכיר.");
const u8 gMoveDescription_HealBell[] = _("פעמון מרגיע\nמצלצל כדי לרפא\nאת בעיות הסטטוס\nשל כל בני הברית.");
const u8 gMoveDescription_Return[] = _("מהלך התקפה זה\nנהיה חזק יותר ככל\nשהמשתמש אוהב את\nהמאמן שלו.");
const u8 gMoveDescription_Present[] = _("היריב מקבל מתנה\nממולכדת. לפעמים\nהיא משחזרת נקודות\nחיים, עם זאת.");
const u8 gMoveDescription_Frustration[] = _("מהלך התקפה זה\nנהיה חזק יותר ככל\nשהמשתמש פחות אוהב\nאת המאמן.");
const u8 gMoveDescription_Safeguard[] = _("הוא מגן על\nקבוצת המשתמש מפני\nכל בעיות הסטטוס\nלמשך חמישה תורות.");
const u8 gMoveDescription_PainSplit[] = _("המשתמש מאחד את\nנק' החיים שלו עם\nאלו של היריב ומחלק\nשווה בשווה.");
const u8 gMoveDescription_SacredFire[] = _("התקפת אש\nמיסטית וחזקה\nשעלולה\nלגרום לכוויה.");
const u8 gMoveDescription_Magnitude[] = _("רעידה שפוגעת בכל\nהפוקימונים בקרב.\nהעוצמה משתנה.");
const u8 gMoveDescription_DynamicPunch[] = _("היריב מוכה במלוא\nהכוח של המשתמש.\nזה מבלבל את היריב\nאם זה פוגע.");
const u8 gMoveDescription_Megahorn[] = _("התקפת נגיחה\nאכזרית המועברת\nעם קרן קשה\nומרשימה.");
const u8 gMoveDescription_DragonBreath[] = _("היריב מוכה עם\nפרץ מדהים של\nנשימה שעלול\nגם לשתק.");
const u8 gMoveDescription_BatonPass[] = _("המשתמש מתחלף,\nמעביר כל שינוי\nסטטיסטי\nללוחם החדש.");
const u8 gMoveDescription_Encore[] = _("גורם ליריב לחזור\nעל המהלך האחרון\nשלו, 2 עד 6 תורות.");
const u8 gMoveDescription_Pursuit[] = _("מהלך התקפה שעובד\nטוב במיוחד\nעל יריב\nשמתחלף החוצה.");
const u8 gMoveDescription_RapidSpin[] = _("התקפה שמשחררת\nאת המשתמש מכבילה,\nכריכה, זרע יניקה,\nוקוצים.");
const u8 gMoveDescription_SweetScent[] = _("מפתה את היריב\nלהפחית התחמקות.\nזה גם מושך\nפוקימונים פראיים.");
const u8 gMoveDescription_IronTail[] = _("התקפה עם זנב קשה\nכפלדה. זה עלול\nלהוריד את נתון\nההגנה של היריב.");
const u8 gMoveDescription_MetalClaw[] = _("היריב מותקף עם\nטפרי פלדה. זה עשוי\nגם להעלות את\nההתקפה של המשתמש.");
const u8 gMoveDescription_VitalThrow[] = _("גורם למשתמש\nלתקוף אחרי\nהיריב. בתמורה,\nזה לא יחטיא.");
const u8 gMoveDescription_MorningSun[] = _("משחזר נקודות חיים\nלמשתמש. הכמות\nתלויה במזג האוויר.");
const u8 gMoveDescription_Synthesis[] = _("משחזר נקודות חיים\nלמשתמש. הכמות\nתלויה במזג האוויר.");
const u8 gMoveDescription_Moonlight[] = _("משחזר נקודות חיים\nלמשתמש. הכמות\nתלויה במזג האוויר.");
const u8 gMoveDescription_HiddenPower[] = _("התקפה שמשתנה\nבסוג ובעוצמה\nבהתאם\nלמשתמש.");
const u8 gMoveDescription_CrossChop[] = _("היריב מוכה\nעם קיצוצים כפולים.\nיש לזה יחס\nפגיעה קריטית גבוה.");
const u8 gMoveDescription_Twister[] = _("סופה אכזרית\nתוקפת את היריב.\nזה עלול לגרום\nליריב להירתע.");
const u8 gMoveDescription_RainDance[] = _("גשם כבד יורד\nלמשך חמישה תורות,\nמחזק מהלכים\nמסוג מים.");
const u8 gMoveDescription_SunnyDay[] = _("השמש בוערת למשך\nחמישה תורות, מחזקת\nמהלכים\nמסוג אש.");
const u8 gMoveDescription_Crunch[] = _("היריב נכרס עם\nניבים חדים. זה\nעלול להוריד את\nהגנת-על של היריב.");
const u8 gMoveDescription_MirrorCoat[] = _("מהלך תגמול שמחזיר\nאת התקפת-העל של\nהיריב כפול.");
const u8 gMoveDescription_PsychUp[] = _("המשתמש מעתיק כל\nשינוי נתונים שחל\nעל היריב.");
const u8 gMoveDescription_ExtremeSpeed[] = _("התקפת הסתערות\nמהירה באופן מסנוור\nשתמיד מגיעה לפני\nכל התקפה אחרת.");
const u8 gMoveDescription_AncientPower[] = _("התקפה בכוח עתיק.\nעשויה להעלות את\nכל נתוני המשתמש.");
const u8 gMoveDescription_ShadowBall[] = _("כדור צללים נזרק על\nהיריב. עלול גם\nלהוריד את\nהגנת-העל של היריב.");
const u8 gMoveDescription_FutureSight[] = _("שני תורות אחרי\nשמשתמשים במהלך\nזה, היריב מותקף\nבאופן פסיכי.");
const u8 gMoveDescription_RockSmash[] = _("התקפה שעלולה\nגם לחתוך הגנה.\nהיא יכולה גם לנפץ\nסלעים סדוקים.");
const u8 gMoveDescription_Whirlpool[] = _("היריב לכוד\nבמערבולת מהירה\nואכזרית למשך שניים\nעד חמישה תורות.");
const u8 gMoveDescription_BeatUp[] = _("כל הפוקימונים\nבקבוצה תוקפים.\nיותר חברים, יותר\nנזק.");
const u8 gMoveDescription_FakeOut[] = _("התקפה שפוגעת\nראשונה וגורמת\nלהירתעות. רק בתור\nהראשון.");
const u8 gMoveDescription_Uproar[] = _("המשתמש תוקף\nבמהומה שמונעת\nשינה למשך שניים עד\nחמישה תורות.");
const u8 gMoveDescription_Stockpile[] = _("המשתמש טוען כוח\nלשימוש מאוחר יותר.\nניתן להשתמש בזה\nשלוש פעמים.");
const u8 gMoveDescription_SpitUp[] = _("הכוח שנבנה\nבאמצעות אגירה\nמשוחרר בבת אחת\nלהתקפה.");
const u8 gMoveDescription_Swallow[] = _("האנרגיה שנבנתה\nבאמצעות אגירה\nנספגת כדי לשחזר\nנקודות חיים.");
const u8 gMoveDescription_HeatWave[] = _("המשתמש נושף נשימה\nמחוממת להתקפה. זה\nעלול גם לגרום\nלכוויה.");
const u8 gMoveDescription_Hail[] = _("סופת ברד הנמשכת\nחמישה תורות פוגעת\nבכל הפוקימונים חוץ\nמסוג קרח.");
const u8 gMoveDescription_Torment[] = _("מרגיז את היריב\nומונע ממנו לחזור\nעל אותו מהלך.");
const u8 gMoveDescription_Flatter[] = _("חנופה משמשת\nלבלבל את היריב,\nאבל התקפת-העל שלו\nגם עולה.");
const u8 gMoveDescription_WillOWisp[] = _("להבה כחולה-לבנה\nמרושעת נורית\nעל היריב כדי\nלגרום לכוויה.");
const u8 gMoveDescription_Memento[] = _("המשתמש מתעלף, אבל\nמוריד בחדות את\nההתקפה והתקפת-העל\nשל היריב.");
const u8 gMoveDescription_Facade[] = _("התקפה שמתחזקת\nאם המשתמש שרוף,\nמורעל,\nאו משותק.");
const u8 gMoveDescription_FocusPunch[] = _("התקפה שמבוצעת\nאחרונה. המשתמש\nנרתע אם הוא נפגע\nלפני כן.");
const u8 gMoveDescription_SmellingSalt[] = _("יעיל פי שניים\nעל יריב משותק,\nאבל זה גם מרפא\nאת שיתוק היריב.");
const u8 gMoveDescription_FollowMe[] = _("המשתמש מושך\nתשומת לב לעצמו,\nגורם ליריבים לתקוף\nרק את המשתמש.");
const u8 gMoveDescription_NaturePower[] = _("התקפה שמשנה\nסוג\nבהתאם למיקום\nשל המשתמש.");
const u8 gMoveDescription_Charge[] = _("המשתמש טוען כוח\nכדי להגביר את מהלך\nהחשמל שהוא משתמש\nבו הבא.");
const u8 gMoveDescription_Taunt[] = _("היריב מתגרה\nלכדי זעם שמאפשר\nלו להשתמש\nרק במהלכי התקפה.");
const u8 gMoveDescription_HelpingHand[] = _("מהלך שמגביר\nאת כוח ההתקפה\nשל בן הברית\nבקרב.");
const u8 gMoveDescription_Trick[] = _("מהלך שמרמה\nאת היריב להחליף\nפריטים מוחזקים\nעם המשתמש.");
const u8 gMoveDescription_RolePlay[] = _("המשתמש מחקה\nאת היריב לחלוטין\nומעתיק את\nהיכולת של היריב.");
const u8 gMoveDescription_Wish[] = _("מהלך ריפוי עצמי\nשמשחזר חצי\nמנקודות החיים\nהמלאות בתור הבא.");
const u8 gMoveDescription_Assist[] = _("המשתמש בוחר\nבאקראי ומשתמש\nבמהלך של פוקימון\nבן ברית.");
const u8 gMoveDescription_Ingrain[] = _("שורשים משחזרים נק'\nחיים בכל תור. אי\nאפשר להתחלף.");
const u8 gMoveDescription_Superpower[] = _("התקפה חזקה,\nאבל היא גם מורידה\nאת נתוני ההתקפה\nוההגנה של המשתמש.");
const u8 gMoveDescription_MagicCoat[] = _("מחזיר את זרע\nהיניקה של היריב וכל\nמהלך שגורם נזק\nסטטוס.");
const u8 gMoveDescription_Recycle[] = _("מהלך שממחזר\nפריט משומש\nלשימוש\nפעם נוספת.");
const u8 gMoveDescription_Revenge[] = _("מהלך התקפה שצובר\nעוצמה אם\nהמטרה פגעה\nבמשתמש.");
const u8 gMoveDescription_BrickBreak[] = _("התקפה שגם\nשוברת כל מחסום\nכמו מסך אור\nוהחזרה.");
const u8 gMoveDescription_Yawn[] = _("פיהוק ענק מרדים\nאת היריב לשינה\nבתור\nהבא.");
const u8 gMoveDescription_KnockOff[] = _("מפיל את הפריט\nשהיריב מחזיק כדי\nלמנוע את השימוש בו\nבמהלך הקרב.");
const u8 gMoveDescription_Endeavor[] = _("צובר כוח ככל\nשלמשתמש יש פחות\nנקודות חיים\nבהשוואה ליריב.");
const u8 gMoveDescription_Eruption[] = _("ככל שנקודות החיים\nשל המשתמש גבוהות\nיותר, כך התקפה זו\nחזקה יותר.");
const u8 gMoveDescription_SkillSwap[] = _("המשתמש מפעיל\nאת כוחו הפסיכי\nכדי להחליף יכולות\nעם היריב.");
const u8 gMoveDescription_Imprison[] = _("מונע מהיריבים\nלהשתמש בכל מהלך\nשגם המשתמש\nמכיר.");
const u8 gMoveDescription_Refresh[] = _("מהלך ריפוי עצמי\nשמרפא את המשתמש\nמהרעלה, כוויה,\nאו שיתוק.");
const u8 gMoveDescription_Grudge[] = _("אם המשתמש מתעלף,\nמהלך זה מוחק את\nנקודות הכוח של\nהמהלך שסיים אותו.");
const u8 gMoveDescription_Snatch[] = _("גונב את ההשפעות\nשל מהלך הריפוי\nאו שינוי הסטטוס\nשל היריב.");
const u8 gMoveDescription_SecretPower[] = _("התקפה שעשויה\nלהיות לה השפעה\nנוספת שמשתנה\nעם השטח.");
const u8 gMoveDescription_Dive[] = _("המשתמש צולל\nמתחת למים בתור\nהראשון ותוקף\nבתור הבא.");
const u8 gMoveDescription_ArmThrust[] = _("סדרה מהירה של\nאגרופים ישרים\nשפוגעים פעמיים\nעד חמש פעמים.");
const u8 gMoveDescription_Camouflage[] = _("משנה את סוג\nהמשתמש בהתאם\nלשטח\nשל המיקום.");
const u8 gMoveDescription_TailGlow[] = _("המשתמש מהבהב\nאור שמעלה בחדות\nאת נתון\nהתקפת-העל שלו.");
const u8 gMoveDescription_LusterPurge[] = _("פרץ של אור\nפוגע ביריב. זה\nעשוי גם להוריד את\nהגנת-העל של היריב.");
const u8 gMoveDescription_MistBall[] = _("מטח נוצות פוגע\nביריב. עשוי להוריד\nאת התקפת-העל שלו.");
const u8 gMoveDescription_FeatherDance[] = _("היריב מכוסה\nבהמון נוצות\nשחותכות בחדות\nאת נתון ההתקפה.");
const u8 gMoveDescription_TeeterDance[] = _("ריקוד מתנדנד\nשמבלבל את כל\nהפוקימונים\nבקרב.");
const u8 gMoveDescription_BlazeKick[] = _("בעיטה לוהטת עם\nיחס פגיעה קריטית\nגבוה. זה עשוי גם\nלשרוף את היריב.");
const u8 gMoveDescription_MudSport[] = _("מחליש התקפות\nמסוג חשמל\nבזמן שהמשתמש\nנמצא בקרב.");
const u8 gMoveDescription_IceBall[] = _("התקפת גלגול\nשנמשכת 5 תורות\nומתחזקת בכל פעם\nשהיא מתגלגלת.");
const u8 gMoveDescription_NeedleArm[] = _("התקפה באמצעות\nזרועות קוצניות.\nזה עשוי לגרום\nליריב להירתע.");
const u8 gMoveDescription_SlackOff[] = _("המשתמש מתרשל\nומשחזר מחצית\nמנקודות החיים שלו.");
const u8 gMoveDescription_HyperVoice[] = _("המשתמש משחרר\nצעקה נוראית\nעם הכוח\nלגרום נזק.");
const u8 gMoveDescription_PoisonFang[] = _("היריב ננשך\nעם ניבים רעילים.\nזה עשוי גם להרעיל\nקשות את היריב.");
const u8 gMoveDescription_CrushClaw[] = _("היריב מותקף\nעם טפרים חדים.\nזה עשוי גם להוריד\nאת ההגנה של היריב.");
const u8 gMoveDescription_BlastBurn[] = _("היריב נפגע מפיצוץ\nענק. המשתמש לא\nיכול לזוז בתור\nהבא.");
const u8 gMoveDescription_HydroCannon[] = _("היריב נפגע מתותח\nמים. המשתמש לא\nיכול לזוז בתור\nהבא.");
const u8 gMoveDescription_MeteorMash[] = _("היריב נפגע מאגרוף\nחזק ומהיר. זה עשוי\nגם להעלות את\nההתקפה של המשתמש.");
const u8 gMoveDescription_Astonish[] = _("התקפה באמצעות\nצעקה מפתיעה.\nזה עשוי גם לגרום\nליריב להירתע.");
const u8 gMoveDescription_WeatherBall[] = _("התקפה שמשתנה\nבעוצמה ובסוג\nבהתאם\nלמזג האוויר.");
const u8 gMoveDescription_Aromatherapy[] = _("ריח מרגיע משתחרר\nכדי לרפא את כל\nבעיות הסטטוס\nבקבוצת המשתמש.");
const u8 gMoveDescription_FakeTears[] = _("המשתמש בוכה\nומוריד בחדות את\nהגנת-העל של היריב.");
const u8 gMoveDescription_AirCutter[] = _("היריב נפגע\nמרוח חדה כתער.\nיש לה יחס\nפגיעה קריטית גבוה.");
const u8 gMoveDescription_Overheat[] = _("התקפה עזה\nשגם מפחיתה בחדות\nאת נתון התקפת-העל\nשל המשתמש.");
const u8 gMoveDescription_OdorSleuth[] = _("מבטל לחלוטין\nאת מאמצי היריב\nלהגביר את יכולתו\nלהתחמק.");
const u8 gMoveDescription_RockTomb[] = _("סלעים נזרקים על\nהיריב. זה גם מוריד\nאת המהירות של\nהיריב אם זה פוגע.");
const u8 gMoveDescription_SilverWind[] = _("אבק כסף פוגע\nביריב. עשוי להעלות\nאת כל נתוני\nהמשתמש.");
const u8 gMoveDescription_MetalSound[] = _("צריחה מתכתית\nנוראית משמשת\nלהוריד בחדות את\nהגנת-העל של היריב.");
const u8 gMoveDescription_GrassWhistle[] = _("מנגינה נעימה\nמנוגנת כדי להרדים\nאת היריב לשינה\nעמוקה.");
const u8 gMoveDescription_Tickle[] = _("היריב מצחקק,\nמה שמוריד את\nנתוני ההתקפה\nוההגנה שלו.");
const u8 gMoveDescription_CosmicPower[] = _("המשתמש סופג\nכוח מיסטי כדי\nלהעלות את ההגנה\nוהגנת-העל שלו.");
const u8 gMoveDescription_WaterSpout[] = _("ככל שנקודות החיים\nשל המשתמש גבוהות\nיותר, כך התקפה זו\nחזקה יותר.");
const u8 gMoveDescription_SignalBeam[] = _("היריב נפגע\nמקרן מהבהבת\nשעשויה גם\nלגרום לבלבול.");
const u8 gMoveDescription_ShadowPunch[] = _("המשתמש מטיח\nאגרוף מהצללים.\nאי אפשר\nלהתחמק ממנו.");
const u8 gMoveDescription_Extrasensory[] = _("המשתמש תוקף\nעם כוח מוזר\nשעשוי לגרום\nליריב להירתע.");
const u8 gMoveDescription_SkyUppercut[] = _("המשתמש תוקף\nעם אפרקאט\nשנזרק לשמיים\nבכוח רב.");
const u8 gMoveDescription_SandTomb[] = _("היריב נלכד\nבתוך סופת חול\nכואבת למשך שני\nעד חמישה תורות.");
const u8 gMoveDescription_SheerCold[] = _("היריב מותקף\nבקור קיצוני\nשגורם להתעלפות\nאם הוא פוגע.");
const u8 gMoveDescription_MuddyWater[] = _("המשתמש תוקף\nעם מים בוציים.\nזה עשוי גם להוריד\nאת דיוק היריב.");
const u8 gMoveDescription_BulletSeed[] = _("המשתמש יורה זרעים\nעל היריב. שניים עד\nחמישה זרעים נורים\nבבת אחת.");
const u8 gMoveDescription_AerialAce[] = _("התקפה מהירה\nבמיוחד נגד מטרה\nאחת. אי אפשר\nלהתחמק ממנה.");
const u8 gMoveDescription_IcicleSpear[] = _("נטיפי קרח חדים\nנורים על היריב.\nהם פוגעים שתיים\nעד חמש פעמים.");
const u8 gMoveDescription_IronDefense[] = _("המשתמש מקשיח\nאת פני גופו\nכדי להעלות בחדות\nאת נתון ההגנה שלו.");
const u8 gMoveDescription_Block[] = _("המשתמש חוסם\nאת דרכו של היריב\nעם זרועות פרושות\nכדי למנוע בריחה.");
const u8 gMoveDescription_Howl[] = _("המשתמש מיילל\nכדי להרים את רוחו\nולהגביר את נתון\nההתקפה שלו.");
const u8 gMoveDescription_DragonClaw[] = _("טפרים חדים וענקיים\nתופסים וחותכים את\nהיריב במהירות\nובעוצמה רבה.");
const u8 gMoveDescription_FrenzyPlant[] = _("היריב נפגע מענף\nענק. המשתמש לא\nיכול לזוז בתור\nהבא.");
const u8 gMoveDescription_BulkUp[] = _("המשתמש מנפח\nאת גופו כדי להגביר\nאת נתוני ההתקפה\nוההגנה שלו.");
const u8 gMoveDescription_Bounce[] = _("המשתמש מקפץ\nעל היריב בתור\nהשני. זה עשוי\nלשתק את היריב.");
const u8 gMoveDescription_MudShot[] = _("המשתמש תוקף\nעל ידי זריקת בוץ.\nזה גם מפחית את\nמהירות היריב.");
const u8 gMoveDescription_PoisonTail[] = _("התקפה עם יחס\nפגיעה קריטית גבוה.\nהיא עשויה גם\nלהרעיל את היריב.");
const u8 gMoveDescription_Covet[] = _("התקפה מבוצעת\nבחמידות שגם\nגונבת את הפריט\nשהיריב מחזיק.");
const u8 gMoveDescription_VoltTackle[] = _("המשתמש מטיח\nהתנגשות חשמלית.\nזה פוגע במשתמש\nמעט.");
const u8 gMoveDescription_MagicalLeaf[] = _("היריב מותקף\nעם עלה מוזר\nשאי אפשר\nלהתחמק ממנו.");
const u8 gMoveDescription_WaterSport[] = _("מחליש התקפות\nמסוג אש\nבזמן שהמשתמש\nנמצא בקרב.");
const u8 gMoveDescription_CalmMind[] = _("המשתמש מתרכז\nומעלה את\nהתקפת-העל\nוהגנת-העל.");
const u8 gMoveDescription_LeafBlade[] = _("היריב נחתך\nעם עלה חד.\nיש לו יחס\nפגיעה קריטית גבוה.");
const u8 gMoveDescription_DragonDance[] = _("ריקוד מיסטי ועוצמתי\nשמגביר את נתוני\nההתקפה והמהירות\nשל המשתמש.");
const u8 gMoveDescription_RockBlast[] = _("המשתמש מטיח\nשתיים עד חמש\nאבנים קשות ביריב\nכדי לתקוף.");
const u8 gMoveDescription_ShockWave[] = _("זרם חשמל מהיר\nפוגע ביריב.\nאי אפשר\nלהתחמק ממנו.");
const u8 gMoveDescription_WaterPulse[] = _("התקפה עם\nפרץ מים פועם.\nהיא עשויה גם\nלבלבל את היריב.");
const u8 gMoveDescription_DoomDesire[] = _("מהלך שתוקף\nאת היריב עם\nפרץ אור שני\nתורות לאחר השימוש.");
const u8 gMoveDescription_PsychoBoost[] = _("התקפה עזה\nשגם מפחיתה בחדות\nאת נתון התקפת-העל\nשל המשתמש.");

const u8 *const gMoveDescriptionPointers[MOVES_COUNT - 1] = {
    [MOVE_POUND         - 1] = gMoveDescription_Pound,
    [MOVE_KARATE_CHOP   - 1] = gMoveDescription_KarateChop,
    [MOVE_DOUBLE_SLAP   - 1] = gMoveDescription_DoubleSlap,
    [MOVE_COMET_PUNCH   - 1] = gMoveDescription_CometPunch,
    [MOVE_MEGA_PUNCH    - 1] = gMoveDescription_MegaPunch,
    [MOVE_PAY_DAY       - 1] = gMoveDescription_PayDay,
    [MOVE_FIRE_PUNCH    - 1] = gMoveDescription_FirePunch,
    [MOVE_ICE_PUNCH     - 1] = gMoveDescription_IcePunch,
    [MOVE_THUNDER_PUNCH - 1] = gMoveDescription_ThunderPunch,
    [MOVE_SCRATCH       - 1] = gMoveDescription_Scratch,
    [MOVE_VICE_GRIP     - 1] = gMoveDescription_ViceGrip,
    [MOVE_GUILLOTINE    - 1] = gMoveDescription_Guillotine,
    [MOVE_RAZOR_WIND    - 1] = gMoveDescription_RazorWind,
    [MOVE_SWORDS_DANCE  - 1] = gMoveDescription_SwordsDance,
    [MOVE_CUT           - 1] = gMoveDescription_Cut,
    [MOVE_GUST          - 1] = gMoveDescription_Gust,
    [MOVE_WING_ATTACK   - 1] = gMoveDescription_WingAttack,
    [MOVE_WHIRLWIND     - 1] = gMoveDescription_Whirlwind,
    [MOVE_FLY           - 1] = gMoveDescription_Fly,
    [MOVE_BIND          - 1] = gMoveDescription_Bind,
    [MOVE_SLAM          - 1] = gMoveDescription_Slam,
    [MOVE_VINE_WHIP     - 1] = gMoveDescription_VineWhip,
    [MOVE_STOMP         - 1] = gMoveDescription_Stomp,
    [MOVE_DOUBLE_KICK   - 1] = gMoveDescription_DoubleKick,
    [MOVE_MEGA_KICK     - 1] = gMoveDescription_MegaKick,
    [MOVE_JUMP_KICK     - 1] = gMoveDescription_JumpKick,
    [MOVE_ROLLING_KICK  - 1] = gMoveDescription_RollingKick,
    [MOVE_SAND_ATTACK   - 1] = gMoveDescription_SandAttack,
    [MOVE_HEADBUTT      - 1] = gMoveDescription_Headbutt,
    [MOVE_HORN_ATTACK   - 1] = gMoveDescription_HornAttack,
    [MOVE_FURY_ATTACK   - 1] = gMoveDescription_FuryAttack,
    [MOVE_HORN_DRILL    - 1] = gMoveDescription_HornDrill,
    [MOVE_TACKLE        - 1] = gMoveDescription_Tackle,
    [MOVE_BODY_SLAM     - 1] = gMoveDescription_BodySlam,
    [MOVE_WRAP          - 1] = gMoveDescription_Wrap,
    [MOVE_TAKE_DOWN     - 1] = gMoveDescription_TakeDown,
    [MOVE_THRASH        - 1] = gMoveDescription_Thrash,
    [MOVE_DOUBLE_EDGE   - 1] = gMoveDescription_DoubleEdge,
    [MOVE_TAIL_WHIP     - 1] = gMoveDescription_TailWhip,
    [MOVE_POISON_STING  - 1] = gMoveDescription_PoisonSting,
    [MOVE_TWINEEDLE     - 1] = gMoveDescription_Twineedle,
    [MOVE_PIN_MISSILE   - 1] = gMoveDescription_PinMissile,
    [MOVE_LEER          - 1] = gMoveDescription_Leer,
    [MOVE_BITE          - 1] = gMoveDescription_Bite,
    [MOVE_GROWL         - 1] = gMoveDescription_Growl,
    [MOVE_ROAR          - 1] = gMoveDescription_Roar,
    [MOVE_SING          - 1] = gMoveDescription_Sing,
    [MOVE_SUPERSONIC    - 1] = gMoveDescription_Supersonic,
    [MOVE_SONIC_BOOM    - 1] = gMoveDescription_SonicBoom,
    [MOVE_DISABLE       - 1] = gMoveDescription_Disable,
    [MOVE_ACID          - 1] = gMoveDescription_Acid,
    [MOVE_EMBER         - 1] = gMoveDescription_Ember,
    [MOVE_FLAMETHROWER  - 1] = gMoveDescription_Flamethrower,
    [MOVE_MIST          - 1] = gMoveDescription_Mist,
    [MOVE_WATER_GUN     - 1] = gMoveDescription_WaterGun,
    [MOVE_HYDRO_PUMP    - 1] = gMoveDescription_HydroPump,
    [MOVE_SURF          - 1] = gMoveDescription_Surf,
    [MOVE_ICE_BEAM      - 1] = gMoveDescription_IceBeam,
    [MOVE_BLIZZARD      - 1] = gMoveDescription_Blizzard,
    [MOVE_PSYBEAM       - 1] = gMoveDescription_Psybeam,
    [MOVE_BUBBLE_BEAM   - 1] = gMoveDescription_BubbleBeam,
    [MOVE_AURORA_BEAM   - 1] = gMoveDescription_AuroraBeam,
    [MOVE_HYPER_BEAM    - 1] = gMoveDescription_HyperBeam,
    [MOVE_PECK          - 1] = gMoveDescription_Peck,
    [MOVE_DRILL_PECK    - 1] = gMoveDescription_DrillPeck,
    [MOVE_SUBMISSION    - 1] = gMoveDescription_Submission,
    [MOVE_LOW_KICK      - 1] = gMoveDescription_LowKick,
    [MOVE_COUNTER       - 1] = gMoveDescription_Counter,
    [MOVE_SEISMIC_TOSS  - 1] = gMoveDescription_SeismicToss,
    [MOVE_STRENGTH      - 1] = gMoveDescription_Strength,
    [MOVE_ABSORB        - 1] = gMoveDescription_Absorb,
    [MOVE_MEGA_DRAIN    - 1] = gMoveDescription_MegaDrain,
    [MOVE_LEECH_SEED    - 1] = gMoveDescription_LeechSeed,
    [MOVE_GROWTH        - 1] = gMoveDescription_Growth,
    [MOVE_RAZOR_LEAF    - 1] = gMoveDescription_RazorLeaf,
    [MOVE_SOLAR_BEAM    - 1] = gMoveDescription_SolarBeam,
    [MOVE_POISON_POWDER - 1] = gMoveDescription_PoisonPowder,
    [MOVE_STUN_SPORE    - 1] = gMoveDescription_StunSpore,
    [MOVE_SLEEP_POWDER  - 1] = gMoveDescription_SleepPowder,
    [MOVE_PETAL_DANCE   - 1] = gMoveDescription_PetalDance,
    [MOVE_STRING_SHOT   - 1] = gMoveDescription_StringShot,
    [MOVE_DRAGON_RAGE   - 1] = gMoveDescription_DragonRage,
    [MOVE_FIRE_SPIN     - 1] = gMoveDescription_FireSpin,
    [MOVE_THUNDER_SHOCK - 1] = gMoveDescription_ThunderShock,
    [MOVE_THUNDERBOLT   - 1] = gMoveDescription_Thunderbolt,
    [MOVE_THUNDER_WAVE  - 1] = gMoveDescription_ThunderWave,
    [MOVE_THUNDER       - 1] = gMoveDescription_Thunder,
    [MOVE_ROCK_THROW    - 1] = gMoveDescription_RockThrow,
    [MOVE_EARTHQUAKE    - 1] = gMoveDescription_Earthquake,
    [MOVE_FISSURE       - 1] = gMoveDescription_Fissure,
    [MOVE_DIG           - 1] = gMoveDescription_Dig,
    [MOVE_TOXIC         - 1] = gMoveDescription_Toxic,
    [MOVE_CONFUSION     - 1] = gMoveDescription_Confusion,
    [MOVE_PSYCHIC       - 1] = gMoveDescription_Psychic,
    [MOVE_HYPNOSIS      - 1] = gMoveDescription_Hypnosis,
    [MOVE_MEDITATE      - 1] = gMoveDescription_Meditate,
    [MOVE_AGILITY       - 1] = gMoveDescription_Agility,
    [MOVE_QUICK_ATTACK  - 1] = gMoveDescription_QuickAttack,
    [MOVE_RAGE          - 1] = gMoveDescription_Rage,
    [MOVE_TELEPORT      - 1] = gMoveDescription_Teleport,
    [MOVE_NIGHT_SHADE   - 1] = gMoveDescription_NightShade,
    [MOVE_MIMIC         - 1] = gMoveDescription_Mimic,
    [MOVE_SCREECH       - 1] = gMoveDescription_Screech,
    [MOVE_DOUBLE_TEAM   - 1] = gMoveDescription_DoubleTeam,
    [MOVE_RECOVER       - 1] = gMoveDescription_Recover,
    [MOVE_HARDEN        - 1] = gMoveDescription_Harden,
    [MOVE_MINIMIZE      - 1] = gMoveDescription_Minimize,
    [MOVE_SMOKESCREEN   - 1] = gMoveDescription_Smokescreen,
    [MOVE_CONFUSE_RAY   - 1] = gMoveDescription_ConfuseRay,
    [MOVE_WITHDRAW      - 1] = gMoveDescription_Withdraw,
    [MOVE_DEFENSE_CURL  - 1] = gMoveDescription_DefenseCurl,
    [MOVE_BARRIER       - 1] = gMoveDescription_Barrier,
    [MOVE_LIGHT_SCREEN  - 1] = gMoveDescription_LightScreen,
    [MOVE_HAZE          - 1] = gMoveDescription_Haze,
    [MOVE_REFLECT       - 1] = gMoveDescription_Reflect,
    [MOVE_FOCUS_ENERGY  - 1] = gMoveDescription_FocusEnergy,
    [MOVE_BIDE          - 1] = gMoveDescription_Bide,
    [MOVE_METRONOME     - 1] = gMoveDescription_Metronome,
    [MOVE_MIRROR_MOVE   - 1] = gMoveDescription_MirrorMove,
    [MOVE_SELF_DESTRUCT - 1] = gMoveDescription_SelfDestruct,
    [MOVE_EGG_BOMB      - 1] = gMoveDescription_EggBomb,
    [MOVE_LICK          - 1] = gMoveDescription_Lick,
    [MOVE_SMOG          - 1] = gMoveDescription_Smog,
    [MOVE_SLUDGE        - 1] = gMoveDescription_Sludge,
    [MOVE_BONE_CLUB     - 1] = gMoveDescription_BoneClub,
    [MOVE_FIRE_BLAST    - 1] = gMoveDescription_FireBlast,
    [MOVE_WATERFALL     - 1] = gMoveDescription_Waterfall,
    [MOVE_CLAMP         - 1] = gMoveDescription_Clamp,
    [MOVE_SWIFT         - 1] = gMoveDescription_Swift,
    [MOVE_SKULL_BASH    - 1] = gMoveDescription_SkullBash,
    [MOVE_SPIKE_CANNON  - 1] = gMoveDescription_SpikeCannon,
    [MOVE_CONSTRICT     - 1] = gMoveDescription_Constrict,
    [MOVE_AMNESIA       - 1] = gMoveDescription_Amnesia,
    [MOVE_KINESIS       - 1] = gMoveDescription_Kinesis,
    [MOVE_SOFT_BOILED   - 1] = gMoveDescription_SoftBoiled,
    [MOVE_HI_JUMP_KICK  - 1] = gMoveDescription_HiJumpKick,
    [MOVE_GLARE         - 1] = gMoveDescription_Glare,
    [MOVE_DREAM_EATER   - 1] = gMoveDescription_DreamEater,
    [MOVE_POISON_GAS    - 1] = gMoveDescription_PoisonGas,
    [MOVE_BARRAGE       - 1] = gMoveDescription_Barrage,
    [MOVE_LEECH_LIFE    - 1] = gMoveDescription_LeechLife,
    [MOVE_LOVELY_KISS   - 1] = gMoveDescription_LovelyKiss,
    [MOVE_SKY_ATTACK    - 1] = gMoveDescription_SkyAttack,
    [MOVE_TRANSFORM     - 1] = gMoveDescription_Transform,
    [MOVE_BUBBLE        - 1] = gMoveDescription_Bubble,
    [MOVE_DIZZY_PUNCH   - 1] = gMoveDescription_DizzyPunch,
    [MOVE_SPORE         - 1] = gMoveDescription_Spore,
    [MOVE_FLASH         - 1] = gMoveDescription_Flash,
    [MOVE_PSYWAVE       - 1] = gMoveDescription_Psywave,
    [MOVE_SPLASH        - 1] = gMoveDescription_Splash,
    [MOVE_ACID_ARMOR    - 1] = gMoveDescription_AcidArmor,
    [MOVE_CRABHAMMER    - 1] = gMoveDescription_Crabhammer,
    [MOVE_EXPLOSION     - 1] = gMoveDescription_Explosion,
    [MOVE_FURY_SWIPES   - 1] = gMoveDescription_FurySwipes,
    [MOVE_BONEMERANG    - 1] = gMoveDescription_Bonemerang,
    [MOVE_REST          - 1] = gMoveDescription_Rest,
    [MOVE_ROCK_SLIDE    - 1] = gMoveDescription_RockSlide,
    [MOVE_HYPER_FANG    - 1] = gMoveDescription_HyperFang,
    [MOVE_SHARPEN       - 1] = gMoveDescription_Sharpen,
    [MOVE_CONVERSION    - 1] = gMoveDescription_Conversion,
    [MOVE_TRI_ATTACK    - 1] = gMoveDescription_TriAttack,
    [MOVE_SUPER_FANG    - 1] = gMoveDescription_SuperFang,
    [MOVE_SLASH         - 1] = gMoveDescription_Slash,
    [MOVE_SUBSTITUTE    - 1] = gMoveDescription_Substitute,
    [MOVE_STRUGGLE      - 1] = gMoveDescription_Struggle,
    [MOVE_SKETCH        - 1] = gMoveDescription_Sketch,
    [MOVE_TRIPLE_KICK   - 1] = gMoveDescription_TripleKick,
    [MOVE_THIEF         - 1] = gMoveDescription_Thief,
    [MOVE_SPIDER_WEB    - 1] = gMoveDescription_SpiderWeb,
    [MOVE_MIND_READER   - 1] = gMoveDescription_MindReader,
    [MOVE_NIGHTMARE     - 1] = gMoveDescription_Nightmare,
    [MOVE_FLAME_WHEEL   - 1] = gMoveDescription_FlameWheel,
    [MOVE_SNORE         - 1] = gMoveDescription_Snore,
    [MOVE_CURSE         - 1] = gMoveDescription_Curse,
    [MOVE_FLAIL         - 1] = gMoveDescription_Flail,
    [MOVE_CONVERSION_2  - 1] = gMoveDescription_Conversion2,
    [MOVE_AEROBLAST     - 1] = gMoveDescription_Aeroblast,
    [MOVE_COTTON_SPORE  - 1] = gMoveDescription_CottonSpore,
    [MOVE_REVERSAL      - 1] = gMoveDescription_Reversal,
    [MOVE_SPITE         - 1] = gMoveDescription_Spite,
    [MOVE_POWDER_SNOW   - 1] = gMoveDescription_PowderSnow,
    [MOVE_PROTECT       - 1] = gMoveDescription_Protect,
    [MOVE_MACH_PUNCH    - 1] = gMoveDescription_MachPunch,
    [MOVE_SCARY_FACE    - 1] = gMoveDescription_ScaryFace,
    [MOVE_FAINT_ATTACK  - 1] = gMoveDescription_FaintAttack,
    [MOVE_SWEET_KISS    - 1] = gMoveDescription_SweetKiss,
    [MOVE_BELLY_DRUM    - 1] = gMoveDescription_BellyDrum,
    [MOVE_SLUDGE_BOMB   - 1] = gMoveDescription_SludgeBomb,
    [MOVE_MUD_SLAP      - 1] = gMoveDescription_MudSlap,
    [MOVE_OCTAZOOKA     - 1] = gMoveDescription_Octazooka,
    [MOVE_SPIKES        - 1] = gMoveDescription_Spikes,
    [MOVE_ZAP_CANNON    - 1] = gMoveDescription_ZapCannon,
    [MOVE_FORESIGHT     - 1] = gMoveDescription_Foresight,
    [MOVE_DESTINY_BOND  - 1] = gMoveDescription_DestinyBond,
    [MOVE_PERISH_SONG   - 1] = gMoveDescription_PerishSong,
    [MOVE_ICY_WIND      - 1] = gMoveDescription_IcyWind,
    [MOVE_DETECT        - 1] = gMoveDescription_Detect,
    [MOVE_BONE_RUSH     - 1] = gMoveDescription_BoneRush,
    [MOVE_LOCK_ON       - 1] = gMoveDescription_LockOn,
    [MOVE_OUTRAGE       - 1] = gMoveDescription_Outrage,
    [MOVE_SANDSTORM     - 1] = gMoveDescription_Sandstorm,
    [MOVE_GIGA_DRAIN    - 1] = gMoveDescription_GigaDrain,
    [MOVE_ENDURE        - 1] = gMoveDescription_Endure,
    [MOVE_CHARM         - 1] = gMoveDescription_Charm,
    [MOVE_ROLLOUT       - 1] = gMoveDescription_Rollout,
    [MOVE_FALSE_SWIPE   - 1] = gMoveDescription_FalseSwipe,
    [MOVE_SWAGGER       - 1] = gMoveDescription_Swagger,
    [MOVE_MILK_DRINK    - 1] = gMoveDescription_MilkDrink,
    [MOVE_SPARK         - 1] = gMoveDescription_Spark,
    [MOVE_FURY_CUTTER   - 1] = gMoveDescription_FuryCutter,
    [MOVE_STEEL_WING    - 1] = gMoveDescription_SteelWing,
    [MOVE_MEAN_LOOK     - 1] = gMoveDescription_MeanLook,
    [MOVE_ATTRACT       - 1] = gMoveDescription_Attract,
    [MOVE_SLEEP_TALK    - 1] = gMoveDescription_SleepTalk,
    [MOVE_HEAL_BELL     - 1] = gMoveDescription_HealBell,
    [MOVE_RETURN        - 1] = gMoveDescription_Return,
    [MOVE_PRESENT       - 1] = gMoveDescription_Present,
    [MOVE_FRUSTRATION   - 1] = gMoveDescription_Frustration,
    [MOVE_SAFEGUARD     - 1] = gMoveDescription_Safeguard,
    [MOVE_PAIN_SPLIT    - 1] = gMoveDescription_PainSplit,
    [MOVE_SACRED_FIRE   - 1] = gMoveDescription_SacredFire,
    [MOVE_MAGNITUDE     - 1] = gMoveDescription_Magnitude,
    [MOVE_DYNAMIC_PUNCH - 1] = gMoveDescription_DynamicPunch,
    [MOVE_MEGAHORN      - 1] = gMoveDescription_Megahorn,
    [MOVE_DRAGON_BREATH - 1] = gMoveDescription_DragonBreath,
    [MOVE_BATON_PASS    - 1] = gMoveDescription_BatonPass,
    [MOVE_ENCORE        - 1] = gMoveDescription_Encore,
    [MOVE_PURSUIT       - 1] = gMoveDescription_Pursuit,
    [MOVE_RAPID_SPIN    - 1] = gMoveDescription_RapidSpin,
    [MOVE_SWEET_SCENT   - 1] = gMoveDescription_SweetScent,
    [MOVE_IRON_TAIL     - 1] = gMoveDescription_IronTail,
    [MOVE_METAL_CLAW    - 1] = gMoveDescription_MetalClaw,
    [MOVE_VITAL_THROW   - 1] = gMoveDescription_VitalThrow,
    [MOVE_MORNING_SUN   - 1] = gMoveDescription_MorningSun,
    [MOVE_SYNTHESIS     - 1] = gMoveDescription_Synthesis,
    [MOVE_MOONLIGHT     - 1] = gMoveDescription_Moonlight,
    [MOVE_HIDDEN_POWER  - 1] = gMoveDescription_HiddenPower,
    [MOVE_CROSS_CHOP    - 1] = gMoveDescription_CrossChop,
    [MOVE_TWISTER       - 1] = gMoveDescription_Twister,
    [MOVE_RAIN_DANCE    - 1] = gMoveDescription_RainDance,
    [MOVE_SUNNY_DAY     - 1] = gMoveDescription_SunnyDay,
    [MOVE_CRUNCH        - 1] = gMoveDescription_Crunch,
    [MOVE_MIRROR_COAT   - 1] = gMoveDescription_MirrorCoat,
    [MOVE_PSYCH_UP      - 1] = gMoveDescription_PsychUp,
    [MOVE_EXTREME_SPEED - 1] = gMoveDescription_ExtremeSpeed,
    [MOVE_ANCIENT_POWER - 1] = gMoveDescription_AncientPower,
    [MOVE_SHADOW_BALL   - 1] = gMoveDescription_ShadowBall,
    [MOVE_FUTURE_SIGHT  - 1] = gMoveDescription_FutureSight,
    [MOVE_ROCK_SMASH    - 1] = gMoveDescription_RockSmash,
    [MOVE_WHIRLPOOL     - 1] = gMoveDescription_Whirlpool,
    [MOVE_BEAT_UP       - 1] = gMoveDescription_BeatUp,
    [MOVE_FAKE_OUT      - 1] = gMoveDescription_FakeOut,
    [MOVE_UPROAR        - 1] = gMoveDescription_Uproar,
    [MOVE_STOCKPILE     - 1] = gMoveDescription_Stockpile,
    [MOVE_SPIT_UP       - 1] = gMoveDescription_SpitUp,
    [MOVE_SWALLOW       - 1] = gMoveDescription_Swallow,
    [MOVE_HEAT_WAVE     - 1] = gMoveDescription_HeatWave,
    [MOVE_HAIL          - 1] = gMoveDescription_Hail,
    [MOVE_TORMENT       - 1] = gMoveDescription_Torment,
    [MOVE_FLATTER       - 1] = gMoveDescription_Flatter,
    [MOVE_WILL_O_WISP   - 1] = gMoveDescription_WillOWisp,
    [MOVE_MEMENTO       - 1] = gMoveDescription_Memento,
    [MOVE_FACADE        - 1] = gMoveDescription_Facade,
    [MOVE_FOCUS_PUNCH   - 1] = gMoveDescription_FocusPunch,
    [MOVE_SMELLING_SALT - 1] = gMoveDescription_SmellingSalt,
    [MOVE_FOLLOW_ME     - 1] = gMoveDescription_FollowMe,
    [MOVE_NATURE_POWER  - 1] = gMoveDescription_NaturePower,
    [MOVE_CHARGE        - 1] = gMoveDescription_Charge,
    [MOVE_TAUNT         - 1] = gMoveDescription_Taunt,
    [MOVE_HELPING_HAND  - 1] = gMoveDescription_HelpingHand,
    [MOVE_TRICK         - 1] = gMoveDescription_Trick,
    [MOVE_ROLE_PLAY     - 1] = gMoveDescription_RolePlay,
    [MOVE_WISH          - 1] = gMoveDescription_Wish,
    [MOVE_ASSIST        - 1] = gMoveDescription_Assist,
    [MOVE_INGRAIN       - 1] = gMoveDescription_Ingrain,
    [MOVE_SUPERPOWER    - 1] = gMoveDescription_Superpower,
    [MOVE_MAGIC_COAT    - 1] = gMoveDescription_MagicCoat,
    [MOVE_RECYCLE       - 1] = gMoveDescription_Recycle,
    [MOVE_REVENGE       - 1] = gMoveDescription_Revenge,
    [MOVE_BRICK_BREAK   - 1] = gMoveDescription_BrickBreak,
    [MOVE_YAWN          - 1] = gMoveDescription_Yawn,
    [MOVE_KNOCK_OFF     - 1] = gMoveDescription_KnockOff,
    [MOVE_ENDEAVOR      - 1] = gMoveDescription_Endeavor,
    [MOVE_ERUPTION      - 1] = gMoveDescription_Eruption,
    [MOVE_SKILL_SWAP    - 1] = gMoveDescription_SkillSwap,
    [MOVE_IMPRISON      - 1] = gMoveDescription_Imprison,
    [MOVE_REFRESH       - 1] = gMoveDescription_Refresh,
    [MOVE_GRUDGE        - 1] = gMoveDescription_Grudge,
    [MOVE_SNATCH        - 1] = gMoveDescription_Snatch,
    [MOVE_SECRET_POWER  - 1] = gMoveDescription_SecretPower,
    [MOVE_DIVE          - 1] = gMoveDescription_Dive,
    [MOVE_ARM_THRUST    - 1] = gMoveDescription_ArmThrust,
    [MOVE_CAMOUFLAGE    - 1] = gMoveDescription_Camouflage,
    [MOVE_TAIL_GLOW     - 1] = gMoveDescription_TailGlow,
    [MOVE_LUSTER_PURGE  - 1] = gMoveDescription_LusterPurge,
    [MOVE_MIST_BALL     - 1] = gMoveDescription_MistBall,
    [MOVE_FEATHER_DANCE - 1] = gMoveDescription_FeatherDance,
    [MOVE_TEETER_DANCE  - 1] = gMoveDescription_TeeterDance,
    [MOVE_BLAZE_KICK    - 1] = gMoveDescription_BlazeKick,
    [MOVE_MUD_SPORT     - 1] = gMoveDescription_MudSport,
    [MOVE_ICE_BALL      - 1] = gMoveDescription_IceBall,
    [MOVE_NEEDLE_ARM    - 1] = gMoveDescription_NeedleArm,
    [MOVE_SLACK_OFF     - 1] = gMoveDescription_SlackOff,
    [MOVE_HYPER_VOICE   - 1] = gMoveDescription_HyperVoice,
    [MOVE_POISON_FANG   - 1] = gMoveDescription_PoisonFang,
    [MOVE_CRUSH_CLAW    - 1] = gMoveDescription_CrushClaw,
    [MOVE_BLAST_BURN    - 1] = gMoveDescription_BlastBurn,
    [MOVE_HYDRO_CANNON  - 1] = gMoveDescription_HydroCannon,
    [MOVE_METEOR_MASH   - 1] = gMoveDescription_MeteorMash,
    [MOVE_ASTONISH      - 1] = gMoveDescription_Astonish,
    [MOVE_WEATHER_BALL  - 1] = gMoveDescription_WeatherBall,
    [MOVE_AROMATHERAPY  - 1] = gMoveDescription_Aromatherapy,
    [MOVE_FAKE_TEARS    - 1] = gMoveDescription_FakeTears,
    [MOVE_AIR_CUTTER    - 1] = gMoveDescription_AirCutter,
    [MOVE_OVERHEAT      - 1] = gMoveDescription_Overheat,
    [MOVE_ODOR_SLEUTH   - 1] = gMoveDescription_OdorSleuth,
    [MOVE_ROCK_TOMB     - 1] = gMoveDescription_RockTomb,
    [MOVE_SILVER_WIND   - 1] = gMoveDescription_SilverWind,
    [MOVE_METAL_SOUND   - 1] = gMoveDescription_MetalSound,
    [MOVE_GRASS_WHISTLE - 1] = gMoveDescription_GrassWhistle,
    [MOVE_TICKLE        - 1] = gMoveDescription_Tickle,
    [MOVE_COSMIC_POWER  - 1] = gMoveDescription_CosmicPower,
    [MOVE_WATER_SPOUT   - 1] = gMoveDescription_WaterSpout,
    [MOVE_SIGNAL_BEAM   - 1] = gMoveDescription_SignalBeam,
    [MOVE_SHADOW_PUNCH  - 1] = gMoveDescription_ShadowPunch,
    [MOVE_EXTRASENSORY  - 1] = gMoveDescription_Extrasensory,
    [MOVE_SKY_UPPERCUT  - 1] = gMoveDescription_SkyUppercut,
    [MOVE_SAND_TOMB     - 1] = gMoveDescription_SandTomb,
    [MOVE_SHEER_COLD    - 1] = gMoveDescription_SheerCold,
    [MOVE_MUDDY_WATER   - 1] = gMoveDescription_MuddyWater,
    [MOVE_BULLET_SEED   - 1] = gMoveDescription_BulletSeed,
    [MOVE_AERIAL_ACE    - 1] = gMoveDescription_AerialAce,
    [MOVE_ICICLE_SPEAR  - 1] = gMoveDescription_IcicleSpear,
    [MOVE_IRON_DEFENSE  - 1] = gMoveDescription_IronDefense,
    [MOVE_BLOCK         - 1] = gMoveDescription_Block,
    [MOVE_HOWL          - 1] = gMoveDescription_Howl,
    [MOVE_DRAGON_CLAW   - 1] = gMoveDescription_DragonClaw,
    [MOVE_FRENZY_PLANT  - 1] = gMoveDescription_FrenzyPlant,
    [MOVE_BULK_UP       - 1] = gMoveDescription_BulkUp,
    [MOVE_BOUNCE        - 1] = gMoveDescription_Bounce,
    [MOVE_MUD_SHOT      - 1] = gMoveDescription_MudShot,
    [MOVE_POISON_TAIL   - 1] = gMoveDescription_PoisonTail,
    [MOVE_COVET         - 1] = gMoveDescription_Covet,
    [MOVE_VOLT_TACKLE   - 1] = gMoveDescription_VoltTackle,
    [MOVE_MAGICAL_LEAF  - 1] = gMoveDescription_MagicalLeaf,
    [MOVE_WATER_SPORT   - 1] = gMoveDescription_WaterSport,
    [MOVE_CALM_MIND     - 1] = gMoveDescription_CalmMind,
    [MOVE_LEAF_BLADE    - 1] = gMoveDescription_LeafBlade,
    [MOVE_DRAGON_DANCE  - 1] = gMoveDescription_DragonDance,
    [MOVE_ROCK_BLAST    - 1] = gMoveDescription_RockBlast,
    [MOVE_SHOCK_WAVE    - 1] = gMoveDescription_ShockWave,
    [MOVE_WATER_PULSE   - 1] = gMoveDescription_WaterPulse,
    [MOVE_DOOM_DESIRE   - 1] = gMoveDescription_DoomDesire,
    [MOVE_PSYCHO_BOOST  - 1] = gMoveDescription_PsychoBoost,
};
