@ Unused
FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
    .string "とびらを　あけるには\n"
    .string "パスワードが　2つ　いるようだ$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
    .string "{PLAYER} הזין סיסמה.\p"
    .string "“גולדין צריך בול עץ.”\p"
    .string "… …  … …  … …\p"
    .string "דרושה עוד סיסמה כדי\n"
    .string "לפתוח את הדלת…$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
    .string "{PLAYER} הזין שתי סיסמאות.\p"
    .string "“גולדין צריך בול עץ.”\n"
    .string "“כן, לא, צ'נסי.”\p"
    .string "… …  … …  … …\p"
    .string "דלת המחסן נפתחה!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
    .string "דלת המחסן כבר\n"
    .string "פתוחה.$"

FiveIsland_Meadow_Text_Rocket1Intro::
    .string "האזור הזה סגור לחלוטין!\n"
    .string "החוצה, החוצה!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
    .string "זה באמת קרה?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
    .string "אין לך מה לחפש כאן!\n"
    .string "לך הביתה!$"

FiveIsland_Meadow_Text_Rocket2Intro::
    .string "אין כאן כלום מלבד\n"
    .string "המחסן שלנו.\p"
    .string "אז מה מביא אותך לכאן?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
    .string "זה לא היה אמור לקרות…$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
    .string "אתה רוצה לדעת מה יש\n"
    .string "בתוך המחסן הזה?\p"
    .string "עדיף שלא תדע.\n"
    .string "לטובתך, אני מתכוון.$"

FiveIsland_Meadow_Text_Rocket3Intro::
    .string "גם אם תצליח לעבור אותי,\n"
    .string "זה יהיה בזבוז זמן.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
    .string "אוי, זה מרגיז אותי נורא!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
    .string "בלי הסיסמאות לא תוכל\n"
    .string "להיכנס בכל מקרה.$"

