Text_CounterTeach::
    .string "אה, היי! סוף-סוף\n"
    .string "סיימתי לשחק בפוקימון!\p"
    .string "עוד לא סיימת? אולי זה יעזור!\p$"

CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
    .string "כשפוקימון נתפס, הוא מקבל מספר\n"
    .string "זהות - או DI - וTO, שהוא השם של\l"
    .string "המאמן שתפס אותו!$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
    .string "יאללה!\p"
    .string "החבר שלי מוכן להחליף את הקנגסקאן\l"
    .string "שלו בעד הגרבלר שלי!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
    .string "בוא אלי, גרבלר!\p"
    .string "אני אוהבת גרבלרים! אני אוסף אותם!\p"
    .string "רגע, מה?\p"
    .string "גרבלר הפך לפוקימון אחר!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
    .string "אתה יכול לזהות\n"
    .string "פוקימונים שקיבלת דרך החלפה לפי\l"
    .string "מספר הזהות שלהם, ה-DI!$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "זה קונסולה!$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "זה משחק תפקידים!\n"
    .string "אין לך זמן לזה!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "משחק ספורט!\n"
    .string "אבא יאהב את זה!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "משחק מחשבה!\n"
    .string "נראה ממכר!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "משחק מכות!\n"
    .string "נראה קשוח!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "ק3: חנות משחקי\n"
    .string "מחשב$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "אדום וירוק!\n"
    .string "שתי גרסאות של פוקימון!$"

Text_CounterDeclined::
    .string "אתה לא מעוניין?\n"
    .string "תבוא לראות אותי שוב אם אתה\l"
	.string "משנה את דעתך.$"

Text_CounterWhichMon::
    .string "איזה פוקימון תרצה שאלמד\n"
    .string "את המהלך נגידה?$"

Text_CounterTaught::
    .string "נו, כבר השתמשת במהלך\n"
    .string "נגידה שלימדתי אותך?$"
