Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
    .string "היי! זוכר אותי? אני אחד מהסייעים\n"
    .string "של פרופ' אוק. אם הפוקדקס שלך מכיל\l"
    .string "נתונים מלאים על {STR_VAR_1} מיני\l"
    .string "פוקימון, אני אמור לתת לך פרס.\p"
    .string "פרופ' אוק הטיל עליי את המשימה\n"
    .string "לתת לך את ה-{STR_VAR_2}.\p"
    .string "אז, {PLAYER}, תן לי לשאול אותך.\n"
    .string "האם אספת נתונים על לפחות\l"
    .string "{STR_VAR_1} סוגי פוקימון?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
    .string "מצוין! תפסת או החזקת\n"
    .string "{STR_VAR_3} סוגי פוקימון!\l"
    .string "מזל טוב!\l"
    .string "הנה זה בשבילך!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
    .string "{PLAYER} קיבל את ה-{STR_VAR_2}\n"
    .string "מהסייע.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
    .string "יש פריטים על הקרקע שיכולים להיות\n"
    .string "מוסתרים מהעין. השתמש במוצא כדי\l"
    .string "לזהות פריטים מוסתרים בסמוך לך.\l"
    .string "המכשיר מוגבל במעט. הוא לא יכול\l"
    .string "לאתר את מיקום הפריט. מה שהוא\l"
    .string "עושה זה להראות את הכיוון שבו\l"
    .string "נמצא הפריט. השתמש בו כדי למקד את\l"
    .string "הכיוונים, ואז חפש את האזור החשוד\l"
    .string "ידנית.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
    .string "בוא נראה מה יש למשקפות\n"
    .string "להראות…\l"
    .string "פוקימון גדול ישן על הדרך!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
    .string "בוא נראה מה יש למשקפות\n"
    .string "להראות…\l"
    .string "איזו תצפית מדהימה!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
    .string "בוא נראה מה יש למשקפות\n"
    .string "להראות…\l"
    .string "כדי להגיע לעיר לאבנדר מ-\l"
    .string "עיר סרוליאן…\l"
    .string "מנהרת הסלע נראית כדרך טובה\l"
    .string "ללכת בה.$"
