PewterCity_Gym_Text_BrockIntro::
    .string "אז, הגעת. אני ברוק.\n"
    .string "אני מנהיג מכון פיוטר.\p"
    .string "הכוח הרצון שלי, שהוא קשה כאבן,\n"
    .string "ניכר אפילו בפוקימונים שלי.\p"
    .string "הפוקימונים שלי כולם קשים כאבן,\n"
    .string "ונחושים בדעתם.\p"
    .string "נכון - הפוקימונים שלי הם כולם\n"
    .string "מסוג אבן!\p"
    .string "פוואהאהא! אתה הולך לאתגר אותי\n"
    .string "למרות שאתה יודע שתפסיד?\p"
    .string "זה כבודו של מאמן שמאלץ אותך\n"
    .string "לאתגר אותי.\p"
    .string "טוב, אז!\n"
    .string "הראה לי את הטוב ביותר שלך!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PewterCity_Gym_Text_BrockDefeat::
    .string "לקחתי אותך כמובן מאליו, ולכן\n"
    .string "הפסדתי.\p"
    .string "כהוכחה לניצחונך, אני מעניק לך\n"
    .string "את זה…תג הבולדר הרשמי של ליגת\l"
    .string "הפוקימונים.\p"
    .string "{FONT_NORMAL}{PLAYER} קיבל את תג הבולדר\n"
    .string "מברוק!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{FONT_MALE}עצם קבלת תג הבולדר הופכת את\n"
    .string "הפוקימונים שלך לחזקים יותר.\p"
    .string "התג גם מאפשר שימוש במהלך הבזק\n"
    .string "מחוץ לקרב.\p"
    .string "כמובן, פוקימון חייב לדעת את\n"
    .string "המהלך הבזק כדי להשתמש בו.$"

PewterCity_Gym_Text_TakeThisWithYou::
    .string "חכה!\n"
    .string "קח את זה איתך.$"

PewterCity_Gym_Text_ReceivedTM39FromBrock::
    .string "{PLAYER} קיבל את מ“מ93\n"
    .string "מברוק.$"

PewterCity_Gym_Text_ExplainTM39::
    .string "מ“מ, מהלך מאמן, מכיל\n"
    .string "טכניקה לפוקימון.\p"
    .string "שימוש במ“מ מלמד את המהלך שהוא\n"
    .string "מכיל לפוקימון.\p"
    .string "מ“מ טוב לשימוש אחד בלבד.\p"
    .string "לכן, כאשר אתה משתמש באחד, בחר את\n"
    .string "הפוקימון בקפידה.\p"
    .string "בכל מקרה…\n"
    .string "מ“מ93 מכיל את מהלך קבר אבן.\p"
    .string "הוא משליך סלעים על היריב ומוריד\n"
    .string "את מהירותו.$"

PewterCity_Gym_Text_BrockPostBattle::
    .string "ישנם כל מיני מאמנים בעולם\n"
    .string "העצום שלנו.\p"
    .string "נראה שאתה מוכשר מאוד בתור\n"
    .string "מאמן פוקימונים.\p"
    .string "אז תן לי לתת לך עצה.\p"
    .string "לך למכון בעקרת המים ותבחן\n"
    .string "את יכולותיך.$"

PewterCity_Gym_Text_DontHaveRoomForThis::
    .string "אין לך מקום לזה.$"

PewterCity_Gym_Text_LiamIntro::
    .string "עצור שם, ילד!\p"
    .string "אתה במרחק עשרת אלפים שנות אור\n"
    .string "מלהתמודד מול ברוק!$"

PewterCity_Gym_Text_LiamDefeat::
    .string "לעזאזל!\p"
    .string "שנות אור אינן זמן…\n"
    .string "הן מודדות מרחק!$"

PewterCity_Gym_Text_LiamPostBattle::
    .string "אתה די לוהט.\n"
    .string "…אבל לא כמו ברוק!$"

PewterCity_Gym_Text_LetMeTakeYouToTheTop::
    .string "היי!\n"
    .string "רוצה לחלום בגדול?\p"
    .string "יש לך אומץ לחלום על להיות\n"
    .string "אלוף הפוקימונים?\p"
    .string "אני לא מאמן, אבל אני יכול לייעץ\n"
    .string "לך איך לנצח.\p"
    .string "תן לי לקחת אותך לפסגה!$"

PewterCity_Gym_Text_LetsGetHappening::
    .string "בסדר!\n"
    .string "בוא נתחיל!$"

PewterCity_Gym_Text_TryDifferentPartyOrders::
    .string "הפוקימון הראשון בקרב הוא זה\n"
    .string "שנמצא בצד שמאל של רשימת\l"
    .string "הפוקימונים.\p"
    .string "על ידי שינוי הסדר, ייתכן שתשיג\n"
    .string "יתרון על היריב שלך.\p"
    .string "נסה סדרים שונים כדי להתאים\n"
    .string "למסיבה של היריב שלך.$"

PewterCity_Gym_Text_ItsFreeLetsGetHappening::
    .string "זו שירות חינמי!\n"
    .string "בוא נתחיל!$"

PewterCity_Gym_Text_YoureChampMaterial::
    .string "כמו שחשבתי!\n"
    .string "אתה חומר לאלוף פוקימונים!$"

PewterCity_Gym_Text_GymStatue::
    .string "מכון הפוקימונים פיוטר\n"
    .string "מנהיג: ברוק\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}$"

PewterCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון הפוקימונים פיוטר\n"
    .string "מנהיג: ברוק\p"
    .string "מאמנים שניצחו:\n"
    .string "{RIVAL}, {PLAYER}$"
