Route13_Text_SebastianIntro::
    .string "הפוקימונים המעופפים שלי רוצים\n"
    .string "להילחם איתך!$"

Route13_Text_SebastianDefeat::
    .string "הצמד פידג'י ופידג'יוטו שלי\n"
    .string "הפסיד?$"

Route13_Text_SebastianPostBattle::
    .string "הפוקימונים שלי נראים שמחים\n"
    .string "אפילו שהם הפסידו.$"

Route13_Text_SusieIntro::
    .string "אמרו לי שאני טובה בשביל ילדה.$"

Route13_Text_SusieDefeat::
    .string "אוי!\n"
    .string "הפסדתי!$"

Route13_Text_SusiePostBattle::
    .string "אני רוצה להפוך למאמנת טובה.\n"
    .string "אתאמן קשה, רק תראה.$"

Route13_Text_ValerieIntro::
    .string "וואו!\n"
    .string "התגים שלך ממש מגניבים!$"

Route13_Text_ValerieDefeat::
    .string "לא מספיק!$"

Route13_Text_ValeriePostBattle::
    .string "אתה קיבלת את התגים האלו ממנהיגי\n"
    .string "אולמות. אני יודעת!$"

Route13_Text_GwenIntro::
    .string "הפוקימונים החמודים שלי רוצים\n"
    .string "להכיר אותך.$"

Route13_Text_GwenDefeat::
    .string "כל הכבוד!\n"
    .string "ניצחת לגמרי!$"

Route13_Text_GwenPostBattle::
    .string "צריך לגרום לפוקימונים להילחם\n"
    .string "כדי לחזק אותם.$"

Route13_Text_AlmaIntro::
    .string "מצאתי קרבוס פעם במערה בזמן\n"
    .string "ששחזרתי.$"

Route13_Text_AlmaDefeat::
    .string "אוי, חבל!\n"
    .string "פשוט טעיתי!$"

Route13_Text_AlmaPostBattle::
    .string "קרבוס שיפר את המהירות של\n"
    .string "הפוקימונים שלי.$"

Route13_Text_PerryIntro::
    .string "אני לא עומד להפסיד.\n"
    .string "לא כשהרוח לטובתי!$"

Route13_Text_PerryDefeat::
    .string "הרוח התהפכה!$"

Route13_Text_PerryPostBattle::
    .string "אני מותש.\n"
    .string "אני מניח שאעוף הביתה.$"

Route13_Text_LolaIntro::
    .string "בטח, אשחק איתך, מתוק.$"

Route13_Text_LolaDefeat::
    .string "אוי!\n"
    .string "איזה שדון קטן אתה!$"

Route13_Text_LolaPostBattle::
    .string "מעניין מי יותר חזק, פוקימונים\n"
    .string "זכרים או נקבות?$"

Route13_Text_SheilaIntro::
    .string "רוצה להילחם בפוקימונים יחד\n"
    .string "איתי?$"

Route13_Text_SheilaDefeat::
    .string "זה נגמר כבר?$"

Route13_Text_SheilaPostBattle::
    .string "אני לא יודעת כלום על\n"
    .string "פוקימונים בעצם.\p"
    .string "את אלו שאני משתמשת בהם… בחרתי\n"
    .string "בגלל איך שהם נראים!$"

Route13_Text_JaredIntro::
    .string "על מה אתה מסתכל?$"

Route13_Text_JaredDefeat::
    .string "אוף!\n"
    .string "הרסת אותי!$"

Route13_Text_JaredPostBattle::
    .string "תסתלק מכאן!$"

Route13_Text_RobertIntro::
    .string "אני תמיד בוחר בפוקימונים מעופפים.\n"
    .string "הקדשתי את עצמי להם.$"

Route13_Text_RobertDefeat::
    .string "נגמר לי הכוח!$"

Route13_Text_RobertPostBattle::
    .string "הלוואי שיכולתי לעוף כמו פידג'י\n"
    .string "ופידג'יוטו…$"

Route13_Text_LookToLeftOfThatPost::
    .string "טיפים למאמנים\p"
    .string "תסתכל, תסתכל!\n"
    .string "תסתכל שמאלה מהעמוד הזה!$"

Route13_Text_SelectToSwitchItems::
    .string "טיפים למאמנים\p"
    .string "השתמש ב-SELECT כדי להחליף פריטים\n"
    .string "בחלון הפריטים.$"

Route13_Text_RouteSign::
    .string "דרך 31\n"
    .string "צפונה אל גשר השקט$"
