ViridianCity_Text_CanCarryMonsAnywhere::
    .string "אלו פוקיבולים\n"
    .string "שתלויים על חגורתך! אם כן,\l"
    .string "יש לך פוקימונים.\p"
    .string "זה נדיר שאתה יכול לסחוב אותם\l"
    .string "איתך ולהשתמש בהם בכל זמן ומקום!$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
    .string "מכון הפוקימון הזה\n"
    .string "תמיד סגור.\p"
    .string "מעניין מי המנהיג במכון הזה?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
    .string "המנהיג של מכון\n"
    .string "הארגמן חזר!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
    .string "רוצה ללמוד\n"
    .string "על 2 סוגי פוקימוני הזחלים?$"

ViridianCity_Text_OhOkayThen::
    .string "אה, בסדר!$"

ViridianCity_Text_ExplainCaterpieWeedle::
    .string "לקטרפי אין עוקץ,\n"
    .string "אבל לווידל יש.\p"
    .string "כדאי להיזהר ממתקפת\n"
    .string "עקיצת הרעל שלו!$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
    .string "נו באמת, סבא!\n"
    .string "אל תדבר ככה! הוא עדיין לא שתה\l"
    .string "את הקפה של הבוקר.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
    .string "כשאני הולכת לקניות\n"
    .string "בעיר הכספית, אני חייבת לעבור דרך\l"
    .string "השביל המתפתל ביער ירוק-עד.$"

ViridianCity_Text_ThisIsPrivateProperty::
    .string "אתה לא יכול לעבור\n"
    .string "פה!\p"
    .string "זה שטח פרטי!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
    .string "הא!\n"
    .string "כנראה שנרדמתי קצת בשמש.\p"
    .string "היה לי חלום על דראוזי שאוכל\n"
    .string "את החלום שלי. מה זה?\l"
    .string "מאיפה הגיע המ”מ הזה?\p"
    .string "זה מפחיד! הנה, אתה יכול\l"
    .string "לקבל את המ”מ הזה.\p"
    .string "$"

ViridianCity_Text_ShowYouHowToCatchMons::
    .string "הה, סוף סוף שתיתי\n"
    .string "את הקפה שלי, ואני מרגיש מצוין!\p"
    .string "כמובן שאתה יכול לעבור כאן!\p"
    .string "אתה ממהר? אני רואה שאתה עושה\n"
    .string "שימוש בפוקדקס.\p"
    .string "כשאתה תופס פוקימון, הפוקדקס\l"
    .string "מתעדכן אוטומטית.\p"
    .string "מה? אתה לא יודע איך תופסים\l"
    .string "פוקימון?\p"
    .string "אם כך, אני אראה לך איך.$"

ViridianCity_Text_TooBusyForTeachyTV::
    .string "זמן זה כסף...\n"
    .string "תמשיך ללכת.$"

ViridianCity_Text_WatchThatToLearnBasics::
    .string "אם יש משהו שאתה לא מבין\n"
    .string "תסתכל בזה.\p"
    .string "זה ילמד אותך את הבסיס.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
    .string "הה, סוף סוף שתיתי\n"
    .string "את הקפה שלי, ואני מרגיש מצוין!\p"
    .string "עשיתי אותו חזק מידי\n"
    .string "הוא עשה לי כאב ראש...\p"
    .string "ילד, אתה ממלא את הפוקדקס שלך?\n"
    .string "בהתחלה, אתה צריך להחליש את\l"
    .string "הפוקימון שאתה מנסה לתפוס.$"

ViridianCity_Text_HowsTeachyTVHelping::
    .string "הה, סוף סוף שתיתי\n"
    .string "את הקפה שלי, ואני מרגיש מצוין!\p"
    .string "עשיתי אותו חזק מידי\n"
    .string "הוא עשה לי כאב ראש...\p"
    .string "זה הנכד שלי בטלוויזיה!\n"
    .string "אני בטוח שהוא ילמד אותך היטב.\p"
    .string "העיר ורידיאן גן העדן ירוק- העד$"

ViridianCity_Text_CatchMonsForEasierBattles::
    .string "טיפים למאמנים\p"
    .string "תפוס פוקימונים והרחב את האוסף\l"
    .string "שלך!\p"
    .string "ככל שיהיו לך יותר, כך יהיה לך קל\l"
    .string "להילחם בקרבות!$"

ViridianCity_Text_MovesLimitedByPP::
    .string "טיפים למאמנים\p"
    .string "המהלכים של פוקימונים מוגבלים\n"
    .string "בנקודות הכוח שלהם, או בקיצור\l"
    .string "נ”כ.\p"
    .string "כדי לשחזר נ”כ, רפא את הפוקימון\l"
    .string "במרכז הפוקימונים!$"

ViridianCity_Text_GymSign::
    .string "העיר ורידיאן\n"
    .string "מכון הפוקימון$"

ViridianCity_Text_GymDoorsAreLocked::
    .string "דלתות המכון\n"
    .string "סגורות...$"
	
ViridianCity_Text_MyGrandsonOnTheShow::
    .string "וואהאהאה!\n"
    .string "זה הנכד שלי בתוכנית!\p"
    .string "מכיוון שהוא זה שמלמד,\n"
    .string "אתה בטוח תלמד.$"

ViridianCity_Text_CitySign::
    .string "עיר ורידיאן\n"
    .string "גן העדן הירוק הנצחי$"
