@ The 5 texts below are supposed to be in FourIsland_House1
Text_BodySlamTeach::
    .string "מוכן?\n"
    .string "בוינג!\p"
    .string "אנחנו עורכים תחרות חבטת גוף\n"
    .string "כדי לראות מי מתקפל ראשון.\p"
    .string "אבל אם תצטרף אלינו, אתה\n"
    .string "תימעך כמו חרק…\p"
    .string "מה דעתך שבמקום זה אלמד\n"
    .string "חבטת גוף לפוקימון שלך?$"

Text_BodySlamDeclined::
    .string "בוא שוב!\n"
    .string "בוינג!$"

Text_BodySlamWhichMon::
    .string "איזה פוקימון רוצה ללמוד\n"
    .string "חבטת גוף?$"

Text_BodySlamTaught::
    .string "בויוינג!$"

FourIsland_House1_Text_FatMan::
    .string "それ　ぼよーん！\n"
    .string "おまえ　おもいなあー！$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
    .string "יש מין נדיר של פוקימון קרח\n"
    .string "שחי בתוך המערה.\p"
    .string "מגיעים לכאן הרבה מבקרים\n"
    .string "בתקווה לראות אותו.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
    .string "הא? ביצת פוקימון?\n"
    .string "…אין לי מושג.\p"
    .string "…רגע, רגע. האנשים ממעון היום\n"
    .string "בעיירה סיפרו משהו.\p"
    .string "הם אמרו שהם מצאו ביצים\n"
    .string "בחצר שלהם בעבר.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
    .string "מה זה?\p"
    .string "עיתון הפוקימון החדש עוד לא\n"
    .string "הגיע לאי הזה?$"

