CeruleanCity_House4_Text_NothingEntertaining::
    .string "אוף… יותר מידי זמן פנוי ופחות מידי\n"
    .string "לעשות…\p"
    .string "אין שום דבר מעניין בשום מקום?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
    .string "הו!\n"
    .string "דיווח חדשות!\p"
    .string "המממ…\p"
    .string "הבנתי!\n"
    .string "זה היה מלמד מאוד!\p"
    .string "כל הכבוד לך שאתה מתעניין בחדשות\n"
    .string "מגיל צעיר.\p"
    .string "כאות תודה שחלקת איתי את החדשות\n"
    .string "אני רוצה שתקבל את זה.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
    .string "אואה!\n"
    .string "דיווח החדשות הזה!\p"
    .string "המממ…\p"
    .string "מדהים!\n"
    .string "איזו כתבה מרתקת!\p"
    .string "לא נתקלתי בסיפור כה מעניין\n"
    .string "כבר המון זמן!\p"
    .string "תודה שחלקת את זה איתי.\n"
    .string "קח קצת פירות יער!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
    .string "זה ממש בזבוז לא לחלוק את החדשות\n"
    .string "האלה עם אנשים אחרים…\p"
    .string "הלוואי והייתי יכול לספר למישהו…\n"
    .string "לגרום לעוד אנשים לדעת…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
    .string "אה, הפצת את החדשות עבורי?\p"
    .string "כאות תודה שחלקת איתי את החדשות\n"
    .string "אני רוצה שתקבל את זה.$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
    .string "המשכת להפיץ את החדשות אפילו יותר?\n"
    .string "מדהים!\p"
    .string "אני מאמין שפיסת החדשות הזו נהנת\n"
    .string "מאוד לעבור לעוד אנשים.\p"
    .string "כן, אני בטוח!\p"
    .string "תחשיב את זה כאות תודה ממני\n"
    .string "ומהחדשות\p"
    .string "אתן לך יותר פירות יער ממה\n"
    .string "שאני בדרך כלל נותן.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
    .string "אני נהנה מכל מיני סוגים של חדשות\p"
    .string "כן, אני מרוצה! אני לא אהיה משועמם\n"
    .string "יותר לתקופה ארוכה.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
    .string "המ, נראה שתיק פירות היער שלך מלא\n"
    .string "אני לא יכול לתת לך את המתנה שלך.$"
