VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
    .string "שלום!\n"
    .string "יש לך {STR_VAR_1}?\p"
    .string "רוצה להחליף אותו ב-{STR_VAR_2}\n"
    .string "שלי?$"

VermilionCity_House2_Text_ThatsTooBad::
    .string "זה חבל.$"

VermilionCity_House2_Text_ThisIsNoMon::
    .string "…זה לא {STR_VAR_1}.\p"
    .string "אם תמצא אחד, בבקשה החלף אותו\n"
    .string "איתי!$"

VermilionCity_House2_Text_ThankYou::
    .string "תודה לך!$"

VermilionCity_House2_Text_HowIsMyOldMon::
    .string "איך הולך ל-{STR_VAR_2} הישן שלי?\p"
    .string "{STR_VAR_1} שלי במצב מעולה!$"
