CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "תפסתי את הקופינג\n"
    .string "שלי באי הצנובר!\p"
    .string "הוא נחמד, אבל הוא נושף אדי רעל\l"
    .string "כשהוא כועס!$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "חיחיחי! המכון הזה\n"
    .string "נהדר! הוא מלא בנשים!$"
	
CeladonCity_Text_BlewItAllAtSlots::
    .string "אוח! בזבזתי הכל\n"
    .string "במכונות המזל!\p"
    .string "ידעתי שהיה כדאי לי להחליף את\l"
    .string "האסימונים שלי בפרסים!$"

CeladonCity_Text_Poliwrath::
    .string "פוליראת': קוה\n"
    .string "קוה קוה!{}$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "למה אתה מסתכל\n"
    .string "עלי ככה?$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "אל תעמוד בדרכם\n"
    .string "של צוות רוקט!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "טיפים למאמנים\p"
    .string "+דיוק הוא פריט שמגביר את\l"
    .string "הדייקנות של מהלכים!\p"
    .string "הפריט +קריטי מגביר את הסבירות\l"
    .string "של מכה קריטית!\p"
    .string "קנה לך כאלה בחנות של העיר סלדון!$"

CeladonCity_Text_CitySign::
    .string "העיר סלדון\n"
    .string "העיר שבה חולמים בצבעי הקשת$"

CeladonCity_Text_GymSign::
    .string "סלדון\n"
    .string "מכון הפוקימון מנהיגה: אריקה\p"
    .string "הנסיכה אוהבת הטבע!$"

CeladonCity_Text_MansionSign::
    .string "אחוזת סלדון$"

CeladonCity_Text_DeptStoreSign::
    .string "תמצאו כל מה שאתם\n"
    .string "צריכים בחנות של סלדון!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "טיפים למאמנים\p"
    .string "הפריט הגנה מיוחדת מגן על הפוקימון\n"
    .string "שלך מפני מתקפות מיוחדות, כמו\l"
    .string "אש ומים!\p"
    .string "קנה לך כאלה בכל-בו אביב!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "החלפת אסימונים\n"
    .string "בפרסים! דלפק הפרסים$"

CeladonCity_Text_GameCornerSign::
    .string "משחקיית רוקט\n"
    .string "המשחקיה למבוגרים בלבד!$"

Text_SoftboiledDeclined::
    .string "אני אמשיך לבדוק אם\n"
    .string "אתה בסביבה.\p"
    .string "אני מקווה שנתראה שוב בקרוב.$"

Text_SoftboiledWhichMon::
    .string "אז, מי הפוקימון שיזכה ללמוד\n"
    .string "את המהלך הטלת ביצה?$"

Text_SoftboiledTaught::
    .string "שיהיה בהצלחה!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "אוי, מה אני אעשה…\p"
    .string "מישהו גנב את עדשת הסילף שלנו.\p"
    .string "הגנב ברח לכיוון הזה,\n"
    .string "אני בטוח בזה.\p"
    .string "אבל איבדתי אותו!\n"
    .string "לאן הוא ברח?$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "סלדון מתגעה במאמצים שלה לשמור\n"
    .string "על העיר יפיפיה.\p"
    .string "זה למה המשחקיה לא\n"
    .string "טובה לתדמית של העיר.$"
	
Text_SoftboiledTeach::
    .string "שלום לך!\p"
    .string "ראיתי אותך חולף,\n"
    .string "אבל מעולם לא היתה לנו הזדמנות\l"
    .string "לפטפט!\p"
    .string "הנה שי קטן על שעצרת כדי לדבר\l"
    .string "איתי!\p$"
	
CeladonCity_Text_ScaldedTongueOnTea::
    .string "אייי, אוו…\n"
    .string "שרפתי את הלשון!\p"
    .string "הגברת הזקנה הנחמדה מאחוזת סלדון\n"
    .string "הביאה לי קצת תה.\p"
    .string "אבל הוא היה רותח!\n"
    .string "חייב לקרר אותו לפני שטועמים.$"
	
CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "זה ידידי הטוב,\n"
    .string "פוליראת'!\p"
    .string "הוא היה פעם פוליוורל! הוא התפתח\n"
    .string "לפוליראת' כשהשתמשתי\l"
    .string "באבן מים עליו!$"
