VermilionCity_Gym_Text_LtSurgeIntro::
    .string "היי, ילד! מה אתה חושב שאתה\n"
    .string "עושה כאן?\p"
    .string "אתה לא תחזיק מעמד בקרב!\n"
    .string "לא עם הכוח העלוב שלך!\p"
    .string "אני אומר לך, ילד, פוקימונים\n"
    .string "חשמליים הצילו אותי במלחמה!\p"
    .string "הם שיתקו את האויבים שלי!\p"
    .string "זה בדיוק מה שאני אעשה לך!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "מילה אחת של עצה, ילד!\p"
    .string "חשמל הוא בהחלט עוצמתי!\p"
    .string "אבל, הוא חסר תועלת נגד\n"
    .string "פוקימוני אדמה!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "תג הרעם מגדיל את מהירות\n"
    .string "הפוקימון שלך!\p"
    .string "הוא גם מאפשר לפוקימון שלך\n"
    .string "לעוף כמו ברק בכל רגע, ילד!\p"
    .string "אתה מיוחד, ילד!\n"
    .string "קח את זה!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} קיבל את מ”מ43\n"
    .string "מ-לוטננט סרג'!$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "מ”מ43 מכיל את גל רעם!\p"
    .string "תלמד אותו לפוקימון חשמלי!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "היי, ילד, תפנה מקום בתיק שלך!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "עכשיו זה הפתיע אותי!\p"
    .string "אתה באמת מיוחד, ילד!\p"
    .string "בסדר, קח את תג הרעם!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "כשהייתי בצבא, לוטננט סרג' היה\n"
    .string "המפקד שלי.\p"
    .string "הוא היה מפקד קשוח.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "עצור!\n"
    .string "אתה טוב מאוד!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "זה לא קל לפתוח את הדלת הזו.\p"
    .string "לוטננט סרג' תמיד היה מפורסם\n"
    .string "בזהירות שלו בצבא.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "אני לא כבד, אבל אני טוב\n"
    .string "עם חשמל!\p"
    .string "לכן הצטרפתי למכון הזה.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "שרוף!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "בסדר, אני אדבר!\p"
    .string "לוטננט סרג' אמר שהוא הסתיר את\n"
    .string "המפסקים בתוך משהו.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "זה לא מקום לילדים!\n"
    .string "גם אם אתה טוב!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "וואו!\n"
    .string "הפתעת אותי!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "לוטננט סרג' התקין את המלכודות\n"
    .string "במכון בעצמו.\p"
    .string "הוא שם נעילות כפולות בכל מקום.\n"
    .string "תן לי לתת לך רמז.\p"
    .string "כשתפתח את המנעול הראשון, המנעול\n"
    .string "השני יהיה ממש לידו.$"

VermilionCity_Gym_Text_GymGuyAdvice::
    .string "היי!\n"
    .string "אלוף בהתהוות!\p"
    .string "לוטננט סרג' יש לו כינוי.\p"
    .string "אנשים קוראים לו\n"
    .string "האמריקאי החשמלי!\p"
    .string "הוא מומחה לפוקימונים\n"
    .string "חשמליים.\p"
    .string "פוקימונים מסוג מעופף/מים\n"
    .string "לא מתאימים לחשמל.\p"
    .string "תיזהר גם משיתוק.\p"
    .string "לוטננט סרג' מאוד זהיר.\p"
    .string "הוא נעל את עצמו בפנים, אז לא\n"
    .string "יהיה קל להגיע אליו.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
    .string "וואו!\n"
    .string "הקרב היה חשמלי!$"

VermilionCity_Gym_Text_GymStatue::
    .string "מכון פוקימון ורמיליון\n"
    .string "מנהל: לוטננט סרג'\p"
    .string "מאמנים מנצחים:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "מכון פוקימון ורמיליון\n"
    .string "מנהל: לוטננט סרג'\p"
    .string "מאמנים מנצחים:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "לא!\n"
    .string "יש כאן רק זבל.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "היי! יש מתג מתחת לזבל!\n"
    .string "להדליק אותו?\p"
    .string "המנעול החשמלי הראשון נפתח!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "המנעול החשמלי השני נפתח!\n"
    .string "הדלת הממונעת נפתחה!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "לא!\n"
    .string "יש כאן רק זבל.\p"
    .string "היי!\n"
    .string "המנעולים החשמליים אופסו!$"
