FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
    .string "ברוך הבא\n"
    .string "לאזור הספארי!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
    .string "עבור רק 005¥\n"
    .string "אתה יכול לתפוס כמה פוקימונים שרק\l"
    .string "תרצה בפארק!\p"
    .string "האם תרצה להצטרף למצוד?{}$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
    .string "זה 005¥\n"
    .string "בבקשה!\p"
    .string "אנחנו משתמשים בפוקיבול מיוחד כאן.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
    .string "{PLAYER} קיבל\n"
    .string "03 כדורי ספארי!$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
    .string "אנחנו נכרוז\n"
    .string "לך כשהזמן נגמר או כשנגמרים לך\l"
    .string "כדורי הספארי!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
    .string "אוקיי! בוא שוב!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
    .string "אופס! אין מספיק\n"
    .string "כסף!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
    .string "מסיים מוקדם?{}$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
    .string "החזר בבקשה את\n"
    .string "כדורי הספארי שנשארו ברשותך.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
    .string "בהצלחה!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
    .string "יצאת עם שלל\n"
    .string "טוב? בוא שוב!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
    .string "היי! זאת הפעם\n"
    .string "הראשונה שלך פה?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
    .string "באזור הספארי יש\n"
    .string "4 אזורים.\p"
    .string "בכל אזור יש זנים שונים של\n"
    .string "פוקימונים. השתמש בכדורי הספארי\l"
    .string "כדי לתפוס אותם!\p"
    .string "כשנגמר לך הזמן או כשאוזלים לך\l"
    .string "הכדורים, המשחק שלך נגמר!\p"
    .string "לפני שאתה הולך, פנה מקום בתא\n"
    .string "הפוקימונים במחשב\l"
    .string "לפוקימונים חדשים!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
    .string "סליחה, אתה\n"
    .string "קבוע כאן!$"
