SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "הא?\n"
    .string "אתה…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "אתה אולי…\n"
    .string "… …\p"
    .string "זה אתה!\n"
    .string "אתה {PLAYER}!\p"
    .string "בדיוק דיברנו עליך!\p"
    .string "דיברנו על איך הופיע מאמן\n"
    .string "כל כך טוב.\p"
    .string "וזה אתה!\n"
    .string "אתה כל כך מגניב!\p"
    .string "אז החלטנו שנהפוך למועדון\n"
    .string "המעריצים שלך!\p"
    .string "כולנו מקווים שתמשיך להילחם\n"
    .string "ותראה לנו כמה אתה מגניב.\p"
    .string "ככה אולי גם אחרים יהפכו\n"
    .string "למעריצים בדיוק כמוני.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "אני תמיד אעודד אותך!\p"
    .string "קדימה, {PLAYER}, קדימה!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "אני תמיד אאמין בך,\n"
    .string "{PLAYER}.\p"
    .string "בבקשה תראה לאחרים איך אתה\n"
    .string "נראה כשאתה נלחם ברצינות.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "אני מצטער.\n"
    .string "פעם הייתי מעריץ שלך.\p"
    .string "אבל עכשיו נראה שאיבדת\n"
    .string "את המוטיבציה שהייתה לך פעם.\p"
    .string "לאחרונה, אני חושב ש-{STR_VAR_1}\n"
    .string "הרבה יותר מגניב.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "או!\n"
    .string "{PLAYER}!\p"
    .string "כולם כל כך נרגשים ממך לאחרונה.\p"
    .string "אני מבין למה.\n"
    .string "אני יודע שאתה חזק.\p"
    .string "אבל, אתה יודע מה?\p"
    .string "מאז שהפכתי למעריץ של {STR_VAR_1},\n"
    .string "אני פשוט לא יכול להפסיק\l"
    .string "להיות מעריץ.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "אני חושב שמאמנים כל כך מגניבים\n"
    .string "כשהם נלחמים.\p"
    .string "גם אתה חושב ככה?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "או! זה {PLAYER}!\n"
    .string "ממש מגניב!\p"
    .string "או!\n"
    .string "או, כן!\p"
    .string "אפשר חתימה על משהו?\n"
    .string "מה לגבי המכנסיים שלי?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "לא משנה כמה חם היה…\p"
    .string "וכמה קר עשוי להיות…\p"
    .string "תמיד האמנתי, ולבשתי,\n"
    .string "מכנסיים קצרים!\p"
    .string "אני סומך עליך שתמשיך\n"
    .string "לנצח!\p"
    .string "אני מאמין בך בדיוק כמו שאני\n"
    .string "מאמין במכנסיים קצרים!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "ברוק הוא הגיבור שלי!\n"
    .string "הוא גבר שבגברים!\p"
    .string "חחח, שכנעתי את אמא שלי\n"
    .string "לעשות משהו בשבילי.\p"
    .string "שכנעתי אותה לרקום את השם\n"
    .string "”ברוק“ על המכנסיים שלי!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "…  …\p"
    .string "…  …\n"
    .string "אני מעריץ של ברוק!\p"
    .string "גם אם הייתי המעריץ היחיד שלו,\n"
    .string "אני נשבע על הרצון הסלעי שלי,\l"
    .string "ועל המכנסיים שלי!\p"
    .string "אני אשאר המעריץ שלו עד הסוף המר!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "ברוק הוא המילה האחרונה\n"
    .string "במגניבות, סוף פסוק!\p"
    .string "עכשיו יש מישהו שאני באמת\n"
    .string "רוצה להיות כמוהו!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "{PLAYER}, היה לי העונג\n"
    .string "לצפות בקרבות שלך.\p"
    .string "זה מחזיר לי זיכרונות מתוקים\n"
    .string "מהנעורים האבודים שלי.\p"
    .string "מי ייתן ותמשיך למצוא הצלחה.\n"
    .string "יש לך מעריץ!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "נדדתי רחוק ורחב\n"
    .string "בכל הארץ.\p"
    .string "אבל מעולם לא ראיתי מאמן\n"
    .string "בגדולה כמוך.\p"
    .string "תתחזק ותמשיך להילחם!\p"
    .string "תן לי הבטחה אחת,\n"
    .string "אלילי הצעיר!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "הממ…\n"
    .string "ומי אתה?\p"
    .string "קיווית להירשם כחבר\n"
    .string "במועדון המעריצים שלנו?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "אה, אז אתה הוא ה-{PLAYER}\n"
    .string "שמדברים עליו כל כך הרבה.\p"
    .string "בהחלט יש לך מראה של מנצח.\p"
    .string "אבל כדי שאקבל אותך כגדול\n"
    .string "באמת בפוקימון…\p"
    .string "… …\p"
    .string "עדיין יש לך דרך לעבור!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "כולנו כאן מעריצים של מאמני\n"
    .string "פוקימון.\p"
    .string "הדרך בה הם נראים בקרב…\n"
    .string "הם התגלמות המגניבות.\p"
    .string "אולי גם ידברו עליך כאן,\n"
    .string "אם תמשיך לנצח.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "זה {PLAYER}!\n"
    .string "זה {PLAYER}!\p"
    .string "אני רוצה להיות כמו {PLAYER} יום\n"
    .string "אחד!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "כולם הפסיקו להיות מעריצים\n"
    .string "של {PLAYER}…\p"
    .string "אבל זה אומר שאני יכול לקבל\n"
    .string "את {PLAYER} רק לעצמי!\p"
    .string "יש! קדימה!\n"
    .string "ה-{PLAYER} האחד והיחיד שלי!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "אתה יודע מה?\n"
    .string "אני רוצה להיות כמו סברינה!\p"
    .string "אני רוצה להיות ילדה על-חושית\n"
    .string "בדיוק כמוה!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "גם אם אהיה היחידה, לא אפסיק\n"
    .string "להיות מעריצה של סברינה.\p"
    .string "החלום שלי הוא להיות כמו סברינה,\n"
    .string "חמודה, אבל מגניבה.\p"
    .string "אני רוצה להיות ילדה על-חושית\n"
    .string "בדיוק כמוה!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "מעניין אם אוכל להפוך\n"
    .string "למאמן מגניב ביום אחד!\p"
    .string "המאמן הזה {PLAYER} בטח מגניב.\n"
    .string "אולי יום אחד אני אוכל להיות\l"
    .string "כמו {PLAYER}!\p"
    .string "אני אצטרך לפתח לעצמי\n"
    .string "סגנון!$"

SaffronCity_PokemonTrainerFanClub_Text_TooExcitedToTalk::
    .string "הה!\n"
    .string "הנה! {PLAYER}!\p"
    .string "אני כל כך מתרגש לדבר איתך,\n"
    .string "שאין לי מילים.\p"
    .string "כמו, תראה!\p"
    .string "אני לא יכול להפסיק\n"
    .string "להסתובב!$"

SaffronCity_PokemonTrainerFanClub_Text_CoolTrainerLikeYou::
    .string "אני אוהב מאמנים מגניבים\n"
    .string "כמוך, {PLAYER}!\p"
    .string "אתה פוקימון מעניין!\p"
    .string "אם אתה יוכל\n"
    .string "להתאמן כמוני, יום אחד אתה\l"
    .string "יהיה כוכב!\l"
    .string "אני באמת מאמין בזה!$"

SaffronCity_PokemonTrainerFanClub_Text_MySisterIsInYourFanClub::
    .string "אחותי במועדון המעריצים שלך!\p"
    .string "היא ממש נלהבת\n"
    .string "לראות אותך!\p"
    .string "אני מקווה שהיא תהיה\n"
    .string "חברה טובה שלך, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TooAfraidToSayAnything::
    .string "אני כל כך מתרגש\n"
    .string "שאני לא יכול לדבר!\p"
    .string "אבל אני מאמין בך,\n"
    .string "{PLAYER}!\l"
    .string "אתה חזק ומגניב!\p"
    .string "אף פעם לא נוותר לך!$"

SaffronCity_PokemonTrainerFanClub_Text_ComeBackToTownAgain::
    .string "כשתחזור לעיר, בבקשה,\n"
    .string "אל תשכח לבקר את המעריצים שלך.\p"
    .string "אני בהחלט אצפה לזה.\n"
    .string "תן לי את ה{PLAYER} שלי חזרה!$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "וואו, וואו!\n"
    .string "מגניב! מגניב מדי!\p"
    .string "…האה?\n"
    .string "לא, לא אתה.\p"
    .string "רק הדרך שבה אתה נלחם.\n"
    .string "זה מגניב.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "היי, {PLAYER}!\p"
    .string "נראה שאני האוהד האחרון שלך.\p"
    .string "אבל, אתה יודע, אני אוהב להיות\n"
    .string "האוהד היחיד… זה פחות מלחיץ.\p"
    .string "תמשיך ככה!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "{STR_VAR_1} מגניב, אה?\n"
    .string "אני אוהב את הדרך שהוא מדבר.\p"
    .string "הייתי באמת נהנה לפגוש אותו באופן\n"
    .string "אישי פעם.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "האה, אתה מאמין בזה?\n"
    .string "כולם הפכו לאוהדים שלך.\p"
    .string "אז אחרי כל מה שעברנו,\n"
    .string "אני האוהד היחיד של {STR_VAR_1}?\p"
    .string "אה, להיות האוהד היחיד {STR_VAR_1}\n"
    .string "זה הסגנון שלי, בכל מקרה.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "וואו, אלוהים!\n"
    .string "האם זה באמת אתה, {PLAYER}?\p"
    .string "אני חייב להגיד לך, אני מעריץ את\n"
    .string "הדרך שבה אתה נלחם.\p"
    .string "אני מקווה שתמשיך ככה.\n"
    .string "אני אהיה האוהד מספר אחד שלך!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "וואו, אלוהים!\n"
    .string "אם לא {PLAYER}!\p"
    .string "זה כל כך מאכזב… הבנתי\n"
    .string "שאני האוהד מספר אחד והיחיד שלך!\p"
    .string "ובכן, אי אפשר לעזור!\n"
    .string "אני לפחות אתמוך בך!\p"
    .string "חיים, חיים, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "באחרונה, {STR_VAR_1} היה בוער.\p"
    .string "הדרך שבה הוא נלחם… זה בדיוק\n"
    .string "הסגנון שאני אוהב!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "היי, שלום!\n"
    .string "אם לא {PLAYER}!\p"
    .string "לאחרונה, כולם מדברים רק עליך.\p"
    .string "אני מרגיש בודד כי אני\n"
    .string "מעדיף את {STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "מדהים!\n"
    .string "{PLAYER}, אתה באמת מדהים!\p"
    .string "במקום רק לצפות, אולי\n"
    .string "אני צריך להיות מאמן גם.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "אני האוהד היחיד שלך…\n"
    .string "ההה… זה בודד…\p"
    .string "אתה לא יכול לנסות יותר ולהשיג את\n"
    .string "שאר האנשים שיראו אותך?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "מאסטר {STR_VAR_1} כל כך מכובד…\n"
    .string "הוא בדיוק הטיפוס שלי.\p"
    .string "למה אחרים לא יכולים לראות את\n"
    .string "הכבוד שהוא פשוט משדר?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "אני מאמין במאסטר {STR_VAR_1}\n"
    .string "עם כל הלב שלי.\p"
    .string "אפילו אם אני היחיד שמאמין בו.\p"
    .string "אני לא ארגיש בודד אף פעם, עם\n"
    .string "זאת.\p"
    .string "לא אם אני ממשיך לחשוב על מאסטר\n"
    .string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "היי!\p"
    .string "הסגנון שלך בקרב הוא מאוד\n"
    .string "חינוכי.\p"
    .string "אני מקווה שאתה תמשיך לשאוף\n"
    .string "להצלחה, היי!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "במקום רק לצפות באחרים\n"
    .string "נלחמים, נלחם בעצמך!\p"
    .string "…המאסטר שלי מהדוגו' הציק לי\n"
    .string "ככה…\p"
    .string "אבל אני לא אתן לזה לעצור אותי\n"
    .string "מלהיות האוהד שלך!\p"
    .string "אני לא יכול להפסיק להיות האוהד\n"
    .string "שלך!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "היי! יש רק מאמן אחד\n"
    .string "שיש לו את הכבוד שלי.\p"
    .string "וזה אף אחד אחר מאשר המאסטר שלי\n"
    .string "בדוגו'.\p"
    .string "אתה צריך להיות אוהד של המאסטר\n"
    .string "שלי כמוני! היי!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "היי! אני מכבד את המאסטר שלי\n"
    .string "בדוגו'.\p"
    .string "אני לעולם לא אהיה אוהד של\n"
    .string "מישהו אחר חוץ מהמאסטר שלי!\p"
    .string "אפילו אני אגנוב מהדוגו' שלי\n"
    .string "כדי להפיץ את גדולתו.\p"
    .string "היי!$"
