Route8_Text_AidanIntro::
    .string "אתה נראה טוב עם פוקימונים,\n"
    .string "אבל איך הציון שלך בכימיה?$"

Route8_Text_AidanDefeat::
    .string "או!\n"
    .string "התמוטטות!$"

Route8_Text_AidanPostBattle::
    .string "אני יותר טוב בלימודים מאשר בזה!$"

Route8_Text_StanIntro::
    .string "בסדר!\n"
    .string "בוא נשחק משחק!$"

Route8_Text_StanDefeat::
    .string "לעזאזל!\n"
    .string "פספסתי!$"

Route8_Text_StanPostBattle::
    .string "הדברים לא עבדו היום.$"

Route8_Text_GlennIntro::
    .string "אתה צריך לדעת.\n"
    .string "צריך אסטרטגיה כדי לנצח בזה!$"

Route8_Text_GlennDefeat::
    .string "זה לא הגיוני!$"

Route8_Text_GlennPostBattle::
    .string "לך עם גריימר ראשון…ואז…\n"
    .string "…ואז…$"

Route8_Text_PaigeIntro::
    .string "אני אוהבת נידורן, אז אני אוספת\n"
    .string "אותם!$"

Route8_Text_PaigeDefeat::
    .string "למה?\n"
    .string "למה??$"

Route8_Text_PaigePostBattle::
    .string "כשפוקימונים גדלים, הם הופכים\n"
    .string "מכוערים! הם לא צריכים להתפתח.$"

Route8_Text_LeslieIntro::
    .string "בית הספר כיף, אבל גם פוקימונים.$"

Route8_Text_LeslieDefeat::
    .string "הבהרת לי שאני צריך להמשיך עם\n"
    .string "בית הספר.$"

Route8_Text_LesliePostBattle::
    .string "תכננתי לקחת קצת אוויר צח לשם\n"
    .string "שינוי, אבל…\p"
    .string "אנחנו תקועים כאן בגלל השערים\n"
    .string "בסאפרון.$"

Route8_Text_AndreaIntro::
    .string "מיאות' כל כך חמוד, מיאו, מיאו,\n"
    .string "מיאו!$"

Route8_Text_AndreaDefeat::
    .string "מייייייאו!$"

Route8_Text_AndreaPostBattle::
    .string "אני חושבת שפידג'י וראטטה גם\n"
    .string "חמודים!$"

Route8_Text_MeganIntro::
    .string "אנחנו בטח נראים טיפשים כשאנחנו\n"
    .string "עומדים ככה.$"

Route8_Text_MeganDefeat::
    .string "תראה מה עשית לפוקימונים\n"
    .string "המסכנים והחמודים שלי!$"

Route8_Text_MeganPostBattle::
    .string "שומר השער של סאפרון לא נותן\n"
    .string "לנו לעבור.\p"
    .string "אני יודעת שהוא עושה את העבודה\n"
    .string "שלו, אבל אני חושבת שהוא מרושע.$"

Route8_Text_RichIntro::
    .string "אני בחור שמבלה ומזל משחקים!$"

Route8_Text_RichDefeat::
    .string "פספסתי את ההזדמנות הגדולה!$"

Route8_Text_RichPostBattle::
    .string "לשחק משחקים ופוקימונים זה כמו\n"
    .string "לאכול בוטנים! אני פשוט לא יכול\l"
    .string "להפסיק!$"

Route8_Text_JuliaIntro::
    .string "מה זה פוקימון חמוד, עגול,\n"
    .string "ורך?$"

Route8_Text_JuliaDefeat::
    .string "תפסיק!\p"
    .string "אל תהיה כל כך מרושע כלפי קלפירי!$"

Route8_Text_JuliaPostBattle::
    .string "קראתי שקלפירי מתפתח כשנחשף\n"
    .string "לאבן ירח.\p"
    .string "קראתי את זה בעיתון פוקימון.\n"
    .string "מעניין אם זה נכון?$"

Route8_Text_UndergroundPathSign::
    .string "דרך תת קרקעית\n"
    .string "עיר סלדון - עיר לבנדר$"

Route8_Text_EliIntro::
    .string "אילי: כוח תאומים הוא מדהים.\n"
    .string "ידעת?$"

Route8_Text_EliDefeat::
    .string "אילי: אבל…\n"
    .string "השתמשנו בכוח התאומים שלנו…$"

Route8_Text_EliPostBattle::
    .string "אילי: תפסתי את הפוקימונים שלי עם\n"
    .string "אן!$"

Route8_Text_EliNotEnoughMons::
    .string "אילי: אנחנו לא יכולים להילחם אם\n"
    .string "אין לך שני פוקימונים.$"

Route8_Text_AnneIntro::
    .string "אן: אנחנו נדהים אותך עם כוח\n"
    .string "התאומים שלנו!$"

Route8_Text_AnneDefeat::
    .string "אן: כוח התאומים שלנו…$"

Route8_Text_AnnePostBattle::
    .string "אן: אני מגדלת פוקימונים עם\n"
    .string "אילי.$"

Route8_Text_AnneNotEnoughMons::
    .string "אן: היי, היי! בוא נילחם!\n"
    .string "אבל תביא שני פוקימונים.$"

Route8_Text_RicardoIntro::
    .string "האופניים שלי מתנהגות מוזר, חבר.$"

Route8_Text_RicardoDefeat::
    .string "אוי, חבר.\n"
    .string "אני לא בקטע הזה.$"

Route8_Text_RicardoPostBattle::
    .string "נתפסה לי דשא בחישורים, חבר.$"

Route8_Text_JarenIntro::
    .string "פנה את הדרך, או שאני ארוץ\n"
    .string "עליך!$"

Route8_Text_JarenDefeat::
    .string "אתה באמת, ילד?$"

Route8_Text_JarenPostBattle::
    .string "אל תחשוב שאתה מיוחד רק\n"
    .string "בגלל זה.$"
