FiveIsland_LostCave_Room10_Text_SelphyIntro::
    .string "מ-מה אתה מתכוון לעשות\n"
    .string "לי?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
    .string "הו… חששתי שאתה מתכוון\n"
    .string "לפגוע בי.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
    .string "אני כל כך שמחה שהגעת\n"
    .string "לכאן.\p"
    .string "נמאס לי קצת ללכת,\n"
    .string "ואני מרגישה עייפה.\p"
    .string "אפשר לבקש ממך לקחת\n"
    .string "אותי הביתה מכאן?$"

