CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
    .string "אני קונה בובת\n"
    .string "פוקימון לחברה שלי!$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
    .string "שמעתי עובדה\n"
    .string "שימושית.\p"
    .string "אפשר לברוח מקרבות מול פוקימונים\n"
    .string "פראים אם מסיחים את דעתם בעזרת\l"
    .string "בובת פוקימון!$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
    .string "הביעו את אהבתכם\n"
    .string "דרך מתנות!\p"
    .string "ק4: חנות מזכרות\p"
    .string "מבצע התפתחות מיוחד!\l"
    .string "קנו אבני יסוד! עכשיו במלאי!$"
