SilphCo_3F_Text_WhatAmIToDo::
    .string "אני עובד עבור ארגון סילף.\n"
    .string "מה עלי לעשות?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
    .string "{PLAYER}!\n"
    .string "אתה ופוקמון שלך הצלתם אותנו!$"

SilphCo_3F_Text_GruntIntro::
    .string "תפסיק להטריד אותנו, ילד!$"

SilphCo_3F_Text_GruntDefeat::
    .string "אני מוותר!$"

SilphCo_3F_Text_GruntPostBattle::
    .string "רמז? אפשר לפתוח דלתות עם\n"
    .string "כרטיס גישה!$"

SilphCo_3F_Text_JoseIntro::
    .string "אני תומך בצוות רוקט יותר\n"
    .string "מאשר בארגון סילף.!$"

SilphCo_3F_Text_JoseDefeat::
    .string "אתה באמת הצלחת להשיג אותי!$"

SilphCo_3F_Text_JosePostBattle::
    .string "חפ…\p"
    .string "צוות רוקט אמרו לי שאם אני אעזור\n"
    .string "להם הם יתנו לי ללמוד על פוקימון.$"

SilphCo_3F_Text_FloorSign::
    .string "ארגון סילף. משרד ראשי\n"
    .string "קומה 3$"
