ThreeIsland_BerryForest_Text_HelpScaryPokemon::
    .string "לוסטל: בוהו… סנייף…\n"
    .string "אוי! בבקשה, תעזור!\p"
    .string "פוקימון מפחיד הופיע שם\n"
    .string "לפני קצת זמן.\p"
    .string "הוא כל הזמן הפחיד…\n"
    .string "הוא הפחיד את לוסטל.\p"
    .string "אני פוחדת מדי לזוז!\n"
    .string "אבל אני רוצה הביתה…$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
    .string "אוי! הנה הוא בא שוב!\n"
    .string "לא! לך מפה! הוא מפחיד אותי!\p"
    .string "וואאאאאה!\n"
    .string "אני רוצה את אבא שלי!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
    .string "אוהה! זה היה כל כך מפחיד!\n"
    .string "תודה לך!\p"
    .string "לוסטל באה לקטוף כמה\n"
    .string "פירות יער.\p"
    .string "אתה יכול לקחת את זה!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
    .string "איך קוראים לך?\p"
    .string "לוסטל מפחדת, אפשר לבוא\n"
    .string "איתך לבית של אבא שלי?\p"
    .string "בסדר!\n"
    .string "בוא נלך הביתה!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
    .string "נרתיק הפירות שלך מלא.\n"
    .string "כנראה שאתה לא רוצה את זה.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
    .string "ברוכים הבאים ליער הפירות\p"
    .string "תהיו נחמדים ותחלקו פירות\n"
    .string "עם אחרים ועם פוקימונים.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
    .string "היזהרו מפוקימוני בר\n"
    .string "שאוהבים פירות!$"
