FourIsland_Text_IslandSign::
    .string "אי 4\n"
    .string "אי הקרחונים החמים והכחולים$"

FourIsland_Text_LoreleiHasReturned::
    .string "לורליי חזרה הביתה.\p"
    .string "אני תוהה, אולי חיי העיר\n"
    .string "היו מלחיצים מדי בשבילה?$"

FourIsland_Text_LoreleiMetLaprasAsChild::
    .string "לורליי חזרה לליגה.\p"
    .string "הלפרס שלה, אני מניח שזה\n"
    .string "אותו אחד שהיא פגשה כילדה.\p"
    .string "אני מאמין שהיא תפסה אותו\n"
    .string "במערת מפל הקרח.\p"
    .string "אולי הפוקימון הזה איתה\n"
    .string "מאז ומתמיד.$"

FourIsland_Text_RivalAlreadyGotEggBeSmellingYa::
    .string "{RIVAL}: היי!\n"
    .string "{PLAYER}!\p"
    .string "מה אתה עושה כאן\n"
    .string "באיי סווי?\p"
    .string "כדאי שתפסיק לחקות אותי,\n"
    .string "אתה יודע?\p"
    .string "בכל מקרה, כבר השגתי ביצת\n"
    .string "פוקימון, אז סיימתי פה.\p"
    .string "חה, אני בטוח שאתה בכלל לא\n"
    .string "יודע מה זה ביצי פוקימון.\p"
    .string "ככה לעולם לא תמלא את\n"
    .string "הפוקדקס הארצי שלך.\p"
    .string "דרך אגב, ראיתי כאן באי מישהי\n"
    .string "ששנינו מכירים.\p"
    .string "אם זה מסקרן אותך,\n"
    .string "לך לחפש אותה.\p"
    .string "אני? אין לי זמן\n"
    .string "לבזבז.\p"
    .string "נתרחרח אחר-כך!$"

FourIsland_Text_LoreleiHasLotsOfStuffedDolls::
    .string "הו, מצאת אותי!\n"
    .string "בבקשה אל תספר ללורליי.\p"
    .string "ידעת שללורליי יש המון המון\n"
    .string "בובות ממולאות?\p"
    .string "בכל פעם שהיא חוזרת\n"
    .string "לאי 4, האוסף שלה גדל!$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
    .string "אוו, קר!\p"
    .string "הכנתי ברד מקרח שגירדתי\n"
    .string "בתוך מערת מפל הקרח.\p"
    .string "קר וטעים!$"

FourIsland_Text_LoreleisHouse::
    .string "הבית של לורליי$"

